unpackaged/main/default/objects/EBH_ActiveTriggers__c/EBH_ActiveTriggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>[EBH] (EPH-5) Active trigger controller - to switch on/off and bypass for deployment or data migration</description>
    <label>Active Triggers</label>
</CustomObject>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/fields/EBH_ContactTrigger__c.field-meta.xml
<CustomField>
    <fullName>EBH_ContactTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>[EBH] (EPH-3270) : Sprint 7: To enable/disable the Contact trigger.</description>
    <inlineHelpText>Trigger switch for Contact Trigger(s)</inlineHelpText>
    <label>Contact Trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/fields/EBH_ContractApprovalHierarchyTrigger__c.field-meta.xml
<CustomField>
    <fullName>EBH_ContractApprovalHierarchyTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>[EBH] (EPH-51)</description>
    <label>Contract Approval Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/fields/EBH_ExecuteContractUpdateBatch__c.field-meta.xml
<CustomField>
    <fullName>EBH_ExecuteContractUpdateBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-51) - to track technically if contract update batch needs to be executed</description>
    <label>Execute Contract Update Batch</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/EBH_ContractApprovalHierarchyHandlerTest.cls
/*****************************************************************************************************************************
@ Class:       EBH_ContractApprovalHierarchyHandler
@ Author:      Mony Nou (mony.nou@gaea-sys.com)
@ Purpose:     US-0008361 test class for EBH_ContractApprovalHierarchyHandler
------------------------------------------------------------------------------------------------------------------------------
@ Change history:  17.11.2021 / Mony Nou / Created the method.
@*****************************************************************************************************************************/
@IsTest 
private class EBH_ContractApprovalHierarchyHandlerTest {
    
    @isTest static void test_method() {

        Test.startTest();

            EBH_ActiveTriggers__c cusettingTrigger = new EBH_ActiveTriggers__c();
            cusettingTrigger.Name = 'EBH Trigger Controller';
            cusettingTrigger.EBH_ContactTrigger__c = true;
            cusettingTrigger.EBH_ContractApprovalHierarchyTrigger__c = true;
            cusettingTrigger.EBH_ExecuteContractUpdateBatch__c = false;
            insert cusettingTrigger; 

            List<User> users = EBH_TestDataFactory.createUsers(4, 'Standard User');
            insert users;  

            EBH_ContractApprovalMatrix__c  matrixRecordDE = EBH_TestDataFactory.createContractApprovalMatrix ( 'DE', users[0].id, users[1].id ) ;
            EBH_ContractApprovalMatrix__c  matrixRecordFR = EBH_TestDataFactory.createContractApprovalMatrix ( 'FR', users[0].id, users[1].id ) ;
            EBH_ContractApprovalMatrix__c  matrixRecordIT = EBH_TestDataFactory.createContractApprovalMatrix ('IT', users[0].id, users[1].id ) ;
            EBH_ContractApprovalMatrix__c  matrixRecordES = EBH_TestDataFactory.createContractApprovalMatrix ( 'ES', users[0].id, users[1].id ) ;
            EBH_ContractApprovalMatrix__c  matrixRecordUK = EBH_TestDataFactory.createContractApprovalMatrix ( 'UK', users[0].id, users[1].id ) ;
            EBH_ContractApprovalMatrix__c  matrixRecordRest = EBH_TestDataFactory.createContractApprovalMatrix ( 'Rest of Europe', users[0].id, users[1].id ) ;
            insert new List<EBH_ContractApprovalMatrix__c>{matrixRecordDE,matrixRecordFR,matrixRecordIT,matrixRecordES,matrixRecordUK,matrixRecordRest};

            EBH_ContractApprovalHierarchy__c child1 = EBH_TestDataFactory.createContractApprovalHierarchy ( EBH_ConstantsUtility.HIERARCHY_CONTROLLING, users[2].id, 5000000.0);
            child1.EBH_ContractApprovalMatrix__c = matrixRecordDE.Id;
            EBH_ContractApprovalHierarchy__c child2 = EBH_TestDataFactory.createContractApprovalHierarchy ( EBH_ConstantsUtility.HIERARCHY_FINANCE, users[3].id, 5000000.0);
            child2.EBH_ContractApprovalMatrix__c = matrixRecordFR.Id;
            insert new List<EBH_ContractApprovalHierarchy__c>{child1,child2};

            cusettingTrigger.EBH_ExecuteContractUpdateBatch__c = false;
            update cusettingTrigger;

            child1.EBH_Threshold__c = 3000000.0;
            update child1;

        Test.stopTest();

    }

}