unpackaged/main/default/objects/Hive_Project__c/Hive_Project__c.object-meta.xml
<CustomObject>
    <description>US-0008533 - HIVE Project</description>
    <label>Hive Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hive Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hive_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Under Review (Requirement Clarification)</fullName>
            </value>
            <value>
                <fullName>Prioritization</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hive_Project__c/recordTypes/Hive_Project.recordType-meta.xml
<RecordType>
    <fullName>Hive_Project</fullName>
    <active>true</active>
    <description>HIVE Project - a time limited work on a HIVE Product, that required discovery, collection of Feature requests, prioritization across them. Realization of HIVE Project as a rule takes more than 2 sprints and 15 story points.</description>
    <label>HIVE Project</label>
</RecordType>

unpackaged/main/default/objects/Requirement_Request__c/Requirement_Request__c.object-meta.xml
<CustomObject>
    <description>https://hive.lightning.force.com/apex/GoToUserStory?US-0007812</description>
    <label>Feature Request</label>
    <nameField>
        <label>Feature Request (Name)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Requirement_Request__c/fields/Hive_Project__c.field-meta.xml
<CustomField>
    <fullName>Hive_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008533 - HIVE Project
US-0011126
US-0010666</description>
    <label>HIVE Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Hive Project Status must not be in following values: Draft, New, Completed, Rejected, On-hold</errorMessage>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Draft</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>New</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>On-hold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hive_Project__c</referenceTo>
    <relationshipLabel>Feature Requests</relationshipLabel>
    <relationshipName>Feature_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Requirement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Requirements Clarification</fullName>
                <label>Under Review (Requirement Clarification)</label>
            </value>
            <value>
                <fullName>Requires Prioritization</fullName>
            </value>
            <value>
                <fullName>Sizing by HIVE team</fullName>
            </value>
            <value>
                <fullName>Requirement Accepted</fullName>
                <label>User Story Creation</label>
            </value>
            <value>
                <fullName>Development</fullName>
                <label>Coming Soon</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
                <label>Product Backlog</label>
            </value>
            <value>
                <fullName>Needs Clarification</fullName>
                <isActive>false</isActive>
                <label>Needs Clarification</label>
            </value>
            <value>
                <fullName>Prioritization</fullName>
                <isActive>false</isActive>
                <label>Prioritization</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
            <value>
                <fullName>Waiting for feedback</fullName>
                <isActive>false</isActive>
                <label>Waiting for Feedback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/HiveProjectTriggerHandler.cls
/*********************************************************************************************************************************
 @ Class:          HiveProjectTriggerHandler
 @ Version:        1.0
 @ Author:         David Herrero
 @ Purpose:        handler for trigger/ object Hive_Project
 ----------------------------------------------------------------------------------------------------------------------------------
 @ Change history: 2.08.2021 / David Herrero / Created the class.
 *********************************************************************************************************************************/
public without sharing class HiveProjectTriggerHandler{
	public static final String COMPLETED_STATUS = 'Completed';
	public static final String QUERY_USER_STORIES = 'select id,hive_project__c from copado__user_story__c where Hive_Project__c in :completedProjectsToValidate and copado__status__c not in :EXCLUDED_US_STATUS';
	public static final String QUERY_REQUIREMENT_REQUESTS = 'select id,hive_project__c from Requirement_Request__c where Hive_Project__c in :completedProjectsToValidate and Status__c not in :EXCLUDED_FR_STATUS';
	public static final String ERROR_MESSAGE = 'You can not close a project with open feature requests or user stories. Please, progress before closing project.';

    public static final String[] EXCLUDED_US_STATUS= new String[] {'Closed - Complete','Rejected' ,'Deployed in PROD','Duplicated' };
    public static final String[] EXCLUDED_FR_STATUS= new String[] {'Delivered','Completed' ,'Rejected' ,'On-hold' };

	public static void validateCompletedStatus(Hive_Project__c[] newList, Map<Id, Hive_Project__c> newMap){
        
		List<copado__User_Story__c> lus;
		List<Requirement_Request__c> lfr;
		set<id> addedError = new set<id>();

		set<id> completedProjectsToValidate = new set<id>();
		for (Hive_Project__c p : newList){
			if (p.Status__c == COMPLETED_STATUS){
				completedProjectsToValidate.add(p.ID);

			}
		}
		System.debug('completedProjectsToValidate:::'+completedProjectsToValidate);
		if (!completedProjectsToValidate.isEmpty()){
			lus = Database.query(QUERY_USER_STORIES);
            lfr = Database.query(QUERY_REQUIREMENT_REQUESTS);

			System.debug('lus:::'+lus);
			if (lus != null && lus.size()>0){
                System.debug('size of lus = ' + lus);

				for (copado__User_Story__c cus : lus){
					newMap.get(cus.hive_project__c).addError(ERROR_MESSAGE);
					addedError.ADD(cus.hive_project__c);
				}
			} 
				
                System.debug('size of lfr = ' + lfr);

				if (lfr != null){
                    System.debug('lfr not null ' + lfr);

					for (Requirement_Request__c rr : lfr){
                        System.debug('Requirement_Request__c ' + rr);
                        System.debug('addedError ' + addedError);

						if (!addedError.contains(rr.Hive_Project__c)){
                            System.debug('addedError ' + addedError);

							newMap.get(rr.Hive_Project__c).addError(ERROR_MESSAGE);
							addedError.ADD(rr.hive_project__c);


				
				}
			}
		}
        System.debug('addedError ' + addedError);

        }
    }
}