unpackaged/main/default/objects/Hive_Project__c/Hive_Project__c.object-meta.xml
<CustomObject>
    <description>US-0008533 - HIVE Project</description>
    <label>Hive Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hive Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hive_Project__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>US-0010250 - SM - Adding new fields to Hive Project</description>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>EEC</fullName>
                <isActive>false</isActive>
                <label>EEC</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <isActive>false</isActive>
                <label>ES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Hive_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Under Review (Requirement Clarification)</fullName>
            </value>
            <value>
                <fullName>Prioritization</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Requirement_Request__c/Requirement_Request__c.object-meta.xml
<CustomObject>
    <description>https://hive.lightning.force.com/apex/GoToUserStory?US-0007812</description>
    <label>Feature Request</label>
    <nameField>
        <label>Feature Request (Name)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Requirement_Request__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <description>US-0011982 - Feature request &amp; Project object Technical estimation fields</description>
    <label>Component</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Survey Vista</fullName>
            </value>
            <value>
                <fullName>Domo</fullName>
            </value>
            <value>
                <fullName>Einstein Analytics</fullName>
            </value>
            <value>
                <fullName>ETL</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Salesforce - Admin</fullName>
            </value>
            <value>
                <fullName>UX</fullName>
            </value>
            <value>
                <fullName>SF Community</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Requirement_Request__c/fields/HIVE_Product__c.field-meta.xml
<CustomField>
    <fullName>HIVE_Product__c</fullName>
    <description>US-0008600 - HIVE EPIC,
US-0011331 - New Hive Products Object - Hive Products field changes</description>
    <label>(NOT USED) HIVE Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Functional_Area</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Requirement_Request__c/fields/Hive_Project__c.field-meta.xml
<CustomField>
    <fullName>Hive_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008533 - HIVE Project
US-0011126
US-0010666</description>
    <label>HIVE Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Hive Project Status must not be in following values: Draft, New, Completed, Rejected, On-hold</errorMessage>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Draft</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>New</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Rejected</value>
        </filterItems>
        <filterItems>
            <field>Hive_Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>On-hold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hive_Project__c</referenceTo>
    <relationshipLabel>Feature Requests</relationshipLabel>
    <relationshipName>Feature_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Requirement_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>US-0008283 - Feature Request Advancements</description>
    <inlineHelpText>Please specify for which regions this feature request is relevant to.</inlineHelpText>
    <label>Region</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>EEC</fullName>
                <isActive>false</isActive>
                <label>EEC</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <isActive>false</isActive>
                <label>ES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Requirement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Requirements Clarification</fullName>
                <label>Under Review (Requirement Clarification)</label>
            </value>
            <value>
                <fullName>Requires Prioritization</fullName>
            </value>
            <value>
                <fullName>Sizing by HIVE team</fullName>
            </value>
            <value>
                <fullName>Requirement Accepted</fullName>
                <label>User Story Creation</label>
            </value>
            <value>
                <fullName>Development</fullName>
                <label>Coming Soon</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
                <label>Product Backlog</label>
            </value>
            <value>
                <fullName>Needs Clarification</fullName>
                <isActive>false</isActive>
                <label>Needs Clarification</label>
            </value>
            <value>
                <fullName>Prioritization</fullName>
                <isActive>false</isActive>
                <label>Prioritization</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
            <value>
                <fullName>Waiting for feedback</fullName>
                <isActive>false</isActive>
                <label>Waiting for Feedback</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/HiveProjectTriggerHandlerTest.cls
@isTest
private class HiveProjectTriggerHandlerTest {
    static testMethod void testValidateCloseProjectOpenUS() {

        //create project
        Hive_Project__c p = new Hive_Project__c(name='Testint project',Status__c='Draft');
        insert p;

        //Create copado Project
        copado__Project__c cp = new copado__Project__c(name='Project test 1');
        insert cp;


        // Create User Story
        copado__User_Story__c cus = new copado__User_Story__c(copado__User_Story_Title__c='Test User Story');
        cus.copado__Project__c=cp.id;
        cus.HIVE_Product__c='Advertising';
        cus.Component__c='Salesforce';
        cus.copado__Status__c='Draft';
        cus.BU_Requester__c=UserInfo.getUserId();
        cus.Hive_Project__c=p.ID;
        insert cus;

        Test.startTest();
        p.Status__c='Completed';
        try{
            update p;
        }catch(Exception e){
            System.assert(e.getMessage().indexOf(HiveProjectTriggerHandler.ERROR_MESSAGE)>0, 'Must validate number of user stories not closed');
        }

    }


    static testMethod void testValidateCloseProjectOpenFR() {

        //create project
        Hive_Project__c p2 = new Hive_Project__c(name='Testint project',Status__c='Draft');
        insert p2;

     

        // Create Feature Request
       
        Requirement_Request__c rr = new Requirement_Request__c (name='RR title');
        rr.Hive_Project__c=p2.id;
        rr.Status__c='New';
        rr.Region__c='IT';
        
        insert rr;

        Test.startTest();
        p2.Status__c='Completed';
        try{
            update p2;
        }catch(Exception e){
            System.assert(e.getMessage().indexOf(HiveProjectTriggerHandler.ERROR_MESSAGE)>0, 'Must validate number of user stories not closed');
        }

    }

}