unpackaged/main/default/objects/Account/fields/Below_SP_Standard_Date__c.field-meta.xml
<CustomField>
    <fullName>Below_SP_Standard_Date__c</fullName>
    <label>Below SP Standard Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Below_SP_Standards__c.field-meta.xml
<CustomField>
    <fullName>Below_SP_Standards__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Below Seller Portal Standards</description>
    <inlineHelpText>Below Seller Portal Standards</inlineHelpText>
    <label>Below SP Standards</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_ActualStandard__c.field-meta.xml
<CustomField>
    <fullName>EBH_ActualStandard__c</fullName>
    <description>[EBH] - (US-0032) : to capture the actual standard value</description>
    <inlineHelpText>Seller&#39;s performance standard level (i.e. ETRS, Above Standard, Below Standard), based on the sellers primary listing site.</inlineHelpText>
    <label>Actual Standard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ETRS</fullName>
            </value>
            <value>
                <fullName>Above Standard</fullName>
            </value>
            <value>
                <fullName>Below Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_GMVLast12Months__c.field-meta.xml
<CustomField>
    <fullName>EBH_GMVLast12Months__c</fullName>
    <description>[EBH] US-0032: to store GMV information of last 12 months</description>
    <inlineHelpText>$ GMV in Plan Currency over the last 12 months.</inlineHelpText>
    <label>GMV (Last 12 Months)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_LastSellDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_LastSellDate__c</fullName>
    <description>[EBH] (US-0031) : Last Sell Date</description>
    <inlineHelpText>Seller´s last selling date.</inlineHelpText>
    <label>Last Sell Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_PredictedStandard__c.field-meta.xml
<CustomField>
    <fullName>EBH_PredictedStandard__c</fullName>
    <description>[EBH] (US-0032) : to capture Predicted Standard Value</description>
    <inlineHelpText>Sellers predicted performance standard level for the next evaluation cycle based on current trend.</inlineHelpText>
    <label>Predicted Standard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ETRS</fullName>
            </value>
            <value>
                <fullName>Above Standard</fullName>
            </value>
            <value>
                <fullName>Below Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_RevRollup__c.field-meta.xml
<CustomField>
    <fullName>EBH_RevRollup__c</fullName>
    <description>[EBH] (EPH-176) - Rev RollUp</description>
    <inlineHelpText>Where we attribute revenue for the Seller. Revenue is assigned based on seller country.</inlineHelpText>
    <label>Rev RollUp</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>OTHER EA</fullName>
            </value>
            <value>
                <fullName>OTHER EAPAC</fullName>
            </value>
            <value>
                <fullName>OTHER EEMEA</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>ROE -Other</fullName>
            </value>
            <value>
                <fullName>RU</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>UA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_VeROViolation__c.field-meta.xml
<CustomField>
    <fullName>EBH_VeROViolation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VeRO Violation (Last 30 Days)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_ActualStandard__c.field-meta.xml
<CustomField>
    <fullName>EBH_ActualStandard__c</fullName>
    <formula>TEXT(Account.EBH_ActualStandard__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Standard</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BatchDeactivateIneligiblePortalUsers.cls
/*********************************************************************************************************************************
@ Class:        BatchDeactivateUsers
@ Version:      1.0
@ Author:       Chetra Sarom (chetra.sarom@gaea-sys.com)
@ Purpose:      EPH-5578: Auto deactivate SEP Users if their Account falls below minimum Standards for more than 30 Days
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 29.Apr.2022 / Chetra Sarom (chetra.sarom@gaea-sys.com) :US-0011530 - related tasks not visible
*********************************************************************************************************************************/
global with sharing class BatchDeactivateIneligiblePortalUsers implements Database.Batchable<SObject>,Schedulable ,Database.stateful {
    private static Set<String> SET_REVROLLUPS = new Set<String>{'US', 'CA'};
    private static Date last90Days = Date.today().addDays(-90);
    private static Decimal AmountGMVLast12Months = 48000; // 
    private static String EBH_PREDICTEDSTANDARD_ETRS = 'ETRS';
    private static String EBH_PREDICTEDSTANDARD_BELOWSTANDARD = 'Below Standard';
    private static String EBH_PREDICTEDSTANDARD_ABOVESTARDARD = 'Above Standard';
    private static String SOQL_CUSTOMER = 'SELECT id, EBH_PredictedStandard__c, EBH_VeROViolation__c, EBH_LastSellDate__c, EBH_ActualStandard__c, EBH_GMVLast12Months__c, Below_SP_Standard_Date__c, Name FROM Account' +
    ' WHERE (EBH_RevRollup__c IN: SET_REVROLLUPS OR (EBH_LastSellDate__c >: last90Days OR EBH_PredictedStandard__c !=: EBH_PREDICTEDSTANDARD_ETRS OR EBH_VeROViolation__c = true OR EBH_ActualStandard__c =: EBH_PREDICTEDSTANDARD_BELOWSTANDARD OR EBH_GMVLast12Months__c <=: AmountGMVLast12Months)'+
    ' OR (EBH_LastSellDate__c <: last90Days AND EBH_PredictedStandard__c =: EBH_PREDICTEDSTANDARD_ETRS AND EBH_VeROViolation__c = false AND (EBH_ActualStandard__c =: EBH_PREDICTEDSTANDARD_ABOVESTARDARD OR EBH_ActualStandard__c =: EBH_PREDICTEDSTANDARD_ETRS) AND EBH_GMVLast12Months__c >=: AmountGMVLast12Months))';

    private Set<Id> accountIds = new Set<Id>();
    
    public BatchDeactivateIneligiblePortalUsers(){
        
    }
    public BatchDeactivateIneligiblePortalUsers(Set <Id> accountIds) {
        this.accountIds = accountIds;
    }

    //private static Set<Id> accIds_forUpdate = new Set<Id>();
    global Database.querylocator start(Database.BatchableContext bc) {
        //System.debug('>>>> SOQL_CUSTOMER'+SOQL_CUSTOMER);
        return Database.getQueryLocator(accountIds.isEmpty() ? SOQL_CUSTOMER : SOQL_CUSTOMER + ' AND id IN: accountIds');
    }
    global void execute(Database.BatchableContext bc, List<Account> scope) {
        List<Account> lstAccount = new List<Account>();

        for(Account acc : scope){
            if ( 
                acc.EBH_LastSellDate__c > last90Days
                || acc.EBH_PredictedStandard__c != 'ETRS' 
                || acc.EBH_VeROViolation__c == true 
                || acc.EBH_ActualStandard__c == 'Below Standard' 
                || acc.EBH_GMVLast12Months__c <= AmountGMVLast12Months
            ){
                acc.Below_SP_Standards__c = true;
                acc.Below_SP_Standard_Date__c = Date.today();
            }
            
            System.debug('>>>>>>>>> EBH_ActualStandard__c '+ acc.EBH_ActualStandard__c);
            
            if ( 
                acc.EBH_LastSellDate__c < last90Days 
                && acc.EBH_PredictedStandard__c == 'ETRS' 
                && acc.EBH_VeROViolation__c == false 
                && (acc.EBH_ActualStandard__c == 'Above Standard' || acc.EBH_ActualStandard__c == 'ETRS') 
                && acc.EBH_GMVLast12Months__c >= AmountGMVLast12Months
            ){
                acc.Below_SP_Standards__c = false;
                acc.Below_SP_Standard_Date__c = NULL;
            }

            /* if (last90Days > acc.Below_SP_Standard_Date__c) {
                accIds_forUpdate.add(acc.Id);
            } */
            
            lstAccount.add(acc);
        }
        update lstAccount;
    }
    global void finish(Database.BatchableContext bc) {
        /* Set<String> portalProfile = new Set<String>{'NA - Seller Portal', 'DE - Seller Portal'};
        String SOQL_USER = 'SELECT Id, Profile.Name, Contact.Name From User Where Contact.AccountId IN: accIds_forUpdate AND Profile.Name IN: portalProfile ';
        List<User> lstUser = new List<User>();
        for(User usr : Database.query(SOQL_USER)){
            usr.isActive = false;
        }
        try {
            update lstUser;
        } catch (Exception ex) {

            //log error on exception to apex logger object
            EBH_ApexLogger.logError(new List<Exception> { ex }, 
            'BatchDeactivateIneligiblePortalUsers', 'finish');
        } */

        
    }
    
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new BatchDeactivateIneligiblePortalUsers());
    }
}