unpackaged/main/default/objects/Account/fields/Below_SP_Standard_Date__c.field-meta.xml
<CustomField>
    <fullName>Below_SP_Standard_Date__c</fullName>
    <label>Below SP Standard Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_ActualStandard__c.field-meta.xml
<CustomField>
    <fullName>EBH_ActualStandard__c</fullName>
    <description>[EBH] - (US-0032) : to capture the actual standard value</description>
    <inlineHelpText>Seller&#39;s performance standard level (i.e. ETRS, Above Standard, Below Standard), based on the sellers primary listing site.</inlineHelpText>
    <label>Actual Standard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ETRS</fullName>
            </value>
            <value>
                <fullName>Above Standard</fullName>
            </value>
            <value>
                <fullName>Below Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_DealsProgram__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealsProgram__c</fullName>
    <description>[EBH] (EPH-4527) - Deals Program</description>
    <inlineHelpText>Is the seller eligible for the Deals Program?</inlineHelpText>
    <label>Deals Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allow</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_GMVLast12Months__c.field-meta.xml
<CustomField>
    <fullName>EBH_GMVLast12Months__c</fullName>
    <description>[EBH] US-0032: to store GMV information of last 12 months</description>
    <inlineHelpText>$ GMV in Plan Currency over the last 12 months.</inlineHelpText>
    <label>GMV (Last 12 Months)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_LastSellDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_LastSellDate__c</fullName>
    <description>[EBH] (US-0031) : Last Sell Date</description>
    <inlineHelpText>Seller´s last selling date.</inlineHelpText>
    <label>Last Sell Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_PredictedStandard__c.field-meta.xml
<CustomField>
    <fullName>EBH_PredictedStandard__c</fullName>
    <description>[EBH] (US-0032) : to capture Predicted Standard Value</description>
    <inlineHelpText>Sellers predicted performance standard level for the next evaluation cycle based on current trend.</inlineHelpText>
    <label>Predicted Standard</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ETRS</fullName>
            </value>
            <value>
                <fullName>Above Standard</fullName>
            </value>
            <value>
                <fullName>Below Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_RevRollup__c.field-meta.xml
<CustomField>
    <fullName>EBH_RevRollup__c</fullName>
    <description>[EBH] (EPH-176) - Rev RollUp</description>
    <inlineHelpText>Where we attribute revenue for the Seller. Revenue is assigned based on seller country.</inlineHelpText>
    <label>Rev RollUp</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>OTHER EA</fullName>
            </value>
            <value>
                <fullName>OTHER EAPAC</fullName>
            </value>
            <value>
                <fullName>OTHER EEMEA</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>ROE -Other</fullName>
            </value>
            <value>
                <fullName>RU</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>UA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_VeROViolation__c.field-meta.xml
<CustomField>
    <fullName>EBH_VeROViolation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VeRO Violation (Last 30 Days)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Risk_Tier_manual__c.field-meta.xml
<CustomField>
    <fullName>Risk_Tier_manual__c</fullName>
    <description>US-0010687 - New Field on Customer 360 and modifications to Seller Risk process</description>
    <label>Risk Tier (manual)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/EBH_ActualStandard__c.field-meta.xml
<CustomField>
    <fullName>EBH_ActualStandard__c</fullName>
    <formula>TEXT(Account.EBH_ActualStandard__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Standard</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_OracleId__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleId__c</fullName>
    <description>[EBH] (EPH-52) : Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID</inlineHelpText>
    <label>Oracle Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/EBH_DWH.recordType-meta.xml
<RecordType>
    <fullName>EBH_DWH</fullName>
    <active>true</active>
    <description>Contact that comes from DW Warehouse</description>
    <label>DWH</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Seller_Portal.recordType-meta.xml
<RecordType>
    <fullName>Seller_Portal</fullName>
    <active>true</active>
    <label>Seller Portal</label>
</RecordType>

unpackaged/main/default/classes/BatchDeactivateIneligiblePortalUsersTest.cls
@isTest
public with sharing class BatchDeactivateIneligiblePortalUsersTest {

    @TestSetup
    static void makeData(){
        User[] admins = [Select Id From User WHERE Profile.Name ='System Administrator' AND IsActive=TRUE LIMIT 2];
        RecordType recSeller = ApexUtil.getRecordTypeByName('Account', 'EBH_Seller');

        Account portalAccount1, portalAccount2,portalAccount3;
        Contact contact1,contact2,contact3;
        System.runAs(admins[0])
        {
            //Create account
            portalAccount1 = new Account(
                EBH_OracleId__c='1003293591',
                Name='Test Acc1',
                Risk_tier_manual__c=1,
                RecordTypeID = recSeller.Id,
                EBH_RevRollup__c='US',
                EBH_DealsProgram__c ='Accepted',
                EBH_VeROViolation__c = true,
                EBH_PredictedStandard__c = 'Above Standard',
                EBH_GMVLast12Months__c= 48000,
                EBH_ActualStandard__c='Below Standard',
                EBH_LastSellDate__c= Date.today().addDays(-89)
            );

            portalAccount2 = new Account(
                EBH_OracleId__c='1004444444',
                Name='Test Acc2',
                Risk_tier_manual__c=1,
                RecordTypeID = recSeller.Id,
                EBH_RevRollup__c='US',
                EBH_DealsProgram__c ='Accepted',
                EBH_VeROViolation__c =false,
                EBH_PredictedStandard__c = 'ETRS',
                EBH_GMVLast12Months__c= 58000,
                EBH_ActualStandard__c='Above Stardard',
                EBH_LastSellDate__c= Date.today().addDays(-91)
            );
            portalAccount3 = new Account(
                EBH_OracleId__c='1004444664',
                Name='Test Acc3',
                Risk_tier_manual__c=1,
                RecordTypeID = recSeller.Id,
                EBH_RevRollup__c='US',
                EBH_DealsProgram__c ='Accepted',
                EBH_VeROViolation__c =false,
                EBH_PredictedStandard__c = 'ETRS',
                EBH_GMVLast12Months__c= 58000,
                EBH_ActualStandard__c='Above Stardard',
                Below_SP_Standard_Date__c = Date.today().addDays(-100),
                EBH_LastSellDate__c= Date.today().addDays(-90)
            );
            insert new List<Account>{portalAccount1, portalAccount2, portalAccount3};
            RecordType recSP = ApexUtil.getRecordTypeByName('Contact', 'Seller_Portal');
            RecordType recDWH = ApexUtil.getRecordTypeByName('Contact', 'EBH_DWH');
            contact1 = new Contact(
                FirstName = 'Test1111111111',
                Lastname = 'AMT_TEST',
                AccountId = portalAccount1.Id,
                Email = System.now().millisecond() + 'test1@test.com',
                RecordTypeId=recSP.Id
            );
            contact2 = new Contact(
                FirstName = 'Test',
                Lastname = 'test con2',
                AccountId = portalAccount2.Id,
                Email = System.now().millisecond() + 'test2@test.com',
                RecordTypeId=recDWH.Id
            );
            contact1 = new Contact(
                FirstName = 'Test1111111111',
                Lastname = 'AMT_TEST',
                AccountId = portalAccount1.Id,
                Email = System.now().millisecond() + 'test1@test.com',
                RecordTypeId=recSP.Id
            );
            contact3 = new Contact(
                FirstName = 'Test',
                Lastname = 'test con3',
                AccountId = portalAccount3.Id,
                Email = System.now().millisecond() + 'test3@test.com',
                RecordTypeId=recDWH.Id
            );
            insert new Contact[]{contact1,contact2,contact3};

            AccountContactRelation acr =  new AccountContactRelation(ContactId=contact1.Id,AccountId=portalAccount2.Id,IsActive=True);
            insert acr;
        }
        System.runAs(admins[1])
        {
            //Create user
            Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'NA - Seller Portal' LIMIT 1];
            Profile portalProfileDE = [SELECT Id FROM Profile WHERE Name = 'DE - Seller Portal' LIMIT 1];
            User user1 = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = contact1.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'AMT_TEST',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            User user2 = new User(
                Username = System.now().millisecond() + 'test2@test.com',
                ContactId = contact2.Id,
                ProfileId = portalProfileDE.Id,
                Alias = 'test2',
                Email = 'test2@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Test2',
                CommunityNickname = 'test2',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            User user3 = new User(
                Username = System.now().millisecond() + 'test3@test.com',
                ContactId = contact3.Id,
                ProfileId = portalProfileDE.Id,
                Alias = 'test3',
                Email = 'test3@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Test3',
                CommunityNickname = 'test3666',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            insert new User[]{user1,user2,user3};
        }   

    }
    static testMethod void testDeactivateIneligiblePortalUsers(){
        Test.startTest();
            Database.executeBatch(new BatchDeactivateIneligiblePortalUsers());
        Test.stopTest();
    }
}