unpackaged/main/default/objects/Account/fields/BoB_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>BoB_Subsegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <inlineHelpText>A seller can be managed by one of the following groups: Category Mgmt. (Focus), Platin AMs (Platin &amp; Bolt-On) or GCX (MSO). If a seller is not part of a BoB the value will appear blank.</inlineHelpText>
    <label>Managed Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-on</fullName>
            </value>
            <value>
                <fullName>UK MSO Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBCNTRY__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBCNTRY__c</fullName>
    <description>[EBH] (EPH-2539) -  BOB COUNTRY</description>
    <inlineHelpText>Country where seller is managed.</inlineHelpText>
    <label>Managed Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>193</fullName>
                <label>CH</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>186</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>163</fullName>
                <label>PL</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>IE</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>NL</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Small Site</label>
            </value>
            <value>
                <fullName>168</fullName>
                <label>EEC-Unsited</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CA</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>AT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBManaged__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBManaged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-1901) - BOB Managed</description>
    <inlineHelpText>Sellers who are managed by Seller Growth Verticals or GCX (MSO).</inlineHelpText>
    <label>Managed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBSegment__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBSegment__c</fullName>
    <description>[EBH] (EPH-1901) - BOB Seller Segment</description>
    <inlineHelpText>A seller can be managed by Seller Growth Verticals (MANAGED) or GCX (MSO). If a seller is not part of the BOB this value will appear blank.</inlineHelpText>
    <label>Managed Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Pro-Trader Cat</fullName>
            </value>
            <value>
                <fullName>PT LTAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBVertical__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBVertical__c</fullName>
    <description>[EBH] (EPH-1901) -  BOB Vertical</description>
    <inlineHelpText>Vertical where seller is managed.</inlineHelpText>
    <label>Managed Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>Collectibles</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>FMCG</fullName>
            </value>
            <value>
                <fullName>Home &amp; Garden</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parts &amp; Accessories</fullName>
            </value>
            <value>
                <fullName>Soft Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/BoB_Seller__c/BoB_Seller__c.object-meta.xml
<CustomObject>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Cohort Seller</label>
    <nameField>
        <displayFormat>BS-{0000000}</displayFormat>
        <label>Cohort Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohort Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BoB_Seller__c/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB__c.field-meta.xml
<CustomField>
    <fullName>BoB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller Mgmt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BOB__c.Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>BOB__c</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB_Cohort__c.field-meta.xml
<CustomField>
    <fullName>BoB_Cohort__c</fullName>
    <description>EPH-6473 BOB - SELLER RECORD &gt; RELATED Tab &gt; BOB SELLERS SECTION &gt; ADD ADDTIONAL FIELDS</description>
    <formula>BoB__r.Bob_Cohort__c</formula>
    <label>Managed Cohort</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB_Country__c.field-meta.xml
<CustomField>
    <fullName>BoB_Country__c</fullName>
    <description>EPH-6473 BOB - SELLER RECORD &gt; RELATED Tab &gt; BOB SELLERS SECTION &gt; ADD ADDTIONAL FIELDS</description>
    <formula>TEXT( BoB__r.EBH_BOBCNTRY__c)</formula>
    <label>Managed Country</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>BoB_Subsegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Managed Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>UK MSO Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/EBH_BOBSegment__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBSegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Managed Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Extended Key</fullName>
            </value>
            <value>
                <fullName>Inventory Partners</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Pro-Trader Cat</fullName>
            </value>
            <value>
                <fullName>PT LTAM</fullName>
            </value>
            <value>
                <fullName>LTTM</fullName>
                <isActive>false</isActive>
                <label>LTTM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Parent_Seller__c.field-meta.xml
<CustomField>
    <fullName>Parent_Seller__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Parent Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Child_BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Seller does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/LTTM.recordType-meta.xml
<RecordType>
    <fullName>LTTM</fullName>
    <active>true</active>
    <label>LTTM</label>
</RecordType>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/Managed.recordType-meta.xml
<RecordType>
    <fullName>Managed</fullName>
    <active>true</active>
    <label>Managed</label>
</RecordType>

unpackaged/main/default/classes/BoBSellerTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class BoBSellerTriggerHandlerTest {
	/*
    static testMethod void testPopulateBoBFieldsToSeller() {
        List<Account> sellers = EBH_TestDataFactory.createAccounts(2, 'EBH_Seller');
        Test.startTest();
            BoB__c bob = new BoB__c(Status__c='Draft',EBH_BOBCNTRY__c='3',EBH_BOBVertical__c='Fashion');
            insert bob;
            BoB_Seller__c bs = new BoB_Seller__c(Account_Manager__c=UserInfo.getUserId(),Parent_Seller__c=sellers[0].Id,Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_NEW,Seller__c=sellers[0].Id,BoB__c = bob.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
            BoB_Seller__c bs2 = new BoB_Seller__c(Account_Manager__c=UserInfo.getUserId(),Parent_Seller__c=sellers[0].Id,Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_REMOVED,Seller__c=sellers[1].Id,BoB__c = bob.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
            insert new List<BoB_Seller__c>{bs,bs2};  
            bob.Status__c=EBH_ConstantsUtility.BOB_STATUS_ACTIVE;
            update bob;
            //delete bs;
        Test.stopTest();
        Account acc = [Select Id,EBH_BOBManaged__c,EBH_BOBCNTRY__c,EBH_BOBVertical__c,EBH_BOBSegment__c,BoB_Subsegment__c From Account Where Id=:sellers[0].Id];
         System.assertEquals(true,acc.EBH_BOBManaged__c,' acc.EBH_BOBManaged__c is true from BoB');
         System.assertEquals(acc.EBH_BOBCNTRY__c,EBH_ConstantsUtility.MAP_CODE_TO_COUNTRY.get(bob.EBH_BOBCNTRY__c),' bob country from bob to seller');
         System.assertEquals(bob.EBH_BOBVertical__c,acc.EBH_BOBVertical__c,' acc.EBH_BOBVertical__c is   from BoB');
         System.assertEquals(bs.EBH_BOBSegment__c,bs.EBH_BOBSegment__c,' acc.EBH_BOBSegment__c is   from BoB');
         System.assertEquals(bs.BoB_Subsegment__c,acc.BoB_Subsegment__c,' acc.BoB_Subsegment__c is   from BoB');
    }
    */
    static testMethod void testValidateBoBSeller()
    {
        User existAdmin = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

        BoBSellerViewControllerTest.setUpUserGroup();
        List<Account> sellers = EBH_TestDataFactory.createAccounts(3, 'EBH_Seller');
        RecordType bobRecordTypeManage = ApexUtil.getRecordTypeByName('BOB__c',EBH_ConstantsUtility.BOB_MANAGE_RECORDTYPE);
        RecordType bobSellerRecordTypeManaged = ApexUtil.getRecordTypeByName('BoB_Seller__c','Managed');
        Test.startTest();
            BoB__c bob = new BoB__c(RecordTypeId = bobRecordTypeManage.Id ,Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_DRAFT,/*BoB_Cohort__c='2018',*/EBH_BOBCNTRY__c='Spain',EBH_BOBVertical__c='Fashion');
            insert bob;
            BoB_Seller__c bs = new BoB_Seller__c(RecordTypeId = bobSellerRecordTypeManaged.Id,Account_Manager__c=UserInfo.getUserId(),Parent_Seller__c=sellers[0].Id,Seller__c=sellers[0].Id,BoB__c = bob.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
            insert bs;  
        Test.stopTest();
        //test duplicate
        BoB_Seller__c bs2 = new BoB_Seller__c(RecordTypeId = bobSellerRecordTypeManaged.Id,Account_Manager__c=UserInfo.getUserId(),Parent_Seller__c=sellers[0].Id,Seller__c=sellers[1].Id,BoB__c = bob.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
        insert bs2;
        try
        {
            bs2.Seller__c=sellers[0].Id;
            update bs2;
        }catch(Exception ex)
        {
            System.assert(ex.getDmlMessage(0).startsWith(System.Label.ErrorSellerDuplicate.substring(0,10)),'duplicate error');
        }
        //test seller occupied by another active bob
        BoB__c bob2 = new BoB__c(RecordTypeId = bobRecordTypeManage.Id ,Status__c=EBH_ConstantsUtility.BOB_STATUS_ACTIVE/*,BoB_Cohort__c='2018'*/,EBH_BOBCNTRY__c='3',EBH_BOBVertical__c='Fashion');
        insert bob2;
        BoB_Seller__c bs3 = new BoB_Seller__c(RecordTypeId = bobSellerRecordTypeManaged.Id,Account_Manager__c=UserInfo.getUserId(),Parent_Seller__c=sellers[0].Id,Seller__c=sellers[2].Id,BoB__c = bob2.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
        insert bs3;
//        BoB__c bob4 = new BoB__c(Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_DRAFT,BoB_Cohort__c='2018',EBH_BOBCNTRY__c=null,EBH_BOBVertical__c='Fashion');
        BoB__c bob4 = new BoB__c(RecordTypeId = bobRecordTypeManage.Id , Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_DRAFT,EBH_BOBCNTRY__c='Portugal',EBH_BOBVertical__c='Fashion');
        insert bob4;
        BoB_Seller__c bs4 = new BoB_Seller__c(RecordTypeId = bobSellerRecordTypeManaged.Id,Account_Manager__c=UserInfo.getUserId(),Parent_Seller__c=sellers[0].Id,Seller__c=sellers[0].Id,BoB__c = bob4.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
        try
        {
            insert bs4;
        }catch(Exception ex)
        {
            system.debug('>>>error: '+ex.getDmlMessage(0));
            System.assert(ex.getDmlMessage(0).startsWith(System.Label.ErrorSellerPartOfActiveBoB.substring(0,10)),'error: bob seller occupied by another aticve bob');
        }
        //test delete
        try
        {
            delete bs;
        }catch(Exception ex)
        {
            System.assert(ex.getMessage().contains(System.Label.ErrorBoBSellerDelete),'error: only New can be deleted');
        }
        //test assignAccountManagerToSellerOwner
        List<User> admUsers = EBH_TestDataFactory.createUsers(1, 'System Administrator');
        admUsers[0].BoB_Country__c = '3';

        System.runAs(existAdmin){
            insert admUsers;
        }

        
        System.runAs(admUsers[0])
        {
        	Group gcxOp = [Select Id,Name,DeveloperName From Group Where DeveloperName =:EBH_ConstantsUtility.BOB_GROUP_BOB_GCX_OPERATIONS];
        	GroupMember gm1 = new GroupMember(UserOrGroupId=admUsers[0].Id,GroupId=gcxOp.Id);
        	insert gm1;
        }
        bs3.Account_Manager__c = admUsers[0].Id;
        update bs3;
        /*
        Account selAccount = [Select Id,OwnerId from Account where Id=:sellers[2].Id];
        System.assertEquals(bs3.Account_Manager__c,selAccount.OwnerId,'Owner updated from BoBSeller Account Manager');
        */
    }
    static testMethod void testpopulateBobSeller(){

        User existAdmin = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

    	RecordType bobRecordTypeLTTM = ApexUtil.getRecordTypeByName('BOB__c',EBH_ConstantsUtility.BOB_LTTM_RECORDTYPE);
    	RecordType bobSellerRecordTypeLttm = ApexUtil.getRecordTypeByName('BoB_Seller__c','LTTM');
    	List<User> admUsers = EBH_TestDataFactory.createUsers(1, 'System Administrator');
        admUsers[0].BoB_Country__c = '3';
        System.runAs(existAdmin){
            insert admUsers;
        }
        List<Account> sellers = EBH_TestDataFactory.createAccounts(1, 'EBH_Seller');
    	 Test.startTest();
            BoB__c bob = new BoB__c(Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_DRAFT,EBH_BOBCNTRY__c='Spain',EBH_BOBVertical__c='Fashion',RecordTypeId = bobRecordTypeLTTM.Id,Account_Manager__c = admUsers[0].Id);
            insert bob;
            BoB_Seller__c bs = new BoB_Seller__c(RecordTypeId = bobSellerRecordTypeLttm.Id,Account_Manager__c=UserInfo.getUserId(),Seller__c=sellers[0].Id,BoB__c = bob.Id,EBH_BOBSegment__c='MSO',BoB_Subsegment__c='Platin');
            insert bs;  
        Test.stopTest();
        BoB_Seller__c bss = [select Account_Manager__c, Parent_Seller__c,Seller__c, EBH_BOBSegment__c from BoB_Seller__c where id =: bs.Id];
        System.assertEquals(bss.Account_Manager__c,bob.Account_Manager__c,'auto populate bobSeller.Account Manager = bob.Account Manager');
        System.assertEquals(bss.Parent_Seller__c,bss.Seller__c,'set "Parent Seller" = seller if Parent Seller is empty');
        //System.assertEquals(bss.EBH_BOBSegment__c,EBH_ConstantsUtility.BOB_SELLER_SEGMENT_LTTM,'set default Segment to LTTM for LTTML bob record type');
    }


    @isTest
    private static void testUpdateUserAvailibilityWithBobSeller(){
        insert new EBH_ActiveTriggers__c(Name = 'EBH Trigger Controller',UserAvailabilityTrigger__c = true, EBH_TaskTrigger__c = true);

        RecordType bobRecordTypeLTTM = ApexUtil.getRecordTypeByName('BOB__c',EBH_ConstantsUtility.BOB_LTTM_RECORDTYPE);
    	RecordType bobSellerRecordTypeLTTM = ApexUtil.getRecordTypeByName('BoB_Seller__c','LTTM');
        
        BoB__c bob = new BoB__c(
            RecordTypeId = bobRecordTypeLTTM.Id ,
            Name='Bob 1',
            Status__c = 'BoB Active',
            Managed_Type__c = 'LTTM Managed'
        );
        insert bob;
        
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
 		Account seller = new Account(Name='Seller',RecordTypeID = sellerRecordType.Id);
        Account seller1 = new Account(Name='Seller222',RecordTypeID = sellerRecordType.Id);
        insert new List<Account>{seller,seller1};

        Id currentUserId = UserInfo.getUserId();

        Date d = Date.newInstance(Date.today().year(), Date.today().month(), Date.today().day());
        Datetime dt = (DateTime)d;
        String dow = dt.format('EEEE');
        if (dow == 'Saturday') d = Date.today().addDays(3);
        else if (dow == 'Sunday') d = Date.today().addDays(2);
        
        BOB_Seller__c bobSeller = new BOB_Seller__c(
            RecordTypeId = bobSellerRecordTypeLTTM.Id ,
            BOB__c=bob.Id, 
            Seller__c=seller.Id,
            Next_Call_Schedule_Date__c = d,
            Time_Slot__c = 'Morning (9 AM to 12 PM)'
        );
        
        insert bobSeller;
        
        bobSeller.Account_Manager__c = currentUserId;
        update bobSeller;



        Test.startTest();
            User_Availability__c uv = new User_Availability__c(Date__c=d, Unique_Id__c=(currentUserId+'#'+d), Available_Calls_Morning_Slot__c = 4, Available_Calls_Afternoon_Slot__c = 4, OwnerId=currentUserId);
            insert uv;
            uv = [Select Id, Date__c, Unique_Id__c, Scheduled_Calls_Morning_Slot__c, Scheduled_Calls_Afternoon_Slot__c From User_Availability__c Where Id =: uv.Id];
            System.assertEquals(1, uv.Scheduled_Calls_Morning_Slot__c);
            System.assertEquals(null, uv.Scheduled_Calls_Afternoon_Slot__c);

            BOB_Seller__c bobSeller1 = new BOB_Seller__c(
                RecordTypeId = bobSellerRecordTypeLTTM.Id ,
                BOB__c=bob.Id, 
                Seller__c=seller1.Id,
                Next_Call_Schedule_Date__c = d,
                Time_Slot__c = 'Afternoon(1 PM to 5 PM)'
            );

            insert bobSeller1;
            bobSeller1.Account_Manager__c = currentUserId;
            update bobSeller1;

            uv = [Select Id, Date__c, Unique_Id__c, Scheduled_Calls_Morning_Slot__c, Scheduled_Calls_Afternoon_Slot__c From User_Availability__c Where Id =: uv.Id];
            System.assertEquals(1, uv.Scheduled_Calls_Morning_Slot__c);
            System.assertEquals(1, uv.Scheduled_Calls_Afternoon_Slot__c);

        Test.stopTest();
    }
}