unpackaged/main/default/objects/Account/fields/BoB_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>BoB_Subsegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <inlineHelpText>A seller can be managed by one of the following groups: Category Mgmt. (Focus), Platin AMs (Platin &amp; Bolt-On) or GCX (MSO). If a seller is not part of a BoB the value will appear blank.</inlineHelpText>
    <label>Managed Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-on</fullName>
            </value>
            <value>
                <fullName>UK MSO Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBCNTRY__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBCNTRY__c</fullName>
    <description>[EBH] (EPH-2539) -  BOB COUNTRY</description>
    <inlineHelpText>Country where seller is managed.</inlineHelpText>
    <label>Managed Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>193</fullName>
                <label>CH</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>186</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>163</fullName>
                <label>PL</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>IE</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>NL</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Small Site</label>
            </value>
            <value>
                <fullName>168</fullName>
                <label>EEC-Unsited</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CA</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>AT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBSegment__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBSegment__c</fullName>
    <description>[EBH] (EPH-1901) - BOB Seller Segment</description>
    <inlineHelpText>A seller can be managed by Seller Growth Verticals (MANAGED) or GCX (MSO). If a seller is not part of the BOB this value will appear blank.</inlineHelpText>
    <label>Managed Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Pro-Trader Cat</fullName>
            </value>
            <value>
                <fullName>PT LTAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBVertical__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBVertical__c</fullName>
    <description>[EBH] (EPH-1901) -  BOB Vertical</description>
    <inlineHelpText>Vertical where seller is managed.</inlineHelpText>
    <label>Managed Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>Collectibles</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>FMCG</fullName>
            </value>
            <value>
                <fullName>Home &amp; Garden</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parts &amp; Accessories</fullName>
            </value>
            <value>
                <fullName>Soft Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_StoreSubscription__c.field-meta.xml
<CustomField>
    <fullName>EBH_StoreSubscription__c</fullName>
    <description>[EBH] (EPH-2857) - The subscription level of the store</description>
    <inlineHelpText>Seller´s store subscription Level. Potential values are:
- No Store
- Basic (On eBay.de the Level is called Basis Shop)
- Featured/Premium (On eBay.de the Level is called Top Shop)
- Anchor (On eBay.de the Level is called Premium Shop)
- Platinum</inlineHelpText>
    <label>Store Subscription Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Anchor</fullName>
            </value>
            <value>
                <fullName>Featured / Premium</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Managed_Type__c.field-meta.xml
<CustomField>
    <fullName>Managed_Type__c</fullName>
    <description>US-0007674 - Add new field &quot;Managed Type&quot; in Account and sync values with BoB_Seller__c</description>
    <label>Managed Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others Managed</fullName>
                <label>Focus</label>
            </value>
            <value>
                <fullName>LTTM Managed</fullName>
                <label>Pro-Trader</label>
            </value>
            <value>
                <fullName>LTTM Plus</fullName>
            </value>
            <value>
                <fullName>Managed BoB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/BoB_Seller__c.object-meta.xml
<CustomObject>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Cohort Seller</label>
    <nameField>
        <displayFormat>BS-{0000000}</displayFormat>
        <label>Cohort Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohort Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BoB_Seller__c/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB__c.field-meta.xml
<CustomField>
    <fullName>BoB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller Mgmt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BOB__c.Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>BOB__c</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>BoB_Subsegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Managed Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>UK MSO Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/EBH_BOBSegment__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBSegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Managed Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Extended Key</fullName>
            </value>
            <value>
                <fullName>Inventory Partners</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Pro-Trader Cat</fullName>
            </value>
            <value>
                <fullName>PT LTAM</fullName>
            </value>
            <value>
                <fullName>LTTM</fullName>
                <isActive>false</isActive>
                <label>LTTM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Managed_Type__c.field-meta.xml
<CustomField>
    <fullName>Managed_Type__c</fullName>
    <description>US-0007598 - [LTTM] New field in BoB__c and BoB_Seller__c</description>
    <formula>TEXT(BoB__r.Managed_Type__c)</formula>
    <label>Managed Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Seller does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/Managed.recordType-meta.xml
<RecordType>
    <fullName>Managed</fullName>
    <active>true</active>
    <label>Managed</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Accepted_Current_Deals_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Current_Deals_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Current Deals Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/EBH_ActiveTriggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>[EBH] (EPH-5) Active trigger controller - to switch on/off and bypass for deployment or data migration</description>
    <label>Active Triggers</label>
</CustomObject>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/fields/Subscription_Request_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Request_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>US-0010561 - [AM] Store Account Manager Subscription Requests in Hive</description>
    <label>Subscription_Request_Trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AccountManagementControllerTest.cls
/*********************************************************************************************************************************
@ Class:          AccountManagementControllerTest
@ Version:        1.0
@ Author:         Sochettra Saing
@ Purpose:        Ability to run test the logic in class AccountManagementController(EBAY-749)
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 22.10.2021 / Sochettra Saing / Created the class.
*********************************************************************************************************************************/

@isTest 
public with sharing class AccountManagementControllerTest {
    @testSetup
    static void setup(){
        //create an account
        Account acc = new Account( Name = 'TestAccount', EBH_StoreSubscription__c = 'Anchor');//Basic
        insert acc;
        Account acc2 = new Account( Name = 'TestAccount2', EBH_StoreSubscription__c = 'Anchor');//Basic
        insert acc2;

        //create a contact
        Contact con = new Contact(Accepted_Current_Deals_Agreement__c=false,
                                    FirstName='test fn', LastName='test ln', AccountId=acc.Id, Email = 'test123@test.com');
        insert con;

        //create Custom Setting record for EBH_ActiveTriggers__c
        insert new EBH_ActiveTriggers__c(Name = 'EBH Trigger Controller', Subscription_Request_Trigger__c = false);

        Profile adminProfile = [select Id,Name from Profile where Name = 'System Administrator'];
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];

        User adminUser = new User();
        adminUser.Alias='admin';
        adminUser.Email='admintest@ebay.com';
        adminUser.EmailEncodingKey='UTF-8';
        adminUser.LastName='AdminUser';
        adminUser.LanguageLocaleKey='en_US';
        adminUser.LocaleSidKey='en_US';
        adminUser.ProfileId = adminProfile.Id;
        adminUser.TimeZoneSidKey='America/Los_Angeles';
        adminUser.UserName='adminprofile@ebay.com';
        
        User currentUser = [Select Id,Name from User where Id=: UserInfo.getUserId()];
        
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,
                                Alias = 'testU',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'de_DE',
                                LanguageLocaleKey = 'de'
                                );
        System.runAs(currentUser) {
            insert new List<User>{adminUser,user1};
        }
    }

    @IsTest
    static void testMethod1(){

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        /*User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );*/
        User user1 = [SELECT Id,name From User WHERE Alias='testU' limit 1];
        
        Test.startTest(); 

        System.runAs(user1) {
            Account acc1 = AccountManagementController.getStoreSubscription();
            System.assertEquals('Store Subscription Level:Anchor','Store Subscription Level:'+ acc1.EBH_StoreSubscription__c);
            Account accName = AccountManagementController.getAccountName();
            System.assertEquals('Account Name:TestAccount','Account Name:'+ accName.Name);

            Map<String,Object> mapResult1 =  AccountManagementController.getSellerInfo();

            Map<String,Object> mapResult2 = AccountManagementController.createSubscription();
            Subscription_Request__c[] srequest = [Select Id from Subscription_Request__c];
            System.assert(!srequest.isEmpty(),'subscription request created');
        }
        Test.stopTest();
    }

    @IsTest
    static void testMethod2(){

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];

        //Create Active Initial Cohort Seller
        BoB__c bob = new BoB__c(Status__c='Draft',EBH_BOBCNTRY__c='3',EBH_BOBVertical__c='Fashion',Managed_Type__c ='Others Managed');
        insert bob;
        RecordType bobSellerRecordTypeManaged = ApexUtil.getRecordTypeByName('BoB_Seller__c','Managed');
        BoB_Seller__c bs = new BoB_Seller__c(
            RecordTypeId = bobSellerRecordTypeManaged.Id,
            Account_Manager__c = UserInfo.getUserId(),
            Status__c = 'New',
            Seller__c = acc.Id,
            BoB__c = bob.Id,
            EBH_BOBSegment__c = 'MSO',
            BoB_Subsegment__c = 'Platin'
        );

        insert new List<BoB_Seller__c>{bs};  
        bob.Status__c = 'BoB Active';
        update bob;

        List<Subscription_Request__c> srequest = new List<Subscription_Request__c>();
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];

        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        User admin = [SELECT Id,name From User WHERE Alias='admin' limit 1];
       	User user1 = [SELECT Id,name From User WHERE Alias='testU' limit 1];
        Test.startTest(); 

        System.runAs(user1) {
            Account acc1 = AccountManagementController.getStoreSubscription();
            System.assertEquals('Store Subscription Level:Anchor','Store Subscription Level:'+ acc1.EBH_StoreSubscription__c);
            Account accName = AccountManagementController.getAccountName();
            System.assertEquals('Account Name:TestAccount','Account Name:'+ accName.Name);

            Map<String,Object> mapResult1 =  AccountManagementController.getSellerInfo();

            Map<String,Object> mapResult2 = AccountManagementController.createSubscription();
            srequest = [Select Id, Seller__c from Subscription_Request__c];
            System.assert(!srequest.isEmpty(),'subscription request created');

        }
        System.runAs(admin) {

            for (Subscription_Request__c sr : srequest) { sr.Initial_Cohort_Seller__c = bs.Id; }
    
            update srequest;
        }
        System.runAs(user1) {
            Map<String,Object> mapResult1 =  AccountManagementController.getActiveCohortSeller();

            User usr = (User) mapResult1.get('accountMgmtInfo');

            System.assert( usr != null && usr.Id != null, 'There is an Account Manager');
        }

        Test.stopTest();
        
    }

    @IsTest
    static void testMethod3(){

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];

        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];

        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        List<Subscription_Request__c> srequest = new List<Subscription_Request__c>();
        
        User admin = [SELECT Id,name From User WHERE Alias='admin' limit 1];
        User user1 = [SELECT Id,name From User WHERE Alias='testU' limit 1];
        
        Test.startTest(); 

        System.runAs(user1) {
            Account acc1 = AccountManagementController.getStoreSubscription();
            System.assertEquals('Store Subscription Level:Anchor','Store Subscription Level:'+ acc1.EBH_StoreSubscription__c);
            Account accName = AccountManagementController.getAccountName();
            System.assertEquals('Account Name:TestAccount','Account Name:'+ accName.Name);

            Map<String,Object> mapResult1 =  AccountManagementController.getSellerInfo();

            Map<String,Object> mapResult2 = AccountManagementController.createSubscription();
            srequest = [Select Id,Seller__c,Status__c from Subscription_Request__c];
        }
        System.runAs(admin) {
        
            for (Subscription_Request__c sr : srequest) { sr.Status__c = 'Subscribed';} 
            update srequest;
        }
        System.runAs(user1) {
            Map<String,Object> mapResult1 =  AccountManagementController.requestUnsubscription();
             
            Subscription_Request__c[] srequest1 = [Select Id,Status__c from Subscription_Request__c];
            System.assert(!srequest1.isEmpty(),'Unsubscribe Request');
        }
        
        Test.stopTest();
    }

   
}