unpackaged/main/default/objects/Account/fields/BoB_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>BoB_Subsegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <inlineHelpText>A seller can be managed by one of the following groups: Category Mgmt. (Focus), Platin AMs (Platin &amp; Bolt-On) or GCX (MSO). If a seller is not part of a BoB the value will appear blank.</inlineHelpText>
    <label>Managed Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-on</fullName>
            </value>
            <value>
                <fullName>UK MSO Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBCNTRY__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBCNTRY__c</fullName>
    <description>[EBH] (EPH-2539) -  BOB COUNTRY</description>
    <inlineHelpText>Country where seller is managed.</inlineHelpText>
    <label>Managed Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>193</fullName>
                <label>CH</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>186</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>163</fullName>
                <label>PL</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>IE</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>NL</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Small Site</label>
            </value>
            <value>
                <fullName>168</fullName>
                <label>EEC-Unsited</label>
            </value>
            <value>
                <fullName>77</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CA</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>AT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBSegment__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBSegment__c</fullName>
    <description>[EBH] (EPH-1901) - BOB Seller Segment</description>
    <inlineHelpText>A seller can be managed by Seller Growth Verticals (MANAGED) or GCX (MSO). If a seller is not part of the BOB this value will appear blank.</inlineHelpText>
    <label>Managed Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Pro-Trader Cat</fullName>
            </value>
            <value>
                <fullName>PT LTAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBVertical__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBVertical__c</fullName>
    <description>[EBH] (EPH-1901) -  BOB Vertical</description>
    <inlineHelpText>Vertical where seller is managed.</inlineHelpText>
    <label>Managed Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>Collectibles</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>FMCG</fullName>
            </value>
            <value>
                <fullName>Home &amp; Garden</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parts &amp; Accessories</fullName>
            </value>
            <value>
                <fullName>Soft Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Managed_Type__c.field-meta.xml
<CustomField>
    <fullName>Managed_Type__c</fullName>
    <description>US-0007674 - Add new field &quot;Managed Type&quot; in Account and sync values with BoB_Seller__c</description>
    <label>Managed Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others Managed</fullName>
                <label>Focus</label>
            </value>
            <value>
                <fullName>LTTM Managed</fullName>
                <label>Pro-Trader</label>
            </value>
            <value>
                <fullName>LTTM Plus</fullName>
            </value>
            <value>
                <fullName>Managed BoB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/BoB_Seller__c/BoB_Seller__c.object-meta.xml
<CustomObject>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Cohort Seller</label>
    <nameField>
        <displayFormat>BS-{0000000}</displayFormat>
        <label>Cohort Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohort Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BoB_Seller__c/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB__c.field-meta.xml
<CustomField>
    <fullName>BoB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller Mgmt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BOB__c.Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>BOB__c</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB_Subsegment__c.field-meta.xml
<CustomField>
    <fullName>BoB_Subsegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Managed Subsegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>UK MSO Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Call_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Call_Attempt__c</fullName>
    <description>US-0007450 - LTTM - Managed Sellers Layout changes</description>
    <label>Call Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Call_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Call_Outcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DMC Not reached</fullName>
            </value>
            <value>
                <fullName>Follow up Required</fullName>
            </value>
            <value>
                <fullName>Wrong Phone Number</fullName>
            </value>
            <value>
                <fullName>Next call scheduled</fullName>
            </value>
            <value>
                <fullName>DMC Committed</fullName>
            </value>
            <value>
                <fullName>DMC Not Committed</fullName>
            </value>
            <value>
                <fullName>Coaching ended</fullName>
            </value>
            <value>
                <fullName>Call rescheduled by seller</fullName>
            </value>
            <value>
                <fullName>Exited Coaching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/EBH_BOBSegment__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBSegment__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Managed Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Extended Key</fullName>
            </value>
            <value>
                <fullName>Inventory Partners</fullName>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Platin</fullName>
            </value>
            <value>
                <fullName>AM Bolt-On</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Pro-Trader Cat</fullName>
            </value>
            <value>
                <fullName>PT LTAM</fullName>
            </value>
            <value>
                <fullName>LTTM</fullName>
                <isActive>false</isActive>
                <label>LTTM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/LTTM_Group__c.field-meta.xml
<CustomField>
    <fullName>LTTM_Group__c</fullName>
    <description>US-0007540 - [LTTM] Create Actions - Feedback</description>
    <formula>HYPERLINK(&#39;/lightning/r/BOB__c/&#39; &amp; BoB__r.Id &amp;&#39;/view&#39;  ,  BoB__r.LTTM_Group__c , &#39;blank&#39;)</formula>
    <label>Seller Facing Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Managed_Type__c.field-meta.xml
<CustomField>
    <fullName>Managed_Type__c</fullName>
    <description>US-0007598 - [LTTM] New field in BoB__c and BoB_Seller__c</description>
    <formula>TEXT(BoB__r.Managed_Type__c)</formula>
    <label>Managed Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Parent_Seller__c.field-meta.xml
<CustomField>
    <fullName>Parent_Seller__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Parent Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Child_BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Seller does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/LTTM.recordType-meta.xml
<RecordType>
    <fullName>LTTM</fullName>
    <active>true</active>
    <label>LTTM</label>
</RecordType>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/Managed.recordType-meta.xml
<RecordType>
    <fullName>Managed</fullName>
    <active>true</active>
    <label>Managed</label>
</RecordType>

unpackaged/main/default/classes/TransferSellersControllerTest.cls
/*********************************************************************************************************************************
@ Class:          TransferSellersControllerTest
@ Version:        1.0
@ Author:         Loumang SENG (loumang.seng@gaea-sys.com)
@ Purpose:        test Class for TransferSellersController
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 10.06.2021 / Loumang SENG / Created the class			 
*********************************************************************************************************************************/
@isTest
private  class TransferSellersControllerTest {
    static Account acc;
    static Account acc2;
    static Contact cont;
    static Contact cont2;
    static BoB__c bob;
    static BoB__c bob2;
    static BoB__c bob3;
    static BoB_Seller__c bs;
    static BoB_Seller__c bs2;
    static Action_Template__c template1;
    static Action__c action1;
    static Action_Template__c template2;
    static Action__c action2;

    static void setUpData()
    {
         	RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
            acc = new Account(
                Name='Test Account',
                RecordTypeId=sellerRecordType.Id,
                Managed_Type__c = 'LTTM Managed'
            );
            acc2 = new Account(
                Name='Test Account2',
                RecordTypeId=sellerRecordType.Id,
                Managed_Type__c = 'LTTM Plus'
            );
            insert new List<Account>{acc,acc2};
    
            cont = new Contact(LastName='Last',AccountId=acc.Id);
            cont2 = new Contact(LastName='Last2',AccountId=acc2.Id);
            insert new List<Contact>{cont,cont2};
    
            RecordType boblttmRecordType = ApexUtil.getRecordTypeByName('BOB__c','Light_Touch_Category_Cohort');
            bob = new BoB__c(
                Status__c='BoB Active',
                EBH_BOBCNTRY__c='3',
                EBH_BOBVertical__c='Fashion',
                Managed_Type__c ='LTTM Managed',
                LTTM_Group__c='test group',
                RecordTypeId=boblttmRecordType.Id,
                ownerId = UserInfo.getUserId()
            );
            bob2 = new BoB__c(
                Status__c='BoB Active',
                EBH_BOBCNTRY__c='3',
                EBH_BOBVertical__c='Fashion',
                Managed_Type__c ='LTTM Managed',
                LTTM_Group__c='test group2',
                RecordTypeId=boblttmRecordType.Id,
                ownerId = UserInfo.getUserId()
            );
            bob3 = new BoB__c(
                Status__c='BoB Active',
                EBH_BOBCNTRY__c='3',
                EBH_BOBVertical__c='Fashion',
                Managed_Type__c ='LTTM Plus',
                LTTM_Group__c='test group3',
                RecordTypeId=boblttmRecordType.Id,
                ownerId = UserInfo.getUserId()
            );
            insert new List<BoB__c>{bob,bob2,bob3};
    
            RecordType bobSellerlttmRecordType = ApexUtil.getRecordTypeByName('BoB_Seller__c','LTTM');
    
            bs = new BoB_Seller__c(
                RecordTypeId = bobSellerlttmRecordType.Id,
                Parent_Seller__c=acc.Id,
                Account_Manager__c=UserInfo.getUserId(),
                Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_DRAFT,
                Seller__c=acc.Id,
                BoB__c = bob.Id,
                EBH_BOBSegment__c='MSO',
                BoB_Subsegment__c='Platin',
                Call_Outcome__c='Next call scheduled',
                Call_Attempt__c = 0
            );
            bs2 = new BoB_Seller__c(
                RecordTypeId = bobSellerlttmRecordType.Id,
                Parent_Seller__c=acc2.Id,
                Account_Manager__c=UserInfo.getUserId(),
                Status__c=EBH_ConstantsUtility.BOB_SELLER_STATUS_DRAFT,
                Seller__c=acc2.Id,
                BoB__c = bob3.Id,
                EBH_BOBSegment__c='MSO',
                BoB_Subsegment__c='Platin',
                Call_Outcome__c='Next call scheduled',
                Call_Attempt__c = 0
            );
    
            insert new List<BoB_Seller__c>{bs,bs2};
    
            template1 = new Action_Template__c(Name='Tempalte1',Active__c=true);
            insert template1;
    
            action1 = new Action__c(Name='Action1',Action_Template__c=template1.Id,LTTM_Seller__c=bs.Id,Status__c='Not Started');
            insert action1;
    
            template2 = new Action_Template__c(Name='Tempalte2',Active__c=true);
            insert template2;
    
            action2 = new Action__c(Name='Action2',Action_Template__c=template2.Id,LTTM_Seller__c=bs2.Id,Status__c='Not Started');
            insert action2;   
    }

    @IsTest
    static void testApexInit(){
        setUpData();
        Test.startTest(); 
            Map<String,Object> mapResult1 =  TransferSellersController.apexInit(bob2.Id,null);
            Map<String,Object> mapResult2 =  TransferSellersController.apexInit(bob3.Id,bs2.Id);
            Map<String,Object> mapResult3 =  TransferSellersController.apexInit(bob2.Id,bs.Id);
            //system.System.debug('size:::'+mapResult1);
            //System.assertEquals(1, ((List<BOB__C>)mapResult.get('listPossibleBob')).size(),'1 realted contact');

        Test.stopTest();
        
    }  

    @IsTest
    static void testApexSave(){
        setUpData();
        BoB_Seller__c bobSeller = new BoB_Seller__c(Account_Manager__c = UserInfo.getUserId(),TTEC_MANAGER__c=UserInfo.getUserId());

        Test.startTest();
            Map<String,Object> mapResult =  TransferSellersController.apexSave(bob2.Id,bs.Id,bobSeller);
        Test.stopTest();
        BoB_Seller__c bsSel = [Select Id,Name,BoB__c From BoB_Seller__c Where Id=:bs.Id];
        //System.assertEquals(bsSel.BoB__c, bob2.Id);
    }

    @isTest
    static void test_createaction() {
        setUpData();

        Test.startTest();
            List<BoB_Seller__c> lstbs = [select Id, BOB__c, RecordTypeId from BoB_Seller__c where BOB__c=:bob.Id AND RecordType.DeveloperName='LTTM' AND Managed_Type__c='LTTM Managed'];
            Test.setCurrentPage(Page.TransferSellers);

            ApexPages.currentPage().getParameters().put('id',bob.Id);

            ApexPages.StandardSetController sc = new ApexPages.StandardSetController(lstbs);
            sc.setSelected(new List<BoB_Seller__c>());
            TransferSellersController tc = new TransferSellersController(sc);
            sc.setSelected(lstbs);
            tc = new TransferSellersController(sc);
            //tc.backToListView();

            System.assert(String.isNotBlank(tc.bobId));
            System.assert(String.isNotBlank(tc.bobSellerIds));

        Test.stopTest();
    }

}