unpackaged/main/default/objects/Account/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Action_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Action_Outcome__c</fullName>
    <description>US-0018705 Merchant Support Group - Add Fields in Tasks for MSO,
US-0008531</description>
    <label>Action Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Highly engaged (committed)</fullName>
            </value>
            <value>
                <fullName>Engaged (listened but no commitment)</fullName>
            </value>
            <value>
                <fullName>Not engaged at present</fullName>
            </value>
            <value>
                <fullName>Not interested in Gold</fullName>
            </value>
            <value>
                <fullName>Unreachable - no action</fullName>
            </value>
            <value>
                <fullName>To be called back</fullName>
            </value>
            <value>
                <fullName>Unreachable - email sent</fullName>
            </value>
            <value>
                <fullName>Not reached (wrong details)</fullName>
            </value>
            <value>
                <fullName>Not reached ( failed call attempt)</fullName>
            </value>
            <value>
                <fullName>DMC Not Interested</fullName>
            </value>
            <value>
                <fullName>DMC Interested</fullName>
            </value>
            <value>
                <fullName>DMC Committed</fullName>
            </value>
            <value>
                <fullName>Seller ineligible</fullName>
            </value>
            <value>
                <fullName>Bounced Email</fullName>
                <isActive>false</isActive>
                <label>Bounced Email</label>
            </value>
            <value>
                <fullName>Busy</fullName>
                <isActive>false</isActive>
                <label>Busy</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <isActive>false</isActive>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>Left Message</fullName>
                <isActive>false</isActive>
                <label>Left Message</label>
            </value>
            <value>
                <fullName>Unable to Contact</fullName>
                <isActive>false</isActive>
                <label>Unable to Contact</label>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
                <isActive>false</isActive>
                <label>Wrong Number</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Call_attempts__c.field-meta.xml
<CustomField>
    <fullName>Call_attempts__c</fullName>
    <label>Call attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/EBH_Account__c.field-meta.xml
<CustomField>
    <fullName>EBH_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-4122) - to populate comments with Urgency Action and Urgency Reason</description>
    <label>Seller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/EBH_DMC__c.field-meta.xml
<CustomField>
    <fullName>EBH_DMC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-3664)</description>
    <label>DMC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Log_Task__c.field-meta.xml
<CustomField>
    <fullName>Log_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EPH-7946 Coupon Seller - attach the excel to the related</description>
    <label>Log Task</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/SR_Number__c.field-meta.xml
<CustomField>
    <fullName>SR_Number__c</fullName>
    <description>US-0007466 - [AU] Changes to AU Task Recordtype</description>
    <inlineHelpText>Enter the relevant SR number</inlineHelpText>
    <label>SR-Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Activity/fields/Task_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed_Date__c</fullName>
    <description>EPH-7879 &quot;Open Related Tasks&quot; and &quot;Completed Related Tasks&quot; tab in Task Detail Page</description>
    <label>Task Completed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/BoB_Seller__c.object-meta.xml
<CustomObject>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Cohort Seller</label>
    <nameField>
        <displayFormat>BS-{0000000}</displayFormat>
        <label>Cohort Seller Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohort Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BoB_Seller__c/fields/Advisor_Comments__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Comments__c</fullName>
    <description>US-0009514</description>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/BoB__c.field-meta.xml
<CustomField>
    <fullName>BoB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller Mgmt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BOB__c.Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>BOB__c</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Call_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Call_Attempt__c</fullName>
    <description>US-0007450 - LTTM - Managed Sellers Layout changes</description>
    <label>Call Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Call_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Call_Outcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DMC Not reached</fullName>
            </value>
            <value>
                <fullName>Follow up Required</fullName>
            </value>
            <value>
                <fullName>Wrong Phone Number</fullName>
            </value>
            <value>
                <fullName>Next call scheduled</fullName>
            </value>
            <value>
                <fullName>DMC Committed</fullName>
            </value>
            <value>
                <fullName>DMC Not Committed</fullName>
            </value>
            <value>
                <fullName>Coaching ended</fullName>
            </value>
            <value>
                <fullName>Call rescheduled by seller</fullName>
            </value>
            <value>
                <fullName>Exited Coaching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>US-0007452 - LTTM - Managed Sellers(Initiate call)
US-0009514- rename label</description>
    <inlineHelpText>This field is updated by Marketing Cloud with Pro-Trader Seller registration details.</inlineHelpText>
    <label>Pro-Trader registration details</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/LastCallDate__c.field-meta.xml
<CustomField>
    <fullName>LastCallDate__c</fullName>
    <description>US-0010363 - [AU] Last Call Date to be Captured at Cohort Seller Level</description>
    <inlineHelpText>Date when Latest Call attempt happened.</inlineHelpText>
    <label>Last Call Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/LTTM_Group__c.field-meta.xml
<CustomField>
    <fullName>LTTM_Group__c</fullName>
    <description>US-0007540 - [LTTM] Create Actions - Feedback</description>
    <formula>HYPERLINK(&#39;/lightning/r/BOB__c/&#39; &amp; BoB__r.Id &amp;&#39;/view&#39;  ,  BoB__r.LTTM_Group__c , &#39;blank&#39;)</formula>
    <label>Seller Facing Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Next_Call_Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Call_Schedule_Date__c</fullName>
    <description>US-0007450 - LTTM - Managed Sellers Layout changes</description>
    <label>Next Call Schedule Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Seller does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>BoB_Sellers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/SRNumber__c.field-meta.xml
<CustomField>
    <fullName>SRNumber__c</fullName>
    <description>US-0010363 - [AU] Last Call Date to be Captured at Cohort Seller Level</description>
    <label>SR Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>EPH-5727 BOB MGMT - Seller BOB Object - Fields</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/LTTM.recordType-meta.xml
<RecordType>
    <fullName>LTTM</fullName>
    <active>true</active>
    <label>LTTM</label>
</RecordType>

unpackaged/main/default/objects/BoB_Seller__c/recordTypes/Managed.recordType-meta.xml
<RecordType>
    <fullName>Managed</fullName>
    <active>true</active>
    <label>Managed</label>
</RecordType>

unpackaged/main/default/objects/Task/recordTypes/X3CallAttempts.recordType-meta.xml
<RecordType>
    <fullName>X3CallAttempts</fullName>
    <active>true</active>
    <description>record type for task with 3 call attempts</description>
    <label>3CallAttempts</label>
</RecordType>

unpackaged/main/default/classes/ManageSellerInitiateCallController.cls
/*********************************************************************************************************************************
@ Class:        ManageSellerInitiateCallController
@ Version:      1.0
@ Author:       vadhanak.voun (vadhanak.voun@gaea-sys.com)
@ Purpose:      US-0007452 - LTTM - Managed Sellers(Initiate call)
@				Controller for aura: ManageSellerInitiate
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 22.04.2020 / vadhanak.voun (vadhanak.voun@gaea-sys.com) / Created the class.
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 30.07.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Modify a method.
*********************************************************************************************************************************/
public without sharing class ManageSellerInitiateCallController {
	
	final static String TASK_TYPE_GCC = 'Growth Coaching Call';
	private final static String AU_PROFILE = 'AU Standard User Profile';

	/*****************************************************************************************************************************
    @ Method:   apexInit
    @ Version:  1.0
    @ Author:   Vadhanak Voun (vadhanak.voun@gaea-sys.com)
    @ Purpose:  US-0007452 - LTTM - Managed Sellers(Initiate call)
	@		    Init list for component
	@		Validation on the button "Initiate call"
	@		LTTM Agent (Standard user profile user)cannot click "Initiate call" with seller if BoB_seller has NO associated Actions
	@		On Click of “Initiate Call” check
	@		if the BoB_seller has associated Actions
	@		If yes proceed with the Initiate call flow
	@		If no Actions throw below error message
	@		Error Message
	@		Click “Create Actions” to create the Actions for each of the LTTM Sellers before initiating the call with Seller.
    @------------------------------------------------------------------------------------------------------------------------------
    @ Parameter:      String bob seller id
    ------------------------------------------------------------------------------------------------------------------------------
	@ Change history: 24.04.2020 / Vadhanak Voun / Created the  Method.
	@				: 23/06/2020 / Vadhanak Voun / US-0007763 - [Hyper Care] "DMC Not Committed" label not appearing once the mass Edit of Action Outcome is saved
	@							 label has been renamed but value still the same. datatable can not reflect the change
	@				: 06/08/2021 / Sovantheany Dim/ US-0010034 : hide colum Seller facing Dashboard message from Action Table for GCX
	@				: 15.10.2021/ vadhanak voun (vadhanak.voun@gaea-sys.com) / US-0010579 - [AU] Remove Visibility of Activity.SR Number for AU Standard user profile users
    *****************************************************************************************************************************/
	
	@AuraEnabled
	public static Map<String,Object> apexInit(String recordId) {
		Map<String,Object> mapResult = new Map<String,Object>();
		
		//SOQL_BOBSELLER
		//LA:20-09-2021:US-0010363: add two fields SRNumber__c,LastCallDate__c in query
        List<BoB_Seller__c> bseller = [Select  SRNumber__c,LastCallDate__c,Advisor_Comments__c,Call_Attempt__c,Next_Call_Schedule_Date__c,Comments__c,Name, Call_Outcome__c, Status__c,Id,Seller__c,LTTM_Group__c,BoB__r.LTTM_Group__c,(Select Id From Actions__r limit 1) from BoB_Seller__c where Id =:recordId];
        //System.debug('>>recordId: '+ recordId +' >>:bseller:  '+bseller);
        if(bseller[0].Actions__r.isEmpty())
        {
        	mapResult.put('status','ko');
        	mapResult.put('error','vadlidation error');
        }else
        {
			Boolean isAUProfileOnly = Userinfo.getprofileId()== ApexUtil.getProfileByName(AU_PROFILE).Id; //NK:15/10/2021:US-0010579
			//LA:20-09-2021:US-0010363
			Boolean isAUProfile = (Userinfo.getprofileId()== ApexUtil.getProfileByName(AU_PROFILE).Id || UserInfo.getProfileId().equals(EBH_ConstantsUtility.ADMIN_PROFILE_ID));//Loumang:20-09-2021:US-0010363
			//System.debug('isAUProfile::'+isAUProfile);
        	Set<Id> sellerId = new Set<Id>();
	        for (BoB_Seller__c oneSeller : bseller) {
	            sellerId.add(oneSeller.Seller__c);
	        }
	        Map<String,String> mapFixLabel = new Map<String,String>{'RecordType.Name'=>'Record Type','Owner.Name'=>'Owner'};
	        
	       // List<Map<String,Object>> listColNameContact = new List<Map<String,Object>>();
	        List<ColName> listColNameContact = new List<ColName>();
	        Set<String> setFieldNameCont = new Set<String>{'id'};
	        
	        for(Schema.FieldSetMember f: SObjectType.Contact.FieldSets.InitiateCallBoBSeller.getFields())
	        {
	        	setFieldNameCont.add(f.getFieldPath());
	        	if(f.getFieldPath().contains('.') && f.getFieldPath().endsWith('Name'))
	        	{
	        		String fId = ApexUtil.getFieldIdRef(f.getFieldPath());
	        		setFieldNameCont.add(fId);
	        	}
        	 
	        	listColNameContact.add(
	        		new ColName(mapFixLabel.containsKey(f.getFieldPath())?mapFixLabel.get(f.getFieldPath()):f.getLabel(),
	        		f.getFieldPath(),
	        		f.getType()+'')
	            );
	        }
	        
	        List<ColName> listColNameAction = new List<ColName>();
			Set<String> setFieldNameAction = new Set<String>{'id'};
			Map<String,String> mapFixPkl = new Map<String,String>{'Action_Outcome__c'=>'toLabel(Action_Outcome__c)Action_Outcome__c'};
            for(Schema.FieldSetMember f: SObjectType.Action__c.FieldSets.InitiateCall.getFields())
	        {
                //TH:US-0010034:06/08/2021:hide colum "Seller facing Dashboard message" from Action Table for GCX 
                if(Userinfo.getprofileId()==EBH_ConstantsUtility.PROFILE_GCX_PARTNER_ID && f.getFieldPath() == 'Seller_facing_Dashboard_message__c') continue;
				
				if(!isAUProfile && (f.getFieldPath() == 'SRNumber__c' || f.getFieldPath() == 'LastCallDate__c' )) continue;//LA:20-09-2021:US-0010363:if profile is not AU profile, hide column SRNumber__c and LastCallDate__c
                
				setFieldNameAction.add(mapFixPkl.containsKey(f.getFieldPath())?mapFixPkl.get(f.getFieldPath()):f.getFieldPath() );
				
	        	if(f.getFieldPath().contains('.') && f.getFieldPath().endsWith('Name'))
	        	{
	        		String fId = ApexUtil.getFieldIdRef(f.getFieldPath());
	        		setFieldNameAction.add(fId);
	        	}
        	 
	        	listColNameAction.add(
	        		new ColName(mapFixLabel.containsKey(f.getFieldPath())?mapFixLabel.get(f.getFieldPath()):f.getLabel(),
	        		f.getFieldPath(),
	        		f.getType()+'')
	            );
	        }
	        String soql_cont = 'Select '+String.join(new List<String>(setFieldNameCont),',')+' From Contact Where AccountId IN :sellerId';
	        String soql_action = ' Select '+String.join(new List<String>(setFieldNameAction),',')+' From Action__c Where LTTM_Seller__c=:recordId';//LA:20-09-2021:US-0010363: add two fields SRNumber__c,LastCallDate__c in query
	        
        	Contact[] listContact = Database.query(soql_cont); //[Select Id, Name, Account.Name, Email, RecordType.Name, Phone, Owner.Alias From Contact Where AccountId IN :sellerId];
        	Action__c[] listActions = Database.query(soql_action);
        	
        	mapResult.put('listColNameContact',listColNameContact);
        	mapResult.put('listContact',listContact);
        	mapResult.put('listColNameAction',listColNameAction);
			mapResult.put('listActions',listActions);
			mapResult.put('bobSeller',bseller[0]);
			mapResult.put('recordTypeActionId',ApexUtil.getRecordTypeByName('Action__c','LTTM').Id);
			mapResult.put('sitePrefix',Site.getPathPrefix());
			
        	mapResult.put('status','ok');
			mapResult.put('isAUProfile',isAUProfile);//Loumang:20-09-2021:US-0010363: put AU profile in mapResult
			mapResult.put('isAUProfileOnly',isAUProfileOnly);
			
        }
        
        
        return mapResult;
    }	
	
	/*****************************************************************************************************************************
    @ Method:   apexSave
    @ Version:  2.0
    @ Author:   Sophal Noch (sophal.noch@gaea-sys.com)
	@ Purpose:        US-0007888
	@                 As a...
	@                 Any user
	@                 Want to...
	@                 the capability to record Growth coaching call with Sellers and record Call Log - Agent Name, Date when call recorded, record Inbound Call Attempts.
	@                 So that...
	@                 every Inbound call can be recorded and the Agent performance can be calculated.
	@                 Description
	@                 Summary - Inbound call tracking capability to record call Log for every Inbound call initiated by LTTM + Concierge team
    @------------------------------------------------------------------------------------------------------------------------------
    @ Parameter:      bob seller bs, list action, boolean bsOnly, list contact
    ------------------------------------------------------------------------------------------------------------------------------
	@ Change history: 30.07.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / modify a method
    *****************************************************************************************************************************/
	@AuraEnabled
	public static Map<String,Object> apexSave(BoB_Seller__c bs, List<Action__c> listActions,Boolean bsOnly,Boolean isFromSeller,List<Contact> listContacts,Map<String,String> addParam) {

		//System.debug('>>addParam: '+ addParam );
		//System.debug('>>listActions: '+ listActions );
		//System.debug('>>bs: '+ bs );

		Map<String,Object> mapResult = new Map<String,Object>();
		//try {
			bs.Call_Attempt__c = (bs.Call_Attempt__c==null?0:bs.Call_Attempt__c) +1;
			update bs;
			if(!bsOnly)update listActions;

			if(isFromSeller){ //US-0007888 if user click from RecordInboundCall page, create Task
				createTask(bs,listContacts,addParam);
			}

			mapResult.put('status','ok');
		/*}catch(DMLException dex)
    	{	mapResult.put('status','ko');mapResult.put('error',dex.getDmlMessage(0));mapResult.put('errorDetail',dex.getStackTraceString());
    	}catch(Exception ex)
    	{   mapResult.put('status','ko');mapResult.put('error',ex.getMessage());mapResult.put('errorDetail',ex.getStackTraceString());	}
        */
		return mapResult;
	}

	/*****************************************************************************************************************************
    @ Method:   createTask
    @ Version:  2.0
    @ Author:   Sophal Noch (sophal.noch@gaea-sys.com)
	@ Purpose:        US-0007888
	@                 As a...
	@                 Any user
	@                 Want to...
	@                 the capability to record Growth coaching call with Sellers and record Call Log - Agent Name, Date when call recorded, record Inbound Call Attempts.
	@                 So that...
	@                 every Inbound call can be recorded and the Agent performance can be calculated.
	@                 Description
	@                 Summary - Inbound call tracking capability to record call Log for every Inbound call initiated by LTTM + Concierge team
    @------------------------------------------------------------------------------------------------------------------------------
    @ Parameter:      bob seller bs, list action, boolean bsOnly, list contact
    ------------------------------------------------------------------------------------------------------------------------------
	@ Change history: 30.07.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / modify a method
	@ 				: 15/10/2020/ Vadhanak Voun (vadhanak.voun@gaea-sys.com) / US-0008206 - [LTTM Plus] Campaign Code to be mandated and Cohort Seller Comments ,DMC, SR# to be recorded in Activities
    *****************************************************************************************************************************/
	private static void createTask(BoB_Seller__c bs, List<Contact> listContacts,Map<String,String> addParam) {

		Task tsk = new Task();
		tsk.Type = TASK_TYPE_GCC;

		if(!listContacts.isEmpty()){
			tsk.WhoId = listContacts[0].Id;
		}

		tsk.WhatId = bs.Id;
		tsk.Status = 'Completed';
		tsk.Subject= bs.BoB__r.LTTM_Group__c + '_ ' + TASK_TYPE_GCC;
		//LA:US-0009514: replace field Comments__c with Advisor_Comments__c
		//tsk.Description = bs.Comments__c;
		tsk.Description = bs.Advisor_Comments__c;
		tsk.Call_attempts__c = 1;
		tsk.RecordtypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('X3CallAttempts').getRecordTypeId();
		tsk.Task_Completed_Date__c =  System.now();
		tsk.Log_Task__c = true;


		//NK:15/10/2020/:US-0008206
		//tsk.Description = bs.Comments__c ;
		tsk.SR_Number__c  = addParam.get('SRNumber');
		tsk.EBH_Account__c = bs.Seller__c;
		//system.debug('>>bs: '+bs.Seller__c+'  >ts: '+tsk.EBH_Account__c);
		tsk.EBH_DMC__c = bs.Call_Outcome__c == 'DMC Committed';
		 

		insert tsk;
		
	}

	
    static Map<String,String> mapLinkField = new Map<String,String>{'Name'=>'Name','Account.Name'=>'AccountId','RecordType.Name'=>'RecordTypeId','Owner.Name'=>'OwnerId'};
    //static Set<String> setEditableFields = new Set<String>{'Action_Outcome__c','Completed_Date__c','Status__c'};
    
    
    class ColName{
    	@AuraEnabled
    	public String label;
    	
    	@AuraEnabled
    	public String fieldName;
      
        @AuraEnabled
    	public String type;
    	
        @AuraEnabled
    	public Boolean sortable = true;
    	
    	//@AuraEnabled
    	//public Boolean editable = false;
    	
    	@AuraEnabled
    	public Map<String,Object> typeAttributes;
    	
    	public ColName(String label,String fieldName,String type)
    	{
    		this.label = label;
    		this.fieldName = fieldName;
    		this.type = type.toLowerCase();
    		//this.editable = setEditableFields.contains(fieldName);
    		
    		if(fieldName=='RecordType.Name')
    		{
    			this.fieldName = mapLinkField.get(fieldName);
    		}else if(mapLinkField.containsKey(fieldName))
    		{
    			typeAttributes = new Map<String,Object>{
    				'label' => new Map<String,Object>{'fieldName'=>mapLinkField.get(fieldName)},
    				'target'=>'_blank',
    				'tooltip'=>''
    			};
    			this.fieldName = 'link_'+mapLinkField.get(fieldName);
    			this.type = 'url';
    		} 
    	}
    }
   
   
}