unpackaged/main/default/objects/Account/fields/Contact_Data_Quality__c.field-meta.xml
<CustomField>
    <fullName>Contact_Data_Quality__c</fullName>
    <description>EPH-5630 Seller - Quality &amp; Preference</description>
    <label>Contact Data Quality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_BOBManaged__c.field-meta.xml
<CustomField>
    <fullName>EBH_BOBManaged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-1901) - BOB Managed</description>
    <inlineHelpText>Sellers who are managed by Seller Growth Verticals or GCX (MSO).</inlineHelpText>
    <label>Managed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (US-0030) - to capture the Status</description>
    <inlineHelpText>Seller´s current active status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>On Credit Hold</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>CC Verification</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>User CCVerify Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_LegalEntity.recordType-meta.xml
<RecordType>
    <fullName>EBH_LegalEntity</fullName>
    <active>true</active>
    <label>Legal Entity</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Contact_Data_Quality__c.field-meta.xml
<CustomField>
    <fullName>Contact_Data_Quality__c</fullName>
    <description>EPH-5629 Contact - Quality &amp; Preference</description>
    <formula>IF( Email_Bounced__c  ||  Incorrect_Phone_Number__c , &#39;Red&#39;, &#39;Green&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If contact has invalid email or invalid phonenumber then red else green</inlineHelpText>
    <label>Contact Data Quality</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_MailingAddress__c.field-meta.xml
<CustomField>
    <fullName>EBH_MailingAddress__c</fullName>
    <description>[EBH] (US:0036) - Mailing Address</description>
    <label>Mailing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_MailingCity__c.field-meta.xml
<CustomField>
    <fullName>EBH_MailingCity__c</fullName>
    <description>[EBH] (US:0036) - to capture mailing address fields without length restriction for ETL</description>
    <label>Mailing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_MailingCountry__c.field-meta.xml
<CustomField>
    <fullName>EBH_MailingCountry__c</fullName>
    <description>[EBH] (US-0036) : Mailing Country</description>
    <label>Mailing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_MailingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>EBH_MailingPostalCode__c</fullName>
    <description>[EBH] (US-0036) : Mailing Postal Code</description>
    <label>Mailing Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_MailingStreet__c.field-meta.xml
<CustomField>
    <fullName>EBH_MailingStreet__c</fullName>
    <description>[EBH] (US-0036) : To capture the Mailing address without length restrictions for ETL</description>
    <label>Mailing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_OracleId__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleId__c</fullName>
    <description>[EBH] (EPH-52) : Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID</inlineHelpText>
    <label>Oracle Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-3293) - to track the status of the contact</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_Bounced__c.field-meta.xml
<CustomField>
    <fullName>Email_Bounced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EPH-5629 Contact - Quality &amp; Preference</description>
    <inlineHelpText>Invalid primary email</inlineHelpText>
    <label>Email Bounced</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Incorrect_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Incorrect_Phone_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EPH-5629 Contact - Quality &amp; Preference</description>
    <inlineHelpText>Invalid primary phonenumber</inlineHelpText>
    <label>Incorrect Phone Number</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CreateTaskForSellerControllerTest.cls
/*********************************************************************************************************************************
@ Class:          CreateTaskForSellerControllerTest
@ Version:        1.0
@ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
@ Purpose:        Test logic for CreateTaskForSellerController
@ EPH-5671 Create Contact Quality Task in Seller Record when Status = red for managed sellers
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 15.03.2019 / Sovantheany Dim / Created the class.
                : 28.04.2022 / Loumang SENG / US-0011388 - Deactivate Contact Quality Task creation in the Seller Record
*********************************************************************************************************************************/

@isTest
private class CreateTaskForSellerControllerTest {

    /*static testMethod void myUnitTest() {
    	Test.startTest();
    	EBH_TestDataFactory.setUpCustomSettings();
    	
    	RecordType sellerId = [SELECT Id FROM RecordType where SobjectType = 'Account' and DeveloperName = 'EBH_Seller'];
		RecordType legalEntityId = [SELECT Id FROM RecordType where SobjectType = 'Account' and DeveloperName = 'EBH_LegalEntity'];
        Account legalAcc0 = new Account(Name = 'testLegalAcc0',RecordTypeId = legalEntityId.Id);
        Account legalAcc1 = new Account(Name = 'testLegalAcc1',RecordTypeId = legalEntityId.Id);
        insert new List<Account>{legalAcc0,legalAcc1};
        Account acc1 = new Account(Name = 'testAccount0', RecordTypeId = sellerId.ID, ParentId = legalAcc0.Id,EBH_OracleID__c = '1111', BillingStreet = 'testStreet1',BillingState ='testState1',BillingPostalCode='testpostalcode1',BillingCountry = 'testcountry1',BillingCity='testcity1');
        Account acc2 = new Account(Name = 'testAccount1', RecordTypeId = sellerId.ID, ParentId = legalAcc1.Id,EBH_OracleID__c = '2222', BillingStreet = 'testStreet2',BillingState ='testState2',BillingPostalCode='testpostalcode2',BillingCountry = 'testcountry2',BillingCity='testcity2',EBH_BOBManaged__c = true);
        List<Account> lstAccount = new List<Account>{acc1,acc2};
        insert lstAccount;
        List<Contact> lstCont = new List<Contact>();
        for(Integer i = 0; i < 2; i++){
        	Contact con = new Contact(LastName = 'testContact' + i, AccountId = lstAccount[i].Id, EBH_Status__c='Active',Email='test'+i+'@gmail.com',
        	Phone='123456'+i,EBH_MailingStreet__c='testMailingStreet'+i,EBH_MailingPostalCode__c='testMailingPostalcode'+i,
        	EBH_MailingCountry__c='testMailingCountry'+i,EBH_MailingCity__c='testMailingCity'+i,EBH_MailingAddress__c='testMailingAddress'+i);
        	
        	lstCont.add(con);
        }
        insert lstCont;
        
        Map<String,Object> mapResult = CreateTaskForSellerController.createTask(String.valueOf(acc1.id));
        
        System.assertEquals(mapResult.get('status'), 'info');
        System.assertEquals(mapResult.get('info'), 'Task is created only when BoB Managed = TRUE and Contact Data Quality = RED or YELLOW');
        
        Account accSeller2 = [select Contact_Data_Quality__c,EBH_BOBManaged__c from Account where id =: acc2.Id];
        System.assertEquals(accSeller2.EBH_BOBManaged__c,true);
        System.assertEquals(accSeller2.Contact_Data_Quality__c,'Green');
        
        for(Contact con : lstCont){
        	con.AccountId = accSeller2.Id;
        	con.Email_Bounced__c = true;
        	con.Incorrect_Phone_Number__c = true;
        }
        update lstCont;
        
        Account accSeller3 = [select Contact_Data_Quality__c,EBH_BOBManaged__c from Account where id =: acc2.Id];
        System.assertEquals(accSeller3.EBH_BOBManaged__c,true);
        System.assertEquals(accSeller3.Contact_Data_Quality__c,'Red');
        
        Map<String,Object> mapResult2 = CreateTaskForSellerController.createTask(String.valueOf(acc2.id));
		//System.assertEquals(mapResult2.get('status'), 'ok');
        
        List<Task> taskCreated = [select id from Task where Subject = 'Contact Quality Task is created' and WhatId =: acc2.Id];
        //System.assertEquals(taskCreated.size(),1);
        Test.stopTest();
    }*/
    static testMethod void testDepreciatedClass(){
        Test.startTest();
            CreateTaskForSellerController depreciatedMSR = new CreateTaskForSellerController();
        Test.stopTest();

    }
}