unpackaged/main/default/objects/Account/fields/EBH_RevRollup__c.field-meta.xml
<CustomField>
    <fullName>EBH_RevRollup__c</fullName>
    <description>[EBH] (EPH-176) - Rev RollUp</description>
    <inlineHelpText>Where we attribute revenue for the Seller. Revenue is assigned based on seller country.</inlineHelpText>
    <label>Rev RollUp</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>OTHER EA</fullName>
            </value>
            <value>
                <fullName>OTHER EAPAC</fullName>
            </value>
            <value>
                <fullName>OTHER EEMEA</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>ROE -Other</fullName>
            </value>
            <value>
                <fullName>RU</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>UA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/SP_Coupons__c.field-meta.xml
<CustomField>
    <fullName>SP_Coupons__c</fullName>
    <description>US-0010430 - Coupon tab visibility + coupon landing page</description>
    <label>SP Coupons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/SP_Deals__c.field-meta.xml
<CustomField>
    <fullName>SP_Deals__c</fullName>
    <description>US-0011312 - Rebuild Deals Page</description>
    <inlineHelpText>&quot;Full Access&quot; means a Seller can view and create Deals, &quot;Read Only&quot; means a Seller can only view Deals, &quot;Allowed&quot; means they can see the Deals tab in the portal</inlineHelpText>
    <label>SP Deals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>EPH-7262 Adjustment to Coupon Object</description>
    <inlineHelpText>Defines the coupon contract type &amp; language - All sellers in that coupon will receive the same template.</inlineHelpText>
    <label>Contract Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Co_invest_Type__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Co_invest_Type__c</fullName>
    <description>US-0008867 - AU Coupon BCD generation</description>
    <inlineHelpText>The value in this filed has impact on the billing process. For &quot;Contra&quot; type the seller co-invest costs will be derived from coupon redeem amount (contra). For &quot;GMV&quot; type the co-invest costs will be derived from transaction GMV, potentially resulting in higher co-invest costs for the seller (depending on coupon cap and coupon discount %)</inlineHelpText>
    <label>Coupon Co-invest Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Main_Coupon_Site__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GMV</fullName>
            </value>
            <value>
                <fullName>Contra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  DATEVALUE(&quot;2099-1-1&quot;) , null)</defaultValue>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_end_Time__c.field-meta.xml
<CustomField>
    <fullName>Coupon_end_Time__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  TIMEVALUE(&quot;00:00:00.000&quot;) , null)</defaultValue>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <label>Coupon End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Time__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <label>Coupon Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Main_Coupon_Site__c.field-meta.xml
<CustomField>
    <fullName>Main_Coupon_Site__c</fullName>
    <description>US-0008867 - AU Coupon BCD generation</description>
    <label>Main Coupon Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ebay.de</fullName>
            </value>
            <value>
                <fullName>ebay.es</fullName>
            </value>
            <value>
                <fullName>ebay.co.uk</fullName>
            </value>
            <value>
                <fullName>ebay.fr</fullName>
            </value>
            <value>
                <fullName>ebay.it</fullName>
            </value>
            <value>
                <fullName>ebay.ch</fullName>
            </value>
            <value>
                <fullName>ebay.at</fullName>
            </value>
            <value>
                <fullName>ebay.pl</fullName>
            </value>
            <value>
                <fullName>ebay.nl</fullName>
            </value>
            <value>
                <fullName>ebay.com</fullName>
            </value>
            <value>
                <fullName>ebay.com.au</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>US-0018725 	Coupon Seller - Add condition to workflow for stage T4Statement and T40 Statement</description>
    <formula>TEXT(Coupon__r.Contract_Language__c)</formula>
    <label>Contract Language</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Time__c</fullName>
    <description>US-0007260 POP COUPON - NEW RECORD TYPE COUPON SELLER OBJECT</description>
    <formula>Coupon__r.Coupon_end_Time__c</formula>
    <label>Coupon End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Time__c</fullName>
    <description>US-0007260 POP COUPON - NEW RECORD TYPE COUPON SELLER OBJECT</description>
    <formula>Coupon__r.Coupon_Start_Time__c</formula>
    <label>Coupon Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AnyEventCalCtrlTest.cls
/**
 * @description     Update test unit for more coverage above 75%
 * @modifiedDate    25/10/2021
 * @modifiedBy      Samnang MUONG
 */

//@isTest(seeAllData=true) Samnang MUONG: Comment see all data then create sample data
@isTest
public class AnyEventCalCtrlTest {

    @TestSetup
    static void makeData(){
      
        // create event for handle existing test methods
        Event e = new Event(StartDateTime=System.today(), EndDateTime = System.today()+5);
        insert e;

        // create seller (Account)

        Account acc = new Account(SP_Deals__c='Full Access',SP_Coupons__c='Full Access',Name='Test Abc123',RecordTypeId = Schema.sObjectType.Account.getRecordTypeInfosByName().get('Seller').getRecordTypeId(),EBH_RevRollup__c='DE');

        insert acc;

        // create coupon 
        String recIdCoupon = Schema.sObjectType.Coupon__c.getRecordTypeInfosByName().get('Seller / Category Based').getRecordTypeId();
        Coupon__c c = new Coupon__c(Contract_Language__c='DE', Coupon_Start_Time__c=System.Now().timeGmt(), Coupon_End_Time__c=Time.newInstance(12, 22, 30, 000), Coupon_Start_Date__c=System.Today(), Coupon_End_Date__c=System.Today().addDays(2),Main_Coupon_Site__c = 'ebay.de', Coupon_Co_invest_Type__c = 'Contra');
        insert c;

        // create coupon seller
        Coupon_Seller__c cs = new Coupon_Seller__c(Coupon__c = c.Id, Coupon_Seller_Stage__c=EBH_ConstantsUtility.COUPON_SELLER_STAGE_CONTRACT_SIGNED, Seller__c=acc.Id);
        insert cs;

        // create deal retail campaign
        
        EBH_DealRetailCampaign__c d = new EBH_DealRetailCampaign__c(EBH_DealTitle__c='test title',Focus_Categories__c = 'Electronics', EBH_Date__c = System.today(), EPH_EndDate__c = System.today()+1, EBH_Country__c = '0' );
        insert d;

        
    }

    @isTest static void test_getCoupan() {
        AnyEventCalCtrl.getCoupan('Coupon_Seller__c', 'Coupon_Start_Date__c', 'Coupon_End_Date__c', 'EBH_DealRetailCampaign__c');
    }
    
    //TH:04/05/2022:US-0011536
/*static testMethod void getEventsTest() {
        AnyEventCalCtrl.getEvents('Event', 'Subject', 'StartDateTime', 'EndDateTime', 'Description', 'OwnerId', true);
        AnyEventCalCtrl.getEvents('Event', 'Subject', 'StartDateTime', 'EndDateTime', 'Description', 'OwnerId', false);
    }
    static testMethod void upsertEventsTest() {
        AnyEventCalCtrl.upsertEvents('{"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Event', 'Subject', 'StartDateTime', 'EndDateTime', 'Description', 'OwnerId');
    	AnyEventCalCtrl.upsertEvents('{"id":"sadad","title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Event', 'Subject', 'StartDateTime', 'EndDateTime', 'Description', 'OwnerId');
    }
    static testMethod void deleteEventTest() {
        Event e = [SELECT Id FROM Event LIMIT 1];
        AnyEventCalCtrl.deleteEvent(e.Id, 'Event', 'Subject', 'StartDateTime', 'EndDateTime', 'Description', 'OwnerId');
    }
    static testMethod void crudSecurityTest() {
        AnyEventCalCtrl.isAccessible('Event');
        AnyEventCalCtrl.isAccessible('Event','Subject');
        AnyEventCalCtrl.isCreateable('Event');
        AnyEventCalCtrl.isDeletable('Event');
    }
*/
    @IsTest
    static void testGetCalendarItems(){
        
        Test.startTest();
        List<Object> listCal = AnyEventCalCtrl.getCalendarItems(Datetime.now().format('YYYY-MM-dd'), Datetime.now().format('YYYY-MM-dd'),new List<String>(),new List<String>{'EBH_DealRetailCampaign__c'},new List<String>());
            System.assertEquals(false, listCal.isEmpty(),'setting with data');

        Test.stopTest();
        
    }

    @IsTest
    static void testGetCalendarItems_withFiltering(){
        
        Test.startTest();
            String criteria = 'EPH_EndDate__c < TODAY';
            List<Object> listCal = AnyEventCalCtrl.getCalendarItems(Datetime.now().format('YYYY-MM-dd'), Datetime.now().format('YYYY-MM-dd'),new List<String>{criteria},new List<String>{'EBH_DealRetailCampaign__c'},new List<String>());
            System.assertEquals(false, listCal.isEmpty(),'setting with data');

        Test.stopTest();
        
    }

    @IsTest
    static void testfetchStatusFilterMetadata(){
        
        Test.startTest();
            
            List<Seller_Portal_Global_Variables__mdt> lstMeta = AnyEventCalCtrl.fetchStatusFilterMetadata('DECalendarFilter_Status');
            System.assertEquals(false, lstMeta.isEmpty(),'setting with data');

        Test.stopTest();
        
    }

    @IsTest
    static void testinitLocalCode(){
        
        Test.startTest();
            
            String result = AnyEventCalCtrl.initLocalCode();
            System.assertEquals(false, String.isBlank(result),'there should be locale return.');

        Test.stopTest();
        
    }

    @IsTest
    static void testgetAccounts(){
        
        User[] admins = [Select Id From User WHERE Profile.Name ='System Administrator' AND IsActive=TRUE LIMIT 2];

        RecordType recSeller = ApexUtil.getRecordTypeByName('Account', 'EBH_Seller');
        Account portalAccount1, portalAccount2;
        Contact contact1,contact2,contact3;
        System.runAs(admins[0])
        {
            //Create account
            portalAccount1 = new Account(
                Name = 'AMT_TEST',
                eBay_API_User_Id__c = 'test_test_test',
                RecordTypeId = recSeller.Id,
                SP_Deals__c = 'Full Access'
            );

            portalAccount2 = new Account(
                Name = 'test_seller007',
                eBay_API_User_Id__c = 'test_test_test2',
                RecordTypeId = recSeller.Id,
                SP_Deals__c = 'Full Access'
            );
            insert new List<Account>{portalAccount1, portalAccount2};
            RecordType recSP = ApexUtil.getRecordTypeByName('Contact', 'Seller_Portal');
            RecordType recDWH = ApexUtil.getRecordTypeByName('Contact', 'EBH_DWH');
            contact1 = new Contact(
                FirstName = 'Test1111111111',
                Lastname = 'AMT_TEST',
                AccountId = portalAccount1.Id,
                Email = System.now().millisecond() + 'test1@test.com',
                RecordTypeId=recSP.Id
            );
            contact2 = new Contact(
                FirstName = 'Test',
                Lastname = 'test con2',
                AccountId = portalAccount2.Id,
                Email = System.now().millisecond() + 'test2@test.com',
                RecordTypeId=recDWH.Id
            );
            insert new Contact[]{contact1,contact2};

            AccountContactRelation acr =  new AccountContactRelation(ContactId=contact1.Id,AccountId=portalAccount2.Id,IsActive=True);
            insert acr;
        }

        System.runAs(admins[1])
        {
            //Create user
            Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'NA - Seller Portal' LIMIT 1];
            Profile portalProfileDE = [SELECT Id FROM Profile WHERE Name = 'DE - Seller Portal' LIMIT 1];
            User user1 = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = contact1.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'AMT_TEST',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            User user2 = new User(
                Username = System.now().millisecond() + 'test2@test.com',
                ContactId = contact2.Id,
                ProfileId = portalProfileDE.Id,
                Alias = 'test2',
                Email = 'test2@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Test2',
                CommunityNickname = 'test2',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            insert new User[]{user1,user2};
        }   

        Test.startTest();
            
            User[] userPortals = [Select Id From User Where Email='test12345@test.com'];
            

            System.runAs(userPortals[0])
            {

                List<Account> lstAcc = AnyEventCalCtrl.getAccounts();
                
                System.assert(!lstAcc.isEmpty(), 'There should be records return.');
            }
            

        Test.stopTest();
        
    }


}