unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Strategic_Seller_Share_w__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Seller_Share_w__c</fullName>
    <description>US-0007755 - [AU] New Coupon Preference Fields on Customer Object</description>
    <inlineHelpText>Seller Agreed Coupon Co-Fund Share</inlineHelpText>
    <label>Strategic Seller Share %</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Coupon_Funding_Preference__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>70</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
            <value>
                <fullName>85</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>95</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>EPH-7262 Adjustment to Coupon Object</description>
    <inlineHelpText>Defines the coupon contract type &amp; language - All sellers in that coupon will receive the same template.</inlineHelpText>
    <label>Contract Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Couponsite_s__c.field-meta.xml
<CustomField>
    <fullName>Couponsite_s__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>Site(s) where coupon will be visisble</inlineHelpText>
    <label>Couponsite(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ebay.de</fullName>
            </value>
            <value>
                <fullName>ebay.co.uk</fullName>
            </value>
            <value>
                <fullName>ebay.fr</fullName>
            </value>
            <value>
                <fullName>ebay.it</fullName>
            </value>
            <value>
                <fullName>ebay.es</fullName>
            </value>
            <value>
                <fullName>ebay.ch</fullName>
            </value>
            <value>
                <fullName>ebay.at</fullName>
            </value>
            <value>
                <fullName>ebay.pl</fullName>
            </value>
            <value>
                <fullName>ebay.nl</fullName>
            </value>
            <value>
                <fullName>ebay.com</fullName>
            </value>
            <value>
                <fullName>ebay.com.au</fullName>
            </value>
            <value>
                <fullName>ebay.ca</fullName>
            </value>
            <value>
                <fullName>ebay.cfr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Seller_Co_funding_share_forecast__c.field-meta.xml
<CustomField>
    <fullName>Seller_Co_funding_share_forecast__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>This is the forecast provided by the Coupon Owner</inlineHelpText>
    <label>Seller Co-funding Share (forecast)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/TriggerEmailManhattan__c.field-meta.xml
<CustomField>
    <fullName>TriggerEmailManhattan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EPH-7725 Send BCD file via email to Finance DL after Coupon ended</description>
    <label>TriggerEmailManhattan</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>US-0018725 	Coupon Seller - Add condition to workflow for stage T4Statement and T40 Statement</description>
    <formula>TEXT(Coupon__r.Contract_Language__c)</formula>
    <label>Contract Language</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <description>EPH-7157 Object: Coupon Seller
US-0012156</description>
    <label>Coupon Seller Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pitch Ready</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
                <default>true</default>
                <label>Targeted</label>
            </value>
            <value>
                <fullName>Reached</fullName>
            </value>
            <value>
                <fullName>Commited</fullName>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Contract Send</fullName>
            </value>
            <value>
                <fullName>Contract Accepted</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Invoice paid</fullName>
            </value>
            <value>
                <fullName>Seller Declined</fullName>
            </value>
            <value>
                <fullName>Contract Appended</fullName>
            </value>
            <value>
                <fullName>Contract Terminated</fullName>
            </value>
            <value>
                <fullName>Invoice approved</fullName>
                <isActive>false</isActive>
                <label>Invoice approved</label>
            </value>
            <value>
                <fullName>Invoice pending</fullName>
                <isActive>false</isActive>
                <label>Invoice pending</label>
            </value>
            <value>
                <fullName>Invoice rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice rejected</label>
            </value>
            <value>
                <fullName>Invoice send</fullName>
                <isActive>false</isActive>
                <label>Invoice send</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Date_34_days_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_34_days_Sent__c</fullName>
    <description>EPH-7565 Coupon - Manhattan Invoice Statment send to coupon seller</description>
    <label>Date 34 days Sent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Date_4days_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_4days_Sent__c</fullName>
    <description>EPH-7565 Coupon - Manhattan Invoice Statment send to coupon seller</description>
    <label>Date 4days Sent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller_Co_funding_Share_forecast__c.field-meta.xml
<CustomField>
    <fullName>Seller_Co_funding_Share_forecast__c</fullName>
    <formula>Coupon__r.Seller_Co_funding_share_forecast__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seller Co-funding Share (forecast)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/TriggerEmailManhattan__c.field-meta.xml
<CustomField>
    <fullName>TriggerEmailManhattan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>EPH-7565 Coupon - Manhattan Invoice Statment send to coupon seller</description>
    <label>TriggerEmailManhattan</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/Batch_CreateCoInvest.cls
/*********************************************************************************************************************************
	@ Method:         Batch_CreateCoInvest
	@ Version:       1.0
	@ Author:        Vadhanak Voun (vadhanak.voun@gaea-sys.com)
	@ Purpose:       US-0007195 - Coupon Co-Invest records creation is causing System.LimitException: Too many SOQL queries: 101 error
	@               CouponTriggerHandler.createCoInvestWithRecordType
	@               to fix CPU limit
	----------------------------------------------------------------------------------------------------------------------------------
	@ Change history: 15.05.2020/ Vadhanak Voun (vadhanak.voun@gaea-sys.com) / Created the Method.
	*********************************************************************************************************************************/
global without sharing class Batch_CreateCoInvest implements Database.Batchable<SObject>{
	 /****************************************************************************************************************************
	* CONSTANTS DEFINITION
	*****************************************************************************************************************************/
	private Set<ID> sCoupon;
    private String whereCS = ' where Coupon__c IN: sCoupon';
	private final static String SOQL_COUPON_SELLER_2 = 'Select Coupon__r.Couponsite_s__c,Seller__r.Strategic_Seller_Share_w__c,Coupon__r.Seller_Co_funding_share_forecast__c,Coupon__r.Contract_Language__c, Date_4days_Sent__c, Date_34_days_Sent__c, TriggerEmailManhattan__c, Id,Seller__c,Seller__r.EBH_OracleID__c,Coupon__c,Coupon_Seller_Stage__c,Coupon__r.RecordTypeID,Coupon__r.RecordType.DeveloperName,Coupon__r.Stage__c,SellerShareHolder__c From Coupon_Seller__c' ;
	/************************************END CONSTANTS DEFINITION*************************************************************/

    public Batch_CreateCoInvest(Set<ID> sCoupon) 
    {
        this.sCoupon = sCoupon;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {        
        return Database.getQueryLocator(SOQL_COUPON_SELLER_2 + whereCS);
    }

    global void execute(Database.BatchableContext pBc, List<Coupon_Seller__c> scope)
    {
       CouponTriggerHandler.processCoInvest(scope);
		 
    }  
    
    
    global void finish(Database.BatchableContext pBc)
    {
        
    }
}