unpackaged/main/default/objects/Account/fields/EBH_PartnerType__c.field-meta.xml
<CustomField>
    <fullName>EBH_PartnerType__c</fullName>
    <description>[EBH] (US-0046) : To capture partner type on a Partner record
[#EPH-7476] Partner Record - Enhance fields for Partner Contact Management</description>
    <label>Partner Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Listing Tool</fullName>
            </value>
            <value>
                <fullName>Middleware</fullName>
            </value>
            <value>
                <fullName>Shop Plugin</fullName>
            </value>
            <value>
                <fullName>Shop System</fullName>
            </value>
            <value>
                <fullName>Template Design</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Shipping Provider</fullName>
            </value>
            <value>
                <fullName>Listing Optimisation</fullName>
            </value>
            <value>
                <fullName>Integration Partner</fullName>
            </value>
            <value>
                <fullName>Commerce Platform</fullName>
            </value>
            <value>
                <fullName>3PP</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
            </value>
            <value>
                <fullName>Reporting Management</fullName>
            </value>
            <value>
                <fullName>Advertising Services ERP</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
            <value>
                <fullName>Promoted Listings Specialist</fullName>
            </value>
            <value>
                <fullName>Full Service Provider</fullName>
                <isActive>false</isActive>
                <label>Full Service Provider</label>
            </value>
            <value>
                <fullName>Sales Service Provider</fullName>
                <isActive>false</isActive>
                <label>Sales Service Provider</label>
            </value>
            <value>
                <fullName>Translation Service Provider</fullName>
                <isActive>false</isActive>
                <label>Translation Service Provider</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (US-0030) - to capture the Status</description>
    <inlineHelpText>Seller´s current active status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>On Credit Hold</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>CC Verification</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>User CCVerify Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_LegalEntity.recordType-meta.xml
<RecordType>
    <fullName>EBH_LegalEntity</fullName>
    <active>true</active>
    <label>Legal Entity</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/EBH_Partner.recordType-meta.xml
<RecordType>
    <fullName>EBH_Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Campaign/fields/EBH_LastResponseDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_LastResponseDate__c</fullName>
    <description>[EBH] (EPH-1880) -  Date of LAST response of the contact in this campaign</description>
    <label>Last Response Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/EBH_ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>EBH_ResponseCode__c</fullName>
    <description>[EBH] (EPH-1880) - Response Code Unified</description>
    <label>Response Code</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/EBH_Vertical__c.field-meta.xml
<CustomField>
    <fullName>EBH_Vertical__c</fullName>
    <description>[EBH] (EPH-2641) - Vertical
US-0011867</description>
    <label>Vertical</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>Collectibles</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Home &amp; Garden</fullName>
            </value>
            <value>
                <fullName>Lifestyle</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Parts &amp; Accessories</fullName>
            </value>
            <value>
                <fullName>Bussiness &amp; Industry</fullName>
            </value>
            <value>
                <fullName>Sneakers</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
            <value>
                <fullName>Re-Store</fullName>
            </value>
            <value>
                <fullName>Outlet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/EBH_LastResponseDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_LastResponseDate__c</fullName>
    <description>[EBH] (EPH-1912) : Date of LAST response of the contact in this campaign</description>
    <label>Last Response Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/EBH_ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>EBH_ResponseCode__c</fullName>
    <defaultValue>10</defaultValue>
    <description>[EBH] (EPH-1912) :Response Code Unified</description>
    <label>Response Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/EBH_Results__c.field-meta.xml
<CustomField>
    <fullName>EBH_Results__c</fullName>
    <description>[EBH] (EPH-1912) :Response</description>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Failed (Blocked)</fullName>
            </value>
            <value>
                <fullName>Failed (Wrong Details)</fullName>
            </value>
            <value>
                <fullName>Failed (Timeout)</fullName>
            </value>
            <value>
                <fullName>Not Reached</fullName>
            </value>
            <value>
                <fullName>Reached - No Action</fullName>
            </value>
            <value>
                <fullName>Reached - Not Interested</fullName>
            </value>
            <value>
                <fullName>Reached - Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Reached - Interested</fullName>
            </value>
            <value>
                <fullName>Reached - Committed</fullName>
            </value>
            <value>
                <fullName>Reached - Acted</fullName>
            </value>
            <value>
                <fullName>Unknown Result</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
            </value>
            <value>
                <fullName>Block Bounce</fullName>
            </value>
            <value>
                <fullName>Hard Bounce</fullName>
            </value>
            <value>
                <fullName>Soft Bounce</fullName>
            </value>
            <value>
                <fullName>Not Opened</fullName>
            </value>
            <value>
                <fullName>Opened</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Unsubscribed</fullName>
            </value>
            <value>
                <fullName>Clicked</fullName>
            </value>
            <value>
                <fullName>Committed to Act</fullName>
            </value>
            <value>
                <fullName>Call Planned</fullName>
            </value>
            <value>
                <fullName>Phone Blacklist</fullName>
            </value>
            <value>
                <fullName>Wrong Phone Number</fullName>
            </value>
            <value>
                <fullName>Call Not Answered</fullName>
            </value>
            <value>
                <fullName>DMC Not Reached</fullName>
            </value>
            <value>
                <fullName>DMC Not Interested</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>DMC Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_GDPRRemoved__c.field-meta.xml
<CustomField>
    <fullName>EBH_GDPRRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-5413) to track if contact has been GDPR removed</description>
    <label>GDPR Removed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/EBH_Project__c.object-meta.xml
<CustomObject>
    <description>#US-0015700</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Project__c/fields/LeadSegment__c.field-meta.xml
<CustomField>
    <fullName>LeadSegment__c</fullName>
    <description>#US-0018736</description>
    <label>Lead Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SMB</fullName>
                <label>SMB (small medium business)</label>
            </value>
            <value>
                <fullName>Enterprise</fullName>
                <label>Enterprise (large retailers)</label>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/fields/LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>LegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0007400</description>
    <inlineHelpText>Legal Entity that responds to this Project, in case if it is existing</inlineHelpText>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_LegalEntity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Legal Entity)</relationshipLabel>
    <relationshipName>Projects6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/fields/OtherLeadSource__c.field-meta.xml
<CustomField>
    <fullName>OtherLeadSource__c</fullName>
    <description>#US-0018736</description>
    <label>Other Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/fields/Shopping_Card__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0007315 - [AU &amp;EU] Integration Partner &amp; Shopping Card</description>
    <inlineHelpText>Ecommerce provider on seller&#39;s website</inlineHelpText>
    <label>Shopping Cart</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Partner</value>
        </filterItems>
        <filterItems>
            <field>Account.EBH_PartnerType__c</field>
            <operation>equals</operation>
            <value>Shop System</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Shopping Card)</relationshipLabel>
    <relationshipName>Projects5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>#US-0018736,
US-0007448</description>
    <inlineHelpText>Team from which country is responsible for seller onboarding</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/recordTypes/eBayAUSMB.recordType-meta.xml
<RecordType>
    <fullName>eBayAUSMB</fullName>
    <active>true</active>
    <label>AU Onboarding</label>
</RecordType>

unpackaged/main/default/objects/EBH_Project__c/recordTypes/EUOnboarding.recordType-meta.xml
<RecordType>
    <fullName>EUOnboarding</fullName>
    <active>true</active>
    <description>HIVE process for Onboarding potential sellers from Leads.  Process includes has such stages as Discovery, Account Set Up, Technical Integration, Scaling (Warranty), Completed.</description>
    <label>EU Onboarding</label>
</RecordType>

unpackaged/main/default/classes/LeadTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LeadTriggerHandlerTest {
	private static Id projAUSMB_RT = ApexUtil.getRecordTypeByName('EBH_Project__c', 'eBayAUSMB').Id;
	private static Id projEU_RT = ApexUtil.getRecordTypeByName('EBH_Project__c', 'EUOnboarding').Id;
	@testSetup static void setup(){
		EBH_TestDataFactory.setUpCustomSettings(); 
		ActiveValidationRules__c avr = new ActiveValidationRules__c();
		avr.All_Validation_Rules_Deactivated__c = false;
		insert avr;

		Account accPartner1 = new Account();
		accPartner1.Name = 'accPartner1';
		accPartner1.RecordTypeId = ApexUtil.getRecordTypeByName('Account', 'EBH_Partner').Id;
		accPartner1.EBH_PartnerType__c = 'Shop System';
		insert accPartner1;

		List<Account> legalEntt =  EBH_TestDataFactory.createAccounts(1, 'EBH_LegalEntity') ;
    	legalEntt[0].Name = 'LegalEntity Test';
    	update legalEntt;

		Lead oneL = EBH_TestDataFactory.createLeads();
		oneL.RecordTypeId = ApexUtil.getRecordTypeByName('Lead', 'EBH_eBayAUSMB').Id;
		oneL.EBH_eBayID__c = 'biggest_sellert_test';
		oneL.Site__c = 'AU';
		oneL.LeadSource = 'Self Gen';
		oneL.LeadSegment__c = 'SMB';
		oneL.OtherLeadSource__c = 'other leadsource tst';
		oneL.LastName = 'AMT Lead tst 01';
		oneL.Phone = '012 345 5678';
		oneL.Website = 'www.test.com.test';
		oneL.Email = 'test@tes.com.invalid';
		oneL.Shopping_Card__c = accPartner1.Id;
		oneL.EBH_Vertical__c = 'Collectibles';
		oneL.VAT_Number__c = '12312312312312';
		oneL.isapproved__c = true;
		oneL.Company = 'test1 company';
		insert oneL;

		Lead oneL2 = EBH_TestDataFactory.createLeads();
		oneL2.RecordTypeId = ApexUtil.getRecordTypeByName('Lead', 'EBH_eBayAUSMB').Id;
		oneL2.EBH_eBayID__c = 'biggest_sellert_test';
		oneL2.Site__c = 'AU';
		oneL2.LeadSource = 'Self Gen';
		oneL2.LeadSegment__c = 'SMB';
		oneL2.OtherLeadSource__c = 'other leadsource tst';
		oneL2.LastName = 'AMT Lead tst 02';
		oneL2.Phone = '012 345 5674';
		oneL2.Website = 'www.test.com.test1';
		oneL2.Email = 'test@tes.com.invalid1';
		oneL2.Shopping_Card__c = accPartner1.Id;
		oneL2.EBH_Vertical__c = 'Collectibles';
		oneL2.VAT_Number__c = '1231231231231223312';
		oneL2.isapproved__c = true;
		oneL2.Company = 'LegalEntity Test'; //Make it same as cc
		insert oneL2;

		Lead oneL3 = EBH_TestDataFactory.createLeads();
		oneL3.RecordTypeId = ApexUtil.getRecordTypeByName('Lead', 'EBH_eBayAUSMB').Id;
		oneL3.EBH_eBayID__c = 'biggest_sellert_test';
		oneL3.Site__c = 'DE'; //EU
		oneL3.LeadSource = 'Self Gen';
		oneL3.LeadSegment__c = 'SMB';
		oneL3.OtherLeadSource__c = 'other leadsource tst';
		oneL3.LastName = 'AMT Lead tst 03';
		oneL3.Phone = '012 345 5674';
		oneL3.Website = 'www.test.com.test1';
		oneL3.Email = 'test@tes.com.invalid3';
		oneL3.Shopping_Card__c = accPartner1.Id;
		oneL3.EBH_Vertical__c = 'Collectibles';
		oneL3.VAT_Number__c = '12312312444444';
		oneL3.isapproved__c = true;
		oneL3.Company = 'LegalEntity Test3';
		oneL3.LegalEntity__c = legalEntt.get(0).Id;
		insert oneL3;

		// AU Task
		Task oneT = new Task();
		oneT.RecordTypeId = ApexUtil.getRecordTypeByName('Task', EBH_ConstantsUtility.TASK_AU_RT).Id;
		oneT.WhoId = oneL.Id;
		insert oneT;

		// Nomal Task
		Task oneT2 = new Task();
		oneT2.WhoId = oneL.Id;
		insert oneT2;
		
		// Campaign
		Campaign cmp1 = new Campaign();
		cmp1.RecordTypeId = EBH_ConstantsUtility.CAMP_RECORDTYPE_OUTREACH_ID;
		cmp1.Name = 'TST Campaign 001';
		cmp1.StartDate = Date.today();
		cmp1.EndDate = Date.today().addDays(7);

		Campaign cmp2 = new Campaign();
		cmp2.RecordTypeId = EBH_ConstantsUtility.CAMP_RECORDTYPE_OUTREACH_ID;
		cmp2.Name = 'TST Campaign 002';
		cmp2.StartDate = Date.today();
		cmp2.EndDate = Date.today().addDays(7);

		insert new List<Campaign>{cmp1, cmp2};

		//CampaignMember
		CampaignMember cpmMember1 = new CampaignMember(
			CampaignId = cmp1.Id, 
			LeadId = oneL.Id, 
			EBH_Results__c = 'Sent', 
			EBH_ResponseCode__c = 20, //EBH_HasResponded__c = hasResponded,
			EBH_LastResponseDate__c = system.today()
		);

		CampaignMember cpmMember2 = new CampaignMember(
			CampaignId = cmp2.Id, 
			LeadId = oneL.Id, 
			EBH_Results__c = 'Sent', 
			EBH_ResponseCode__c = 20, 
			EBH_LastResponseDate__c = system.today()
		);
		
		insert new List<CampaignMember>{cpmMember1, cpmMember2};
	}

    static testMethod void testRemoveLeadGDPR() {
    	    
    	
		Lead l = EBH_TestDataFactory.createLeads();
		l.VAT_Number__c = '123123123123120';
		l.LastName = 'AMT Lead tst 03';
		l.Phone = '012 345 56745';
		l.Website = 'www.test.com.test2';
		l.Email = 'test@tes.com.invalid2';
		l.EBH_eBayID__c = 'biggest_sellert_test';
		l.Company = 'test3company';
    	insert l;
    	
    	List<Account> sellers =  EBH_TestDataFactory.createAccounts(1, 'EBH_LegalEntity') ;
    	sellers[0].Name = 'biggest_sellert_test';
    	update sellers;
    	
        
        Test.startTest();
        	List<Contact> contacts =  EBH_TestDataFactory.createContacts(1, 'Test Contact', sellers[0].id);
	    	contacts[0].Email = 'testxyz@test.com';
	    	contacts[0].EBH_GDPRRemoved__c = true;
	    	contacts[0].EBH_Status__c = 'Active';
	    	update contacts;
        Test.stopTest();
        
        	Lead l_select = [SElect Id,Email,GDPR_Removed__c,Website From Lead where Id =:l.Id];
        	System.assertEquals('deleted@deleted.com',l_select.Email,'field replaced with deleted');
        	System.assertEquals('deleted',l_select.Website,'field replaced with deleted');
        	System.assertEquals(true,l_select.GDPR_Removed__c,'field marked as GDPR deleted');
        	
        	
        
        
    }
    
    static testMethod void testvalidateAUSMBLead() {
    	RecordType recTypeAuSMBLead = ApexUtil.getRecordTypeByName('Lead','EBH_eBayAUSMB');
    	Lead l = EBH_TestDataFactory.createLeads();
    	l.LeadSource = EBH_ConstantsUtility.LEAD_SOURCE_SELF_GEN;
    	l.RecordTypeId = recTypeAuSMBLead.Id;
    	l.isapproved__c = false;
    	l.Site__c = 'AU';
    	l.LeadSegment__c = 'SMB';
    	insert l;
    	Test.startTest();
    	try{
    		l.Status = EBH_ConstantsUtility.LEAD_STATUS_QUALIFIED;
    		update l;
    	}catch(Exception e){
    		System.AssertEquals(e.getMessage().contains(System.label.eBayAuSBM_Err_2), true);
    	}
    	Test.stopTest();
    	System.Assert([select Status from Lead where id =: l.Id].Status != EBH_ConstantsUtility.LEAD_STATUS_QUALIFIED,'Record is not updated, error :'+System.label.eBayAuSBM_Err_2);
	}
	
	@isTest
	private static void leadOnboardingProcessTest(){
		Lead oneL = [SELECT Site__c, Company FROM Lead WHERE LastName = 'AMT Lead tst 01'];
		oneL.Status = 'Qualified';
		update oneL;
		Test.startTest();
			List<EBH_Project__c> lstProj = [SELECT Name, RecordTypeId, LegalEntity__c FROM EBH_Project__c WHERE Lead__c =: oneL.Id];
			System.assert(lstProj.size() == 1);
			System.assert(lstProj.get(0).LegalEntity__c != null);
			System.assert('Onboarding '+ oneL.Site__c + ' ' + oneL.Company == lstProj.get(0).Name);
			System.assert(lstProj.get(0).RecordTypeId == projAUSMB_RT);
			List<Contact> lstCont = [SELECT Id FROM Contact WHERE AccountId =: lstProj.get(0).LegalEntity__c];
			System.assert(lstCont.size() == 1);

			List<Task> lstTask = [SELECT Id FROM Task WHERE WhatId =: lstProj.get(0).Id];
			System.assertEquals(lstTask.size(), 2);
		Test.stopTest();
	}

	@isTest
	private static void leadOnboardingProcessTest2(){
		Lead oneL = [SELECT Site__c, Company FROM Lead WHERE LastName = 'AMT Lead tst 02'];
		
		Test.startTest();
			try {
				oneL.Status = 'Qualified';
				update oneL;
			} catch (Exception ex) {
				System.assert(ex.getMessage().contains(Label.LeadAccount_Duplicate_ErrorMsg));
			}
		Test.stopTest();
	}

	@isTest
	private static void leadOnboardingProcessTest3(){
		Lead oneL = [SELECT Site__c, Company FROM Lead WHERE LastName = 'AMT Lead tst 03'];
		oneL.Status = 'Qualified';
		update oneL;
		Test.startTest();
			List<EBH_Project__c> lstProj = [SELECT Name, RecordTypeId, LegalEntity__c FROM EBH_Project__c WHERE Lead__c =: oneL.Id];
			System.assert(lstProj.size() == 1);
			System.assert(lstProj.get(0).LegalEntity__c != null);
			System.assert('Onboarding '+ oneL.Site__c + ' ' + oneL.Company == lstProj.get(0).Name);
			System.assert(lstProj.get(0).RecordTypeId == projEU_RT);
		Test.stopTest();
	}
}