unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_SoldItems__c.field-meta.xml
<CustomField>
    <fullName>EBH_SoldItems__c</fullName>
    <description>[EBH] (US-0032) - to capture Sold Items value on a Seller record</description>
    <inlineHelpText>Count of items sold over the last 12 months.</inlineHelpText>
    <label>Sold Items (Last 12 Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (US-0030) - to capture the Status</description>
    <inlineHelpText>Seller´s current active status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>On Credit Hold</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>CC Verification</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>User CCVerify Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/NA_Deal_Program_Vetted__c.field-meta.xml
<CustomField>
    <fullName>NA_Deal_Program_Vetted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0009148 - [NA] New fields and Page Layout changes on Account for &#39;Seller&#39; recordtype</description>
    <inlineHelpText>Checkbox to display if a seller is NA Deal Program Subsidy Eligible Subsidy eligible or not</inlineHelpText>
    <label>NA Deal Program Subsidy eligible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NA_Deals_Subsidy_PayPal_Email__c.field-meta.xml
<CustomField>
    <fullName>NA_Deals_Subsidy_PayPal_Email__c</fullName>
    <description>US-0009543 - [NA] New field and on Account for &#39;Seller&#39; recordtype,
US-0011448 - Additional validation for NA un-sub to sub conversion rule</description>
    <inlineHelpText>Used for Seller Subsidy payment</inlineHelpText>
    <label>NA Deals Subsidy PayPal Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>US-0008785 - [NA] Resend Deal Statements to Seller</description>
    <inlineHelpText>Flag contacts in roles for specific communications</inlineHelpText>
    <label>Contact Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advertising NA</fullName>
            </value>
            <value>
                <fullName>B2C Scaling</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>eBay - Active</fullName>
            </value>
            <value>
                <fullName>eBay - Integrations</fullName>
            </value>
            <value>
                <fullName>eBay - Inventory and Pricing</fullName>
            </value>
            <value>
                <fullName>eBay - Marketing</fullName>
            </value>
            <value>
                <fullName>eBay - Non Active - Left Company</fullName>
            </value>
            <value>
                <fullName>eBay - Non Active - Moved Dept/Project</fullName>
            </value>
            <value>
                <fullName>eBay - Non Active - Retired</fullName>
            </value>
            <value>
                <fullName>eBay - Primary Contact</fullName>
            </value>
            <value>
                <fullName>eBay - Secondary Contact</fullName>
            </value>
            <value>
                <fullName>Marketplaces – Executive Contact</fullName>
            </value>
            <value>
                <fullName>Marketplaces – Financial Contact</fullName>
            </value>
            <value>
                <fullName>Primary/MC Contact</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Support Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Training Contact</fullName>
            </value>
            <value>
                <fullName>C-Suite</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deals</fullName>
                <label>NA Deals Contracts</label>
            </value>
            <value>
                <fullName>NA Deals Statement Recipient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_OracleId__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleId__c</fullName>
    <description>[EBH] (EPH-52) : Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID</inlineHelpText>
    <label>Oracle Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-3293) - to track the status of the contact</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/Deal_Contract_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contract_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>INTEG - N || CODE - N || WF - N || AP - N || VAL - N || CLASS – (Internal) || Daily Deals - Deal Configuration || CR - 00201509
US-0008178 : [US]* Deals Mass Cancellation Process for Deals Managers</description>
    <label>Deal Contract Agreement</label>
    <referenceTo>Deal_Contract_Agreement__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_BusinessName__c.field-meta.xml
<CustomField>
    <fullName>EBH_BusinessName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[EBH] (EPH-4163) - Business Name</description>
    <label>eBay Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_BusinessName</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealEndDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealEndDate__c</fullName>
    <description>[EBH] (EPH-4163) - Deal End Date</description>
    <label>Deal End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealEndTime__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealEndTime__c</fullName>
    <defaultValue>TIMEVALUE(&quot;10:00:00.000&quot;)</defaultValue>
    <description>EPH-5169 Adding Deal start and End Time fields</description>
    <label>Deal End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealStartDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealStartDate__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Start Date</description>
    <label>Deal Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealStartTime__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealStartTime__c</fullName>
    <defaultValue>TIMEVALUE(&quot;00:00:00.000&quot;)</defaultValue>
    <description>EPH-5169 Adding Deal start and End Time fields</description>
    <label>Deal Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayItemID__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayItemID__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Item ID</description>
    <label>eBay Item ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EBH_Quantity__c</fullName>
    <description>[EBH] (EPH-4163) - Quantity</description>
    <inlineHelpText>Number of units seller can commit of the item at the deal price</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SellerPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_SellerPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Seller Price</description>
    <inlineHelpText>Price seller has submitted as their offer price for the deal﻿</inlineHelpText>
    <label>Seller Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SoldItems__c.field-meta.xml
<CustomField>
    <fullName>EBH_SoldItems__c</fullName>
    <defaultValue>0</defaultValue>
    <description>[EBH] (EPH-4163) - Sold Items</description>
    <inlineHelpText>Sold Items during the deal timeframe irrespective of the deal sold price, returns or cancelations.</inlineHelpText>
    <label>Sold Items (Total)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SpotlightCategory__c.field-meta.xml
<CustomField>
    <fullName>EBH_SpotlightCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-4163) - Spotlight Category</description>
    <label>Spotlight Category</label>
    <referenceTo>EBH_SpotlightCategory__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_SpotlightCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/Final_Sold_Items__c.field-meta.xml
<CustomField>
    <fullName>Final_Sold_Items__c</fullName>
    <label>Final Sold Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/Seller_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Seller_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008225</description>
    <label>Seller Approver 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/recordTypes/Deal_V2.recordType-meta.xml
<RecordType>
    <fullName>Deal_V2</fullName>
    <active>true</active>
    <label>NA Deal</label>
</RecordType>

unpackaged/main/default/classes/ToDoListViewControllerTest.cls
@isTest
private without sharing class ToDoListViewControllerTest {
    
    private static List<EBH_Deal__c> deals = new List<EBH_Deal__c>();
    private static Deal_Statement_Setting__c setting = new Deal_Statement_Setting__c();
     @testSetup
    static void setup(){
    	setting.Initial_Payout__c=0.60;
    	setting.Amount_Held_Back__c=0.40;
    	setting.Deal_Statement_Owner__c = 'Deals_BU_team';
    	insert setting;
        Account acc = new Account(Name='Test Account Name: 1', BillingCountry='CH');
        insert acc;
        Account eBaySeller1 = new Account (Name='Trigg Digital Ltd',EBH_OracleID__c='12345', NA_Deal_Program_Vetted__c = true, NA_Deals_Subsidy_PayPal_Email__c = 'test@test.com.invalid');
        Account eBaySeller2 = new Account (Name='Test eBaySeller For Doc Approve 2',EBH_OracleID__c='12346', NA_Deal_Program_Vetted__c = true, NA_Deals_Subsidy_PayPal_Email__c = 'test@test.com.invalid');
        Account eBaySeller3 = new Account (Name='Test eBaySeller For Doc Approve 3',EBH_OracleID__c='12347', NA_Deal_Program_Vetted__c = true, NA_Deals_Subsidy_PayPal_Email__c = 'test@test.com.invalid');
        insert new List<Account>{eBaySeller1,eBaySeller2,eBaySeller3};
        Contact contact1 = new Contact(MailingCountry='USA',MailingState='TX',MailingCity='Dallas',
                                      FirstName='firstname',Salutation='Mr.',LastName='test1',
                                      email='test1@test.com' , AccountId = eBaySeller1.Id, Contact_Role__c='Deals');
        Contact contact2 = new Contact(MailingCountry='USA',MailingState='TX',MailingCity='Dallas',
                                      FirstName='firstname',Salutation='Mr.',LastName='test2',
                                      email='test2@test.com' , AccountId = eBaySeller2.Id);
        insert new List<Contact>{contact1,contact2};
        Deal_Timezone__c dealTimezone = new Deal_Timezone__c();
        dealTimezone.TimeZone__c='America/Los_Angeles';     
        insert dealTimezone;
        EBH_SpotlightCategory__c spotCat = new EBH_SpotlightCategory__c(Name = 'test spotLightCat',EBH_Country__c='NA',EBH_SpotlightCategoryID__c='testSpotId');
        insert spotCat;
        Id devRecordTypeId = ApexUtil.getRecordTypeByName('EBH_Deal__c','Deal_V2').Id;
        Deal_Contract_Agreement__c ndca = new Deal_Contract_Agreement__c();
        insert ndca;
        Time t = System.now().time();
        Date myDate = System.Today();
        integer i=0;
        Time startTime = t.addHours(2);
        Time endTime = t.addHours(3);
        deals = new List<EBH_Deal__c>();
            EBH_Deal__c d1 = new EBH_Deal__c(
            EBH_eBayItemID__c = '00000000001'+i++, 
            Seller_Approver_1__c = contact1.Id,
            EBH_BusinessName__c=eBaySeller1.ID,
            EBH_SpotlightCategory__c = spotCat.Id,
            RecordTypeId=devRecordTypeId,
            EBH_SellerPrice__c=20,
            EBH_Quantity__c=2,
            EBH_SoldItems__c=2,
            Final_Sold_Items__c=5,
            EBH_DealPrice__c =10,
            EBH_DealStartDate__c=myDate,
            EBH_DealStartTime__c =  startTime,
            EBH_DealEndDate__c=myDate,
            EBH_DealEndTime__c = endTime,
            EBH_Status__c='Running',
            EBH_Vertical__c = 'Home & Garden',EBH_Category__c='Home & Garden',
            Sub_Category__c='Bedding', EBH_ProductTitle__c='product 1',
            EBH_SellerEmail__c='sales@test.com',Deal_Contract_Agreement__c = ndca.id);

            deals.add( d1);
            
            EBH_Deal__c d2 = new EBH_Deal__c(
            EBH_eBayItemID__c = '00000000001'+i++, 
            Seller_Approver_1__c = contact1.Id,
            EBH_BusinessName__c=eBaySeller2.ID,
            EBH_SpotlightCategory__c = spotCat.Id,
            RecordTypeId=devRecordTypeId,
            EBH_SellerPrice__c=20,
            EBH_Quantity__c=5,
            EBH_DealPrice__c =10,
            EBH_DealStartDate__c=myDate,
            EBH_DealStartTime__c =  startTime,
            EBH_DealEndDate__c=myDate,
            EBH_DealEndTime__c = startTime,           
            EBH_SoldItems__c=5,
            Final_Sold_Items__c=5,
            EBH_Status__c='Running',
            EBH_Vertical__c = 'Home & Garden',EBH_Category__c='Home & Garden',
            Sub_Category__c='Bedding', EBH_ProductTitle__c='product 1',
            EBH_SellerEmail__c='sales@test.com',Deal_Contract_Agreement__c = ndca.id);
            deals.add( d2);
            
            EBH_Deal__c d3 = new EBH_Deal__c(
            EBH_eBayItemID__c = '00000000001'+i, 
            Seller_Approver_1__c = contact1.Id,
            EBH_BusinessName__c=eBaySeller3.ID,
            EBH_SpotlightCategory__c = spotCat.Id,
            RecordTypeId=devRecordTypeId,
            EBH_SellerPrice__c=20,
            EBH_Quantity__c=5,         
            EBH_SoldItems__c=5,
            Final_Sold_Items__c=5,
            EBH_DealStartDate__c=myDate,
            EBH_DealPrice__c =5,
            EBH_DealStartTime__c =  startTime,
            EBH_DealEndDate__c=myDate,
            EBH_DealEndTime__c = startTime,
            EBH_Status__c='Running',
            EBH_Vertical__c = 'Home & Garden',EBH_Category__c='Home & Garden',
            Sub_Category__c='Bedding', EBH_ProductTitle__c='product 1',
            EBH_SellerEmail__c='sales@test.com',Deal_Contract_Agreement__c = ndca.id);     
            deals.add( d3);
            
            EBH_Deal__c d4 = new EBH_Deal__c(
            EBH_eBayItemID__c = '00000000002'+i, 
            Seller_Approver_1__c = contact1.Id,
            EBH_BusinessName__c=eBaySeller3.ID,
            EBH_SpotlightCategory__c = spotCat.Id,
            RecordTypeId=devRecordTypeId,
            EBH_SellerPrice__c=1000,
            EBH_Quantity__c=5,         
            EBH_SoldItems__c=5,
            Final_Sold_Items__c=5,
            EBH_DealStartDate__c=myDate,
            EBH_DealPrice__c =11,
            EBH_DealStartTime__c =  startTime,
            EBH_DealEndDate__c=myDate,
            EBH_DealEndTime__c = startTime,
            EBH_Status__c='Running',
            EBH_Vertical__c = 'Home & Garden',EBH_Category__c='Home & Garden',
            Sub_Category__c='Bedding', EBH_ProductTitle__c='product 1',
            EBH_SellerEmail__c='sales@test.com',Deal_Contract_Agreement__c = ndca.id);
            deals.add(d4);

            EBH_Deal__c d5 = new EBH_Deal__c(
            EBH_eBayItemID__c = '00000000003'+i, 
            Seller_Approver_1__c = contact1.Id,
            EBH_BusinessName__c=eBaySeller1.ID,
            EBH_SpotlightCategory__c = spotCat.Id,
            RecordTypeId=devRecordTypeId,
            EBH_SellerPrice__c=1000,
            EBH_Quantity__c=5,         
            EBH_SoldItems__c=5,
            Final_Sold_Items__c=5,
            EBH_DealStartDate__c=myDate,
            EBH_DealPrice__c =11,
            EBH_DealStartTime__c =  startTime,
            EBH_DealEndDate__c=myDate,
            EBH_DealEndTime__c = startTime,
            EBH_Status__c='Statement Verified',
            EBH_Vertical__c = 'Home & Garden',EBH_Category__c='Home & Garden',
            Sub_Category__c='Bedding', EBH_ProductTitle__c='product 1',
            EBH_SellerEmail__c='sales@test.com');
            deals.add(d5);

            insert deals;
            
    }
    /*
    @IsTest
    static void testCountDeal(){
        
        Test.startTest();       
        
        String numberLiveDeals = ToDoListViewController.initCountLiveDeals('7');       
        System.assert(Integer.ValueOf(numberLiveDeals) > 0);

        String numberScheduledDeals = ToDoListViewController.initCountScheduledDeals('7');       
        System.assert(Integer.ValueOf(numberScheduledDeals) == 0);

        String numberCancelledDeals = ToDoListViewController.initCountCancelledDeals('7');       
        System.assert(Integer.ValueOf(numberCancelledDeals) == 0);
        
        
        Test.stopTest();
        
    }
    */
    @IsTest
    static void testCheckHasPermission(){
        
        Test.startTest();

        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];     
        
        Contact con = [SELECT Id,Email FROM Contact WHERE email='test1@test.com' limit 1];
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,                                
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        insert user1;

        
        System.runAs(user1){
            boolean hasPerm = ToDoListViewController.hasPermission();
            System.assertEquals(false, hasPerm,'no ps assigned yet');
        }
        PermissionSet[] psDE = [Select Id from PermissionSet Where Name='DE_Seller_Portal_Deals'];
        if(!psDE.isEmpty())
        {
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId=psDE[0].Id,AssigneeId=user1.Id);
            insert psa;
          

            System.runAs(user1){
                boolean hasPerm = ToDoListViewController.hasPermission();
                System.assertEquals(true, hasPerm,'ps assigned');
            }
        }
       


        Test.stopTest();
        
    }

    @isTest
    static void test_fetchToDoListMetadata() {

        Test.startTest();

            List<ToDoListViewController.ToDoListWrapper> result = ToDoListViewController.fetchToDoListMetadata('ToDoList');
            System.assert(!result.isEmpty(), 'There should be To-do list notification display on screen.');

        Test.stopTest();
    }
}