unpackaged/main/default/objects/Account/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (US-0030) - to capture the Status</description>
    <inlineHelpText>Seller´s current active status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>On Credit Hold</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>CC Verification</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>User CCVerify Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/SP_Deals__c.field-meta.xml
<CustomField>
    <fullName>SP_Deals__c</fullName>
    <description>US-0011312 - Rebuild Deals Page</description>
    <inlineHelpText>&quot;Full Access&quot; means a Seller can view and create Deals, &quot;Read Only&quot; means a Seller can only view Deals, &quot;Allowed&quot; means they can see the Deals tab in the portal</inlineHelpText>
    <label>SP Deals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-3293) - to track the status of the contact</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealRetailCampaign__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealRetailCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5546 Relationship between Deal and Deal Retail Campaign objects</description>
    <label>Deal Retail Campaign</label>
    <referenceTo>EBH_DealRetailCampaign__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayItemID__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayItemID__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Item ID</description>
    <label>eBay Item ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_ProductTitle__c.field-meta.xml
<CustomField>
    <fullName>EBH_ProductTitle__c</fullName>
    <description>[EBH] (EPH-4163) - Product Title
US-0009410 - DEALS: Increase &#39;Product Title&#39; field length to 150 characters</description>
    <label>Product Title</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_ReasonforRejection__c.field-meta.xml
<CustomField>
    <fullName>EBH_ReasonforRejection__c</fullName>
    <description>[EBH] (EPH-4163) - Reason for Rejection</description>
    <label>Reason for Rejection</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EBH_DealSiteId__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Preis zu hoch</fullName>
            </value>
            <value>
                <fullName>Fehlende oder falsche Angaben</fullName>
            </value>
            <value>
                <fullName>Angebotene Menge zu gering</fullName>
            </value>
            <value>
                <fullName>Deal bereits anderweitig vereinbart</fullName>
            </value>
            <value>
                <fullName>Abverkaufspotenzial zu gering</fullName>
            </value>
            <value>
                <fullName>Saisonal nicht relevant</fullName>
            </value>
            <value>
                <fullName>Schlechte Bildqualität</fullName>
            </value>
            <value>
                <fullName>Falsche Kategorie</fullName>
            </value>
            <value>
                <fullName>Deal-Frequenz zu hoch</fullName>
            </value>
            <value>
                <fullName>Ist bereits im Basket</fullName>
            </value>
            <value>
                <fullName>Low revenue potential</fullName>
            </value>
            <value>
                <fullName>Quantity is too low</fullName>
            </value>
            <value>
                <fullName>Similar deal already agreed</fullName>
            </value>
            <value>
                <fullName>Supply exceeds demand</fullName>
            </value>
            <value>
                <fullName>Incorrect eBay category</fullName>
            </value>
            <value>
                <fullName>Missing or incorrect information</fullName>
            </value>
            <value>
                <fullName>Already promoted</fullName>
            </value>
            <value>
                <fullName>Price is too high</fullName>
            </value>
            <value>
                <fullName>Out of season</fullName>
            </value>
            <value>
                <fullName>Poor picture quality</fullName>
            </value>
            <value>
                <fullName>Prix trop élevé</fullName>
            </value>
            <value>
                <fullName>Informations manquantes ou incorrectes</fullName>
            </value>
            <value>
                <fullName>Quantité insuffisante</fullName>
            </value>
            <value>
                <fullName>Promo similaire déjà acceptée</fullName>
            </value>
            <value>
                <fullName>Faible potentiel de revenu</fullName>
            </value>
            <value>
                <fullName>Hors saison</fullName>
            </value>
            <value>
                <fullName>Photo de mauvaise qualité</fullName>
            </value>
            <value>
                <fullName>Catégorie eBay incorrecte</fullName>
            </value>
            <value>
                <fullName>Offre supérieure à la demande</fullName>
            </value>
            <value>
                <fullName>Annonce déjà sponsorisée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-4163) - Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Negotiating Amended</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Seller Invite</fullName>
            </value>
            <value>
                <fullName>Seller Proposal</fullName>
            </value>
            <value>
                <fullName>Deal Agreed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <label>Statement Verified (Trigger Email to Seller)</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected (Email resend to Seller)</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Completed</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Visual Sales Path</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Internally Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/EBH_DealRetailCampaign__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-5481) - Deal Retail Campaign</description>
    <label>Deal Retail Campaign</label>
    <nameField>
        <displayFormat>DRC-{0000000000}</displayFormat>
        <label>Deal Retail Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Retail Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Country__c.field-meta.xml
<CustomField>
    <fullName>EBH_Country__c</fullName>
    <description>Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>71</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>186</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/recordTypes/Deal_Campaign_V1.recordType-meta.xml
<RecordType>
    <fullName>Deal_Campaign_V1</fullName>
    <active>true</active>
    <label>Standard Campaign</label>
</RecordType>

unpackaged/main/default/classes/CustomDealController.cls
public without sharing class CustomDealController {   


    private static final string DRC_STANDARD_COMPAIGN = 'Deal_Campaign_V1';
    private static final String SITE_DE = '77';
    private static final string FULL_ACCESS = 'Full Access';

    @AuraEnabled(cacheable=true)
    public static String getAccountIdUser() {
        try {           
          
            List<Contact> lstCons = [SELECT AccountId, Id FROM Contact WHERE Id IN (SELECT ContactId FROM User WHERE Id =:UserInfo.getUserID())];

            List<Account> lstDefaultAcc = [SELECT Id FROM Account WHERE Name = 'Trigg Digital Ltd' LIMIT 1]; 

            return (!lstCons.isEmpty()) ? lstCons[0].AccountId : lstDefaultAcc[0].Id; // fixed Id of account Trigg Digital Ltd use as default on sandbox   
            
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }

    }

    @AuraEnabled(cacheable=true)
    public static String initData() {       

            Map<String, String> mapRes = new Map<String, String>();
          
            List<Contact> lstCons = [SELECT AccountId, Id, Email FROM Contact WHERE Id IN (SELECT ContactId FROM User WHERE Id =:UserInfo.getUserID())];

            List<Account> lstDefaultAcc = [SELECT Id FROM Account WHERE Name = 'Trigg Digital Ltd' LIMIT 1];

            List<User> lstIntegUser = [SELECT Id FROM User WHERE Name = 'Integration User'];
            // map integration user
            mapRes.put('intUser', (!lstIntegUser.isEmpty()) ? lstIntegUser[0].Id : '');

            // map contact id
            String conId = (lstCons.isEmpty()) ? '' : lstCons[0].Id ;
            mapRes.put('contactId', conId);
            String email = (lstCons.isEmpty()) ? '' : lstCons[0].Email ;
            mapRes.put('email', email);
            // map account Id
            mapRes.put('accountId', (!lstCons.isEmpty()) ? lstCons[0].AccountId : lstDefaultAcc[0].Id);  // fixed Id of account Trigg Digital Ltd use as default on sandbox      

            System.debug('mapRes >>> '+mapRes);
            
            return JSON.serialize(mapRes); 
       
    }


    @AuraEnabled(cacheable=true)
   public static List<EBH_Deal__c> getExistingDeals(String searchKey, String sortedBy, String sortedDirection) {
    try {
    
       String query = 'SELECT Id, Name, EBH_ProductTitle__c, EBH_eBayItemID__c FROM EBH_Deal__c';
      
       if ( String.isNotBlank(searchKey)) {
           String key = '%' + searchKey + '%';
           query += ' WHERE EBH_ProductTitle__c LIKE :key';
       }
       if ( sortedBy != null && sortedDirection != null ) {
           query += ' ORDER BY ' + sortedBy + ' ' + sortedDirection;
       }

       query += ' LIMIT 5';
       system.debug('query---'+query);
    
       return Database.query( query );    
       
    } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
   }
   

     /***********************************************************************************************************************************
    @ Method:       apexUpdateDeal 
    @ Version:      1.0
    @ Author:       Vadhanak Voun (vadhanak.voun@gaea-sys.com)
    @ Purpose:      US-0010560 - [SP - EU Deals] Allow sellers to edit specific deal fields post deal rejection
    @ Parameter:    deal
    ------------------------------------------------------------------------------------------------------------------------------------
    @ Returns  map result
    ------------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 11.11.2021 / Vadhanak Voun / Created the Method.
    ------------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 21.02.2022 / Mony Nou / US-0011309 - Missing Item-ID: To-Do list and List Views 
                                                - So that we can reuse this method for Enter eBay Item ID as well
    ***********************************************************************************************************************************/
    @AuraEnabled
    public static Map<String,Object> apexUpdateDeal(EBH_Deal__c deal, Boolean isEnterEID) 
    { 
        Map<String,Object>  mapResult = new Map<String,Object>();
       try
       {    
            if (!isEnterEID) {
                deal.EBH_Status__c = 'New';
                deal.EBH_ReasonforRejection__c = null;
            }
            
            update deal;
             
            mapResult.put('status','ok');

       }catch(DmlException dex)
       {
            mapResult.put('status','ko'); mapResult.put('error',dex.getDmlMessage(0));mapResult.put('error_detail',dex.getStackTraceString());
       }

       return mapResult;
    }
    
    /*****************************************************************************************************************************
    @ Method:         getTodayDealSetting
    @ Version:        1.0
    @ Author:          
    @ Purpose:        US-0010733 - [SP - EU Deals] [Bug] Single Deal Form should not allow 
                                    submit when seller has reached daily or DRC limit
    ------------------------------------------------------------------------------------------------------------------------------
    @ Parameter:      String dealReatilCampaingId
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 29-11-2021 /Loumang SENG/ Created the  Method.
    *****************************************************************************************************************************/
    @AuraEnabled
    public static Object getTodayDealSetting(String dealReatilCampaingId){
        Map<String, Object> mResult = new Map<String, Object>();
        mResult.put('status', 'error');
        try{ mResult = ClsBulkUploadCSV.getTodayDealSetting(dealReatilCampaingId);}catch(Exception ex) {mResult.put('message', ex.getMessage());} return mResult;  
    }


    /*****************************************************************************************************************************
    @ Method:         getTodayDEDealSetting
    @ Version:        1.0
    @ Author:          
    @ Purpose:        US-0010950 - Account Selection field on Deal Creation/List Views
    ------------------------------------------------------------------------------------------------------------------------------
    @ Parameter:      String dealReatilCampaingId
    @ Parameter:      String accountId
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 29-04-2022 /Mony Nou/ Created the  Method.
    *****************************************************************************************************************************/
    @AuraEnabled
    public static Object getTodayDEDealSetting(String dealReatilCampaingId, String accountId){
        Map<String, Object> mResult = new Map<String, Object>();
        mResult.put('status', 'error');
        if (String.isNotBlank(accountId)) ClsBulkUploadCSV.eligibleAccountId = accountId;
        try{ mResult = ClsBulkUploadCSV.getTodayDealSetting(dealReatilCampaingId);}catch(Exception ex) {mResult.put('message', ex.getMessage());} return mResult;  
    }

    /*****************************************************************************************************************************
    @ Method:         getDuplicateEbayItemID
    @ Version:        1.0
    @ Author:         SRONG TIN 
    @ Purpose:        US-0011338 - System allowing Deals with same item ID & overlapping dates
    ------------------------------------------------------------------------------------------------------------------------------
    @ Parameter:      String dealReatilCampaingId, Integer eBayItemId
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 14-03-2022 /SRONG TING/ Created the  Method.
    *****************************************************************************************************************************/
    @AuraEnabled
    public static Object getDuplicateEbayItemID(String dealReatilCampaingId,String eBayItemId){
        Map<String, Object> mResult = new Map<String, Object>();
        Id drcRecordTypeId = Schema.SObjectType.EBH_DealRetailCampaign__c.getRecordTypeInfosByDeveloperName().get(DRC_STANDARD_COMPAIGN).getRecordTypeId();
        mResult.put('status', 'error');
        List<EBH_Deal__c> deals = new List<EBH_Deal__c>();
        try{ 
            
            List<EBH_Deal__c> lstDeals = [Select Id from EBH_Deal__c where EBH_eBayItemID__c = :eBayItemId and ( EBH_DealRetailCampaign__c = :dealReatilCampaingId and EBH_DealRetailCampaign__r.RecordTypeId = :drcRecordTypeId and EBH_DealRetailCampaign__r.EBH_Country__c = :SITE_DE ) and EBH_Status__c NOT IN ('Rejected') LIMIT 1];
            mResult.put('deals', lstDeals);
            mResult.put('status', 'success');

        }catch(Exception ex) {
            mResult.put('message', ex.getMessage());
        } 
        
        return mResult;  
    }

    /*****************************************************************************************************************************
    @ Method:         getSelectedCategories
    @ Version:        1.0
    @ Author:         Sambath Seng 
    @ Purpose:        US-0010766 - [SP - EU Deals] EAN is required for specific Category
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 13-12-2021 /Sambath SENG/ Created the  Method.
    *****************************************************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<String> getSelectedCategories(){
        Seller_Portal_Global_Variables__mdt spMdt = [SELECT DeveloperName, Value_Big__c FROM Seller_Portal_Global_Variables__mdt WHERE DeveloperName = 'Deal_Selected_Categories'];
        return String.isNotBlank(spMdt.Value_Big__c) ? spMdt.Value_Big__c.split(';') : new List<String>();
    }

    /*****************************************************************************************************************************
    @ Method:         getLinkedAccSpDeal
    @ Version:        1.0
    @ Author:         Sophal Noch
    @ Purpose:        US-0011156 - Restrict ability for Sellers to be able to create Deals - Linked Account
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 03.05.2022 /Sophal Noch/ Created the  Method.
    *****************************************************************************************************************************/
    @AuraEnabled
    public static Map<String,Object> getLinkedAccSpDeal(){
        Map<String, Object> mResult = new Map<String, Object>();
        try{
            mResult.put('status', 'ok');
            Boolean isHavingNoFullAccess = true;
            RecordType recSeller = ApexUtil.getRecordTypeByName('Account', 'EBH_Seller');
            User cUser = [Select Id,Profile.Name,ContactId, Contact.AccountId, Contact.Account.Id, Contact.Account.SP_Deals__c From User Where Id=:UserInfo.getUserId()];
            Map<Id,Account> mapAcc = new Map<Id,Account>();
            for(AccountContactRelation acr : [Select Id,AccountId,Account.Id,Account.Name, Account.SP_Deals__c From AccountContactRelation Where Account.RecordTypeId =:recSeller.Id And ContactId =: cUser.ContactId]){
                mapAcc.put(acr.AccountId, acr.Account);
                if(isHavingNoFullAccess && acr.Account.SP_Deals__c == FULL_ACCESS){isHavingNoFullAccess = false;}
            }
            mResult.put('profileName', cUser.Profile.Name);
            mResult.put('mapAcc', mapAcc);
            mResult.put('isHavingNoFullAccess', isHavingNoFullAccess);
        }catch(Exception e){mResult.put('status', 'ko');mResult.put('error', e.getMessage());}

        return mResult;
    }
}