unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_SoldItems__c.field-meta.xml
<CustomField>
    <fullName>EBH_SoldItems__c</fullName>
    <description>[EBH] (US-0032) - to capture Sold Items value on a Seller record</description>
    <inlineHelpText>Count of items sold over the last 12 months.</inlineHelpText>
    <label>Sold Items (Last 12 Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (US-0030) - to capture the Status</description>
    <inlineHelpText>Seller´s current active status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>On Credit Hold</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>CC Verification</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>User CCVerify Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_OracleId__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleId__c</fullName>
    <description>[EBH] (EPH-52) : Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID</inlineHelpText>
    <label>Oracle Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-3293) - to track the status of the contact</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/Deal_Contract_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Deal_Contract_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>INTEG - N || CODE - N || WF - N || AP - N || VAL - N || CLASS – (Internal) || Daily Deals - Deal Configuration || CR - 00201509
US-0008178 : [US]* Deals Mass Cancellation Process for Deals Managers</description>
    <label>Deal Contract Agreement</label>
    <referenceTo>Deal_Contract_Agreement__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_BusinessName__c.field-meta.xml
<CustomField>
    <fullName>EBH_BusinessName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[EBH] (EPH-4163) - Business Name</description>
    <label>eBay Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_BusinessName</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealEndDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealEndDate__c</fullName>
    <description>[EBH] (EPH-4163) - Deal End Date</description>
    <label>Deal End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealEndTime__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealEndTime__c</fullName>
    <defaultValue>TIMEVALUE(&quot;10:00:00.000&quot;)</defaultValue>
    <description>EPH-5169 Adding Deal start and End Time fields</description>
    <label>Deal End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealStartDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealStartDate__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Start Date</description>
    <label>Deal Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealStartTime__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealStartTime__c</fullName>
    <defaultValue>TIMEVALUE(&quot;00:00:00.000&quot;)</defaultValue>
    <description>EPH-5169 Adding Deal start and End Time fields</description>
    <label>Deal Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayItemID__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayItemID__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Item ID</description>
    <label>eBay Item ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EBH_Quantity__c</fullName>
    <description>[EBH] (EPH-4163) - Quantity</description>
    <inlineHelpText>Number of units seller can commit of the item at the deal price</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SellerPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_SellerPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Seller Price</description>
    <inlineHelpText>Price seller has submitted as their offer price for the deal﻿</inlineHelpText>
    <label>Seller Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SoldItems__c.field-meta.xml
<CustomField>
    <fullName>EBH_SoldItems__c</fullName>
    <defaultValue>0</defaultValue>
    <description>[EBH] (EPH-4163) - Sold Items</description>
    <inlineHelpText>Sold Items during the deal timeframe irrespective of the deal sold price, returns or cancelations.</inlineHelpText>
    <label>Sold Items (Total)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SpotlightCategory__c.field-meta.xml
<CustomField>
    <fullName>EBH_SpotlightCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-4163) - Spotlight Category</description>
    <label>Spotlight Category</label>
    <referenceTo>EBH_SpotlightCategory__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_SpotlightCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-4163) - Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Negotiating Amended</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Seller Invite</fullName>
            </value>
            <value>
                <fullName>Seller Proposal</fullName>
            </value>
            <value>
                <fullName>Deal Agreed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <label>Statement Verified (Trigger Email to Seller)</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected (Email resend to Seller)</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Completed</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Visual Sales Path</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Internally Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/Final_Sold_Items__c.field-meta.xml
<CustomField>
    <fullName>Final_Sold_Items__c</fullName>
    <label>Final Sold Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/Seller_Approver_1__c.field-meta.xml
<CustomField>
    <fullName>Seller_Approver_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008225</description>
    <label>Seller Approver 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/recordTypes/Deal_V2.recordType-meta.xml
<RecordType>
    <fullName>Deal_V2</fullName>
    <active>true</active>
    <label>NA Deal</label>
</RecordType>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/EBH_DealRetailCampaign__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-5481) - Deal Retail Campaign</description>
    <label>Deal Retail Campaign</label>
    <nameField>
        <displayFormat>DRC-{0000000000}</displayFormat>
        <label>Deal Retail Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Retail Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Country__c.field-meta.xml
<CustomField>
    <fullName>EBH_Country__c</fullName>
    <description>Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>71</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>186</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SEP_CustomTabControllerTest.cls
/*********************************************************************************************************************************
@ Class:          SEP_CustomTabControllerTest
@ Version:        1.0
@ Author:         Sambath Seng
@ Purpose:        US-0010743 - [SP - Seller Portal] [Bug] Fix how results are displayed on Global Search
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 2.12.2021 / Sambath Seng / Created test class for SEP_CustomTabController.
*********************************************************************************************************************************/
@isTest
public with sharing class SEP_CustomTabControllerTest {
    @isTest
    static void testGetGlobalSearchTabs() {
        Account eBaySeller = new Account (Name='Testing',EBH_OracleID__c='12345');
        insert eBaySeller;
        Contact contact = new Contact(MailingCountry='USA',
                                    MailingState='Test', 
                                    MailingCity='Test',
                                    FirstName='Test',
                                    Salutation='Mr.',
                                    LastName='Test',
                                    email='test1@test.com',
                                    AccountId = eBaySeller.Id
                                    );
        insert contact;
        EBH_SpotlightCategory__c spotCat = new EBH_SpotlightCategory__c(Name = 'test spotLightCat',EBH_Country__c='NA',EBH_SpotlightCategoryID__c='testSpotId');
        insert spotCat;
        Id devRecordTypeId = ApexUtil.getRecordTypeByName('EBH_Deal__c','Deal_V2').Id;
        Deal_Contract_Agreement__c ndca = new Deal_Contract_Agreement__c();
        insert ndca;
        EBH_Deal__c deal = new EBH_Deal__c(
            EBH_eBayItemID__c = '000000000012', 
            Seller_Approver_1__c = contact.Id,
            EBH_BusinessName__c = eBaySeller.Id,
            EBH_SpotlightCategory__c = spotCat.Id,
            RecordTypeId = devRecordTypeId,
            EBH_SellerPrice__c = 20,
            EBH_Quantity__c = 2,
            EBH_SoldItems__c = 2,
            Final_Sold_Items__c = 5,
            EBH_DealPrice__c = 10,
            EBH_DealStartDate__c = System.Today(),
            EBH_DealStartTime__c = System.now().time().addHours(2),
            EBH_DealEndDate__c = System.Today(),
            EBH_DealEndTime__c = System.now().time().addHours(3),
            EBH_Status__c = 'Running',
            EBH_Vertical__c = 'Home & Garden',EBH_Category__c='Home & Garden',
            Sub_Category__c = 'Bedding', EBH_ProductTitle__c='product test 1'
        );
        insert deal;
        Map<String, SEP_CustomTabController.TabWrapper> result = new Map<String, SEP_CustomTabController.TabWrapper>();
        // Actual test
        Test.startTest();
            result = SEP_CustomTabController.getGlobalSearchTabs('test 1');
        Test.stopTest();
        // Asserts
        System.assertEquals('EBH_Deal__c', result.get('EBH_Deal__c').objectApi);
        System.assertEquals('Deal_Search_Result', result.get('EBH_Deal__c').developerName);
        System.assertEquals(1, result.get('EBH_Deal__c').recordCount);
        System.assertEquals('EBH_DealRetailCampaign__c', result.get('EBH_DealRetailCampaign__c').objectApi);
        System.assertEquals('Deal_Retail_Campaign_Search_Result', result.get('EBH_DealRetailCampaign__c').developerName);
        System.assertEquals(0, result.get('EBH_DealRetailCampaign__c').recordCount);
    }
}