unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_RevRollup__c.field-meta.xml
<CustomField>
    <fullName>EBH_RevRollup__c</fullName>
    <description>[EBH] (EPH-176) - Rev RollUp</description>
    <inlineHelpText>Where we attribute revenue for the Seller. Revenue is assigned based on seller country.</inlineHelpText>
    <label>Rev RollUp</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>OTHER EA</fullName>
            </value>
            <value>
                <fullName>OTHER EAPAC</fullName>
            </value>
            <value>
                <fullName>OTHER EEMEA</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>ROE -Other</fullName>
            </value>
            <value>
                <fullName>RU</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>UA</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Linked_Acc_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Linked_Acc_Group_Id__c</fullName>
    <description>US-0009125 - [Linked Acc] ETL to pull Linked Accounts grouping information for EU B2C Sellers</description>
    <inlineHelpText>Group Id that shows linked sellers via VAT, PAYPAL Account &amp; BOB Sellers.</inlineHelpText>
    <label>Linked Account Group Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/classes/LinkedCustomersControllerTest.cls
/*********************************************************************************************************************************
@ Class:          LinkedCustomersControllerTest
@ Version:        1.0
@ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
@ Purpose:        US-0009214 - [Linked Acc]Enable Linked B2C Customers to be shown in Customer 360
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 23.03.2021 / Sovantheany Dim / Created the class.
*********************************************************************************************************************************/
@isTest
public class LinkedCustomersControllerTest {
    static testMethod void testgetAccounts(){
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        Account sellerAcc1 = new Account(Linked_Acc_Group_Id__c='11111111',EBH_OracleId__c='1003293592',Name='Test Acc2',RecordTypeID = sellerRecordType.Id,EBH_RevRollup__c='UK');
    	insert sellerAcc1;
        Account sellerAcc2 = new Account(Linked_Acc_Group_Id__c='11111111', EBH_OracleId__c='1003293593',Name='Test Acc3',RecordTypeID = sellerRecordType.Id,EBH_RevRollup__c='UK');
    	insert sellerAcc2;
        Test.startTest();
        	Map<String,Object> mapResult = LinkedCustomersController.getAccounts(sellerAcc1.Id,6);                                 
        Test.stopTest();
        if(mapResult.containsKey('lstWrapper')){
            ContactsRelatedController.LightningTableWraper lstWrapper = (ContactsRelatedController.LightningTableWraper) mapResult.get('lstWrapper');
            System.assert(lstWrapper.tableRecord.size()==1);
        }
    }
}