unpackaged/main/default/objects/Account/fields/EBH_DealsProgram__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealsProgram__c</fullName>
    <description>[EBH] (EPH-4527) - Deals Program</description>
    <inlineHelpText>Is the seller eligible for the Deals Program?</inlineHelpText>
    <label>Deals Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allow</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_GBCulture__c.field-meta.xml
<CustomField>
    <fullName>EBH_GBCulture__c</fullName>
    <description>US-0006931:[AU] Subscribe AU Sellers for Deals Program</description>
    <label>Growth Portal Culture</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>en-GB</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>en-AU</fullName>
                <label>AU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_InvitedtoDealProgram__c.field-meta.xml
<CustomField>
    <fullName>EBH_InvitedtoDealProgram__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-) - Invited to Deal Program</description>
    <label>Invited to Deal Program</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/EBH_InviteToDealsProgramController.cls
public without sharing class EBH_InviteToDealsProgramController {
    
    public Account acc {get;set;}
    public Boolean isAllowed {get;set;}
    
    public ApexPages.StandardController contr;
    
    //defining the account record and the standard controller
    public EBH_InviteToDealsProgramController(ApexPages.StandardController controller) {
        this.acc = (Account)controller.getRecord();
        
    }
    
    // Saving the current record
    public PageReference updateInvitedtoDealProgram() {
    	  
    	   //NK:16/08/2019: EPH-7969: allow re-invite
        //if( acc.EBH_DealsProgram__c == null) {
        	try
        	{
        		if(String.isBlank(selectedCulture))
		    	{
		    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Growth Portal Culture is required.'));
		    		return null;
		    	}else
		    	{
		    		acc.EBH_GBCulture__c = selectedCulture;
		    	}
    	
        		acc.EBH_DealsProgram__c = 'Allow';
	            //acc.EBH_InvitedtoDealProgram__c = TRUE;
	           
	            update acc;
	             
        	}catch(Exception ex)
        	{
        		acc.EBH_DealsProgram__c = null;	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getdmlMessage(0))); return null;	
        	}
            
        //}
        //return null;
        return new PageReference('/' + acc.Id);
    }
    
    //NK:28/03/2018: use select list instead of input field (picklist culture field)
    //since Deal profile has read-only to Account
    public String selectedCulture{get;set;}
     
}