unpackaged/main/default/objects/Account/fields/EBH_OracleID__c.field-meta.xml
<CustomField>
    <fullName>EBH_OracleID__c</fullName>
    <description>[EBH] (US-0030) : To store Oracle ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Oracle ID that uniquely identifies a user.</inlineHelpText>
    <label>Oracle ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/EBH_RegistrationCountry__c.field-meta.xml
<CustomField>
    <fullName>EBH_RegistrationCountry__c</fullName>
    <description>[EBH] (US-0031) : Registration Country</description>
    <inlineHelpText>Country where Seller is registered.</inlineHelpText>
    <label>Registration Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan Republic</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cape Verde Islands</fullName>
            </value>
            <value>
                <fullName>Central African Republic</fullName>
            </value>
            <value>
                <fullName>Chad</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Congo, Democratic Republic of the</fullName>
            </value>
            <value>
                <fullName>Congo, Republic of the</fullName>
            </value>
            <value>
                <fullName>Cote d Ivoire (Ivory Coast)</fullName>
            </value>
            <value>
                <fullName>Croatia, Democratic Republic of the</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/EBH_Project__c/EBH_Project__c.object-meta.xml
<CustomObject>
    <description>#US-0015700</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Project__c/fields/EBH_Seller__c.field-meta.xml
<CustomField>
    <fullName>EBH_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#US-0015700. Lookup (Seller)</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/recordTypes/ManagedPayment.recordType-meta.xml
<RecordType>
    <fullName>ManagedPayment</fullName>
    <active>true</active>
    <description>Outreach tracking of eligible sellers to Managed Payments</description>
    <label>Managed Payment</label>
</RecordType>

unpackaged/main/default/classes/BatchUploadManagedPaymentTest.cls
@isTest
/*********************************************************************************************************************************
@ Class:          BatchUploadManagedPaymentTest
@ Version:        1.0
@ Author:         Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:        US-0007521 
@                 Test Class for BatchUploadManagedPaymentTest
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 18.06.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the class.
*********************************************************************************************************************************/
public with sharing class BatchUploadManagedPaymentTest {

    private static List<Account> sellers;
    private static List<String> oracleIds = new List<String>{'111','222','333','444'};
    private static List<String> invitationDates = new List<String>{'22/04/2020','23/04/2020','24/04/2020','25/04/2020'};


    static void init(){

        
       sellers = new List<Account> ();
        
        String germany = 'Germany';

        Id accountSellerRecordTypeId = ApexUtil.getRecordTypeByName('Account','EBH_Seller').Id;
        
        Integer accountCount = 4;

        for(Integer i = 0; i < accountCount; i++){

            Account acc = new Account(
                    Name = 'Seller_'+(i+1),
                    EBH_RegistrationCountry__c = germany,
                    EBH_OracleID__c = oracleIds[i],
                    RecordTypeId = accountSellerRecordTypeId
            );

            sellers.add(acc);
        }

    
    }


    @isTest static void createManagedPaymentFromCSVWithValidCSVData(){

        init();
        insert sellers;

        String sellerContentOne = oracleIds[0]+','+invitationDates[0];
        String sellerContentTwo = oracleIds[1]+','+invitationDates[1];
        String sellerContentThree = oracleIds[2]+','+invitationDates[2];
        String sellerContentFour = oracleIds[3]+','+invitationDates[3];

        String csvString = 'seller_id;Outreach_dt\r'+sellerContentOne+'\r'+sellerContentTwo+'\r'+sellerContentThree+'\r'+sellerContentFour;

        String uniqueName = ApexUtil.genUniqueString(10);

        //temporary doc. to be processed by Batch + String Iterator. then delete on finish
        Document doc=new Document(Name=uniqueName,Body=Blob.valueOf(csvString+''),FolderId=UserInfo.getUserId());
        insert doc;

        Test.startTest();
            BatchUploadManagedPayment b = new BatchUploadManagedPayment(null,uniqueName,'en',',');
            Database.executeBatch(b);
                         
        Test.stopTest();

            List<EBH_Project__c> createdProjectList = [SELECT Id,Name,RecordType.DeveloperName From EBH_Project__c];

            System.assertEquals(4, createdProjectList.size());

            for(EBH_Project__c eachProject : createdProjectList){
                System.assertEquals(BatchUploadManagedPayment.SELLER_MANAGED_PAYMENT_RECORD_TYPE, eachProject.RecordType.DeveloperName);
            }



    }



    @isTest static void createManagedPaymentFromCSVWithValidAndInValidCSVData(){

        init();
        insert sellers;
       
        String sellerContentOne = oracleIds[0]+','+invitationDates[0];
         // seller content 1 = correct
        
        String sellerContentTwo = (oracleIds[1]+'abc')+','+invitationDates[1];
         // seller content 2 = incorrect oracle id. seller is not  found.
        
        String sellerContentThree = oracleIds[2]+','+invitationDates[2];
        Id projectManagedPaymentRecordTypeId = ApexUtil.getRecordTypeByName('EBH_Project__c',BatchUploadManagedPayment.SELLER_MANAGED_PAYMENT_RECORD_TYPE).Id;
        EBH_Project__c projectManagedPayment = new EBH_Project__c(
            Name = 'Project ManagedPayment', 
            RecordTypeId = projectManagedPaymentRecordTypeId,
            EBH_Seller__c = sellers[2].Id
        );
        insert projectManagedPayment;
        // seller content 3 = incorrect because Managed Payment already exist
        
        String sellerContentFour = oracleIds[3]+','+(invitationDates[3].replaceAll('/', '+'));
        // seller content 4 = incorrect because incorrect Date format

        String csvString = 'seller_id;Outreach_dt\r'+sellerContentOne+'\r'+sellerContentTwo+'\r'+sellerContentThree+'\r'+sellerContentFour;

        String uniqueName = ApexUtil.genUniqueString(10);

        //temporary doc. to be processed by Batch + String Iterator. then delete on finish
        Document doc=new Document(Name=uniqueName,Body=Blob.valueOf(csvString+''),FolderId=UserInfo.getUserId());
        insert doc;

        Test.startTest();
        BatchUploadManagedPayment b = new BatchUploadManagedPayment(null,uniqueName,'en',',');
        Database.executeBatch(b);
                     
        Test.stopTest();

        
        List<EBH_Project__c> createdProjectList = [SELECT Id,Name,EBH_Seller__c From EBH_Project__c WHERE Id !=: projectManagedPayment.Id];

        System.assertEquals(1, createdProjectList.size());

        System.assertEquals(sellers[0].Id, createdProjectList[0].EBH_Seller__c);


    }


}