unpackaged/main/default/objects/Account/fields/EBH_DealsProgram__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealsProgram__c</fullName>
    <description>[EBH] (EPH-4527) - Deals Program</description>
    <inlineHelpText>Is the seller eligible for the Deals Program?</inlineHelpText>
    <label>Deals Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allow</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  DATEVALUE(&quot;2099-1-1&quot;) , null)</defaultValue>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Negotiation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_End_Date__c</fullName>
    <description>US-0018714 [AU] New Fields in Coupon and Coupon Seller</description>
    <label>Negotiation End Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Seller_Co_funding_share_forecast__c.field-meta.xml
<CustomField>
    <fullName>Seller_Co_funding_share_forecast__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>This is the forecast provided by the Coupon Owner</inlineHelpText>
    <label>Seller Co-funding Share (forecast)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/Coupon_Co_Invest__c.object-meta.xml
<CustomObject>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Co-Invest</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Coupon Co-Invest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Co-Invests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Co_Invest__c.field-meta.xml
<CustomField>
    <fullName>Co_Invest__c</fullName>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Seller Share %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Name__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if Coupon Co-Invests is POP, then coupon must be pop</errorMessage>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Seller__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Seller</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if Coupon Co-Invests is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon_Seller__c</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <formula>TEXT(Coupon_Seller__r.Coupon_Seller_Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coupon Seller Stage</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Seller Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Email_Adress__c.field-meta.xml
<CustomField>
    <fullName>Email_Adress__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <inlineHelpText>Email Adress provided by seller</inlineHelpText>
    <label>Email Adress</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_Name_w__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_w__c</fullName>
    <description>EPH-7583 Change logic for contactdatafields in coupon seller</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_Street_w__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Street_w__c</fullName>
    <description>EPH-7583 Change logic for contactdatafields in coupon seller</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_Zip_w__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Zip_w__c</fullName>
    <description>EPH-7583 Change logic for contactdatafields in coupon seller</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Negotiation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_End_Date__c</fullName>
    <formula>Coupon__r.Negotiation_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Negotiation End Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller_Co_funding_Share_forecast__c.field-meta.xml
<CustomField>
    <fullName>Seller_Co_funding_Share_forecast__c</fullName>
    <formula>Coupon__r.Seller_Co_funding_share_forecast__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seller Co-funding Share (forecast)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Seller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0009891 - Create new fields on Coupon and Coupon-Seller required for MC Coupon Flow.
US-0011981</description>
    <inlineHelpText>Seller Contact to be user for the email communication.</inlineHelpText>
    <label>Seller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name__c</fullName>
    <description>US-0010435</description>
    <formula>Seller__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seller Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BulkSendCouponContractControllerTest.cls
/*********************************************************************************************************************************
@ Class:          BulkSendCouponContractControllerTest
@ Version:        1.0
@ Author:         Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:        BulkSendCouponContractController
----------------------------------------------------------------------------------------------------------------------------------
@ Change history:  27.08.2020 / Sophal Noch / Created the class.
*********************************************************************************************************************************/
@isTest
private class BulkSendCouponContractControllerTest {

    static testMethod void testInitAndSaveCoupounSeller(){
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        Account acc = new Account(Name='Test Acc1',RecordTypeID = sellerRecordType.Id,EBH_DealsProgram__c='Accepted');
        insert acc;

        Contact con = new Contact(LastName='Test Con1', Email='test@test.com.invalid', AccountId=acc.Id);
        Contact con2 = new Contact(LastName='Test Con2', Email='test2@test.com.invalid', AccountId=acc.Id);
        insert new List<Contact>{con, con2};

        Coupon__c c1 = new Coupon__c(Seller_Co_funding_share_forecast__c = null,Coupon_Start_Date__c = System.today(),Coupon_End_Date__c = System.today().addDays(1), Negotiation_End_Date__c=System.today().addDays(1));
        insert c1;

        Coupon_Seller__c cs1 = new Coupon_Seller__c(Seller_Contact__c = con.Id, Coupon__c = c1.Id,seller__c = acc.Id,Legal_Entity_Name_w__c = 'testName',Legal_Entity_Street_w__c='testStreet',Legal_Entity_Zip_w__c='testZip');
        Coupon_Seller__c cs2 = new Coupon_Seller__c(Seller_Contact__c = con2.Id, Coupon__c = c1.Id,seller__c = acc.Id,Legal_Entity_Name_w__c = 'testName',Legal_Entity_Street_w__c='testStreet',Legal_Entity_Zip_w__c='testZip');

        /* //MN-30082021-US-0009948-Replace Email_Adress__c with Seller_Contact__c
        Coupon_Seller__c cs1 = new Coupon_Seller__c(Email_Adress__c = 'sophal.noch@gaea-sys.com', Coupon__c = c1.Id,seller__c = acc.Id,Legal_Entity_Name_w__c = 'testName',Legal_Entity_Street_w__c='testStreet',Legal_Entity_Zip_w__c='testZip');
        Coupon_Seller__c cs2 = new Coupon_Seller__c(Email_Adress__c = 'sophal.noch@gaea-sys.com',Coupon__c = c1.Id,seller__c = acc.Id,Legal_Entity_Name_w__c = 'testName',Legal_Entity_Street_w__c='testStreet',Legal_Entity_Zip_w__c='testZip');
        */
        insert new List<Coupon_Seller__c>{cs1,cs2}; 

        cs1.Legal_Entity_Name_w__c = 'testName';
        cs1.Legal_Entity_Street_w__c = 'testStreet';
        cs1.Legal_Entity_Zip_w__c = 'testZip';

        cs2.Legal_Entity_Name_w__c = 'testName';
        cs2.Legal_Entity_Street_w__c = 'testStreet';
        cs2.Legal_Entity_Zip_w__c = 'testZip';

        update new List<Coupon_Seller__c>{cs1,cs2}; 

        
        Coupon_Co_Invest__c coInvestForCs1 = new Coupon_Co_Invest__c(Coupon_Seller__c=cs1.Id, Seller_Name__c=acc.Id,Coupon_Name__c=c1.Id,Co_Invest__c=10);
        Coupon_Co_Invest__c coInvestForCs2 = new Coupon_Co_Invest__c(Coupon_Seller__c=cs2.Id, Seller_Name__c=acc.Id,Coupon_Name__c=c1.Id,Co_Invest__c=20);
        
        insert new List<Coupon_Co_Invest__c>{coInvestForCs1,coInvestForCs2}; 

       

        PermissionSet ps = Database.query('SELECT Id, Name FROM PermissionSet WHERE Name = \'Coupon_Special_Permission\'');

        User standardUser = [
            SELECT Id FROM User 
            WHERE Profile.Name = 'Standard User Profile' 
            AND IsActive = true
            AND Id NOT IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSetId =: ps.Id)
            LIMIT 1
        ];

        System.assertNotEquals(null, standardUser.Id);


        System.runAs(standardUser){

            Map<String,Object> mapResult = BulkSendCouponContractController.apexInit(c1.Id);

            System.assertEquals(System.Label.ErrorNoCouponSpecialPermission, (String)mapResult.get('error'));
            System.assertEquals('ko', (String)mapResult.get('status'));

        }

       

       
        
        Test.startTest();
        System.runAs(standardUser){

            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = UserInfo.getUserId());
            insert psa;

            Map<String,Object> mapResult = BulkSendCouponContractController.apexInit(c1.Id);
            System.assertEquals('ok', (String)mapResult.get('status'));
    
            List<Coupon_Seller__c> listCoSeller = ((List<Coupon_Seller__c>)mapResult.get('listCoSeller'));
    
            System.assertEquals(2, listCoSeller.size());
    
    
            mapResult = BulkSendCouponContractController.apexSave(listCoSeller);
            System.assertEquals('ko', (String)mapResult.get('status'));
            System.assertEquals(System.Label.ErrorNoCouponSellerInApprovedStage, (String)mapResult.get('error'));
    
            listCoSeller[0].Coupon_Seller_Stage__c = EBH_ConstantsUtility.COUPONSELLER_STAGE_APPROVED;
            listCoSeller[1].Coupon_Seller_Stage__c = EBH_ConstantsUtility.COUPONSELLER_STAGE_APPROVED;
            update listCoSeller;
    
            mapResult = BulkSendCouponContractController.apexSave(listCoSeller);
            System.assertEquals(null, (String)mapResult.get('error'));
            System.assertEquals('ok', (String)mapResult.get('status'));
    
            List<Coupon_Seller__c> listCoSellerAfterUpdated = [SELECT Id,Coupon_Seller_Stage__c FROM Coupon_Seller__c where Id =: listCoSeller[0].Id OR Id =: listCoSeller[1].Id];
            System.assertEquals(EBH_ConstantsUtility.COUPON_SELLER_STAGE_CONTRACT_SEND, listCoSellerAfterUpdated[0].Coupon_Seller_Stage__c);
            System.assertEquals(EBH_ConstantsUtility.COUPON_SELLER_STAGE_CONTRACT_SEND, listCoSellerAfterUpdated[1].Coupon_Seller_Stage__c);

        }
        Test.stopTest();


        


    }

}