unpackaged/main/default/objects/Account/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (US-0030) - to capture the Status</description>
    <inlineHelpText>Seller´s current active status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>On Credit Hold</fullName>
            </value>
            <value>
                <fullName>Unconfirmed</fullName>
            </value>
            <value>
                <fullName>CC Verification</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>User CCVerify Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Campaign/fields/EBH_SellerList__c.field-meta.xml
<CustomField>
    <fullName>EBH_SellerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-1880) - Seller List</description>
    <label>Seller List</label>
    <referenceTo>EBH_Filter__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>EBH_Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-3293) - to track the status of the contact</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/EBH_DWH.recordType-meta.xml
<RecordType>
    <fullName>EBH_DWH</fullName>
    <active>true</active>
    <description>Contact that comes from DW Warehouse</description>
    <label>DWH</label>
</RecordType>

unpackaged/main/default/objects/EBH_TargetedSeller__c/EBH_TargetedSeller__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EBH-55), (EBH-103) - Distinct sellers that have been targeted. Targeted sellers that comes from DWH (Targeting Engine)</description>
    <label>Targeted Seller</label>
    <nameField>
        <displayFormat>TS - {0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Sellers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_TargetedSeller__c/fields/EBH_ExitCode__c.field-meta.xml
<CustomField>
    <fullName>EBH_ExitCode__c</fullName>
    <defaultValue>&#39;10&#39;</defaultValue>
    <description>[EBH] (EPH-5625) - to capture exit code Sellers that are &quot;Marketing Blacklist = TRUE&quot; will be flagged &quot;Exit Code&quot; = &quot;02&quot;
If not, Sellers that have 0 Contacts with &quot;Marketing Opt-in&quot; will be flagged &quot;Member Status&quot; = &quot;30)
If not, percentage of &quot;Control Group Size (%)&quot; Sellers will be flagged as &quot;Exit Code&quot; = &quot;10&quot;
Otherwise, all remaining Sellers are set to &quot;Exit Code&quot; = &quot;20&quot;</description>
    <label>Exit Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_TargetedSeller__c/fields/EBH_Seller__c.field-meta.xml
<CustomField>
    <fullName>EBH_Seller__c</fullName>
    <description>[EBH] (EBH-55), (EBH-103) - Targeted seller lookup</description>
    <inlineHelpText>Targeted seller lookup</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Targeted Sellers</relationshipLabel>
    <relationshipName>EBH_TargetedSellers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/EBH_TargetedSeller__c/fields/EBH_SellerList__c.field-meta.xml
<CustomField>
    <fullName>EBH_SellerList__c</fullName>
    <description>[EBH] (EBH-55), (EBH-103) - Filter</description>
    <inlineHelpText>Filter</inlineHelpText>
    <label>Seller List</label>
    <referenceTo>EBH_Filter__c</referenceTo>
    <relationshipLabel>Targeted Sellers</relationshipLabel>
    <relationshipName>EBH_TargetedSellers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/EBH_TargetedSeller__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>EPH-6850 Targeting Engine with Priority</description>
    <label>Priority</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/EBH_CampaignMemberBatchTest.cls
@isTest
private class EBH_CampaignMemberBatchTest {
	@isTest
    static void testCampaignMemberBatch(){
        EBH_CampaignMemberBatch cmb = new EBH_CampaignMemberBatch();
    //     EBH_TestDataFactory.setUpCustomSettings();
    //     Set<Id> accIds = new Set<Id>();
    //     Set<Id> camIds = new Set<Id>();
    //     Map<Id, Campaign> camIdMap = new Map<Id, Campaign>();
    //     Map<Id, List<EBH_TargetedSeller__c>> sellerListTargetedSellerMap = new Map<Id, List<EBH_TargetedSeller__c>>();
    //     List<EBH_TargetedSeller__c> lstTargetedSeller1 = new List<EBH_TargetedSeller__c>();
    //     List<Account> sellers = EBH_TestDataFactory.createAccounts(2, 'EBH_Seller');
    //     RecordType rtSellerList = EBH_TestDataFactory.getRecordTypeByName('EBH_Filter__c', 'EBH_ManualSellerList');
    //     EBH_Filter__c sellerList1 = new EBH_Filter__c(Name='test', RecordTypeId=rtSellerList.Id);
    //     insert sellerList1;
    //     List<Campaign> campaign1 = EBH_TestDataFactory.createCampaignsWithParent(2, 'Test Campaign1', 'UK', EBH_ConstantsUtility.CAMP_RECORDTYPE_OUTREACH, null, 'Feasibility');
    //     RecordType rtContact = EBH_TestDataFactory.getRecordTypeByName('Contact','EBH_DWH');
    //     Contact con1 = new Contact(EBH_Status__c='Active', LastName = 'Test Contact 1', AccountId = sellers[0].Id, recordTypeId = rtContact.Id);
    //     insert con1;
    //     Contact con2 = new Contact(EBH_Status__c='Active', LastName = 'Test Contact 2', AccountId = sellers[1].Id, recordTypeId = rtContact.Id);
    //     insert con2;
    //     lstTargetedSeller1.add(new EBH_TargetedSeller__c(EBH_Seller__c=sellers[0].Id, EBH_SellerList__c=sellerList1.Id, Priority__c=10, EBH_ExitCode__c='10'));
    //     lstTargetedSeller1.add(new EBH_TargetedSeller__c(EBH_Seller__c=sellers[1].Id, EBH_SellerList__c=sellerList1.Id, Priority__c=10, EBH_ExitCode__c='10'));
    //     insert lstTargetedSeller1;
    //     for(Account oAcc : sellers){
    //         accIds.add(oAcc.Id);
    //     }
    //     for(Campaign oCam : campaign1){
    //         camIds.add(oCam.Id);
    //         camIdMap.put(oCam.Id, oCam);
    //     }
    //     sellerListTargetedSellerMap.put(sellerList1.Id, lstTargetedSeller1);
    //     List<AccountContactRelation> lstAccCon = [SELECT ContactId, Account.Name FROM AccountContactRelation WHERE accountId IN :accIds];
    //     System.debug('lst Acc Con ='+lstAccCon);
    //     System.debug('sellerListTargetedSellerMap value = '+sellerListTargetedSellerMap.values());
    //     Test.startTest();
    //         Database.executeBatch(new EBH_CampaignMemberBatch(accIds, camIds, sellerListTargetedSellerMap, camIdMap));
    //     Test.stopTest();
    }
}