unpackaged/main/default/objects/Account/fields/Managed_Payments_Status__c.field-meta.xml
<CustomField>
    <fullName>Managed_Payments_Status__c</fullName>
    <description>Seller&#39;s eligibility status for Managed Payments</description>
    <label>Managed Payments Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preboarded</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Opted-Out</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/CampaignMember/fields/EBH_Seller__c.field-meta.xml
<CustomField>
    <fullName>EBH_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-2201) : Seller Oracle ID</description>
    <label>Seller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>EBH_Seller</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/EBH_Project__c.object-meta.xml
<CustomObject>
    <description>#US-0015700</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Project__c/fields/EBH_Seller__c.field-meta.xml
<CustomField>
    <fullName>EBH_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#US-0015700. Lookup (Seller)</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/fields/EBH_Stage__c.field-meta.xml
<CustomField>
    <fullName>EBH_Stage__c</fullName>
    <description>#US-0015700</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
                <default>true</default>
                <label>Acquisition</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Scalling</fullName>
                <label>Selling</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Negotiate and Close</fullName>
            </value>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>Proposal Created</fullName>
            </value>
            <value>
                <fullName>Pitched</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Pre - Integration</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Present &amp; Validate</fullName>
            </value>
            <value>
                <fullName>Negotiate</fullName>
            </value>
            <value>
                <fullName>Merchant Interested</fullName>
            </value>
            <value>
                <fullName>Merchant Agreement</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Preboarded</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Live to Site (LTS)</fullName>
            </value>
            <value>
                <fullName>Paused during Integration</fullName>
            </value>
            <value>
                <fullName>Paused After Going Live</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Account Set up</fullName>
            </value>
            <value>
                <fullName>Technical Integration</fullName>
            </value>
            <value>
                <fullName>Scaling (Warranty)</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/recordTypes/ManagedPayment.recordType-meta.xml
<RecordType>
    <fullName>ManagedPayment</fullName>
    <active>true</active>
    <description>Outreach tracking of eligible sellers to Managed Payments</description>
    <label>Managed Payment</label>
</RecordType>

unpackaged/main/default/classes/BatchUpdateManagedPaymentsStatus.cls
/********************************************************************************************************************************
@ Class:            BatchUpdateManagedPaymentsStatus
@ Version:          1.0
@ Author:           Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:          US-0007611 If a Managed Payment record exists and
@                   is not already in the stage 'Preboarded' or 'Onboarded' 
@                   than a bulk process will check the related Seller record in Hive 
@                   to see if the Managed Payment Status (updated from DWH) has been set 
@                   to 'Preboarded' or 'Onboarded' {Story 0007543 AC:2} if it has been, 
@                   then the stage on the Managed Payment Project record [Project.EBH_Stage__c] 
@                   will be updated to either 'Preboarded' or 'Onboarded' accordingly.
@                
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 25.05.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the class.
----------------------------------------------------------------------------------------------------------------------------------
@ Class:            BatchUpdateManagedPaymentsStatus
@ Version:          2.0
@ Author:           Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:          US-0007898 
@                   As a...
@                   Any user
@                   Want to...
@                   be able to see the latest status of a managed payment record
@                   So that...
@                   I can understand when a seller has 'onboarded' to managed payments
@                   Description
@                   Summary:
@                   The goal was to make sure all sellers had 'Preboarded' but as there are additional status updates after this and we shouldn't be stopping stage from being updated after a seller has 'Preboarded'.
@                   Currently:
@                   When a Managed Payment record has EBH_Project.Stage__c != 'Preboarded' or 'Onboarded'
@                   The batch process checks the related Seller (Account.Managed_Payments_Status__c)' and updates the 'EBH_Project.Stage__c' accordingly.
@                   Unfortunately this also means that if a seller has 'Preboarded' the batch will not update the record any further.
@                   Fix
@                   Could we please amend the logic of the batch process so that the stage on a Managed Payment record is always updated unless EBH_Stage__c = 'Onboarded'

----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 30.07.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / modify the method BatchUpdateManagedPaymentsStatus / sql string.
*********************************************************************************************************************************
*/

global without sharing class BatchUpdateManagedPaymentsStatus implements Database.Batchable<SObject>,Schedulable{

    public static final Id PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID = ApexUtil.getRecordTypeByName('EBH_Project__c','ManagedPayment').Id;

    public static final Id CUSTOMER_SELLER_RECORDTYPE_ID = ApexUtil.getRecordTypeByName('Account','EBH_Seller').Id;

    public static final String PREBOARDED_STATUS = 'Preboarded';
    public static final String ONBOARDED_STATUS = 'Onboarded';

    public static final Set<String> MANAGED_PAYMENT_STATUS = new Set<String>{PREBOARDED_STATUS,ONBOARDED_STATUS};

    // US-0007898 this below will also run when BH_Seller__r.Managed_Payments_Status__c = 'Onboarded' and EBH_Project__c.EBH_Stage__c = 'Preboarded'
    private string sqlQuery = 'SELECT Id, EBH_Stage__c, EBH_Seller__r.Managed_Payments_Status__c'
    + ' FROM EBH_Project__c'
    + ' WHERE RecordTypeId =: PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID'
    + ' AND EBH_Seller__r.RecordTypeId =: CUSTOMER_SELLER_RECORDTYPE_ID'
    + ' AND('

    + ' (EBH_Stage__c NOT IN: MANAGED_PAYMENT_STATUS'
    + ' AND EBH_Seller__r.Managed_Payments_Status__c IN: MANAGED_PAYMENT_STATUS)'
    + ' OR'
    + ' (EBH_Stage__c =: PREBOARDED_STATUS'
    + ' AND EBH_Seller__r.Managed_Payments_Status__c =: ONBOARDED_STATUS)'

    + ')';   


    /*****************************************************************************************************************************
	@ Method/Constructor:   BatchUpdateManagedPaymentsStatus
	@ Version:  1.0
	@ Author:   Sophal Noch (sophal.noch@gaea-sys.com)
    @ Purpose:  Setup a Query String for retrieveing EBH_Project__c records that 
                Field RecordType = MANAGED_PAYMENT
                AND Field EBH_Stage__c IS NOT Preboarded or Onboarded
                AND Its Child Record Field EBH_Seller__r/Account.RecordType = Seller
                AND EBH_Seller__r/Account.RecordType IS Preboarded or Onboarded
    @ Event:	When Batch instance initialize
	------------------------------------------------------------------------------------------------------------------------------
	@ Parameter:      none
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 25.05.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the method.
    
	*****************************************************************************************************************************/

    public BatchUpdateManagedPaymentsStatus() {

    }

    /*****************************************************************************************************************************
	@ Method:   start
	@ Version:  1.0
	@ Author:   Sophal Noch (sophal.noch@gaea-sys.com)
    @ Purpose:  Query String to retrive the data from Database
    @ Event:	after Batch instance initialize
	------------------------------------------------------------------------------------------------------------------------------
	@ Parameter:      batch context
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 25.05.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the method.
	*****************************************************************************************************************************/

    global Database.QueryLocator start(Database.BatchableContext BC) {


        // System.debug('nsp : CUSTOMER_SELLER_RECORDTYPE_ID is : ' + CUSTOMER_SELLER_RECORDTYPE_ID);
        // System.debug('nsp : PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID is : ' + PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID);
        // System.debug('nsp : MANAGED_PAYMENT_STATUS is : ' + MANAGED_PAYMENT_STATUS);

        
        return Database.getQueryLocator(sqlQuery);
    }


    /*****************************************************************************************************************************
	@ Method:   execute
	@ Version:  1.0
	@ Author:   Sophal Noch (sophal.noch@gaea-sys.com)
    @ Purpose:  take EBH_Project__c record list and loop over its and
                update each of its field EBH_Stage__c to Preboarded or Onboarded
                According to its child record field EBH_Seller__r/Account.Managed_Payments_Status__c
    @ Event:	when each batch run
	------------------------------------------------------------------------------------------------------------------------------
	@ Parameter:      batch context , EBH_Project__c record list
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 25.05.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the method.
	*****************************************************************************************************************************/
    
    global void execute(Database.BatchableContext bc, List<EBH_Project__c> projects){

        for(EBH_Project__c eachProject: projects){
            eachProject.EBH_Stage__c = eachProject.EBH_Seller__r.Managed_Payments_Status__c;
        }

        update projects;


    }

    global void finish(Database.BatchableContext bc){

    }

    /*****************************************************************************************************************************
	@ Method:   execute
	@ Version:  1.0
	@ Author:   Sophal Noch (sophal.noch@gaea-sys.com)
    @ Purpose:  make this class to be available to salesforce schedule. 
    @ Event:	When Schedule instance initialize
	------------------------------------------------------------------------------------------------------------------------------
	@ Parameter:     schedule context
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 25.05.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the method.
	*****************************************************************************************************************************/

    global void execute(SchedulableContext sc) { 
        BatchUpdateManagedPaymentsStatus batchUpdateManagedPaymentStatus = new BatchUpdateManagedPaymentsStatus();
        Database.executeBatch(batchUpdateManagedPaymentStatus);
    }

}