unpackaged/main/default/objects/Account/fields/Managed_Payments_Status__c.field-meta.xml
<CustomField>
    <fullName>Managed_Payments_Status__c</fullName>
    <description>Seller&#39;s eligibility status for Managed Payments</description>
    <label>Managed Payments Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preboarded</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Opted-Out</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/EBH_Project__c.object-meta.xml
<CustomObject>
    <description>#US-0015700</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Project__c/fields/EBH_Seller__c.field-meta.xml
<CustomField>
    <fullName>EBH_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#US-0015700. Lookup (Seller)</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Project__c/fields/EBH_Stage__c.field-meta.xml
<CustomField>
    <fullName>EBH_Stage__c</fullName>
    <description>#US-0015700</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Acquisition</fullName>
                <default>true</default>
                <label>Acquisition</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Scalling</fullName>
                <label>Selling</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Negotiate and Close</fullName>
            </value>
            <value>
                <fullName>New Project</fullName>
            </value>
            <value>
                <fullName>Proposal Created</fullName>
            </value>
            <value>
                <fullName>Pitched</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Pre - Integration</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Present &amp; Validate</fullName>
            </value>
            <value>
                <fullName>Negotiate</fullName>
            </value>
            <value>
                <fullName>Merchant Interested</fullName>
            </value>
            <value>
                <fullName>Merchant Agreement</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Preboarded</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
            <value>
                <fullName>Live to Site (LTS)</fullName>
            </value>
            <value>
                <fullName>Paused during Integration</fullName>
            </value>
            <value>
                <fullName>Paused After Going Live</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Account Set up</fullName>
            </value>
            <value>
                <fullName>Technical Integration</fullName>
            </value>
            <value>
                <fullName>Scaling (Warranty)</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchUpdateManagedPaymentsStatusTest.cls
/*********************************************************************************************************************************
@ Class:            BatchUpdateManagedPaymentsStatusTest
@ Version:          1.0
@ Author:           Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:          US-0007611 Test class for: BatchUpdateManagedPaymentsStatus
@				 
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 25.05.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the class.
----------------------------------------------------------------------------------------------------------------------------------
@ Class:            BatchUpdateManagedPaymentsStatusTest
@ Version:          2.0
@ Author:           Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:          US-0007888 new method testUpdateManagedPaymentStatusFieldViaBatchIfProjectStageAlreadyIsPreboarded		 
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 30.07.2020 / Sophal Noch (sophal.noch@gaea-sys.com) / Created the method.
*********************************************************************************************************************************/

@isTest
private class BatchUpdateManagedPaymentsStatusTest {

    static EBH_Project__c projectPreboarded;
    static EBH_Project__c projectOnboarded;
    static EBH_Project__c projectNoStage;

    private static void initData(){


        Account customerSellerOne = new Account(
            Name='Seller One', 
            RecordTypeId=BatchUpdateManagedPaymentsStatus.CUSTOMER_SELLER_RECORDTYPE_ID,
            Managed_Payments_Status__c = BatchUpdateManagedPaymentsStatus.PREBOARDED_STATUS
        );

        Account customerSellerTwo = new Account(
            Name='Seller Two', 
            RecordTypeId=BatchUpdateManagedPaymentsStatus.CUSTOMER_SELLER_RECORDTYPE_ID,
            Managed_Payments_Status__c = BatchUpdateManagedPaymentsStatus.ONBOARDED_STATUS
        );

        Account customerSellerThree = new Account(
            Name='Seller Three', 
            RecordTypeId=BatchUpdateManagedPaymentsStatus.CUSTOMER_SELLER_RECORDTYPE_ID
        );

        insert new List<Account>{customerSellerOne,customerSellerTwo,customerSellerThree};

        projectPreboarded = new EBH_Project__c(
            Name = 'Project Preboarded', 
            RecordTypeId = BatchUpdateManagedPaymentsStatus.PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID,
            EBH_Seller__c = customerSellerOne.Id
        );

        projectOnboarded = new EBH_Project__c(
            Name = 'Project Onboarded', 
            RecordTypeId = BatchUpdateManagedPaymentsStatus.PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID,
            EBH_Seller__c = customerSellerTwo.Id
        );

        projectNoStage = new EBH_Project__c(
            Name = 'Project No Stage', 
            RecordTypeId = BatchUpdateManagedPaymentsStatus.PROJECT_MANAGED_PAYMENT_RECORDTYPE_ID,
            EBH_Seller__c = customerSellerThree.Id
        );


        insert new List<EBH_Project__c>{projectPreboarded,projectOnboarded,projectNoStage};
    }

    static testMethod void testUpdateManagedPaymentStatusFieldViaBatch() {

        initData();

        Test.startTest();
            Database.executeBatch(new BatchUpdateManagedPaymentsStatus());
        Test.stopTest();

        List<EBH_Project__c> queriedProject = [SELECT Id, Name, EBH_Stage__c From EBH_Project__c];
        System.assertEquals(3,queriedProject.size());
         
        // note: assert equals for project 1 and 2
        // project 1 and 2 lookup to customer that have Managed_Payments_Status__c IN ('Preboarded','Onboarded')

        System.assertEquals(BatchUpdateManagedPaymentsStatus.PREBOARDED_STATUS, queriedProject[0].EBH_Stage__c);

        System.assertEquals(BatchUpdateManagedPaymentsStatus.ONBOARDED_STATUS, queriedProject[1].EBH_Stage__c);

        // note: assert not equals for project 3
        // project 3 lookup to customer that have Managed_Payments_Status__c NOT IN ('Preboarded','Onboarded')

        System.assertNotEquals(BatchUpdateManagedPaymentsStatus.PREBOARDED_STATUS, queriedProject[2].EBH_Stage__c);

        System.assertNotEquals(BatchUpdateManagedPaymentsStatus.ONBOARDED_STATUS, queriedProject[2].EBH_Stage__c);
        
    


    }

    static testMethod void testUpdateManagedPaymentStatusFieldViaSchedule() {

        initData();

        Test.startTest();   
            String sch = '0 0 23 * * ?';
            System.schedule('Test check', sch, new BatchUpdateManagedPaymentsStatus());
        Test.stopTest();
    
    }

    static testMethod void testUpdateManagedPaymentStatusFieldViaBatchIfProjectStageAlreadyIsPreboarded() {

        initData();

        projectOnboarded.EBH_Stage__c = BatchUpdateManagedPaymentsStatus.PREBOARDED_STATUS;
        update projectOnboarded;

        Test.startTest();
            Database.executeBatch(new BatchUpdateManagedPaymentsStatus());
        Test.stopTest();

        List<EBH_Project__c> queriedProject = [SELECT Id, Name, EBH_Stage__c From EBH_Project__c Where Id =: projectOnboarded.Id];
         
        System.assertEquals(BatchUpdateManagedPaymentsStatus.ONBOARDED_STATUS, queriedProject[0].EBH_Stage__c);



    }


}