unpackaged/main/default/objects/Account/fields/NA_Deal_Program_Vetted__c.field-meta.xml
<CustomField>
    <fullName>NA_Deal_Program_Vetted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0009148 - [NA] New fields and Page Layout changes on Account for &#39;Seller&#39; recordtype</description>
    <inlineHelpText>Checkbox to display if a seller is NA Deal Program Subsidy Eligible Subsidy eligible or not</inlineHelpText>
    <label>NA Deal Program Subsidy eligible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NA_Deals_Subsidy_PayPal_Email__c.field-meta.xml
<CustomField>
    <fullName>NA_Deals_Subsidy_PayPal_Email__c</fullName>
    <description>US-0009543 - [NA] New field and on Account for &#39;Seller&#39; recordtype,
US-0011448 - Additional validation for NA un-sub to sub conversion rule</description>
    <inlineHelpText>Used for Seller Subsidy payment</inlineHelpText>
    <label>NA Deals Subsidy PayPal Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>US-0008785 - [NA] Resend Deal Statements to Seller</description>
    <inlineHelpText>Flag contacts in roles for specific communications</inlineHelpText>
    <label>Contact Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advertising NA</fullName>
            </value>
            <value>
                <fullName>B2C Scaling</fullName>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>eBay - Active</fullName>
            </value>
            <value>
                <fullName>eBay - Integrations</fullName>
            </value>
            <value>
                <fullName>eBay - Inventory and Pricing</fullName>
            </value>
            <value>
                <fullName>eBay - Marketing</fullName>
            </value>
            <value>
                <fullName>eBay - Non Active - Left Company</fullName>
            </value>
            <value>
                <fullName>eBay - Non Active - Moved Dept/Project</fullName>
            </value>
            <value>
                <fullName>eBay - Non Active - Retired</fullName>
            </value>
            <value>
                <fullName>eBay - Primary Contact</fullName>
            </value>
            <value>
                <fullName>eBay - Secondary Contact</fullName>
            </value>
            <value>
                <fullName>Marketplaces – Executive Contact</fullName>
            </value>
            <value>
                <fullName>Marketplaces – Financial Contact</fullName>
            </value>
            <value>
                <fullName>Primary/MC Contact</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Sales Contact</fullName>
            </value>
            <value>
                <fullName>Support Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Training Contact</fullName>
            </value>
            <value>
                <fullName>C-Suite</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Deals</fullName>
                <label>NA Deals Contracts</label>
            </value>
            <value>
                <fullName>NA Deals Statement Recipient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/EBH_MANUAL.recordType-meta.xml
<RecordType>
    <fullName>EBH_MANUAL</fullName>
    <active>true</active>
    <description>Record Type for Contact Manually Created</description>
    <label>MANUAL</label>
</RecordType>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealRetailCampaign__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealRetailCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5546 Relationship between Deal and Deal Retail Campaign objects</description>
    <label>Deal Retail Campaign</label>
    <referenceTo>EBH_DealRetailCampaign__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SellerPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_SellerPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Seller Price</description>
    <inlineHelpText>Price seller has submitted as their offer price for the deal﻿</inlineHelpText>
    <label>Seller Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/recordTypes/Deal_V3.recordType-meta.xml
<RecordType>
    <fullName>Deal_V3</fullName>
    <active>true</active>
    <label>NA Unsub Deal</label>
</RecordType>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/EBH_DealRetailCampaign__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-5481) - Deal Retail Campaign</description>
    <label>Deal Retail Campaign</label>
    <nameField>
        <displayFormat>DRC-{0000000000}</displayFormat>
        <label>Deal Retail Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Retail Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Country__c.field-meta.xml
<CustomField>
    <fullName>EBH_Country__c</fullName>
    <description>Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>71</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>186</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Date__c.field-meta.xml
<CustomField>
    <fullName>EBH_Date__c</fullName>
    <description>(EPH-5481) Deal Retail Campaign Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_DealTitle__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealTitle__c</fullName>
    <description>(EPH-5481) Deal Retail Calendar Title</description>
    <label>Retail Campaign Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Slots__c.field-meta.xml
<CustomField>
    <fullName>EBH_Slots__c</fullName>
    <label>Number of Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/End_Retail_Week__c.field-meta.xml
<CustomField>
    <fullName>End_Retail_Week__c</fullName>
    <label>End Retail Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EPH_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EPH_EndDate__c</fullName>
    <description>(EPH-5481) End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Start_Retail_Week__c.field-meta.xml
<CustomField>
    <fullName>Start_Retail_Week__c</fullName>
    <label>Start Retail Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;New&#39;</defaultValue>
    <description>US-0009621</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open for Submissions</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/recordTypes/Deal_Campaign_V2.recordType-meta.xml
<RecordType>
    <fullName>Deal_Campaign_V2</fullName>
    <active>true</active>
    <label>NA Deal Window</label>
</RecordType>

unpackaged/main/default/classes/Subsidize_DealControllerTest.cls
@isTest
private  class Subsidize_DealControllerTest {
    
    public static final String NA_Unsub_Deal = 'Deal_V3';
    public static final String DRC_Deal_WINDOW = 'Deal_Campaign_V2';    
    @testSetup 
    static void setup(){
        //DealRetailCampaignTriggerHandler.updateDealStatusByTimeBaseChange();
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        Id dealRecordTypeId =  ApexUtil.getRecordTypeByName('EBH_Deal__c', NA_Unsub_Deal).Id;
        Id drcRecordTypeId = ApexUtil.getRecordTypeByName('EBH_DealRetailCampaign__c', DRC_Deal_WINDOW).Id;
        Account acc = new Account(Name='Test se2',RecordTypeID = sellerRecordType.Id,NA_Deals_Subsidy_PayPal_Email__c='test@test.com',NA_Deal_Program_Vetted__c = true);
        insert acc;

        RecordType contactRecordTYpe = ApexUtil.getRecordTypeByName('Contact','EBH_MANUAL');
        Contact contact1 = new Contact(MailingCountry='USA',MailingState='TX',MailingCity='Dallas',
                                        FirstName='firstname',Salutation='Mr.',LastName='test1', Contact_Role__c = 'Deals',
                                        email='test1@test.com' , AccountId = acc.Id, recordtypeId = contactRecordTYpe.Id);
        insert contact1;         
         
        EBH_DealRetailCampaign__c drc = new EBH_DealRetailCampaign__c(
            EBH_Country__c = '0',
            RecordTypeId = drcRecordTypeId,
            Status__c = 'Draft',
            EBH_DealTitle__c = 'SRO Test 001',
            Start_Retail_Week__c='2',
            EBH_Date__c = Date.today(),
            EPH_EndDate__c=Date.today().addDays(5),
            End_Retail_Week__c = '5',
            EBH_Slots__c=3);

        insert drc;
        
        DateTime dt = System.today();
        Time myTime = Time.newInstance(dt.hour(), dt.minute(), dt.second(), dt.millisecond());
        // create defualt spotlight category
        EBH_Deal__c d1 = new EBH_Deal__c(RecordTypeId = dealRecordTypeId, 
                                            EBH_SellerPrice__c = 1000,
                                            EBH_DealPrice__c = 11,
                                            EBH_BusinessName__c = acc.Id,
                                            EBH_SoldItems__c = 2,
                                            EBH_Vertical__c = 'CSA',
                                            EBH_DealStartDate__c = System.today(),
                                            EBH_DealEndDate__c = System.today().addDays(1),
                                            EBH_Status__c = 'New',
                                            EBH_Category__c = 'Gold',
                                            EBH_ProductTitle__c = 'product-1',                                            
                                            EBH_Quantity__c = 1,
                                            EBH_DealStartTime__c = myTime,
                                            EBH_DealEndTime__c = myTime,
                                            EBH_DealFormat__c = 'Deal',
                                            EBH_eBayItemID__c = '123456789110',
                                            EBH_DealSiteId__c='77',
                                            EBH_DealRetailCampaign__c = drc.Id,                                            
                                            Seller_Approver_1__c = contact1.Id);
                                             
      

        insert d1;
    }   

    @IsTest
    static void testSubsidize(){
        EBH_DealRetailCampaign__c window = [Select Id from EBH_DealRetailCampaign__c Limit 1];
        EBH_Deal__c d1 = [Select Id from EBH_Deal__c Limit 1];
        Test.startTest();
            Map<String,Object> result = Subsidize_DealController.apexInit(window.Id,d1.Id);
            System.assertEquals('ko', result.get('status')+'','convert success error incorrect status '+result);

            d1.EBH_Status__c = 'Ops Review';
            update d1;
            result = Subsidize_DealController.apexInit(window.Id,d1.Id);

            System.assertEquals('ok', result.get('status')+'','convert success: '+result);
            d1 = [Select Id,EBH_Status__c from EBH_Deal__c Limit 1];
            System.assertEquals('New', d1.EBH_Status__c,'convert success to New NA Deal');

        Test.stopTest();
        
    }
}