unpackaged/main/default/objects/Account/fields/NA_Deal_Program_Vetted__c.field-meta.xml
<CustomField>
    <fullName>NA_Deal_Program_Vetted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0009148 - [NA] New fields and Page Layout changes on Account for &#39;Seller&#39; recordtype</description>
    <inlineHelpText>Checkbox to display if a seller is NA Deal Program Subsidy Eligible Subsidy eligible or not</inlineHelpText>
    <label>NA Deal Program Subsidy eligible</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NA_Deals_Subsidy_PayPal_Email__c.field-meta.xml
<CustomField>
    <fullName>NA_Deals_Subsidy_PayPal_Email__c</fullName>
    <description>US-0009543 - [NA] New field and on Account for &#39;Seller&#39; recordtype,
US-0011448 - Additional validation for NA un-sub to sub conversion rule</description>
    <inlineHelpText>Used for Seller Subsidy payment</inlineHelpText>
    <label>NA Deals Subsidy PayPal Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Accepted_Current_Deals_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Current_Deals_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Current Deals Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/EBH_MANUAL.recordType-meta.xml
<RecordType>
    <fullName>EBH_MANUAL</fullName>
    <active>true</active>
    <description>Record Type for Contact Manually Created</description>
    <label>MANUAL</label>
</RecordType>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/EBH_ActiveTriggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>[EBH] (EPH-5) Active trigger controller - to switch on/off and bypass for deployment or data migration</description>
    <label>Active Triggers</label>
</CustomObject>

unpackaged/main/default/objects/EBH_ActiveTriggers__c/fields/DealRetailCampaign_Trigger__c.field-meta.xml
<CustomField>
    <fullName>DealRetailCampaign_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Trigger switch for Deal Retail Campaign Trigger(s)</description>
    <inlineHelpText>Trigger switch for Deal Retail Campaign Trigger(s)</inlineHelpText>
    <label>Deal Retail Campaign Trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealRetailCampaign__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealRetailCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5546 Relationship between Deal and Deal Retail Campaign objects</description>
    <label>Deal Retail Campaign</label>
    <referenceTo>EBH_DealRetailCampaign__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SpotlightCategory__c.field-meta.xml
<CustomField>
    <fullName>EBH_SpotlightCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-4163) - Spotlight Category</description>
    <label>Spotlight Category</label>
    <referenceTo>EBH_SpotlightCategory__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_SpotlightCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/recordTypes/Deal_V3.recordType-meta.xml
<RecordType>
    <fullName>Deal_V3</fullName>
    <active>true</active>
    <label>NA Unsub Deal</label>
</RecordType>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/EBH_DealRetailCampaign__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-5481) - Deal Retail Campaign</description>
    <label>Deal Retail Campaign</label>
    <nameField>
        <displayFormat>DRC-{0000000000}</displayFormat>
        <label>Deal Retail Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Retail Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Country__c.field-meta.xml
<CustomField>
    <fullName>EBH_Country__c</fullName>
    <description>Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>71</fullName>
            </value>
            <value>
                <fullName>101</fullName>
            </value>
            <value>
                <fullName>186</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Date__c.field-meta.xml
<CustomField>
    <fullName>EBH_Date__c</fullName>
    <description>(EPH-5481) Deal Retail Campaign Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_DealTitle__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealTitle__c</fullName>
    <description>(EPH-5481) Deal Retail Calendar Title</description>
    <label>Retail Campaign Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_Slots__c.field-meta.xml
<CustomField>
    <fullName>EBH_Slots__c</fullName>
    <label>Number of Slots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/End_Retail_Week__c.field-meta.xml
<CustomField>
    <fullName>End_Retail_Week__c</fullName>
    <label>End Retail Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EPH_EndDate__c.field-meta.xml
<CustomField>
    <fullName>EPH_EndDate__c</fullName>
    <description>(EPH-5481) End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Start_Retail_Week__c.field-meta.xml
<CustomField>
    <fullName>Start_Retail_Week__c</fullName>
    <label>Start Retail Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;New&#39;</defaultValue>
    <description>US-0009621</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open for Submissions</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/recordTypes/Deal_Campaign_V2.recordType-meta.xml
<RecordType>
    <fullName>Deal_Campaign_V2</fullName>
    <active>true</active>
    <label>NA Deal Window</label>
</RecordType>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/recordTypes/Deal_Campaign_V3.recordType-meta.xml
<RecordType>
    <fullName>Deal_Campaign_V3</fullName>
    <active>true</active>
    <label>NA Retail Campaign</label>
</RecordType>

unpackaged/main/default/classes/ManagedSharingRecordsHandlerTest.cls
/**
 * @Description Test unit for cover code in ManagedSharingRecordsHandler class
 * @date        18/10/2021
 * @ author      Sochettra SAING
 * change :21-12-2021/ Loumang SENG /US-0010824: Depreciated.
 */
@isTest
private class ManagedSharingRecordsHandlerTest {
    
    //LA-17-12-2021:US-0010824 - [SP - EU Deals] Adjust Sharing for Deal Retail Campaign Object
   /* public static final String NA_Unsub_Deal = 'Deal_V3';
    public static final String DRC_Deal_WINDOW = 'Deal_Campaign_V2';
    public static final String DRC_Deal_WINDOW_CAMPAIGN = 'Deal_Campaign_V3';
    public static Id accId;
    @testSetup static void setup(){
        //DealRetailCampaignTriggerHandler.updateDealStatusByTimeBaseChange();
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        //Id dealRecordTypeId =  ApexUtil.getRecordTypeByName('EBH_Deal__c', NA_Unsub_Deal).Id;
        
        Account acc = new Account(Name='TestAccount',RecordTypeID = sellerRecordType.Id,NA_Deals_Subsidy_PayPal_Email__c='test@test.com',NA_Deal_Program_Vetted__c = true);
        insert acc;

        RecordType contactRecordTYpe = ApexUtil.getRecordTypeByName('Contact','EBH_MANUAL');
        Contact contact1 = new Contact(MailingCountry='USA',MailingState='TX',MailingCity='Dallas',
                                        FirstName='firstname',Salutation='Mr.',LastName='test1',
                                        email='test1@test.com' , AccountId = acc.Id, recordtypeId = contactRecordTYpe.Id);
        insert contact1;
        

        EBH_ActiveTriggers__c setting = new EBH_ActiveTriggers__c();
        setting.Name = 'EBH Trigger Controller';
        setting.DealRetailCampaign_Trigger__c = true;
        insert setting;
        Date startDate = System.today().addDays(20);
        Date endDate = System.today().addDays(21);
        DateTime dt = System.today();
        Time myTime = Time.newInstance(dt.hour(), dt.minute(), dt.second(), dt.millisecond());
        // create defualt spotlight category
        EBH_SpotlightCategory__c sc = new EBH_SpotlightCategory__c();
        sc.Name = Label.US_UnSubDeal_Default_Spotlight;
        sc.EBH_Country__c = 'US';
        sc.EBH_SpotlightCategoryID__c = '123456789012';
        sc.Spotlight_End_Date__c = endDate;
        sc.Spotlight_Start_Date__c = startDate;
        insert sc;
    }

    @isTest static void testFetchRetailCampaign() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];

        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator'];
        //UserRole ur = new UserRole(Name = 'Liny - TEST US Seller Customer User', DeveloperName= 'LinyTESTUSSellerCustomerUser', PortalType = 'CustomerPortal', PortalAccountId = acc.Id);
        //insert ur;
        //UserRole userRole = [SELECT Id FROM UserRole WHERE PortalType = 'CustomerPortal' LIMIT 1]; UserRoleId = userRole.Id,
        /*Account acc = new Account( Name = 'TestAccount' );
        insert acc;

        //create a contact
        Contact con = new Contact(Accepted_Current_Deals_Agreement__c=false,
                                    FirstName='test fn', LastName='test ln', AccountId=acc.Id, Email = 'test123@test.com');
        insert con;  */
        
        /*Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='firstname' AND LastName='test1' limit 1];
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                //ContactId = con.Id,
                                ProfileId = profile1.Id,
                                isActive = true,
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        insert user1;
        Test.startTest(); 
        System.runAs(user1) {
            Id drcRecordTypeId = ApexUtil.getRecordTypeByName('EBH_DealRetailCampaign__c', DRC_Deal_WINDOW).Id;
            List<EBH_DealRetailCampaign__c> lstDW = new List<EBH_DealRetailCampaign__c>();
            
            for(Integer i=0;i<5;i++){
                EBH_DealRetailCampaign__c dw = new EBH_DealRetailCampaign__c(
                                                                                RecordTypeId = drcRecordTypeId,
                                                                                Status__c = 'Draft',
                                                                                EBH_DealTitle__c = 'SCH Test 00'+i,
                                                                                Start_Retail_Week__c='2',
                                                                                EBH_Date__c = System.today().addDays(1),
                                                                                EPH_EndDate__c=System.today().addDays(6),
                                                                                End_Retail_Week__c = '5',
                                                                                EBH_Slots__c=3,
                                                                                EBH_Country__c = '0'
                                                                            );
                                                                                                                
                lstDW.add(dw);
            }
            insert lstDW;

            Set<Id> parentIds = new Set<Id>();
            List<EBH_DealRetailCampaign__c> lstDRC = [SELECT Id, EBH_Country__c FROM EBH_DealRetailCampaign__c WHERE EBH_DealTitle__c LIKE 'SCH Test 00%'];
            for(EBH_DealRetailCampaign__c drcShare : lstDRC) {
                parentIds.add(drcShare.Id);
                //drcShare.EBH_Country__c = '77';
            }
            
            List<EBH_DealRetailCampaign__Share> lstDRCShare = [SELECT Id FROM EBH_DealRetailCampaign__Share WHERE ParentId IN : parentIds]; //new List<EBH_DealRetailCampaign__Share>();
            
            System.assertEquals(5, lstDRCShare.size());

            
        }
        Test.stopTest();
        
    }*/
    //LA-17-12-2021:US-0010824
    static testMethod void testDepreciatedClass(){
        Test.startTest();
        	BatchManagedSharingRecords depreciated = new BatchManagedSharingRecords();
            ManagedSharingRecordsHandler depreciatedMSR = new ManagedSharingRecordsHandler();
        Test.stopTest();

    }
}