unpackaged/main/default/objects/Account/fields/SP_Coupons__c.field-meta.xml
<CustomField>
    <fullName>SP_Coupons__c</fullName>
    <description>US-0010430 - Coupon tab visibility + coupon landing page</description>
    <label>SP Coupons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Accepted_Current_Deals_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Current_Deals_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Current Deals Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date__c</fullName>
    <description>[#EPH-7944] Coupon Object - New field Contract Due Date</description>
    <inlineHelpText>This is the due date by when the seller is asked to accept the contract</inlineHelpText>
    <label>Contract Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>EPH-7262 Adjustment to Coupon Object</description>
    <inlineHelpText>Defines the coupon contract type &amp; language - All sellers in that coupon will receive the same template.</inlineHelpText>
    <label>Contract Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  DATEVALUE(&quot;2099-1-1&quot;) , null)</defaultValue>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Main_Coupon_Site__c.field-meta.xml
<CustomField>
    <fullName>Main_Coupon_Site__c</fullName>
    <description>US-0008867 - AU Coupon BCD generation</description>
    <label>Main Coupon Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ebay.de</fullName>
            </value>
            <value>
                <fullName>ebay.es</fullName>
            </value>
            <value>
                <fullName>ebay.co.uk</fullName>
            </value>
            <value>
                <fullName>ebay.fr</fullName>
            </value>
            <value>
                <fullName>ebay.it</fullName>
            </value>
            <value>
                <fullName>ebay.ch</fullName>
            </value>
            <value>
                <fullName>ebay.at</fullName>
            </value>
            <value>
                <fullName>ebay.pl</fullName>
            </value>
            <value>
                <fullName>ebay.nl</fullName>
            </value>
            <value>
                <fullName>ebay.com</fullName>
            </value>
            <value>
                <fullName>ebay.com.au</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/MC_Whitelisted__c.field-meta.xml
<CustomField>
    <fullName>MC_Whitelisted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0009891 - Create new fields on Coupon and Coupon-Seller required for MC Coupon Flow</description>
    <inlineHelpText>When checked that the coupon will be whitelisted for the Marketing Cloud flow for sending emails to sellers. Otherwise the communication will be sent using the proprietary email templates/flows from Salesforce.</inlineHelpText>
    <label>MC Whitelisted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Seller Negotiation</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon Executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Coupon rejected</fullName>
            </value>
            <value>
                <fullName>Budget Confirmed</fullName>
                <isActive>false</isActive>
                <label>Budget Confirmed</label>
            </value>
            <value>
                <fullName>Budget Rejected</fullName>
                <isActive>false</isActive>
                <label>Budget Rejected</label>
            </value>
            <value>
                <fullName>Budget Requested</fullName>
                <isActive>false</isActive>
                <label>Budget Requested</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
                <isActive>false</isActive>
                <label>Clarification Required</label>
            </value>
            <value>
                <fullName>Invoice(s) approved</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) approved</label>
            </value>
            <value>
                <fullName>Invoice(s) paid</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) paid</label>
            </value>
            <value>
                <fullName>Invoice(s) pending</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) pending</label>
            </value>
            <value>
                <fullName>Invoice(s) rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) rejected</label>
            </value>
            <value>
                <fullName>Invoice(s) send</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) send</label>
            </value>
            <value>
                <fullName>Items Accepted</fullName>
                <isActive>false</isActive>
                <label>Items Accepted</label>
            </value>
            <value>
                <fullName>Items Provided</fullName>
                <isActive>false</isActive>
                <label>Items Provided</label>
            </value>
            <value>
                <fullName>Items Rejected</fullName>
                <isActive>false</isActive>
                <label>Items Rejected</label>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
                <isActive>false</isActive>
                <label>Payment Rejected</label>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
                <isActive>false</isActive>
                <label>Payment Sent</label>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
                <isActive>false</isActive>
                <label>Ready for Payment</label>
            </value>
            <value>
                <fullName>Seller(s) Contract Signed</fullName>
                <isActive>false</isActive>
                <label>Seller(s) Contract Signed</label>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <isActive>false</isActive>
                <label>Statement Verified</label>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
                <isActive>false</isActive>
                <label>Verify Invoice</label>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
                <isActive>false</isActive>
                <label>Verify Statement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date__c</fullName>
    <description>This is for FLOW Time Base using only. US-0011435</description>
    <label>Contract Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>US-0018725 	Coupon Seller - Add condition to workflow for stage T4Statement and T40 Statement</description>
    <formula>TEXT(Coupon__r.Contract_Language__c)</formula>
    <label>Contract Language</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/MC_Whitelisted__c.field-meta.xml
<CustomField>
    <fullName>MC_Whitelisted__c</fullName>
    <description>US-0009891 - Create new fields on Coupon and Coupon-Seller required for MC Coupon Flow</description>
    <formula>Coupon__r.MC_Whitelisted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>When checked that the coupon will be whitelisted for the Marketing Cloud flow for sending emails to sellers. Otherwise the communication will be sent using the proprietary email templates/flows from Salesforce. This setting is set on the Coupon record.</inlineHelpText>
    <label>MC Whitelisted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SEPCouponControllerTest.cls
@isTest
private class SEPCouponControllerTest {
    
    @testSetup
    static void setup(){
        
        EBH_TestDataFactory.setUpCustomSettings();

    	//create an account
        Account acc = new Account( Name = 'TestAccount', SP_Coupons__c='Full Access');
        insert acc;

        //create a contact
        Contact con = new Contact(Accepted_Current_Deals_Agreement__c=false,
                                    FirstName='test fn', LastName='test ln', AccountId=acc.Id, Email = 'test123@test.com');
        insert con;
        
        RecordType couponRecordTypeItem = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
        RecordType couponRecordTypeCat = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_CATEGORYBASE);
        Coupon__c c1 = new Coupon__c(Main_Coupon_Site__c = 'ebay.com',MC_Whitelisted__c = true,Stage__c = 'Draft', RecordTypeID = couponRecordTypeItem.Id,Coupon_Start_Date__c = System.today(),Coupon_End_Date__c=System.today(),Contract_Language__c = 'UK',Contract_Due_Date__c = System.today()-1);
        Coupon__c c2 = new Coupon__c(Main_Coupon_Site__c = 'ebay.com',MC_Whitelisted__c = true,Stage__c = 'Draft', RecordTypeID = couponRecordTypeCat.Id,Coupon_Start_Date__c = System.today(),Coupon_End_Date__c=System.today(),Contract_Language__c = 'UK',Contract_Due_Date__c = System.today()-1);

        insert new List<Coupon__c>{c1,c2};

        RecordType manhattanCouponSellerRecordType = ApexUtil.getRecordTypeByName('Coupon_Seller__c',EBH_ConstantsUtility.COUPONSELLER_MANHATTAN_RECORDTYPE);
        Coupon_Seller__c cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,Coupon_Seller_Stage__c='Targeted',Seller_Contact__c=con.Id,EBH_CouponSellerOwner__c = UserInfo.getUserId(),Seller__c = acc.Id,RecordTypeID=manhattanCouponSellerRecordType.Id);
        Coupon_Seller__c cs2 = new Coupon_Seller__c(Coupon__c = c2.Id,Coupon_Seller_Stage__c='Targeted',Seller_Contact__c=con.Id,EBH_CouponSellerOwner__c = UserInfo.getUserId(),Seller__c = acc.Id,RecordTypeID=manhattanCouponSellerRecordType.Id);
        insert new List<Coupon_Seller__c>{cs1,cs2};

        
    }

    @IsTest
    static void testFetchSingleSEPGlobalVar(){

        Test.startTest();

            Seller_Portal_Global_Variables__mdt result = SEPCouponController.fetchSingleSEPGlobalVar('SEP_Coupon_Seller_Record_Info');

            System.assert( result != null , 'There should be records in custom metadata Seller_Portal_Global_Variables__mdt.');

        Test.stopTest();

    }

    @isTest 
    static void test_updateCouponSellerStage2Review() {

        Coupon_Seller__c cs1 = [SELECT ID FROM Coupon_Seller__c LIMIT 1];

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];
        
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                
                                ProfileId = profile1.Id,
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        
        Test.startTest(); 

        System.runAs(user1) {

            Object result = SEPCouponController.updateCouponSellerStage2Review(String.valueOf(cs1.Id));

            Coupon_Seller__c cs = [SELECT Coupon_Seller_Stage__c FROM Coupon_Seller__c WHERE Id=:cs1.Id];

            System.assert(cs.Coupon_Seller_Stage__c == 'Review', 'This Coupon Seller Stage should changed to Review.');

        }
        
       
        Test.stopTest();
    }

    @isTest 
    static void test_doDeleteCouponCoInvest () {

        Coupon_Seller__c cs1 = [SELECT ID FROM Coupon_Seller__c LIMIT 1];

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];
        
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,
                                
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        
        Test.startTest(); 

        System.runAs(user1) {

            
            List<Coupon_Co_Invest__c> lstCCI = new List<Coupon_Co_Invest__c>();
            Id cciRT = Schema.SObjectType.Coupon_Co_Invest__c.getRecordTypeInfosByName().get('Coupon Co-Invest Item').getRecordTypeId();

            lstCCI.add(new Coupon_Co_Invest__c(
                Coupon_Seller__c = cs1.Id,
                Seller_Name__c = acc.Id,
                Co_Invest__c = 10,
                CurrencyIsoCode = 'USD',
                RecordtypeId = cciRT
            ));

            // Object result = ClsBulkUploadCSV.doSubmitMultipleCouponItems(lstCCI, 'Item Based');
            insert lstCCI;

            List<Coupon_Co_Invest__c> lstCCICreated = [SELECT Id FROM Coupon_Co_Invest__c];


            Object result = SEPCouponController.doDeleteCouponCoInvest(new List<String>{String.valueOf(lstCCICreated.get(0).Id)});

            System.debug('**** result :: ' + result);

        }
        
       
        Test.stopTest();

    }

    @isTest 
    static void test_getCouponContractTemplate () {
        // Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        // Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        // RecordType couponRecordTypeCat = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_CATEGORYBASE);
        // Coupon__c c1 = new Coupon__c(Main_Coupon_Site__c = 'ebay.com',MC_Whitelisted__c = true,Stage__c = 'Draft', RecordTypeID = couponRecordTypeCat.Id,Coupon_Start_Date__c = System.today(),Coupon_End_Date__c=System.today(),Contract_Language__c = 'UK',Contract_Due_Date__c = System.today()-1);
        // insert c1;
        // RecordType manhattanCouponSellerRecordType = ApexUtil.getRecordTypeByName('Coupon_Seller__c',EBH_ConstantsUtility.COUPONSELLER_MANHATTAN_RECORDTYPE);
        // Coupon_Seller__c cs = new Coupon_Seller__c(Coupon__c = c1.Id,Coupon_Seller_Stage__c='Targeted',Seller_Contact__c=con.Id,EBH_CouponSellerOwner__c = UserInfo.getUserId(),Seller__c = acc.Id,RecordTypeID=manhattanCouponSellerRecordType.Id);
        // insert cs;
        // List<Coupon_Co_Invest__c> lstCCI = new List<Coupon_Co_Invest__c>();
        //     Id cciRT = Schema.SObjectType.Coupon_Co_Invest__c.getRecordTypeInfosByName().get('Coupon Co-Invest Item').getRecordTypeId();
        //     lstCCI.add(new Coupon_Co_Invest__c(
        //         Coupon_Seller__c = cs.Id,
        //         Seller_Name__c = acc.Id,
        //         Co_Invest__c = 10,
        //         CurrencyIsoCode = 'USD',
        //         RecordtypeId = cciRT
        //     ));
        //     insert lstCCI;
        // Test.startTest(); 
        //     String result = SEPCouponController.getCouponContractTemplate(cs.Id);
        //     System.assert(String.isNotBlank(result));
        // Test.stopTest();

        RecordType couponRecordTypeItem = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
        
        Coupon_Seller__c cs1 = [SELECT ID FROM Coupon_Seller__c WHERE Coupon__r.RecordTypeId=:couponRecordTypeItem.Id LIMIT 1];

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];
        
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,
                                
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        
        Test.startTest(); 

        System.runAs(user1) {

            
            List<Coupon_Co_Invest__c> lstCCI = new List<Coupon_Co_Invest__c>();
            Id cciRT = Schema.SObjectType.Coupon_Co_Invest__c.getRecordTypeInfosByName().get('Coupon Co-Invest Item').getRecordTypeId();

            lstCCI.add(new Coupon_Co_Invest__c(
                Coupon_Seller__c = cs1.Id,
                Seller_Name__c = acc.Id,
                Co_Invest__c = 10,
                CurrencyIsoCode = 'USD',
                RecordtypeId = cciRT
            ));

            // Object result = ClsBulkUploadCSV.doSubmitMultipleCouponItems(lstCCI, 'Item Based');
            insert lstCCI;

            String result = SEPCouponController.getCouponContractTemplate(cs1.Id);
            System.assert(String.isNotBlank(result));

        }
        
       
        Test.stopTest();

    }

    @isTest 
    static void test_getCouponContractTemplate_2 () {
        

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];

        
        RecordType couponRecordTypeCat = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_CATEGORYBASE);
        Coupon_Seller__c cs1 = [SELECT ID FROM Coupon_Seller__c WHERE Coupon__r.RecordTypeId=:couponRecordTypeCat.Id LIMIT 1];
        
        
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];
        
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,
                                
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        
        Test.startTest(); 

        System.runAs(user1) {

            
            List<Coupon_Co_Invest__c> lstCCI = new List<Coupon_Co_Invest__c>();
            Id cciRT = Schema.SObjectType.Coupon_Co_Invest__c.getRecordTypeInfosByName().get('Coupon Co-Invest Item').getRecordTypeId();

            lstCCI.add(new Coupon_Co_Invest__c(
                Coupon_Seller__c = cs1.Id,
                Seller_Name__c = acc.Id,
                Co_Invest__c = 10,
                CurrencyIsoCode = 'USD',
                RecordtypeId = cciRT
            ));

            // Object result = ClsBulkUploadCSV.doSubmitMultipleCouponItems(lstCCI, 'Item Based');
            insert lstCCI;

            String result = SEPCouponController.getCouponContractTemplate(cs1.Id);
            System.assert(String.isNotBlank(result));

        }
        
       
        Test.stopTest();

    }

    @isTest 
    static void test_handleContractCouponSellerAgree () {
        Coupon_Seller__c cs = [SELECT ID FROM Coupon_Seller__c LIMIT 1];

        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        
        Profile profile1 = [SELECT Id, Name FROM Profile WHERE Name = 'DE - Seller Portal'];
        
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        User user1 = new User(
                                Username = System.now().millisecond() + 'test12345@test.com',
                                ContactId = con.Id,
                                ProfileId = profile1.Id,
                                
                                Alias = 'test123',
                                Email = 'test12345xx@test.com',
                                EmailEncodingKey = 'UTF-8',
                                LastName = 'McTesty',
                                CommunityNickname = 'test12345',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US'
                                );
        
        Test.startTest(); 

        System.runAs(user1) {
            SEPCouponController.handleContractCouponSellerAgree(cs.Id, user1.Id, con.Id);
        }        
       
        Test.stopTest();

    }

    @isTest 
    static void test_handleUpdateCouponSellerStage () {
        Coupon_Seller__c cs = [SELECT ID FROM Coupon_Seller__c LIMIT 1];        
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        String csId = cs.Id;
        String conId = con.Id;
        Test.startTest(); 

        SEPCouponController.handleUpdateCouponSellerStage(csId, 'Other', 'other', conId);  
       
        Test.stopTest();
        
    }

    @isTest 
    static void test_getAllPickListValue () {
        SEPCouponController.getAllPickListValue('Coupon_Seller__c', 'Seller_Declined_Reasons__c');
    }

    @isTest
    static void test_getCouponSeller2 () {
        Coupon_Seller__c cs = [SELECT ID FROM Coupon_Seller__c LIMIT 1];
        Test.startTest(); 
            SEPCouponController.getCouponSeller2(cs.Id);
        Test.stopTest();
    }

}