unpackaged/main/default/objects/Account/fields/SP_Coupons__c.field-meta.xml
<CustomField>
    <fullName>SP_Coupons__c</fullName>
    <description>US-0010430 - Coupon tab visibility + coupon landing page</description>
    <label>SP Coupons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/SP_Deals__c.field-meta.xml
<CustomField>
    <fullName>SP_Deals__c</fullName>
    <description>US-0011312 - Rebuild Deals Page</description>
    <inlineHelpText>&quot;Full Access&quot; means a Seller can view and create Deals, &quot;Read Only&quot; means a Seller can only view Deals, &quot;Allowed&quot; means they can see the Deals tab in the portal</inlineHelpText>
    <label>SP Deals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Federated_Login__c.field-meta.xml
<CustomField>
    <fullName>Federated_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010903 - [Add User] Allow DE Deals Users to add others Contacts to the Seller Portal</description>
    <inlineHelpText>Indicates a User that logs in to Seller Portal using Experience Cloud Username and password</inlineHelpText>
    <label>Federated Login</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AccountPickerController.cls
/*********************************************************************************************************************************
@ Class:        AccountPickerController
@ Version:      1.0
@ Author:       Mony Nou (mony.nou@gaea-sys.com)
@ Purpose:      Controller for lwcAccountPicker  
@               US-0010950 - Account Selection field on Deal Creation/List Views
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 26.04.2022 / mony nou / Created the class.
@               : 14.06.2022 / SRONG TIN / US-0011345 AC7
*********************************************************************************************************************************/
public with sharing class AccountPickerController {
    
    private static final String ELIGIBLE_FOR_DE_DEALS = 'Eligible_for_DE_Deals_Full_Access';
    private static final String ELIGIBLE_FOR_COUPONS = 'Eligible_for_Coupons_Full_Access';//SRONG TIN/14.06.2022/US-0011345

    /*********************************************************************************************************************************
    @ method:       getDEEligibleAccounts
    @ Version:      1.0
    @ Author:       Mony Nou (mony.nou@gaea-sys.com)
    @ Purpose:      US-0010950 - Account Selection field on Deal Creation/List Views
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 26.04.2022 / Mony Nou / Created the method.
    @               : 14.06.2022 / SRONG TIN / US-0011345 AC7
    *********************************************************************************************************************************/
    @AuraEnabled
    public static Map<String,Object> getDEEligibleAccounts()
    {
        //SRONG TIN/14.06.2022/US-0011345 AC7
        Set<String> ELIGIBLE = new Set<String>{ELIGIBLE_FOR_DE_DEALS,ELIGIBLE_FOR_COUPONS};

        List<Seller_Portal_Setting__mdt> meta = [Select Id,DeveloperName,Filter_Values__c from Seller_Portal_Setting__mdt where DeveloperName  IN:ELIGIBLE];

        User currentUser = [Select Id,UserName,Email,ContactId,Contact.RecordType.DeveloperName,Contact.AccountId,Contact.Account.OwnerId,Federated_Login__c From User Where Id=:UserInfo.getUserId()];
        
        Map<String,AccountContactRelation> mapRelation = new Map<String,AccountContactRelation>();
        Map<String,AccountContactRelation> mapRelationDeals = new Map<String,AccountContactRelation>();
        Map<String,AccountContactRelation> mapRelationCoupons = new Map<String,AccountContactRelation>();
        //SRONG TIN/14.06.2022/US-0011345 AC7
        String sFilter = meta[0].Filter_Values__c + ' OR ' +meta[1].Filter_Values__c;
        String sQuery = 'Select Id,AccountId,Account.Name,Account.SP_Coupons__c,Account.SP_Deals__c,Contact.Name,Contact.Email,ContactId,IsActive From AccountContactRelation';
        String sWhere = ' Where Account.RecordType.DeveloperName =\'EBH_Seller\' and ContactId=\'' + currentUser.ContactId + '\'' ;
        sWhere += ' AND AccountId IN (SELECT Id FROM Account WHERE '+ sFilter +')';

        for(AccountContactRelation acr : (List<AccountContactRelation>) Database.query(sQuery + sWhere)) {
            
            if(acr.Account.SP_Coupons__c == 'Full Access'){mapRelationCoupons.put(acr.AccountId,acr);}
            if(acr.Account.SP_Deals__c == 'Full Access'){mapRelationDeals.put(acr.AccountId,acr);}
            mapRelation.put(acr.AccountId,acr);
        }
        return new Map<String,Object> {'curentUser'=>currentUser,'accRelation'=>mapRelationDeals.values(),'accRelationCoupons'=>mapRelationCoupons.values(),'accRelationAll'=>mapRelation.values()};
    }

}