unpackaged/main/default/objects/Account/fields/SP_Deals__c.field-meta.xml
<CustomField>
    <fullName>SP_Deals__c</fullName>
    <description>US-0011312 - Rebuild Deals Page</description>
    <inlineHelpText>&quot;Full Access&quot; means a Seller can view and create Deals, &quot;Read Only&quot; means a Seller can only view Deals, &quot;Allowed&quot; means they can see the Deals tab in the portal</inlineHelpText>
    <label>SP Deals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Access</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Federated_Login__c.field-meta.xml
<CustomField>
    <fullName>Federated_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010903 - [Add User] Allow DE Deals Users to add others Contacts to the Seller Portal</description>
    <inlineHelpText>Indicates a User that logs in to Seller Portal using Experience Cloud Username and password</inlineHelpText>
    <label>Federated Login</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/GenericErrorMessageController.cls
/*********************************************************************************************************************************
@ Class:        GenericErrorMessageController
@ Version:      1.0
@ Author:       Mony Nou (mony.nou@gaea-sys.com)
@ Purpose:      Controller for lwcGenericErrorMessage  
@              
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 25.04.2022 / mony nou / Created the class.
*********************************************************************************************************************************/
public with sharing class GenericErrorMessageController {
    
    private final static String SPDEAL_FULLACCESS = 'Full Access';

    /*********************************************************************************************************************************
    @ method:       validateAllLinkedAccounts
    @ Version:      1.0
    @ Author:       Mony Nou (mony.nou@gaea-sys.com)
    @ Purpose:     US-0011156 - Restrict ability for Sellers to be able to create Deals - Linked Account
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 25.04.2022 / Mony Nou / Created the method.
    *********************************************************************************************************************************/
    @AuraEnabled
    public static Map<String,Object> validateAllLinkedAccounts()
    {
        
        User currentUser = [Select Id,UserName,Email,ContactId,Contact.RecordType.DeveloperName,Contact.AccountId,Contact.Account.OwnerId,Federated_Login__c From User Where Id=:UserInfo.getUserId()];
        
        Map<String,AccountContactRelation> mapRelation = new Map<String,AccountContactRelation>();

        String sQuery = 'Select Id,AccountId,Account.SP_Deals__c From AccountContactRelation';
        String sWhere = ' Where Account.RecordType.DeveloperName =\'EBH_Seller\' and ContactId=\'' + currentUser.ContactId + '\'' ;

        Boolean spDealFullAccess = false;
        String spDealVal = '';
        for(AccountContactRelation acr : (List<AccountContactRelation>) WithoutSharing.doQuery(sQuery, sWhere, '')) {
            //mapRelation.put(acr.AccountId,acr);
            spDealFullAccess = spDealFullAccess || (acr.Account.SP_Deals__c == SPDEAL_FULLACCESS);
            if (acr.AccountId == currentUser.Contact.AccountId) spDealVal = acr.Account.SP_Deals__c;
        }

        Map<String,Object> result = new Map<String,Object> ();
        
        if (spDealFullAccess) result.put('spDealFullAccess',true);
            
        result.put('spDeal', spDealVal);

        return result;
    }

}