unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_BusinessName__c.field-meta.xml
<CustomField>
    <fullName>EBH_BusinessName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[EBH] (EPH-4163) - Business Name</description>
    <label>eBay Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_BusinessName</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealFormat__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealFormat__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Format</description>
    <label>Deal Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Featured</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Deal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealSiteId__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealSiteId__c</fullName>
    <description>[EBH] (EPH-5193) - Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>71</fullName>
                <label>FR</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>186</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Vertical__c.field-meta.xml
<CustomField>
    <fullName>EBH_Vertical__c</fullName>
    <description>[EBH] (EPH-4163) - Vertical</description>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EBH_DealSiteId__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Home</fullName>
            </value>
            <value>
                <fullName>Hard Home</fullName>
            </value>
            <value>
                <fullName>P&amp;A</fullName>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Leisure</fullName>
            </value>
            <value>
                <fullName>Fitness</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Joyería y Belleza</fullName>
            </value>
            <value>
                <fullName>Electrónica</fullName>
            </value>
            <value>
                <fullName>Moda</fullName>
            </value>
            <value>
                <fullName>Casa y Jardín</fullName>
            </value>
            <value>
                <fullName>Ocio</fullName>
            </value>
            <value>
                <fullName>Deportes</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>Coleccionismo</fullName>
            </value>
            <value>
                <fullName>Otras categorías</fullName>
            </value>
            <value>
                <fullName>High-Tech</fullName>
            </value>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Maison &amp; Jardin</fullName>
            </value>
            <value>
                <fullName>Auto et Moto</fullName>
            </value>
            <value>
                <fullName>Collections &amp; Antiquités</fullName>
            </value>
            <value>
                <fullName>Tecnologia</fullName>
            </value>
            <value>
                <fullName>Casa &amp; Giardino</fullName>
            </value>
            <value>
                <fullName>Sport &amp; Viaggi</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Moto</fullName>
            </value>
            <value>
                <fullName>Collezionabili</fullName>
            </value>
            <value>
                <fullName>Commercio, Ufficio e Industria</fullName>
            </value>
            <value>
                <fullName>Suministros industriales</fullName>
            </value>
            <value>
                <fullName>H&amp;G</fullName>
            </value>
            <value>
                <fullName>Parts &amp; BI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/Merchant_Approver__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008086</description>
    <label>Merchant Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ApexUtilTest.cls
@Istest
private class ApexUtilTest {
	static testMethod void testUtil()
	{
		Test.startTest();
			ApexUtil.formatNumber(10000,',','.',2);
			ApexUtil.formatNumber(10000,2,'DE');
			ApexUtil.checkNull(10);
			ApexUtil.formatTime(null);
			ApexUtil.mapCurrencySign.get('USD');
			ApexUtil.toDecimal('1000',2);
			ApexUtil.toDecimal0('1000',2);
			ApexUtil.toInteger('10');
			ApexUtil.toDouble('10');
			ApexUtil.getUserRoleByName('Global');
			ApexUtil.getRecordTypeByName('Account','EBH_Seller');
			ApexUtil.getRecordTypeBySobjectName('Account');
			ApexUtil.doSend('subject','test@test.com','html body here');
			ApexUtil.checkPermissionSet(new Set<String>{'no_permission_name'});
			ApexUtil.getValue('Parent.Name',new Account(Name='Test'));
			ApexUtil.runningInASandbox();
			ApexUtil.getSiteUrl('Deal_Acceptance');
			ApexUtil.getUsersMemberByGroup(new  Set<String>{'group1'});
			ApexUtil.constructQuoteString(new Set<String>{'x','y'});
			ApexUtil.generateSQOLFields('Account');
			ApexUtil.doCompare('=',4,4);
			ApexUtil.doCompare('<',4,4);
			ApexUtil.doCompare('<=',4,4);
			ApexUtil.doCompare('>',4,4);
			ApexUtil.doCompare('>=',4,4);
			ApexUtil.genUniqueString(10);
			ApexUtil.countRunningBatch(new Set<String>{'Batch1'});
			ApexUtil.nullStr('');
			ApexUtil.findCronJob(new Set<String>{'BatchCouponSellerStatus'});
			Map<String, List<ApexUtil.PicklistEntryWrapper>> objResults  = ApexUtil.getDependentMap(EBH_Deal__c.getSObjectType(),'EBH_DealSiteId__c','EBH_Vertical__c');
			ApexUtil.getPicklistValues(EBH_Deal__c.EBH_DealFormat__c);
        ApexUtil.getFieldIdRef('EBH_BusinessName__r.Name');
        ApexUtil.fixNumber('15.5','EN');
        ApexUtil.permissionSetMembers('test');
		ApexUtil.getCurrentUser();

		Map<String,String> binding = new Map<String,String>();
		List<EmailTemplate>  template = [select Id, Name, Body, Subject, HtmlValue, DeveloperName from EmailTemplate where DeveloperName = 'NA_Deals_Notify_Approvals' LIMIT 1];
		if(template.isEmpty()){
			binding.put('{!User.Phone}', 'xxxxxxxxxxxx');
		}else{
			binding.put('{!EBH_Deal__c.Merchant_Approver__c}', 'Test Name');
			binding.put('{!EBH_Deal__c.Link}', URL.getOrgDomainUrl().toExternalForm());
		}

		Messaging.SingleEmailMessage preparedEmail = ApexUtil.prepareEmail(null, new String[] {'sophal.noch@gaea-sys.com.invalid'}, null, 'NA_Deals_Notify_Approvals', 'Sample_GreatMeetingYou', binding, null, null);
		//ApexUtil.sendEmail(new List<Messaging.SingleEmailMessage>{preparedEmail});

		Test.stopTest(); 

		ApexUtil.getProfileByName('Administrator');
		ApexUtil.getPermissionSetL('test');
		ApexUtil.getOWDbyAddress('');
		ApexUtil.getFieldSet('Account', 'test') ;
		ApexUtil.validSFId(UserInfo.getUserId());
		ApexUtil.MAP_LOCALE_DATEFORMAT();

		ApexUtil.chunkList(new List<Object>{'a','b'},1);

		ApexUtil.isProduction();
		ApexUtil.gmtDateToDTZone(system.today(),Time.newInstance(1, 2, 3, 4),'PST');
        ApexUtil.generateUniqueString(new List<ID>{UserInfo.getUserId()});

		ApexUtil.revokeUserAccess3PLink(UserInfo.getUserId(),'xyzabc');
	}
}