unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>Unique Code that will be used by the buyer to redeem the coupon</inlineHelpText>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/Coupon_Co_Invest__c.object-meta.xml
<CustomObject>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Co-Invest</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Coupon Co-Invest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Co-Invests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Seller__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Seller</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if Coupon Co-Invests is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon_Seller__c</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <formula>TEXT(Coupon_Seller__r.Coupon_Seller_Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coupon Seller Stage</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Item_ID__c</fullName>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Item ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_ID__c</formula>
    <inlineHelpText>This is the uniqueCouponcode</inlineHelpText>
    <label>Coupon Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Seller_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_ID__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <displayFormat>CS-{000000}</displayFormat>
    <inlineHelpText>Autogenerated coupon ID</inlineHelpText>
    <label>Coupon Seller ID</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <description>EPH-7157 Object: Coupon Seller
US-0012156</description>
    <label>Coupon Seller Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pitch Ready</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
                <default>true</default>
                <label>Targeted</label>
            </value>
            <value>
                <fullName>Reached</fullName>
            </value>
            <value>
                <fullName>Commited</fullName>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Contract Send</fullName>
            </value>
            <value>
                <fullName>Contract Accepted</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Invoice paid</fullName>
            </value>
            <value>
                <fullName>Seller Declined</fullName>
            </value>
            <value>
                <fullName>Contract Appended</fullName>
            </value>
            <value>
                <fullName>Contract Terminated</fullName>
            </value>
            <value>
                <fullName>Invoice approved</fullName>
                <isActive>false</isActive>
                <label>Invoice approved</label>
            </value>
            <value>
                <fullName>Invoice pending</fullName>
                <isActive>false</isActive>
                <label>Invoice pending</label>
            </value>
            <value>
                <fullName>Invoice rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice rejected</label>
            </value>
            <value>
                <fullName>Invoice send</fullName>
                <isActive>false</isActive>
                <label>Invoice send</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CouponItemTriggerHandlerTest.cls
/*********************************************************************************************************************************
@ Class:          CouponItemTriggerHandlerTest
@ Version:        1.0
@ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
@ Purpose:        test Class for trigger Coupon Item
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 19.04.2019 / Sovantheany Dim / Created the class.
*********************************************************************************************************************************/
@isTest
private class CouponItemTriggerHandlerTest {
    static testmethod void setupData(){
        EBH_TestDataFactory.setUpCustomSettings();   
        
       
    }
    static testMethod void myUnitTest() {
        setupData();
    	RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
    	RecordType coRecordType = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
    	Account acc = new Account(Name='Test Acc1',RecordTypeID = sellerRecordType.Id);
    	insert acc;
    	Coupon__c c1 = new Coupon__c(RecordTypeID = coRecordType.Id);
		insert c1;
		Coupon_Seller__c cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,seller__c = acc.Id,Coupon_Seller_Stage__c=EBH_ConstantsUtility.COUPON_SELLER_STAGE_NEGO);
    	insert cs1;
        Coupon_Co_Invest__c[] cciSel = [select Id From Coupon_Co_Invest__c Where Coupon_Seller__c = :cs1.Id and RecordType.DeveloperName =: EBH_ConstantsUtility.CO_INVEST_ITEM];
        System.assert(cciSel.isEmpty(),'there is no co invest created, because no Coupon item related');
        Test.startTest();
        Coupon_Item__c ci = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='1234567890');
        insert ci;
        Test.stopTest();
        Coupon_Co_Invest__c[] cciSel1 = [select Id,RecordType.DeveloperName From Coupon_Co_Invest__c Where Coupon_Seller__c = :cs1.Id and RecordType.DeveloperName =: EBH_ConstantsUtility.CO_INVEST_ITEM];
        System.assert(cciSel1.size() == 1);
        
    }

    static testMethod void deleteUpdateCouponItemTest(){
    	setupData();
        String userId = UserInfo.getUserId();
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        RecordType coRecordType = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
        Account acc = new Account(Name='Test Acc1',RecordTypeID = sellerRecordType.Id);
        insert acc;
        Coupon__c c1 = new Coupon__c(RecordTypeID = coRecordType.Id);
        insert c1;
        Coupon_Seller__c cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,seller__c = acc.Id,Coupon_Seller_Stage__c='Contract Signed');
        insert cs1;
        Coupon_Item__c ci1 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='123');
        Coupon_Item__c ci2 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='12356');
        List<Coupon_Item__c> ctList = new List<Coupon_Item__c>{ci1};
        insert ctList;
        Test.startTest();
            try {
                ci1.Item_ID__c = '1111';
                update ci1;
                delete ctList;
            }catch(Exception ex) {
                System.assert(ex.getMessage().contains(System.Label.Prevent_Deletion_of_Coupon_Seller_Item_Category));
            }

            cs1.Coupon_Seller_Stage__c = 'Contract Negotiation';
            update cs1;

            ci1.Item_ID__c = '1111';
            update ci1;
            delete ctList;
	        
            //CouponItemTriggerHandler.deleteUpdateCouponItem(ctList);
        Test.stopTest();
    }
    
    static testMethod void testvalidateCouponItem(){
    	setupData();
    	RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        RecordType coRecordType = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
        Account acc = new Account(Name='Test Acc1',RecordTypeID = sellerRecordType.Id);
        insert acc;
        Coupon__c c1 = new Coupon__c(RecordTypeID = coRecordType.Id);
        insert c1;
        Coupon_Seller__c cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,seller__c = acc.Id,Coupon_Seller_Stage__c='Contract Signed');
        insert cs1;
        Coupon_Item__c ci1 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='100001');
        Coupon_Item__c ci2 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='100002');
        List<Coupon_Item__c> ctList = new List<Coupon_Item__c>{ci1,ci2};
        insert ctList;
        Test.startTest();
        try{
        	Coupon_Item__c ci3 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='100001');
       	 	Coupon_Item__c ci4 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='100002');
       	 	insert new List<Coupon_Item__c>{ci3,ci4};
        }catch(Exception e){
        	System.assert(true);
        	//System.assert(e.getMessage().contains(System.Label.Error_Duplicate_Coupon_Item_In_File),'error: '+System.Label.Error_Duplicate_Coupon_Item_In_File);
        	System.assert(e.getMessage().contains(System.Label.Error_Duplicate_Coupon_Item),'error: '+System.Label.Error_Duplicate_Coupon_Item);
        }
        Test.stopTest();
    }

    @isTest
    static void test_preventRecordDeletion(){

    	setupData();
    	
        RecordType sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
        RecordType coRecordType = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
        
        Account acc = new Account(Name='Test Acc1',RecordTypeID = sellerRecordType.Id);
        insert acc;
        
        Coupon__c c1 = new Coupon__c(RecordTypeID = coRecordType.Id);
        insert c1;
        
        Coupon_Seller__c cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,seller__c = acc.Id,Coupon_Seller_Stage__c='Contract Signed');
        insert cs1;
        
        Coupon_Item__c ci1 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='100001');
        Coupon_Item__c ci2 = new Coupon_Item__c(Coupon_ID__c=c1.Id, Coupon_Seller_ID__c=cs1.Id,Item_ID__c='100002');
        List<Coupon_Item__c> ctList = new List<Coupon_Item__c>{ci1,ci2};
        insert ctList;
        
        Test.startTest();
            try{
                delete ctList;

            }catch(Exception ex){
                System.assert(ex.getMessage().contains(System.Label.Prevent_Deletion_of_Coupon_Seller_Item_Category));
            }
        Test.stopTest();
    }
}