unpackaged/main/default/objects/Account/recordTypes/EBH_Seller.recordType-meta.xml
<RecordType>
    <fullName>EBH_Seller</fullName>
    <active>true</active>
    <label>Seller</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Accepted_Current_Deals_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Current_Deals_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Current Deals Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Portal_Display_Density__c.field-meta.xml
<CustomField>
    <fullName>Portal_Display_Density__c</fullName>
    <description>All Custom List View Components being developed must apply this setting to their styling so that either the low density layout is rendered (Figma base) or the high density lists are rendered (as per pilot default)</description>
    <inlineHelpText>All Custom List View Components being developed must apply this setting to their styling so that either the low density layout is rendered (Figma base) or the high density lists are rendered (as per pilot default)</inlineHelpText>
    <label>Portal Display Density</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date__c</fullName>
    <description>[#EPH-7944] Coupon Object - New field Contract Due Date</description>
    <inlineHelpText>This is the due date by when the seller is asked to accept the contract</inlineHelpText>
    <label>Contract Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  DATEVALUE(&quot;2099-1-1&quot;) , null)</defaultValue>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Main_Coupon_Site__c.field-meta.xml
<CustomField>
    <fullName>Main_Coupon_Site__c</fullName>
    <description>US-0008867 - AU Coupon BCD generation</description>
    <label>Main Coupon Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ebay.de</fullName>
            </value>
            <value>
                <fullName>ebay.es</fullName>
            </value>
            <value>
                <fullName>ebay.co.uk</fullName>
            </value>
            <value>
                <fullName>ebay.fr</fullName>
            </value>
            <value>
                <fullName>ebay.it</fullName>
            </value>
            <value>
                <fullName>ebay.ch</fullName>
            </value>
            <value>
                <fullName>ebay.at</fullName>
            </value>
            <value>
                <fullName>ebay.pl</fullName>
            </value>
            <value>
                <fullName>ebay.nl</fullName>
            </value>
            <value>
                <fullName>ebay.com</fullName>
            </value>
            <value>
                <fullName>ebay.com.au</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date__c</fullName>
    <description>This is for FLOW Time Base using only. US-0011435</description>
    <label>Contract Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ClsListViewControllerTest.cls
/*********************************************************************************************************************************
@ Class:          ClsListViewControllerTest
@ Version:        1.0
@ Author:         Sochettra Saing
@ Purpose:        Ability to run test the logic in class ClsListViewController(EBAY-260)
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 28.06.2021 / Sochettra Saing / Created the class.
@ Change history: 25.11.2021 / Sovantheany Dim / Update the class.
*********************************************************************************************************************************/

@isTest
public with sharing class ClsListViewControllerTest {


    static RecordType sellerRecordType;
    static Map<String,RecordType> couponRecordType;
    static Account acc1;
    static Coupon__c c1;
    static Coupon_Seller__c cs1;

    @testSetup
    static void setupData(){

        sellerRecordType = ApexUtil.getRecordTypeByName('Account','EBH_Seller');
    	couponRecordType = ApexUtil.getRecordTypeBySobjectName('Coupon__c');
    	acc1 = new Account(Name='Test Acc1',RecordTypeID = sellerRecordType.Id);
    	insert acc1;
    	// c1 = new Coupon__c(RecordTypeID = couponRecordType.get(EBH_ConstantsUtility.COUPON_CATEGORYBASE).Id);
        c1 = new Coupon__c(Main_Coupon_Site__c = 'ebay.com', RecordTypeID = couponRecordType.get(EBH_ConstantsUtility.COUPON_CATEGORYBASE).Id,Contract_Due_Date__c = System.today()-2, Coupon_Start_Date__c = System.today()+1, Coupon_End_Date__c = System.today() +2);
        insert c1;
    	cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,seller__c = acc1.Id);
    	insert cs1;

    }

    static testMethod void testMethod1() {


        Test.startTest();
        //TH:25.11.2021: test getMtdObjectName for code coverage
        String objectName = ClsListViewController.getMtdObjectName('My_Deal_Related_List');
        System.assertEquals('EBH_Deal__c',objectName);

        //TH:25.11.2021:change to My_Deal_Related_List, previous setting does not exist
        Map<String, Object>  mResult = ClsListViewController.getAllSetting('My_Deal_Related_List');

    //    System.assertEquals('status:success', 'status:'+ mResult.get('status'));

        Map<String, Object>  mSearchResult = ClsListViewController.getSearchResult('Test','My_Deal_Related_List','');
        List<Sobject> lstSobj = (List<Sobject>) mSearchResult.get('listRecord');
        System.assertEquals('listRecord:0', 'listRecord:'+ lstSobj.size());

        Test.stopTest();
    }

    static testMethod void testUpdateContact() {
        Account acc = new Account( Name = 'TestAccount' );
        insert acc;

        //create a contact
        Contact con = new Contact(Accepted_Current_Deals_Agreement__c=false, Portal_Display_Density__c = 'High', FirstName='test fn', LastName='test ln', AccountId=acc.Id, Email = 'test123@test.com');
        insert con;

        Test.StartTest();

        /*String localCode = ClsListViewController.initLocalCode();
        System.debug('>>>>>>> localCode:'+ localCode);
        System.assertEquals('localCode:en', 'localCode:'+localCode);*/
        con.Portal_Display_Density__c = 'Low';
        Map<String, Object>  mResult = ClsListViewController.doUpdateContact(con);

        System.assertEquals('status:success', 'status:'+ mResult.get('status'));
        for(Contact c : [SELECT Id, Portal_Display_Density__c FROM Contact WHERE Id =: con.Id]){

            System.assertEquals('Portal_Display_Density__c:Low', 'Portal_Display_Density__c:'+ c.Portal_Display_Density__c);
        }

        Test.stopTest();
    }

    @isTest
    static void testupdateInterest(){

        setupData();

        List<Id> my_list = new List<Id>();
        my_list.add(c1.id);

        Map<String,Object> result = ClsListViewController.updateInterest(my_list);
        System.assertEquals('success',  result.get('status'));
    }
    @isTest
    static void testupdateNotInterest(){

        setupData();

        List<Id> my_list = new List<Id>();
        my_list.add(c1.id);

        Map<String,Object> result = ClsListViewController.updateNotInterest(my_list);
        System.assertEquals('success',  result.get('status'));
    }

}