unpackaged/main/default/objects/Case/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008603 - [NA] Merchant Integration Case Layout</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets (Seller)</relationshipLabel>
    <relationshipName>Tickets1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Active_Community_User__c.field-meta.xml
<CustomField>
    <fullName>Active_Community_User__c</fullName>
    <description>US-0011435 - Creation of seller communication records for coupons</description>
    <formula>Community_User__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates if the Contact has an active User access to the Seller Portal</inlineHelpText>
    <label>Active Community User</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Community_User__c.field-meta.xml
<CustomField>
    <fullName>Community_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0011435 - Creation of seller communication records for coupons</description>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Code_not_used</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>Unique Code that will be used by the buyer to redeem the coupon</inlineHelpText>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Marketing_Coupon_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Coupon_Name__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>Title that will be used by Marketing</inlineHelpText>
    <label>Marketing Coupon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/recordTypes/Category_Based.recordType-meta.xml
<RecordType>
    <fullName>Category_Based</fullName>
    <active>true</active>
    <label>Seller / Category Based</label>
</RecordType>

unpackaged/main/default/objects/Coupon__c/recordTypes/Item_Based.recordType-meta.xml
<RecordType>
    <fullName>Item_Based</fullName>
    <active>true</active>
    <label>Item Based</label>
</RecordType>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Code__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Code__c</fullName>
    <description>US-0010785 - Refactor Coupon Seller object to support standard search</description>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_ID__c</formula>
    <inlineHelpText>This is the uniqueCouponcode</inlineHelpText>
    <label>Coupon Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Marketing_Name__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Marketing_Name__c</fullName>
    <description>US-0010785 - Refactor Coupon Seller object to support standard search</description>
    <label>Coupon Marketing Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <description>EPH-7157 Object: Coupon Seller
US-0012156</description>
    <label>Coupon Seller Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pitch Ready</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
                <default>true</default>
                <label>Targeted</label>
            </value>
            <value>
                <fullName>Reached</fullName>
            </value>
            <value>
                <fullName>Commited</fullName>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Contract Send</fullName>
            </value>
            <value>
                <fullName>Contract Accepted</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Invoice paid</fullName>
            </value>
            <value>
                <fullName>Seller Declined</fullName>
            </value>
            <value>
                <fullName>Contract Appended</fullName>
            </value>
            <value>
                <fullName>Contract Terminated</fullName>
            </value>
            <value>
                <fullName>Invoice approved</fullName>
                <isActive>false</isActive>
                <label>Invoice approved</label>
            </value>
            <value>
                <fullName>Invoice pending</fullName>
                <isActive>false</isActive>
                <label>Invoice pending</label>
            </value>
            <value>
                <fullName>Invoice rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice rejected</label>
            </value>
            <value>
                <fullName>Invoice send</fullName>
                <isActive>false</isActive>
                <label>Invoice send</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Marketing_Coupon_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Coupon_Name__c</fullName>
    <description>US-0007064 [AU] Coupon Click Contract Template Amends</description>
    <formula>Coupon__r.Marketing_Coupon_Name__c</formula>
    <label>Marketing Coupon Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchSyncCouponFieldsToCouponSeller.cls
/*********************************************************************************************************************************
@ Class     :       BatchSyncCouponFieldsToCouponSeller
@ Version   :       1.0
@ Author    : 	    Mony Nou (mony.nou@gaea-sys.com)
@ Purpose	:	    US-0010785 - Refactor Coupon Seller object to support standard search (AC3)
@					 - In case the sync logic inside CouponTriggerHandler.syncCouponInfo2CouponSellers() fail due to SF Govern limit
                    When there are heap records of coupon seller => we using this batch + schedule daily to update those failed records
------------------------------------------------------------------------------------------------------------------------------
@ Change history: 27.06.2022 / Mony Nou/ Create Method
*********************************************************************************************************************************/
global with sharing class BatchSyncCouponFieldsToCouponSeller implements Database.Batchable<SObject>, Schedulable {
    
    private final static String COUPON_OBJNAME = 'Coupon__c';
	private final static String COUPON_CATEGORYBASE = 'Category_Based'; 
    private final static String COUPON_ITEMBASE = 'Item_Based'; 
	
    global Database.QueryLocator start(Database.BatchableContext BC){

        RecordType cpnRTypeCateBase = ApexUtil.getRecordTypeByName(COUPON_OBJNAME,COUPON_CATEGORYBASE);
		RecordType cpnRTypeItemBase = ApexUtil.getRecordTypeByName(COUPON_OBJNAME,COUPON_ITEMBASE);
        Set<Id> sValidRT = new Set<Id> {cpnRTypeCateBase.Id, cpnRTypeItemBase.Id}; 
        Set<String> sValidStage = new Set<String> {'Targeted','Reached','Commited','Contract Negotiation','Approved','Review','Contract Send','Contract Signed'};
        
        String query = 'SELECT Id,Coupon_Marketing_Name__c,Coupon_Code__c, Coupon__r.Marketing_Coupon_Name__c, Coupon__r.Coupon_ID__c  FROM Coupon_Seller__c WHERE Coupon__r.RecordTypeId IN:sValidRT' 
                        + ' AND Coupon_Seller_Stage__c IN:sValidStage'
                        + ' AND Seller__c IN (SELECT AccountId FROM Contact WHERE Community_User__c != NULL AND Active_Community_User__c = TRUE)';

        return Database.getQueryLocator(query);

    }

    global void execute(Database.BatchableContext bc, List<Coupon_Seller__c> scope) {

        List<Coupon_Seller__c> lstCS2Update = new List<Coupon_Seller__c>();

        for (Coupon_Seller__c cs : scope) {

            Coupon__c cp = (Coupon__c) cs.getSobject('Coupon__r');

            if (cs.Coupon_Marketing_Name__c != cp.Marketing_Coupon_Name__c || cs.Coupon_Code__c != cp.Coupon_ID__c) {
                
                if (cs.Coupon_Marketing_Name__c != cp.Marketing_Coupon_Name__c) cs.Coupon_Marketing_Name__c = cp.Marketing_Coupon_Name__c;
                if (cs.Coupon_Code__c != cp.Coupon_ID__c) cs.Coupon_Code__c = cp.Coupon_ID__c;
                
                lstCS2Update.add(cs);
            } 

            
        }

        if (!lstCS2Update.isEmpty()) Database.update(lstCS2Update, false);

 
    }

    global void finish(Database.BatchableContext bc) {}

    global void execute(SchedulableContext sc) 
    {
        BatchSyncCouponFieldsToCouponSeller bat = new BatchSyncCouponFieldsToCouponSeller();
        Database.executeBatch(bat,200);
    }
}