unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Cofund_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Cofund_End_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Cofund End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Cofund_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Cofund_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Cofund Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <description>EPH-7157 Object: Coupon Seller
US-0012156</description>
    <label>Coupon Seller Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pitch Ready</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
                <default>true</default>
                <label>Targeted</label>
            </value>
            <value>
                <fullName>Reached</fullName>
            </value>
            <value>
                <fullName>Commited</fullName>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Contract Send</fullName>
            </value>
            <value>
                <fullName>Contract Accepted</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Invoice paid</fullName>
            </value>
            <value>
                <fullName>Seller Declined</fullName>
            </value>
            <value>
                <fullName>Contract Appended</fullName>
            </value>
            <value>
                <fullName>Contract Terminated</fullName>
            </value>
            <value>
                <fullName>Invoice approved</fullName>
                <isActive>false</isActive>
                <label>Invoice approved</label>
            </value>
            <value>
                <fullName>Invoice pending</fullName>
                <isActive>false</isActive>
                <label>Invoice pending</label>
            </value>
            <value>
                <fullName>Invoice rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice rejected</label>
            </value>
            <value>
                <fullName>Invoice send</fullName>
                <isActive>false</isActive>
                <label>Invoice send</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/TriggerStageUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>TriggerStageUpdatedDate__c</fullName>
    <description>to avoid error on Coupon Seller trigger blockManualSetStage</description>
    <label>TriggerStageUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/recordTypes/Manhattan_Coupon.recordType-meta.xml
<RecordType>
    <fullName>Manhattan_Coupon</fullName>
    <active>true</active>
    <label>Manhattan Coupon</label>
</RecordType>

unpackaged/main/default/objects/Coupon_Seller__c/recordTypes/Pop_Coupon.recordType-meta.xml
<RecordType>
    <fullName>Pop_Coupon</fullName>
    <active>true</active>
    <label>Pop Coupon Seller</label>
</RecordType>

unpackaged/main/default/classes/BatchUpdateCouponSellerStage.cls
/*********************************************************************************************************************************
@ Class:         BatchUpdateCouponSellerStage
@ Version:       1.0
@ Author:        Mony Nou (mony.nou@gaea-sys.com)
@ Purpose:       US-0012069 - Issue with automatic update of coupon seller stage
@                   - This batch schedule is the replica of Flow "Coupon Seller After Flow" and will run every 2 hours 
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 18.07.2022 / Mony Nou / Created the class.
----------------------------------------------------------------------------------------------------------------------------------
*/
global with sharing class BatchUpdateCouponSellerStage implements Database.Batchable<SObject>, Schedulable {
    
    private final static String STAGE_CONTSIGNED = 'Contract Signed';
    private final static String STAGE_CONTTERMINATED = 'Contract Terminated';
    private final static String STAGE_CONTACCEPTED = 'Contract Accepted';
    private final static String STAGE_CPRUNNING = 'Coupon Running';
    private final static String STAGE_CPEXECUTED = 'Coupon executed';
    private final static String STAGE_RUNNING = 'Running';
    
    private final static String RT_MANHATTAN = 'Manhattan_Coupon';
    private final static String RT_POPCP = 'Pop_Coupon';

    private String sQuery = 'Select Id,Cofund_Start_Date__c, Cofund_End_Date__c, Coupon_Seller_Stage__c, RecordType.DeveloperName From Coupon_Seller__c'; 
    private String sWhere = ' WHERE (Cofund_Start_Date__c = TODAY OR Cofund_End_Date__c = TODAY) AND ('
                            + '(Cofund_Start_Date__c != NULL AND Coupon_Seller_Stage__c =:STAGE_CONTSIGNED AND RecordType.DeveloperName =:RT_MANHATTAN)'
                            + ' OR (Cofund_End_Date__c != NULL AND Coupon_Seller_Stage__c =:STAGE_CPRUNNING AND RecordType.DeveloperName =:RT_MANHATTAN)'
                            + ' OR (Cofund_End_Date__c != NULL AND Coupon_Seller_Stage__c !=:STAGE_CONTTERMINATED AND RecordType.DeveloperName =:RT_POPCP)'
                            + ' OR (Cofund_Start_Date__c != NULL AND Coupon_Seller_Stage__c =:STAGE_CONTACCEPTED AND RecordType.DeveloperName =:RT_POPCP))';

    private String cpSellerId;

    public BatchUpdateCouponSellerStage() {}

    public BatchUpdateCouponSellerStage(String cpSellerId) {
        this.cpSellerId = cpSellerId;
        this.sWhere = ' WHERE Id=:cpSellerId';
    }

    global Database.QueryLocator start(Database.BatchableContext BC){

        return Database.getQueryLocator(sQuery+sWhere);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope){

        List<Coupon_Seller__c> lstCS2Update = new List<Coupon_Seller__c>();

        Date dToday = Date.today();

        for (Coupon_Seller__c cs : (List<Coupon_Seller__c>) scope) {

            //1) From Flow: Contact Signed?
            if (cs.Cofund_Start_Date__c != null && cs.Cofund_Start_Date__c == dToday && cs.Coupon_Seller_Stage__c == STAGE_CONTSIGNED && cs.RecordType.DeveloperName == RT_MANHATTAN) {
                cs.Coupon_Seller_Stage__c = STAGE_CPRUNNING;
            }
            
            //2) From Flow: Coupon Running?
            else if (cs.Cofund_End_Date__c != null && cs.Cofund_End_Date__c == dToday && cs.Coupon_Seller_Stage__c == STAGE_CPRUNNING && cs.RecordType.DeveloperName == RT_MANHATTAN) {
                cs.Coupon_Seller_Stage__c = STAGE_CPEXECUTED;
            }

            //3) From Flow: PopCouponRunning?
            else if (cs.Cofund_End_Date__c != null && cs.Cofund_End_Date__c == dToday && cs.Coupon_Seller_Stage__c != STAGE_CONTTERMINATED && cs.RecordType.DeveloperName == RT_POPCP) {
                cs.Coupon_Seller_Stage__c = STAGE_CONTTERMINATED;
            }

            //4) Contract Accepted?
            else if (cs.Cofund_Start_Date__c != null && cs.Cofund_Start_Date__c == dToday && cs.Coupon_Seller_Stage__c == STAGE_CONTACCEPTED && cs.RecordType.DeveloperName == RT_POPCP) {
                cs.Coupon_Seller_Stage__c = STAGE_RUNNING;
            }

            cs.TriggerStageUpdatedDate__c = System.now();
            
            lstCS2Update.add(cs);

        }
        
        if (!lstCS2Update.isEmpty()) {
            
            Database.SaveResult[] results = Database.update(lstCS2Update,false);
            List<Database.Error> dbError = new List<Database.Error>();

            for (Database.SaveResult result : results) {
                if (!result.isSuccess() && !Test.isRunningTest()){ dbError.addAll(result.getErrors()); }
            }

            if (!dbError.isEmpty()) EBH_ApexLogger.logError(dbError, 'BatchUpdateCouponSellerStage','execute (batch)');
        }
        
        
        
    }

    global void finish(Database.BatchableContext pBc){

    }

    global void execute(SchedulableContext sc) { 
        BatchUpdateCouponSellerStage b = new BatchUpdateCouponSellerStage();
        Database.executeBatch(b, 100);
    }
}