unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Seller_Stage__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller_Stage__c</fullName>
    <description>EPH-7157 Object: Coupon Seller
US-0012156</description>
    <label>Coupon Seller Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pitch Ready</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
                <default>true</default>
                <label>Targeted</label>
            </value>
            <value>
                <fullName>Reached</fullName>
            </value>
            <value>
                <fullName>Commited</fullName>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Contract Send</fullName>
            </value>
            <value>
                <fullName>Contract Accepted</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Invoice paid</fullName>
            </value>
            <value>
                <fullName>Seller Declined</fullName>
            </value>
            <value>
                <fullName>Contract Appended</fullName>
            </value>
            <value>
                <fullName>Contract Terminated</fullName>
            </value>
            <value>
                <fullName>Invoice approved</fullName>
                <isActive>false</isActive>
                <label>Invoice approved</label>
            </value>
            <value>
                <fullName>Invoice pending</fullName>
                <isActive>false</isActive>
                <label>Invoice pending</label>
            </value>
            <value>
                <fullName>Invoice rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice rejected</label>
            </value>
            <value>
                <fullName>Invoice send</fullName>
                <isActive>false</isActive>
                <label>Invoice send</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Type__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Type__c</fullName>
    <description>US-0012156</description>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Item Based</fullName>
            </value>
            <value>
                <fullName>Category Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SEPWindowAlert__c/SEPWindowAlert__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>US-0011689 - Deployment window alert</description>
    <label>SEP Window Alert</label>
</CustomObject>

unpackaged/main/default/objects/SEPWindowAlert__c/fields/Deploying__c.field-meta.xml
<CustomField>
    <fullName>Deploying__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0011689 - Deployment window alert</description>
    <label>Deploying</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SEP_Helper.cls
/*********************************************************************************************************************************
@ Class:          SEP_Helper
@ Version:        1.0
@ Author:         Mony Nou (mony.nou@gaea-sys.com)
@ Purpose:        Controller class for general using in SEP Community
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 19.5.2022 / Mony Nou / Created the class.
*********************************************************************************************************************************/

public with sharing class SEP_Helper {

    /*****************************************************************************************************************************
    @ Method:         initRecordInfo
    @ Version:        1.0
    @ Author:         Mony Nou
    @ Purpose:        US-0011689 - Deployment window alert
    @                   + Init method for lwcRecordInfor
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 17.06.2022 / Mony Nou / Created the  Method.
    *****************************************************************************************************************************/
    
    private static String COUPONSELLER_API = 'Coupon_Seller__c';
    private static String COUPONSELLER_STAGE_TARGETED = 'Targeted';
    private static String COUPONSELLER_STAGE_REACHED = 'Reached';
    private static String COUPONSELLER_STAGE_COMMITED = 'Commited';
    private static String COUPONSELLER_STAGE_NEGOTIATION = 'Contract Negotiation';
    private static String COUPONSELLER_COUPONTYPE_ITEM = 'Item Based';
    private static String COUPONSELLER_COUPONTYPE_CATE = 'Category Based';

    private static Map<String, String> mSObjSOQL = new Map<String, String>{
        COUPONSELLER_API => 'Select Coupon_Seller_Stage__c, Coupon_Type__c From Coupon_Seller__c WHERE Id=:recId'
    };

    @AuraEnabled
    public static Map<String,Object> initRecordInfo(String recId, String metaName, String overrideMetaName) {

        Map<String,Object> mapResult = new Map<String,Object>();
        
        //Get sObject API by RecordId 
        if (String.isNotBlank(recId)) {
            String sobj_api = getSObjectAPI(Id.valueOf(recId));
            SObject rec;
            if (mSObjSOQL.containsKey(sobj_api)) {
                 rec = Database.query(mSObjSOQL.get(sobj_api));
                
            }

            if (sobj_api.equalsIgnoreCase(COUPONSELLER_API)) {
                
                Set<String> sNotConfirmedStage = new Set<String> {COUPONSELLER_STAGE_TARGETED, COUPONSELLER_STAGE_REACHED, COUPONSELLER_STAGE_COMMITED};

                Coupon_Seller__c cs = (Coupon_Seller__c) rec;

                if ((sNotConfirmedStage.contains(cs.Coupon_Seller_Stage__c) && (cs.Coupon_Type__c == COUPONSELLER_COUPONTYPE_ITEM || cs.Coupon_Type__c == COUPONSELLER_COUPONTYPE_CATE)) 
                        || (cs.Coupon_Seller_Stage__c == COUPONSELLER_STAGE_NEGOTIATION && cs.Coupon_Type__c == COUPONSELLER_COUPONTYPE_CATE)) {
                    
                    metaName = 'SEP_Coupon_Seller_Record_Info';
                    mapResult.put('metadataName', metaName);
                    
                }
                
                
            }

        }

        if (String.isNotBlank(overrideMetaName)) metaName = overrideMetaName;

        //Get Metadata
        if (String.isNotBlank(metaName)) {
            for (Seller_Portal_Global_Variables__mdt spgv : [SELECT Value__c, Value_Big__c, Value_in_German__c FROM Seller_Portal_Global_Variables__mdt WHERE DeveloperName =: metaName]) {
                mapResult.put('meta', spgv);
            }
        }


        String userLang = UserInfo.getLanguage();
        SEPWindowAlert__c sepwa = SEPWindowAlert__c.getOrgDefaults();
        
        mapResult.put('userLang',userLang);
        mapResult.put('isDeploying', sepwa.Deploying__c);
        
       
        return mapResult;
    }


    private static String getSObjectAPI (Id recordId) {
        Schema.SObjectType sobjectType = recordId.getSObjectType();
        String sobjectName = sobjectType.getDescribe().getName();
        return sobjectName;
    }

}