unpackaged/main/default/objects/Contact/fields/Accepted_Current_Deals_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Current_Deals_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted Current Deals Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date__c</fullName>
    <description>[#EPH-7944] Coupon Object - New field Contract Due Date</description>
    <inlineHelpText>This is the due date by when the seller is asked to accept the contract</inlineHelpText>
    <label>Contract Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>EPH-7262 Adjustment to Coupon Object</description>
    <inlineHelpText>Defines the coupon contract type &amp; language - All sellers in that coupon will receive the same template.</inlineHelpText>
    <label>Contract Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  DATEVALUE(&quot;2099-1-1&quot;) , null)</defaultValue>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Main_Coupon_Site__c.field-meta.xml
<CustomField>
    <fullName>Main_Coupon_Site__c</fullName>
    <description>US-0008867 - AU Coupon BCD generation</description>
    <label>Main Coupon Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ebay.de</fullName>
            </value>
            <value>
                <fullName>ebay.es</fullName>
            </value>
            <value>
                <fullName>ebay.co.uk</fullName>
            </value>
            <value>
                <fullName>ebay.fr</fullName>
            </value>
            <value>
                <fullName>ebay.it</fullName>
            </value>
            <value>
                <fullName>ebay.ch</fullName>
            </value>
            <value>
                <fullName>ebay.at</fullName>
            </value>
            <value>
                <fullName>ebay.pl</fullName>
            </value>
            <value>
                <fullName>ebay.nl</fullName>
            </value>
            <value>
                <fullName>ebay.com</fullName>
            </value>
            <value>
                <fullName>ebay.com.au</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/MC_Whitelisted__c.field-meta.xml
<CustomField>
    <fullName>MC_Whitelisted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0009891 - Create new fields on Coupon and Coupon-Seller required for MC Coupon Flow</description>
    <inlineHelpText>When checked that the coupon will be whitelisted for the Marketing Cloud flow for sending emails to sellers. Otherwise the communication will be sent using the proprietary email templates/flows from Salesforce.</inlineHelpText>
    <label>MC Whitelisted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Seller Negotiation</fullName>
            </value>
            <value>
                <fullName>Coupon Running</fullName>
            </value>
            <value>
                <fullName>Coupon Executed</fullName>
            </value>
            <value>
                <fullName>T4 Statement Send</fullName>
            </value>
            <value>
                <fullName>T34 Statement Send</fullName>
                <label>T40 Statement Send</label>
            </value>
            <value>
                <fullName>Coupon rejected</fullName>
            </value>
            <value>
                <fullName>Budget Confirmed</fullName>
                <isActive>false</isActive>
                <label>Budget Confirmed</label>
            </value>
            <value>
                <fullName>Budget Rejected</fullName>
                <isActive>false</isActive>
                <label>Budget Rejected</label>
            </value>
            <value>
                <fullName>Budget Requested</fullName>
                <isActive>false</isActive>
                <label>Budget Requested</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
                <isActive>false</isActive>
                <label>Clarification Required</label>
            </value>
            <value>
                <fullName>Invoice(s) approved</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) approved</label>
            </value>
            <value>
                <fullName>Invoice(s) paid</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) paid</label>
            </value>
            <value>
                <fullName>Invoice(s) pending</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) pending</label>
            </value>
            <value>
                <fullName>Invoice(s) rejected</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) rejected</label>
            </value>
            <value>
                <fullName>Invoice(s) send</fullName>
                <isActive>false</isActive>
                <label>Invoice(s) send</label>
            </value>
            <value>
                <fullName>Items Accepted</fullName>
                <isActive>false</isActive>
                <label>Items Accepted</label>
            </value>
            <value>
                <fullName>Items Provided</fullName>
                <isActive>false</isActive>
                <label>Items Provided</label>
            </value>
            <value>
                <fullName>Items Rejected</fullName>
                <isActive>false</isActive>
                <label>Items Rejected</label>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
                <isActive>false</isActive>
                <label>Payment Rejected</label>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
                <isActive>false</isActive>
                <label>Payment Sent</label>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
                <isActive>false</isActive>
                <label>Ready for Payment</label>
            </value>
            <value>
                <fullName>Seller(s) Contract Signed</fullName>
                <isActive>false</isActive>
                <label>Seller(s) Contract Signed</label>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <isActive>false</isActive>
                <label>Statement Verified</label>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
                <isActive>false</isActive>
                <label>Verify Invoice</label>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
                <isActive>false</isActive>
                <label>Verify Statement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/Coupon_Co_Invest__c.object-meta.xml
<CustomObject>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Co-Invest</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Coupon Co-Invest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Co-Invests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Seller__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Seller</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if Coupon Co-Invests is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon_Seller__c</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Due_Date__c</fullName>
    <description>This is for FLOW Time Base using only. US-0011435</description>
    <label>Contract Due Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>US-0018725 	Coupon Seller - Add condition to workflow for stage T4Statement and T40 Statement</description>
    <formula>TEXT(Coupon__r.Contract_Language__c)</formula>
    <label>Contract Language</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/MC_Whitelisted__c.field-meta.xml
<CustomField>
    <fullName>MC_Whitelisted__c</fullName>
    <description>US-0009891 - Create new fields on Coupon and Coupon-Seller required for MC Coupon Flow</description>
    <formula>Coupon__r.MC_Whitelisted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>When checked that the coupon will be whitelisted for the Marketing Cloud flow for sending emails to sellers. Otherwise the communication will be sent using the proprietary email templates/flows from Salesforce. This setting is set on the Coupon record.</inlineHelpText>
    <label>MC Whitelisted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SEPDownloadControllerTest.cls
@isTest
private class SEPDownloadControllerTest {
    
    @testSetup
    static void setup(){
        
        EBH_TestDataFactory.setUpCustomSettings();

    	//create an account
        Account acc = new Account( Name = 'TestAccount' );
        insert acc;

        //create a contact
        Contact con = new Contact(Accepted_Current_Deals_Agreement__c=false,
                                    FirstName='test fn', LastName='test ln', AccountId=acc.Id, Email = 'test123@test.com');
        insert con;
        
        RecordType couponRecordTypeItem = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_ITEMBASE);
        Coupon__c c1 = new Coupon__c(Main_Coupon_Site__c = 'ebay.com',MC_Whitelisted__c = true,Stage__c = 'Draft', RecordTypeID = couponRecordTypeItem.Id,Coupon_Start_Date__c = System.today(),Coupon_End_Date__c=System.today(),Contract_Language__c = 'UK',Contract_Due_Date__c = System.today()-1);
        insert new List<Coupon__c>{c1};

        RecordType manhattanCouponSellerRecordType = ApexUtil.getRecordTypeByName('Coupon_Seller__c',EBH_ConstantsUtility.COUPONSELLER_MANHATTAN_RECORDTYPE);
        Coupon_Seller__c cs1 = new Coupon_Seller__c(Coupon__c = c1.Id,Coupon_Seller_Stage__c='Targeted',Seller_Contact__c=con.Id,EBH_CouponSellerOwner__c = UserInfo.getUserId(),Seller__c = acc.Id,RecordTypeID=manhattanCouponSellerRecordType.Id);
        insert cs1;

        
    }
    @isTest 
    static void test_getDownloadExcel() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount' limit 1];
        Contact con = [SELECT Id,Email FROM Contact WHERE FirstName='test fn' AND LastName='test ln' limit 1];
        RecordType couponRecordTypeCat = ApexUtil.getRecordTypeByName('Coupon__c',EBH_ConstantsUtility.COUPON_CATEGORYBASE);
        Coupon__c c1 = new Coupon__c(Main_Coupon_Site__c = 'ebay.com',MC_Whitelisted__c = true,Stage__c = 'Draft', RecordTypeID = couponRecordTypeCat.Id,Coupon_Start_Date__c = System.today(),Coupon_End_Date__c=System.today(),Contract_Language__c = 'UK',Contract_Due_Date__c = System.today()-1);
        insert c1;
        RecordType manhattanCouponSellerRecordType = ApexUtil.getRecordTypeByName('Coupon_Seller__c',EBH_ConstantsUtility.COUPONSELLER_MANHATTAN_RECORDTYPE);
        Coupon_Seller__c cs = new Coupon_Seller__c(Coupon__c = c1.Id,Coupon_Seller_Stage__c='Targeted',Seller_Contact__c=con.Id,EBH_CouponSellerOwner__c = UserInfo.getUserId(),Seller__c = acc.Id,RecordTypeID=manhattanCouponSellerRecordType.Id);
        insert cs;
        List<Coupon_Co_Invest__c> lstCCI = new List<Coupon_Co_Invest__c>();
            Id cciRT = Schema.SObjectType.Coupon_Co_Invest__c.getRecordTypeInfosByName().get('Coupon Co-Invest Item').getRecordTypeId();
            lstCCI.add(new Coupon_Co_Invest__c(
                Coupon_Seller__c = cs.Id,
                Seller_Name__c = acc.Id,
                Co_Invest__c = 10,
                CurrencyIsoCode = 'USD',
                RecordtypeId = cciRT
            ));
            insert lstCCI;
        Test.startTest(); 
            PageReference pageRef = new PageReference('/apex/SEPDownloadPage');
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id',cs.Id);

            SEPDownloadController controller =new SEPDownloadController();
            SEPDownloadController.CouponSellerWrapper sheet = controller.cs;
            SEPDownloadController.getDownloadExcel(cs.Id);
            System.debug('sheet' +sheet);
            //System.assert(String.isNotBlank(result));
        Test.stopTest();

    }
}