unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealSiteId__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealSiteId__c</fullName>
    <description>[EBH] (EPH-5193) - Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>71</fullName>
                <label>FR</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>186</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealStartDate__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealStartDate__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Start Date</description>
    <label>Deal Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayItemID__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayItemID__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Item ID</description>
    <label>eBay Item ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayLink__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayLink__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Link</description>
    <formula>IF( ISBLANK( EBH_eBayItemID__c ), &quot;Item ID missing&quot;, 
if( TEXT ( EBH_DealSiteId__c ) =&quot;77&quot;,HYPERLINK(&quot;http://www.ebay.de/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;),
if( TEXT ( EBH_DealSiteId__c ) =&quot;3&quot;,HYPERLINK(&quot;http://www.ebay.co.uk/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;),
if( TEXT ( EBH_DealSiteId__c ) =&quot;71&quot;,HYPERLINK(&quot;http://www.ebay.fr/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;),
if( TEXT ( EBH_DealSiteId__c ) =&quot;101&quot;,HYPERLINK(&quot;http://www.ebay.it/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;),
if( TEXT ( EBH_DealSiteId__c ) =&quot;186&quot;,HYPERLINK(&quot;http://www.ebay.es/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;),
if( TEXT ( EBH_DealSiteId__c ) =&quot;15&quot;,HYPERLINK(&quot;http://www.ebay.com.au/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;),
HYPERLINK(&quot;http://www.ebay.com/itm/&quot;&amp; EBH_eBayItemID__c, &quot;Open in eBay&quot;)
)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>eBay Link</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Pricenotmatching__c.field-meta.xml
<CustomField>
    <fullName>EBH_Pricenotmatching__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[EBH] (EPH-4163) - Price not matching</description>
    <label>Price not matching</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-4163) - Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Negotiating Amended</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Seller Invite</fullName>
            </value>
            <value>
                <fullName>Seller Proposal</fullName>
            </value>
            <value>
                <fullName>Deal Agreed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <label>Statement Verified (Trigger Email to Seller)</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected (Email resend to Seller)</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Completed</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Visual Sales Path</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Internally Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/EBH_ScrapDeal.cls
/**10/10/2017:
 vadhanak.voun@gaea-sys.com
 #12702:
   1.  Scheduled job collects all deal__c records where Status__c = “Deal Agreed” or “Running” and Deal_Start_Date__c = Today and ebay_Link__c <> “Item ID missing”
  2.  From these records use the URL in ebay_Link__c to go to the eBay Website of the deal.
  3.  Identify the price of the deal from the website (see screenshot).
     If I understand correctly there is an item on the page with ID prcIsum which contains the price.
    <span class="notranslate" id="prcIsum" itemprop="price" style="" content="439.0">EUR 439,00</span>
  4.  Compare this identified price with Deal_Price__c. If they don’t match set Price_not_matching__c = True
  
  changes:
  	+ 02/03/2018: Vadhanak: findEbayPrice(): replaced regex that unknown reason causes regex too complicate.
  				  Handle redirect in case item moved to HTTPS 
  	+ 03/03/3030: Vadhanak: US-0007241 Rework existing EBH_ScrapDeal class to use API call instead of Web Crawling approach.
*/

global without sharing class EBH_ScrapDeal implements Database.Batchable<SObject>,Database.AllowsCallouts,Schedulable {
   String query = 'Select Id,EBH_DealSiteId__c,EBH_eBayItemID__c,EBH_Status__c,EBH_ebayLink__c,EBH_DealPrice__c,EBH_Pricenotmatching__c From EBH_Deal__c ';
   
   global Database.QueryLocator start(Database.BatchableContext BC)
   {
      String sWhere = ' WHERE EBH_Status__c IN(\'Deal Agreed\',\'Running\') AND EBH_DealStartDate__c=TODAY AND EBH_ebayLink__c <> \'Item ID missing\'';
      return Database.getQueryLocator(query+sWhere);
   }
   public EBH_ScrapDeal(){}
   
   global void execute(Database.BatchableContext BC, List<EBH_Deal__c> scope)
   {
       EBH_DealTriggerHandler.doProcessDealItems(scope);
   }

   global void finish(Database.BatchableContext BC)
   {
     
   }
   
   global void execute(SchedulableContext sc) {
      EBH_ScrapDeal sdbatch = new EBH_ScrapDeal(); 
      Database.executebatch(sdbatch,50); //reduced from 100 to 50; there could be another redirect request
   }
}