unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/DealClonePageController.cls
public with sharing class DealClonePageController {
    
    private ID dealId;
    Private EBH_Deal__c deal;
    public DealClonePageController(ApexPages.StandardController controller) {
        
        if (!test.isRunningTest()){
            controller.addFields(EBH_ConstantsUtility.DEAL_CLONE_FIELDS_TO_COPY);
        }
        
        dealId = controller.getId();
        deal = (EBH_Deal__c)controller.getRecord();
        
        
    }
    
    public pageReference clonecustom(){
        
        EBH_Deal__c d = deal.clone();
        d.EBH_DealPrice__c=0;
        insert d;
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Record Cloned Successfully.Thank you!'));
        PageReference pg = new PageReference('/'+d.Id);
        pg.setRedirect(true);
        return pg; 
    }
}