unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/eBay_Seller_Name__c.field-meta.xml
<CustomField>
    <fullName>eBay_Seller_Name__c</fullName>
    <description>US-0008225</description>
    <formula>EBH_BusinessName__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>eBay Seller Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_BusinessName__c.field-meta.xml
<CustomField>
    <fullName>EBH_BusinessName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[EBH] (EPH-4163) - Business Name</description>
    <label>eBay Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_BusinessName</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Category__c.field-meta.xml
<CustomField>
    <fullName>EBH_Category__c</fullName>
    <description>[EBH] (EPH-4163) - Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EBH_DealSiteId__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DVDs, Films &amp; TV</fullName>
            </value>
            <value>
                <fullName>Antiquitäten &amp; Kunst</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Motorrad: Fahrzeuge</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Motorrad: Teile</fullName>
            </value>
            <value>
                <fullName>Bastel- &amp; Künstlerbedarf</fullName>
            </value>
            <value>
                <fullName>Beauty &amp; Gesundheit</fullName>
            </value>
            <value>
                <fullName>Briefmarken</fullName>
            </value>
            <value>
                <fullName>Bücher</fullName>
            </value>
            <value>
                <fullName>Büro &amp; Schreibwaren</fullName>
            </value>
            <value>
                <fullName>Business &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Computer, Tablets &amp; Netzwerk</fullName>
            </value>
            <value>
                <fullName>Feinschmecker</fullName>
            </value>
            <value>
                <fullName>Filme &amp; DVDs</fullName>
            </value>
            <value>
                <fullName>Foto &amp; Camcorder</fullName>
            </value>
            <value>
                <fullName>Garten</fullName>
            </value>
            <value>
                <fullName>Garten &amp; Terrasse</fullName>
            </value>
            <value>
                <fullName>Handys &amp; Kommunikation</fullName>
            </value>
            <value>
                <fullName>Haushaltsgeräte</fullName>
            </value>
            <value>
                <fullName>Haustierbedarf</fullName>
            </value>
            <value>
                <fullName>Heimwerker</fullName>
            </value>
            <value>
                <fullName>Immobilien</fullName>
            </value>
            <value>
                <fullName>Kleidung &amp; Accessoires</fullName>
            </value>
            <value>
                <fullName>Möbel &amp; Wohnen</fullName>
            </value>
            <value>
                <fullName>Modellbau</fullName>
            </value>
            <value>
                <fullName>Münzen</fullName>
            </value>
            <value>
                <fullName>Musik</fullName>
            </value>
            <value>
                <fullName>Musikinstrumente</fullName>
            </value>
            <value>
                <fullName>PC- &amp; Videospiele</fullName>
            </value>
            <value>
                <fullName>Reisen</fullName>
            </value>
            <value>
                <fullName>Sammeln &amp; Seltenes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealSiteId__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealSiteId__c</fullName>
    <description>[EBH] (EPH-5193) - Deal Site ID</description>
    <label>Deal Site</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>77</fullName>
                <label>DE</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>71</fullName>
                <label>FR</label>
            </value>
            <value>
                <fullName>101</fullName>
                <label>IT</label>
            </value>
            <value>
                <fullName>186</fullName>
                <label>ES</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>AU</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>US</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>CA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayItemID__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayItemID__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Item ID</description>
    <label>eBay Item ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_MaximumPurchases__c.field-meta.xml
<CustomField>
    <fullName>EBH_MaximumPurchases__c</fullName>
    <description>[EBH] (EPH-4172) - Export deal</description>
    <label>Maximum Purchases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_ProductTitle__c.field-meta.xml
<CustomField>
    <fullName>EBH_ProductTitle__c</fullName>
    <description>[EBH] (EPH-4163) - Product Title
US-0009410 - DEALS: Increase &#39;Product Title&#39; field length to 150 characters</description>
    <label>Product Title</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EBH_Quantity__c</fullName>
    <description>[EBH] (EPH-4163) - Quantity</description>
    <inlineHelpText>Number of units seller can commit of the item at the deal price</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_RRPWASPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_RRPWASPrice__c</fullName>
    <description>[EBH] (EPH-4163) - RRP/WAS Price</description>
    <inlineHelpText>Price of strikethrough or previous existing price of deal</inlineHelpText>
    <label>RRP/WAS Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SpotlightCategory__c.field-meta.xml
<CustomField>
    <fullName>EBH_SpotlightCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-4163) - Spotlight Category</description>
    <label>Spotlight Category</label>
    <referenceTo>EBH_SpotlightCategory__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_SpotlightCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Vertical__c.field-meta.xml
<CustomField>
    <fullName>EBH_Vertical__c</fullName>
    <description>[EBH] (EPH-4163) - Vertical</description>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EBH_DealSiteId__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Soft Home</fullName>
            </value>
            <value>
                <fullName>Hard Home</fullName>
            </value>
            <value>
                <fullName>P&amp;A</fullName>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Leisure</fullName>
            </value>
            <value>
                <fullName>Fitness</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Joyería y Belleza</fullName>
            </value>
            <value>
                <fullName>Electrónica</fullName>
            </value>
            <value>
                <fullName>Moda</fullName>
            </value>
            <value>
                <fullName>Casa y Jardín</fullName>
            </value>
            <value>
                <fullName>Ocio</fullName>
            </value>
            <value>
                <fullName>Deportes</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>Coleccionismo</fullName>
            </value>
            <value>
                <fullName>Otras categorías</fullName>
            </value>
            <value>
                <fullName>High-Tech</fullName>
            </value>
            <value>
                <fullName>Mode</fullName>
            </value>
            <value>
                <fullName>Maison &amp; Jardin</fullName>
            </value>
            <value>
                <fullName>Auto et Moto</fullName>
            </value>
            <value>
                <fullName>Collections &amp; Antiquités</fullName>
            </value>
            <value>
                <fullName>Tecnologia</fullName>
            </value>
            <value>
                <fullName>Casa &amp; Giardino</fullName>
            </value>
            <value>
                <fullName>Sport &amp; Viaggi</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Moto</fullName>
            </value>
            <value>
                <fullName>Collezionabili</fullName>
            </value>
            <value>
                <fullName>Commercio, Ufficio e Industria</fullName>
            </value>
            <value>
                <fullName>Suministros industriales</fullName>
            </value>
            <value>
                <fullName>H&amp;G</fullName>
            </value>
            <value>
                <fullName>Parts &amp; BI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DD_RetailWeekSpreadsheetController.cls
/*********************************************************************************************************************************
@ Class:          DD_RetailWeekSpreadsheetController
@ Version:        1.0
@ Author:         Mony Nou (mony.nou@gaea-sys.com)
@ Purpose:        US-0009853 - [SEP] Email notification to Seller when Deal Window is Scheduled
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 20.07.2021 / Mony Nou / Created the class.
*********************************************************************************************************************************/
public without sharing class DD_RetailWeekSpreadsheetController {

    public string xmlheader         {get;set;}
    public string contentType       {get;set;}
    public List<DealWrapper> deals  {get;set;}

    private EBH_SpotlightCategory__c default_spotlight_cate;
    
    private final static string DEAL_STATUS_SCHEDULED = 'Scheduled';
    private final static string DEAL_STATUS_CMREVIEW  = 'CM Review';
    
    
    

    public DD_RetailWeekSpreadsheetController() {

        //VF page gives some issues directly using the below code there, so wrap up in variable    
        xmlheader ='<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?>';

        String param_dwid = ''; //Deal Window Id
        String param_scid = ''; //Seller Contact Id
        String param_dwrw = ''; //Deal Window Retail Week

        if (Apexpages.currentPage().getParameters().containsKey('dwid'))  param_dwid = String.escapeSingleQuotes(Apexpages.currentPage().getParameters().get('dwid')); 
        if (Apexpages.currentPage().getParameters().containsKey('scid'))  param_scid = String.escapeSingleQuotes(Apexpages.currentPage().getParameters().get('scid')); 
        if (Apexpages.currentPage().getParameters().containsKey('dwrw')) param_dwrw = String.escapeSingleQuotes(Apexpages.currentPage().getParameters().get('dwrw')); 

        contentType = 'application/vnd.ms-excel#eBay Daily Deals Retail Week ' + param_dwrw + '.xls;charset=UTF-8'; 

        //MN-22072021-US-0009685-get defualt Spotlight Category if field Spotlight Category == null
        default_spotlight_cate = new EBH_SpotlightCategory__c();
        for(EBH_SpotlightCategory__c spl: [SELECT Name FROM EBH_SpotlightCategory__c WHERE Name = :Label.US_UnSubDeal_Default_Spotlight limit 1]){ default_spotlight_cate = spl; }

        deals = new List<DealWrapper>();
        if (String.isNotBlank(param_dwid) && String.isNotBlank(param_scid)) {
            for (EBH_Deal__c d : [SELECT toLabel(EBH_DealSiteId__c) ds, EBH_DealSiteId__c, EBH_SpotlightCategory__c, EBH_SpotlightCategory__r.Name, EBH_BusinessName__c, eBay_Seller_Name__c, EBH_eBayItemID__c, EBH_DealPrice__c
                                        , EBH_RRPWASPrice__c, EBH_Quantity__c, EBH_MaximumPurchases__c, EBH_ProductTitle__c, EBH_Vertical__c, EBH_Category__c, Sub_Category__c
                                        , EBH_DealStartDate__c, EBH_DealStartTime__c, EBH_DealEndDate__c, EBH_DealEndTime__c, EBH_Status__c, Cancellation_Reason__c, EBH_ReasonforRejection__c, EBH_ReasonforRejectionextd__c
                                    FROM EBH_Deal__c WHERE EBH_DealRetailCampaign__c=:param_dwid AND Seller_Contact__c=:param_scid]) {

                DealWrapper dw = new DealWrapper(d);
                if (String.isNotBlank(d.EBH_DealSiteId__c)) d.EBH_DealSiteId__c = String.valueOf(d.get('ds'));
                if (d.EBH_Status__c == DEAL_STATUS_CMREVIEW && d.EBH_SpotlightCategory__c == null && String.isNotBlank(default_spotlight_cate.Name)) dw.spotlight_cate = default_spotlight_cate.Name;
                if (d.EBH_Status__c == DEAL_STATUS_CMREVIEW) d.EBH_Status__c = DEAL_STATUS_SCHEDULED;
                deals.add(dw);

            }
        }

    }

    public String currencyFormat{
        get{
            return '_("$"* #,##0.00_);_("$"* \\(#,##0.00\\);_("$"* "-"??_);_(@_)';
        }
    }

    public class DealWrapper {

        public EBH_Deal__c deal{get;set;}
        public String startDate {get;set;}
        public String endDate {get;set;}
        public DateTime startTime{get;set;}
        public DateTime endTime{get;set;}
        public String spotlight_cate {get;set;}

        public DealWrapper (EBH_Deal__c deal) {
            this.deal = deal;
            if(deal.EBH_DealStartDate__c!=null){
                this.startTime = DateTime.newInstance(deal.EBH_DealStartDate__c, deal.EBH_DealStartTime__c);
                this.startDate = this.startTime.format('MM/dd/yyyy');
            }
            if(deal.EBH_DealEndDate__c!=null){
                this.endTime = DateTime.newInstance(deal.EBH_DealEndDate__c, deal.EBH_DealEndTime__c);
                this.endDate = this.endTime.format('MM/dd/yyyy');
            }

            this.spotlight_cate = (deal.EBH_SpotlightCategory__c != null)?deal.EBH_SpotlightCategory__r.Name:'';
        }   
    }
}