unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-4163) - Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Negotiating Amended</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Seller Invite</fullName>
            </value>
            <value>
                <fullName>Seller Proposal</fullName>
            </value>
            <value>
                <fullName>Deal Agreed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <label>Statement Verified (Trigger Email to Seller)</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected (Email resend to Seller)</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Completed</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Visual Sales Path</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Internally Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SubsidyFinal__c.field-meta.xml
<CustomField>
    <fullName>EBH_SubsidyFinal__c</fullName>
    <description>[EBH] (EPH-4163) - Subsidy Final
[#EPH-7598] Deal Object - Subsidy fields redesign for Invoicing</description>
    <formula>IF( OR(ISBLANK(Subsidy_Payout_Amount__c),Subsidy_Payout_Amount__c=0), SubsidyFinal_Servicing__c, Subsidy_Payout_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidy Final (Gross)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/NumberOfDaysSinceDealEnd__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysSinceDealEnd__c</fullName>
    <formula>IF(
  (today()- EBH_DealEndDate__c) &lt; 0, NULL,
   today()- EBH_DealEndDate__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Days since Deal End Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/BatchDealVerifyStatement.cls
/*********************************************************************************************************************************
@ Class:         BatchDealVerifyStatement
@ Version:       1.0
@ Author:        Vadhanak Voun (vadhanak.voun@gaea-sys.com)
@ Purpose:       EPH-8050 Verify Statement Work Flow Rule is not working
@				moved from workflow to dail scheduler (formula fields does not trigger!)				 
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 04.09.2019 / Vadhanak Voun / Created the class.
@ Change history: 06.06.2022 / Sophal Noch / US-0011771 - Updating Deals to "Verify Statement" Batch
*********************************************************************************************************************************/
global without sharing class BatchDealVerifyStatement implements Database.Batchable<SObject>, Schedulable{
	private Set<String> setStatusInclude = new Set<String>{EBH_ConstantsUtility.DEAL_STATUS_EXEC};
				
	private String soqlDeal = EBH_ConstantsUtility.SOQL_DEAL;
	
	@testVisible
	// private String sWhere = ' Where NumberOfDaysSinceDealEnd__c=32 AND EBH_Status__c IN:setStatusInclude AND EBH_SubsidyFinal__c >0 ';
    private String sWhere = ' Where NumberOfDaysSinceDealEnd__c >= 32 AND EBH_Status__c IN:setStatusInclude AND EBH_SubsidyFinal__c >0 '; // 06.06.2022 / Sophal Noch / US-0011771
    
    
    private String dealId;
    public BatchDealVerifyStatement()
    {
    }
    
    //testigng purpose
	public BatchDealVerifyStatement(String dealId)
    {
    	this.dealId = dealId;
    	sWhere += ' And Id =:dealId';
    }
	
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(soqlDeal+sWhere);
    }

    global void execute(Database.BatchableContext pBc, List<EBH_Deal__c> scope){

        try 
        {
    		for (EBH_Deal__c d : scope) 
		    { 
		         d.EBH_Status__c = EBH_ConstantsUtility.DEAL_STATUS_VERIFY;
		        
		    }
    		update scope;
        		
        }catch (Exception ex) {
            EBH_ApexLogger.logError(new List<Exception> { ex }, 'BatchDealVerifyStatement','execute');
        }
    }

    global void finish(Database.BatchableContext pBc){

    }
    global void execute(SchedulableContext sc) { 
        BatchDealVerifyStatement b = new BatchDealVerifyStatement();
        Database.executeBatch(b);
    }
    
    
}