unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealRetailCampaign__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealRetailCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5546 Relationship between Deal and Deal Retail Campaign objects</description>
    <label>Deal Retail Campaign</label>
    <referenceTo>EBH_DealRetailCampaign__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_SpotlightCategory__c.field-meta.xml
<CustomField>
    <fullName>EBH_SpotlightCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EBH] (EPH-4163) - Spotlight Category</description>
    <label>Spotlight Category</label>
    <referenceTo>EBH_SpotlightCategory__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>EBH_SpotlightCategory</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Status__c.field-meta.xml
<CustomField>
    <fullName>EBH_Status__c</fullName>
    <description>[EBH] (EPH-4163) - Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Negotiating Amended</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Seller Invite</fullName>
            </value>
            <value>
                <fullName>Seller Proposal</fullName>
            </value>
            <value>
                <fullName>Deal Agreed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Verify Statement</fullName>
            </value>
            <value>
                <fullName>Statement Verified</fullName>
                <label>Statement Verified (Trigger Email to Seller)</label>
            </value>
            <value>
                <fullName>Clarification Required</fullName>
            </value>
            <value>
                <fullName>Verify Invoice</fullName>
            </value>
            <value>
                <fullName>Invoice Rejected (Email resend to Seller)</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Payment Completed</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Visual Sales Path</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Internally Approved</fullName>
            </value>
            <value>
                <fullName>Internally Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/recordTypes/Deal_V3.recordType-meta.xml
<RecordType>
    <fullName>Deal_V3</fullName>
    <active>true</active>
    <label>NA Unsub Deal</label>
</RecordType>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/EBH_DealRetailCampaign__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-5481) - Deal Retail Campaign</description>
    <label>Deal Retail Campaign</label>
    <nameField>
        <displayFormat>DRC-{0000000000}</displayFormat>
        <label>Deal Retail Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Retail Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;New&#39;</defaultValue>
    <description>US-0009621</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open for Submissions</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Batch_DRC_DealUpdate.cls
/*********************************************************************************************************************************
@ Class:          Batch_DRC_DealUpdate
@ Version:        1.0
@ Author:         SRONG TIN (srong.tin@gaea-sys.com)
@ Purpose:        DealRetailCampaignTriggerHandler.updateDealStatusByTimeBaseChange fix CPU limit
@ Change history: 06.July.2021 / SRONG TIN / Created the class.
*********************************************************************************************************************************/
global without sharing class Batch_DRC_DealUpdate implements Database.Batchable<SObject>{
     /****************************************************************************************************************************
	* CONSTANTS DEFINITION
	*****************************************************************************************************************************/
    private Set<ID> dealRetailCampaignIds;
    public static final String NA_Unsub_Deal = 'Deal_V3';
    public Id spotlightUsVerticalsId = null;
    public static final String OPS_REVIEW = 'Ops Review';
    public static final String CM_REVIEW = 'CM Review';
    public static final String SCHEDULED = 'Scheduled';
    public static final String RUNNING = 'Running';
    public static final String COMPLETED = 'Completed';
    // 29.July.2021 / SRONG TIN : US-0010037 
    private Set<String> STATUS_REJECTED_CANCELLED;

    Id dealRecordTypeId =  ApexUtil.getRecordTypeByName('EBH_Deal__c', NA_Unsub_Deal).Id;
    private String whereCS = ' WHERE EBH_DealRetailCampaign__c IN: dealRetailCampaignIds AND RecordTypeId =: dealRecordTypeId';
	private final static String SOQL_DEAL = 'SELECT Id, EBH_Status__c,EBH_DealRetailCampaign__c,EBH_DealRetailCampaign__r.Status__c,EBH_SpotlightCategory__c FROM EBH_Deal__c' ;
    /************************************END CONSTANTS DEFINITION*************************************************************/

    public Batch_DRC_DealUpdate(set<Id> dealRetailCampaignIds) {
        this.dealRetailCampaignIds = dealRetailCampaignIds;
        //get defualt Spotlight Category if field Spotlight Category == null
        for(EBH_SpotlightCategory__c spl: [SELECT Id FROM EBH_SpotlightCategory__c WHERE  Name = :Label.US_UnSubDeal_Default_Spotlight limit 1]){
            spotlightUsVerticalsId = spl.Id;
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {        
        return Database.getQueryLocator(SOQL_DEAL + whereCS);
    }

    global void execute(Database.BatchableContext pBc, List<EBH_Deal__c> scope)
    {
        List<EBH_Deal__c> listDeals = new List<EBH_Deal__c>();
        // 29.July.2021 / SRONG TIN : US-0010037 
        STATUS_REJECTED_CANCELLED = new Set<String>{'Cancelled','Rejected'};
        for(EBH_Deal__c oDeal : scope){
             if(oDeal.EBH_DealRetailCampaign__r.Status__c == CM_REVIEW && oDeal.EBH_Status__c == OPS_REVIEW){
                 // 2 Days at 18:00:00 PST before Deal Window Start Date: 
                 oDeal.EBH_Status__c = CM_REVIEW;
             }else if(oDeal.EBH_DealRetailCampaign__r.Status__c == SCHEDULED && oDeal.EBH_Status__c == CM_REVIEW){
                 // When 1 Day at 18:00:00 PST before Deal Window Start Date:
                 oDeal.EBH_Status__c = SCHEDULED;
                 // If Spotlight Category is NULL, Update 'Spotlight Category' field to 'US Verticals' Category
                if( String.isBlank(oDeal.EBH_SpotlightCategory__c) &&
                    String.isNotBlank(spotlightUsVerticalsId)){
                    oDeal.EBH_SpotlightCategory__c = spotlightUsVerticalsId;
                }   
            // 29.July.2021 / SRONG TIN : US-0010037 
            }else if(oDeal.EBH_DealRetailCampaign__r.Status__c == RUNNING && !STATUS_REJECTED_CANCELLED.contains(oDeal.EBH_Status__c)){
                 // When Deal Window Start Date is reached:
                 oDeal.EBH_Status__c = RUNNING;
             }else if(oDeal.EBH_DealRetailCampaign__r.Status__c == COMPLETED && !STATUS_REJECTED_CANCELLED.contains(oDeal.EBH_Status__c)){
                 // When Deal Window End Date is reached:
                 oDeal.EBH_Status__c = COMPLETED;
             }
             // add list of Deals
             listDeals.add(oDeal);
         }
         if(!listDeals.isEmpty()){
             // update list of Deals
             update listDeals;
         }
		 
    }  
    
    
    global void finish(Database.BatchableContext pBc)
    {
        
    }
}