unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Category__c.field-meta.xml
<CustomField>
    <fullName>EBH_Category__c</fullName>
    <description>[EBH] (EPH-4163) - Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EBH_DealSiteId__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DVDs, Films &amp; TV</fullName>
            </value>
            <value>
                <fullName>Antiquitäten &amp; Kunst</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Motorrad: Fahrzeuge</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Motorrad: Teile</fullName>
            </value>
            <value>
                <fullName>Bastel- &amp; Künstlerbedarf</fullName>
            </value>
            <value>
                <fullName>Beauty &amp; Gesundheit</fullName>
            </value>
            <value>
                <fullName>Briefmarken</fullName>
            </value>
            <value>
                <fullName>Bücher</fullName>
            </value>
            <value>
                <fullName>Büro &amp; Schreibwaren</fullName>
            </value>
            <value>
                <fullName>Business &amp; Industrie</fullName>
            </value>
            <value>
                <fullName>Computer, Tablets &amp; Netzwerk</fullName>
            </value>
            <value>
                <fullName>Feinschmecker</fullName>
            </value>
            <value>
                <fullName>Filme &amp; DVDs</fullName>
            </value>
            <value>
                <fullName>Foto &amp; Camcorder</fullName>
            </value>
            <value>
                <fullName>Garten</fullName>
            </value>
            <value>
                <fullName>Garten &amp; Terrasse</fullName>
            </value>
            <value>
                <fullName>Handys &amp; Kommunikation</fullName>
            </value>
            <value>
                <fullName>Haushaltsgeräte</fullName>
            </value>
            <value>
                <fullName>Haustierbedarf</fullName>
            </value>
            <value>
                <fullName>Heimwerker</fullName>
            </value>
            <value>
                <fullName>Immobilien</fullName>
            </value>
            <value>
                <fullName>Kleidung &amp; Accessoires</fullName>
            </value>
            <value>
                <fullName>Möbel &amp; Wohnen</fullName>
            </value>
            <value>
                <fullName>Modellbau</fullName>
            </value>
            <value>
                <fullName>Münzen</fullName>
            </value>
            <value>
                <fullName>Musik</fullName>
            </value>
            <value>
                <fullName>Musikinstrumente</fullName>
            </value>
            <value>
                <fullName>PC- &amp; Videospiele</fullName>
            </value>
            <value>
                <fullName>Reisen</fullName>
            </value>
            <value>
                <fullName>Sammeln &amp; Seltenes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealPrice__c</fullName>
    <description>[EBH] (EPH-4163) - Deal Price</description>
    <inlineHelpText>Price of deal, including any eBay subsidy. If no eBay subsidy is applied, Deal Price and Seller Price are same amount</inlineHelpText>
    <label>Deal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_DealRetailCampaign__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealRetailCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-5546 Relationship between Deal and Deal Retail Campaign objects</description>
    <label>Deal Retail Campaign</label>
    <referenceTo>EBH_DealRetailCampaign__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_eBayItemID__c.field-meta.xml
<CustomField>
    <fullName>EBH_eBayItemID__c</fullName>
    <description>[EBH] (EPH-4163) - eBay Item ID</description>
    <label>eBay Item ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_ProductTitle__c.field-meta.xml
<CustomField>
    <fullName>EBH_ProductTitle__c</fullName>
    <description>[EBH] (EPH-4163) - Product Title
US-0009410 - DEALS: Increase &#39;Product Title&#39; field length to 150 characters</description>
    <label>Product Title</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_Quantity__c.field-meta.xml
<CustomField>
    <fullName>EBH_Quantity__c</fullName>
    <description>[EBH] (EPH-4163) - Quantity</description>
    <inlineHelpText>Number of units seller can commit of the item at the deal price</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/EBH_RRPWASPrice__c.field-meta.xml
<CustomField>
    <fullName>EBH_RRPWASPrice__c</fullName>
    <description>[EBH] (EPH-4163) - RRP/WAS Price</description>
    <inlineHelpText>Price of strikethrough or previous existing price of deal</inlineHelpText>
    <label>RRP/WAS Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/fields/Status_Seller_Portal__c.field-meta.xml
<CustomField>
    <fullName>Status_Seller_Portal__c</fullName>
    <description>US-0009685, US-0011032, US-0012156</description>
    <formula>IF(TEXT( Seller_Portal_Status__c ) =&quot;Clarification on invoicing&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Klärung zur Abrechnung&quot;,

IF(TEXT( Seller_Portal_Status__c ) =&quot;Deal agreed&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot vereinbart, startet in Kürze&quot;,

IF(TEXT( Seller_Portal_Status__c ) =&quot;Deal closed&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Beendet&quot;,

IF(TEXT( Seller_Portal_Status__c ) =&quot;Deal ended&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot beendet&quot;,

IF(TEXT( Seller_Portal_Status__c ) =&quot;Deal in execution&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot in Durchführung&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Deal proposal rejected&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot abgelehnt&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Deal sent for payment&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Auszahlung ist veranlasst&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Invitation to Deals&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;eBay WOW! Einladung&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Invoice rejected, please verify&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Rechnung abgelehnt, bitte prüfen Sie die Abrechnung&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Invoice verification in process by eBay&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Rechnung in Prüfung durch eBay&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Invoicing in process&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Abrechnung erfolgt in Kürze&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Negotiation&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot in Verhandlung&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Negotiation Amended&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot Verhandlung geändert&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;New Deal proposed to eBay&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;WOW! Angebot eingereicht&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Payment completed&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Auszahlung durchgeführt&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Payment in process&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Auszahlung erfolgt in Kürze&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Payment rejected&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Auszahlung abgelehnt, bitte konktaktieren Sie eBay&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Please agree on the proposed Deal&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Bestätigen Sie das WOW! Angebot&quot;,

IF(TEXT(Seller_Portal_Status__c) =&quot;Please provide an invoice&quot;&amp;&amp;$Profile.Name=&quot;DE - Seller Portal&quot;,&quot;Rechnung hochladen&quot;,

TEXT (Seller_Portal_Status__c))))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/EBH_DealRetailCampaign__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-5481) - Deal Retail Campaign</description>
    <label>Deal Retail Campaign</label>
    <nameField>
        <displayFormat>DRC-{0000000000}</displayFormat>
        <label>Deal Retail Campaign ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Retail Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/EBH_DealTitle__c.field-meta.xml
<CustomField>
    <fullName>EBH_DealTitle__c</fullName>
    <description>(EPH-5481) Deal Retail Calendar Title</description>
    <label>Retail Campaign Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;New&#39;</defaultValue>
    <description>US-0009621</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Open for Submissions</fullName>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>CM Review</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/EBH_DealRetailCampaign__c/fields/Status_Seller_Portal__c.field-meta.xml
<CustomField>
    <fullName>Status_Seller_Portal__c</fullName>
    <description>US-0009684</description>
    <formula>CASE(Status__c,
  &#39;Draft&#39;,&#39;Draft&#39;,
  &#39;Pending&#39;, &#39;Pending&#39;,
  &#39;Open for Submissions&#39;,&#39;Open for Submissions&#39;,
  &#39;Ops Review&#39;,&#39;Closed for Submissions&#39;,
  &#39;CM Review&#39;,&#39;Closed for Submissions&#39;,
  &#39;Scheduled&#39;,&#39;Closed for Submissions&#39;,
  &#39;Running&#39;,&#39;Running&#39;,
  &#39;Completed&#39;,&#39;Completed&#39;,&#39;&#39;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CustomSearchController.cls
/**
 * @change        created mappingSObjectLabel method 
 * @modifiedDate  21/10/2021
 * @modifiedBy    Samnang MUONG
 */
public with sharing class CustomSearchController {

  @AuraEnabled
  public static List<SObject> searchRecords(String searchText) {

    List<SObject> results = new List<SObject>();

   // String currentId = System.UserInfo.getUserId();
    
    String str='%'+searchText+ '%';

    List<EBH_Deal__c> ebhDeal= [SELECT EBH_Deal__c.Id,EBH_Deal__c.EBH_ProductTitle__c, RecordType.SobjectType FROM EBH_Deal__c 
     WHERE Name Like:str OR EBH_ProductTitle__c Like:str OR EBH_DealRetailCampaign__r.EBH_DealTitle__c Like:
     str OR EBH_DealRetailCampaign__r.Name Like:str OR EBH_eBayItemID__c Like:str LIMIT 5];

     List<EBH_DealRetailCampaign__c> ebhDealRetailCampaign =[SELECT Id,EBH_DealTitle__c, RecordType.SobjectType from EBH_DealRetailCampaign__c
     WHERE Name Like:str OR EBH_DealTitle__c Like:str OR Status__c Like:str LIMIT 5];
     
     results.addAll(ebhDeal);
     results.addAll(ebhDealRetailCampaign);
     return results;
         
  }


  @AuraEnabled(cacheable=true)
  public static List<EBH_Deal__c> searchDealRecords(String searchText) {
    String str='%'+searchText+ '%';
    List<EBH_Deal__c> ebhDeal= [SELECT Id,EBH_eBayItemID__c,EBH_ProductTitle__c,Status_Seller_Portal__c,EBH_DealPrice__c,EBH_RRPWASPrice__c,EBH_Quantity__c,EBH_Category__c,EBH_DealStartDate__c,EBH_DealEndDate__c FROM EBH_Deal__c 
    WHERE Name Like:str OR EBH_ProductTitle__c Like:str OR EBH_DealRetailCampaign__r.EBH_DealTitle__c Like:
    str OR EBH_DealRetailCampaign__r.Name Like:str OR EBH_eBayItemID__c Like:str];

    return ebhDeal;
         
  }



  
  @AuraEnabled(cacheable=true)
  public static List<EBH_DealRetailCampaign__c> searchDealCampaignRecords(String searchText) {
    String str='%'+searchText+ '%';
    List<EBH_DealRetailCampaign__c> ebhDealRetailCampaign =[SELECT Id,Name,EBH_Date__c,EPH_EndDate__c,Status_Seller_Portal__c from EBH_DealRetailCampaign__c
    WHERE Name Like:str OR EBH_DealTitle__c Like:str OR Status__c Like:str];

    return ebhDealRetailCampaign;
         
  }


   /***********************************************************************************************************************************
    @ Method:       mappingSObjectLabel 
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Param:    List<String> lstObjNames
    ------------------------------------------------------------------------------------------------------------------------------------
    @ Returns map label of object and fields
    ------------------------------------------------------------------------------------------------------------------------------------
    @ Change history: ??.??.?? / Trigg / @description Method call from customer search component for get sobject label
    @               : 16.12.2021 / vadhanak voun / US-0010919 - [SP EU - Deals] Adjustments required to hide Generic Features                                        
    ***********************************************************************************************************************************/
  @AuraEnabled
  public static Map<String, Object> mappingSObjectLabel(List<String> lstObjNames){

    Map<String, Object> mapObj = new Map<String, Object>();

   // List<Schema.DescribeSObjectResult> describeSobjectsResult = Schema.describeSObjects(lstObjNames); 
      Map<String, String> mapAPIName2Label = new Map<String, String>();
      Map<String, String> mapFieldAPIName2Label = new Map<String, String>();
      for (Schema.DescribeSObjectResult desObjRes :Schema.describeSObjects(lstObjNames)) {
        
          // mapping object name with label
          mapAPIName2Label.put(desObjRes.getName(), desObjRes.getLabel());

          // fetch fields
          Map<String, Schema.SObjectField> fieldMap = desObjRes.fields.getMap();
          
          for (String fieldName :fieldMap.keySet()) {

            String key = desObjRes.getName()+fieldMap.get(fieldName).getDescribe().getName(); // key : Object Name + Field Name
            mapFieldAPIName2Label.put(key, fieldMap.get(fieldName).getDescribe().getLabel());     
          
          }  

      }

      // add to return map

      mapObj.put('mapSobject', mapAPIName2Label);
      mapObj.put('mapField', mapFieldAPIName2Label);

      //NK:16/12/2021:US-0010919:
      mapObj.put('hasPermission', (Schema.sObjectType.EBH_Deal__c.isAccessible() && Schema.sObjectType.EBH_DealRetailCampaign__c.isAccessible()));

      return mapObj;
    
  }

}