unpackaged/main/default/objects/Coupon_Category__c/Coupon_Category__c.object-meta.xml
<CustomObject>
    <description>[#EPH-7160] Object_ Coupon Category</description>
    <label>Coupon Category</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Coupon Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7160 Object: Coupon Category</description>
    <label>Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Category_Tree__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Category_Tree__c</referenceTo>
    <relationshipLabel>Coupon Categories</relationshipLabel>
    <relationshipName>Coupon_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Category__c/fields/Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Category_ID__c</fullName>
    <description>[#EPH-7291] Coupon Category Object - Field lookups to Category Tree Object</description>
    <formula>Category__r.Category_ID__c</formula>
    <label>Category ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Category__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7160 Object: Coupon Category</description>
    <formula>Coupon__r.Coupon_ID__c</formula>
    <label>Coupon ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/Coupon_Co_Invest__c.object-meta.xml
<CustomObject>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Co-Invest</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Coupon Co-Invest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon Co-Invests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>IF( RecordType.DeveloperName = &#39;Coupon_Co_Invest_Pop&#39;, Category_Tree__r.Name, Coupon_Category__r.Category__r.Name)</formula>
    <label>eBay Category Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Category_ID__c.field-meta.xml
<CustomField>
    <fullName>Category_ID__c</fullName>
    <description>EPH-7486 Add Category ID to Object: Coupon Co-Invest</description>
    <formula>IF( RecordType.DeveloperName = &#39;Coupon_Co_Invest_Pop&#39;, Category_Tree__r.Category_ID__c, Coupon_Category__r.Category__r.Category_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Co_Invest__c.field-meta.xml
<CustomField>
    <fullName>Co_Invest__c</fullName>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Seller Share %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Category__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Category Name</label>
    <referenceTo>Coupon_Category__c</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Coupon_Seller__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Coupon Seller</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if Coupon Co-Invests is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <filterItems>
            <field>Coupon_Seller__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Co-Invest</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon_Seller__c</referenceTo>
    <relationshipLabel>Coupon Co-Invests</relationshipLabel>
    <relationshipName>Coupon_Co_Invests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Item_ID__c</fullName>
    <description>EPH-7253 Object: Coupon Co-Invest</description>
    <label>Item ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/fields/Item_Title__c.field-meta.xml
<CustomField>
    <fullName>Item_Title__c</fullName>
    <description>US-0010892</description>
    <label>Item Title</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Co_Invest__c/recordTypes/Coupon_Co_Invest_Item.recordType-meta.xml
<RecordType>
    <fullName>Coupon_Co_Invest_Item</fullName>
    <active>true</active>
    <label>Coupon Co-Invest Item</label>
</RecordType>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Additional_Terms__c.field-meta.xml
<CustomField>
    <fullName>Additional_Terms__c</fullName>
    <description>EPH-7501 Additional Terms field for Coupon Seller to populate in the contract email</description>
    <inlineHelpText>Additional Terms will be visible for sellers in the Coupon Contract. The value if this field is inherited from the parent Coupon record during the Coupon Seller record creation, but can modified if needed before sending the contract.</inlineHelpText>
    <label>Additional Terms</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>US-0018725 	Coupon Seller - Add condition to workflow for stage T4Statement and T40 Statement</description>
    <formula>TEXT(Coupon__r.Contract_Language__c)</formula>
    <label>Contract Language</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Discount_Amount__c</fullName>
    <description>US-0010429 - Ability to sign Agreement in portal</description>
    <formula>Coupon__r.Coupon_Discount_Amount__c</formula>
    <label>Coupon Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Time__c</fullName>
    <description>US-0007260 POP COUPON - NEW RECORD TYPE COUPON SELLER OBJECT</description>
    <formula>Coupon__r.Coupon_end_Time__c</formula>
    <label>Coupon End Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_ID__c</formula>
    <inlineHelpText>This is the uniqueCouponcode</inlineHelpText>
    <label>Coupon Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Site__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Site__c</fullName>
    <description>US-0010429 - Ability to sign Agreement in portal</description>
    <formula>IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.de&quot;), &quot;ebay.de &quot;,&quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.co.uk&quot;), &quot;ebay.co.uk &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.fr&quot;), &quot;ebay.fr &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.it&quot;), &quot;ebay.it &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.es&quot;), &quot;ebay.es &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.ch&quot;), &quot;ebay.ch &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.at&quot;), &quot;ebay.at &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.pl&quot;), &quot;ebay.pl &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.nl&quot;), &quot;ebay.nl &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.com&quot;), &quot;ebay.com &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.com.au&quot;), &quot;ebay.com.au &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.ca&quot;), &quot;ebay.ca &quot;, &quot;&quot;)
&amp;
IF( INCLUDES(Coupon__r.Couponsite_s__c , &quot;ebay.cfr&quot;), &quot;ebay.cfr&quot;, &quot;&quot;)</formula>
    <label>Coupon Site</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Time__c</fullName>
    <description>US-0007260 POP COUPON - NEW RECORD TYPE COUPON SELLER OBJECT</description>
    <formula>Coupon__r.Coupon_Start_Time__c</formula>
    <label>Coupon Start Time</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_City__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_City__c</fullName>
    <description>US-0010003 - Coupon seller: create new field Legal Entity City</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_Name_w__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name_w__c</fullName>
    <description>EPH-7583 Change logic for contactdatafields in coupon seller</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_Street_w__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Street_w__c</fullName>
    <description>EPH-7583 Change logic for contactdatafields in coupon seller</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Legal_Entity_Zip_w__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Zip_w__c</fullName>
    <description>EPH-7583 Change logic for contactdatafields in coupon seller</description>
    <inlineHelpText>Sellers eBay registration data</inlineHelpText>
    <label>Legal Entity Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Marketing_Coupon_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Coupon_Name__c</fullName>
    <description>US-0007064 [AU] Coupon Click Contract Template Amends</description>
    <formula>Coupon__r.Marketing_Coupon_Name__c</formula>
    <label>Marketing Coupon Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <description>US-0010429 - Ability to sign Agreement in portal
US-0011917</description>
    <formula>Coupon__r.Max_Redemptions__c</formula>
    <label>Maximum Redemption</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Maximum_Discount_Value__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Discount_Value__c</fullName>
    <description>US-0010429 - Ability to sign Agreement in portal</description>
    <formula>Coupon__r.Coupon_Cap__c</formula>
    <label>Maximum Discount Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/SP_Coupon_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>SP_Coupon_Discount_Rate__c</fullName>
    <description>US-0010429 - Ability to sign Agreement in portal</description>
    <formula>Coupon__r.Coupon_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coupon Discount (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/classes/SEPDownloadController.cls
/*********************************************************************************************************************************
@ Class:          SEPDownloadController
@ Version:        1.0
@ Author:         Loumang SENG (loumang.seng@gaea-sys.com)
@ Purpose:        Controller vf page: SEPDownloadPage
                  US-0010534 - Downloadable item list in .xls file from portal
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 14.06.2022 / Loumang SENG / Created the class.
                  22.06.2o22 / Sambath Seng / US-0010429 - Ability to sign Agreement in portal
                  25.07.2022 / Mony Nou / US-0012015 - NA Localization for Coupon Contract
*********************************************************************************************************************************/
public with sharing class SEPDownloadController {
    public string currentUser{get;set;}
    public string currentDate{get;set;}
    public List<Coupon_Co_Invest__c> coInvests {get;set;}
    public CouponSellerWrapper cs {get;set;}
    private final static String RT_COUPON_CO_INVEST_ITEM = 'Coupon_Co_Invest_Item';
    private final static String DF_DD_MM_YYYY = 'dd/MM/yyyy';
    private final static String SOQL_COUPONCOINVEST = 'select Item_ID__c,Item_Title__c,Category__c, Coupon_Seller__c, Co_Invest__c, Category_ID__c, Coupon_Category__r.Name from Coupon_Co_Invest__c';
    public string xmlheader{ get{return '<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?>';}}
    private final static String SOQL_COUPONCATEGORY = 'select Id,Name from Coupon_Category__c';

    public SEPDownloadController(){
        String csId = String.escapeSingleQuotes(String.isBlank(ApexPages.currentPage().getParameters().get('id')) ? '': ApexPages.currentPage().getParameters().get('id'));
        currentUser = UserInfo.getUserName();
        currentDate = Datetime.now().format(DF_DD_MM_YYYY);
        if(String.isNotBlank(csId)){
            cs = new CouponSellerWrapper(SEPCouponController.getCS(csId));
            coInvests = getCouponCoInvestItems(csId);
        }       
    }
  
    /*********************************************************************************************************************************
    @ method:         getCouponCoInvestItems
    @ Version:        1.0
    @ Author:         Loumang SENG (loumang.seng@gaea-sys.com)
    @ Purpose:        US-0010534 - Downloadable item list in .xls file from portal
    @ Parameter:      String csId
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 14.06.2022 / Loumang SENG / Created the method.
    *********************************************************************************************************************************/
    public static List<Coupon_Co_Invest__c> getCouponCoInvestItems(String csId){
        return Database.query(SOQL_COUPONCOINVEST+' Where RecordType.DeveloperName=:RT_COUPON_CO_INVEST_ITEM AND Coupon_Seller__c =:csId');
    }

    /*********************************************************************************************************************************
    @ Class:          CouponSellerWrapper
    @ Version:        1.0
    @ Author:         Loumang SENG (loumang.seng@gaea-sys.com)
    @ Purpose:        Reduce coding to mapping coupon seller fields for SEPDownloadController and SEPCouponController
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 14.06.2022 / Loumang SENG / Created the class.
                      22.06.2o22 / Sambath Seng / US-0010429 - Ability to sign Agreement in portal
                      25.07.2022 / Mony Nou / US-0012015 - NA Localization for Coupon Contract
    *********************************************************************************************************************************/
    public class CouponSellerWrapper {
        public String maxRedmeptions{get;set;}
        public DateTime couponStartDate{get;set;}
        public DateTime couponEndDate{get;set;}
        public String legalEntity{get;set;}
        public String streetName{get;set;}
        public String zip{get;set;}
        public String city{get;set;}
        public String country{get;set;}
        public String eBaySellerID{get;set;}
        public String couponSites{get;set;}
        public String couponCode{get;set;}
        public String formatcouponStartDate{get;set;}
        public String formatcouponEndDate{get;set;}
        public String couponStartTime{get;set;}
        public String couponEndTime{get;set;}
        // public String couponDiscount{get;set;}
        public String marketingName{get;set;}
        public String minTransactionVal{get;set;}
        public String maxDisc{get;set;}
        public String additionalArrangement{get;set;}
        // public String couponDiscountAmount{get;set;}
        public String couponName{get;set;}
        public String couponDiscountAndDiscountAmount{get;set;}

        public String sellerShareHolder {get;set;} //MN-25072022-US-0012015
        public String eBayCofundMax {get;set;} //MN-25072022-US-0012015


        public CouponSellerWrapper(Coupon_Seller__c cs){
            couponName = cs.Name;
            couponCode = ApexUtil.checkNull(cs.Coupon_ID__c)+'';//LA-29-06-2022: US-0010429
            couponStartDate = Datetime.newInstance(cs.Coupon_Start_Date__c.Year(),cs.Coupon_Start_Date__c.Month(),cs.Coupon_Start_Date__c.Day());
		    couponEndDate = Datetime.newInstance(cs.Coupon_End_Date__c.Year(),cs.Coupon_End_Date__c.Month(),cs.Coupon_End_Date__c.Day());
            maxRedmeptions = cs.Max_Redemptions__c==null?'N/A':ApexUtil.formatNumber(cs.Max_Redemptions__c,0,cs.Contract_Language__c);//SB 22.6.2022 US-0010429 - Ability to sign Agreement in portal
            legalEntity = ApexUtil.checkNull(cs.Legal_Entity_Name_w__c)+'';
            streetName = ApexUtil.checkNull(cs.Legal_Entity_Street_w__c)+'';
            zip = ApexUtil.checkNull(cs.Legal_Entity_Zip_w__c)+'';
            city = ApexUtil.checkNull(cs.Legal_Entity_City__c)+'';
            eBaySellerID = cs.Seller__r.Name;
            couponSites = ApexUtil.checkNull(cs.Coupon_Site__c)+'';
            couponStartTime = ApexUtil.formatTime(cs.Coupon_Start_Time__c);
            formatcouponStartDate = couponStartDate == null ? '' : couponStartDate.format(DF_DD_MM_YYYY);
            couponEndTime = ApexUtil.formatTime(cs.Coupon_End_Time__c);
            formatcouponEndDate = couponEndDate == null ? '' : couponEndDate.format(DF_DD_MM_YYYY);
            // couponDiscount = cs.SP_Coupon_Discount_Rate__c==null?'':ApexUtil.formatNumber(cs.SP_Coupon_Discount_Rate__c,2,cs.Contract_Language__c)+'%';//SB 22.6.2022 US-0010429 - Ability to sign Agreement in portal
            // couponDiscountAmount = cs.Coupon_Discount_Amount__c==null?'':ApexUtil.mapCurrencySign.get(cs.CurrencyIsoCode)+ApexUtil.formatNumber(cs.Coupon_Discount_Amount__c,3,cs.Contract_Language__c);//SB 22.6.2022 US-0010429 - Ability to sign Agreement in portal
            //LA-05-07-2022-US-0011917: chnge formula field type number to percentage for field 'Coupon Discount (%)' and update mappingg field from(cs.SP_Coupon_Discount_Rate__c*100) to cs.SP_Coupon_Discount_Rate__c
            couponDiscountAndDiscountAmount = (cs.SP_Coupon_Discount_Rate__c==null && cs.Coupon_Discount_Amount__c==null)?'N/A':(cs.SP_Coupon_Discount_Rate__c==null?ApexUtil.mapCurrencySign.get(cs.CurrencyIsoCode)+ApexUtil.formatNumber(cs.Coupon_Discount_Amount__c,2,cs.Contract_Language__c):ApexUtil.formatNumber(cs.SP_Coupon_Discount_Rate__c,2,cs.Contract_Language__c)+'%');//SB 27.6.2022 US-0010429 - Ability to sign Agreement in portal 
            maxDisc = cs.Maximum_Discount_Value__c ==null?'N/A':ApexUtil.mapCurrencySign.get(cs.CurrencyIsoCode)+ApexUtil.formatNumber(cs.Maximum_Discount_Value__c ,2,cs.Contract_Language__c);
            additionalArrangement = cs.Additional_Terms__c==null?'':cs.Additional_Terms__c;
            marketingName = ApexUtil.checkNull(cs.Marketing_Coupon_Name__c)+'';
            minTransactionVal = cs.Min_Transaction_Value__c==null?'N/A':ApexUtil.mapCurrencySign.get(cs.CurrencyIsoCode)+ApexUtil.formatNumber(cs.Min_Transaction_Value__c,2,cs.Contract_Language__c);
            country = ApexUtil.checkNull(cs.Legal_Entity_Country__c)+'';
            
            //MN-25072022-US-0012015
            sellerShareHolder = (cs.SellerShareHolder__c==null)?'N/A':ApexUtil.formatNumber(cs.SellerShareHolder__c,2,cs.Contract_Language__c)+'%';
            eBayCofundMax = (cs.eBay_Co_fund_Max__c==null)?'N/A':ApexUtil.formatNumber(cs.eBay_Co_fund_Max__c,2,cs.Contract_Language__c);
            
        }
    }

    /*********************************************************************************************************************************
    @ method:         getDownloadExcel
    @ Version:        1.0
    @ Author:         Loumang SENG (loumang.seng@gaea-sys.com)
    @ Purpose:        US-0010534 - Downloadable item list in .xls file from portal
    @ Parameter:      String csId
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 14.06.2022 / Loumang SENG / Created the method.
    *********************************************************************************************************************************/
    @AuraEnabled
    public static String getDownloadExcel(String csId) {
        PageReference xlsGenerater = new PageReference('/apex/SEPDownloadPage');
        xlsGenerater.getParameters().put('id',csId);
        return  EncodingUtil.base64encode(!Test.isRunningTest() ? xlsGenerater.getContent() : Blob.valueOf('test'));
    }
    
}