unpackaged/main/default/objects/Deal_Statement__c/Deal_Statement__c.object-meta.xml
<CustomObject>
    <description>US-0008846 - [NA] Migrate JOIN NA Deals Trigger and related Classes to Hive</description>
    <label>Deal Statement</label>
    <nameField>
        <label>Deal Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deal_Statement__c/fields/Adjustment_Approved__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010376: Set to TRUE if Adjusted Statement is fully Approved</description>
    <label>Adjustment Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/eBaySeller_Name__c.field-meta.xml
<CustomField>
    <fullName>eBaySeller_Name__c</fullName>
    <description>US-0009686 - Hypercare: Updates needed to NA Deal Statement Attachment</description>
    <formula>eBay_Seller__r.Name</formula>
    <label>eBaySeller Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Final_Statement_Approved__c.field-meta.xml
<CustomField>
    <fullName>Final_Statement_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010376:Set to TRUE if Final Statement is fully Approved</description>
    <label>Final Statement Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Initial_Payout__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payout__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Initial Payout (60%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/MostRecentAdjustStatement__c.field-meta.xml
<CustomField>
    <fullName>MostRecentAdjustStatement__c</fullName>
    <description>US-0010372 - [NA Deal Statement] Update Deal Statement - Change to Adjusted Payout</description>
    <label>MostRecentAdjustStatement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/MostRecentAdjustStatementDate__c.field-meta.xml
<CustomField>
    <fullName>MostRecentAdjustStatementDate__c</fullName>
    <description>US-0010372 - [NA Deal Statement] Update Deal Statement - Change to Adjusted Payout</description>
    <label>MostRecentAdjustStatementDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/MostRecentFinalStatement__c.field-meta.xml
<CustomField>
    <fullName>MostRecentFinalStatement__c</fullName>
    <description>US-0009248 - [NA] Mass Send created Deal Statements with attached Excel to Sellers. 
stores attachment id (by ETL)</description>
    <label>MostRecentFinalStatement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/MostRecentFinalStatementDate__c.field-meta.xml
<CustomField>
    <fullName>MostRecentFinalStatementDate__c</fullName>
    <description>US-0009424 - NA Deal Statements - Process fixes and updates</description>
    <label>MostRecentFinalStatementDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/MostRecentFirstStatement__c.field-meta.xml
<CustomField>
    <fullName>MostRecentFirstStatement__c</fullName>
    <description>US-0009248 - [NA] Mass Send created Deal Statements with attached Excel to Sellers. 
stores attachment id (by ETL)</description>
    <label>MostRecentFirstStatement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/MostRecentFirstStatementDate__c.field-meta.xml
<CustomField>
    <fullName>MostRecentFirstStatementDate__c</fullName>
    <description>US-0009424 - NA Deal Statements - Process fixes and updates</description>
    <label>MostRecentFirstStatementDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Second_Payout__c.field-meta.xml
<CustomField>
    <fullName>Second_Payout__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Subsidy Final Payout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation
US-0010371</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>1st Statement</fullName>
            </value>
            <value>
                <fullName>In 1st Payout Approval</fullName>
            </value>
            <value>
                <fullName>1st Payout Approved</fullName>
            </value>
            <value>
                <fullName>1st Statement Sent out</fullName>
            </value>
            <value>
                <fullName>1st Statement Paid</fullName>
            </value>
            <value>
                <fullName>2nd Statement</fullName>
                <label>Final Statement</label>
            </value>
            <value>
                <fullName>In 2nd Payout Approval</fullName>
                <label>In Final Payout Approval</label>
            </value>
            <value>
                <fullName>2nd Payout Approved</fullName>
                <label>Final Payout Approved</label>
            </value>
            <value>
                <fullName>2nd Statement Sent out</fullName>
                <label>Final Statement Sent out</label>
            </value>
            <value>
                <fullName>2nd Statement Paid</fullName>
                <label>Final Statement Paid</label>
            </value>
            <value>
                <fullName>In Dispute</fullName>
                <label>Adjusted Statement</label>
            </value>
            <value>
                <fullName>In Dispute Payout Approval</fullName>
                <label>In Adjusted Statement Approval</label>
            </value>
            <value>
                <fullName>Dispute Payout Approved</fullName>
                <label>Adjusted Statement Approved</label>
            </value>
            <value>
                <fullName>Dispute Statement Sent Out</fullName>
                <label>Adjusted Statement Sent Out</label>
            </value>
            <value>
                <fullName>Dispute Statement Paid</fullName>
                <label>Adjusted Statement Paid</label>
            </value>
            <value>
                <fullName>Payout Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Subsidy_Final_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Final_Calculation__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Subsidy Final (60-Day) Calculation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/X1st_Statement_Approved__c.field-meta.xml
<CustomField>
    <fullName>X1st_Statement_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010376: Set to TRUE if 1st Statement is fully Approved</description>
    <label>1st Statement Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>US-0009544 - [NA] Changes for NA Deal Statement emails to Seller</description>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/EBH_Deal__c/EBH_Deal__c.object-meta.xml
<CustomObject>
    <description>[EBH] (EPH-3291) - Deal</description>
    <label>Deal</label>
    <nameField>
        <displayFormat>DN-{0000000000}</displayFormat>
        <label>WoW Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/EBH_Deal__c/fields/Deal_Statement__c.field-meta.xml
<CustomField>
    <fullName>Deal_Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008846 - [NA] Migrate JOIN NA Deals Trigger and related Classes to Hive</description>
    <label>Deal Statement</label>
    <referenceTo>Deal_Statement__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DealStatementTriggerHandler.cls
/*********************************************************************************************************************************
@ Class:          DealStatementTriggerHandler
@ Version:        1.0
@ Author:         Sophal Noch (sophal.noch@gaea-sys.com)
@ Purpose:        Handler Class for DealStatementTrigger Trigger
----------------------------------------------------------------------------------------------------------------------------------
@ Change history:  05.05.2021 / Sophal Noch / Created the class.
----------------------------------------------------------------------------------------------------------------------------------
@ Change history:  11.10.2021 / Mony Nou / US-0010374 - [NA Deal Statement] Adjusted Statement Generation
*********************************************************************************************************************************/
public without sharing class DealStatementTriggerHandler {

    private static String PLV_1ST_STATEM = '1st Statement';
    private static String PLV_FINAL_STATEM = '2nd Statement';
    private static String PLV_ADJUS_STATEM = 'In Dispute'; //MN-11102021-US-0010374

    // private static String PLV_1ST_STATEM_SENTOUT = '1st Statement Sent Out';
    // private static String PLV_FINAL_STATEM_SENTOUT = 'Final Statement Sent Out';

    private static String FIRST_STATEM_FILENAME = '{0} - {1} {2} Deals Subsidy 1st Statement';
    private static String FINAL_STATEM_FILENAME = '{0} - {1} {2} Deals Subsidy Final Statement';
    private static String ADJUS_STATEM_FILENAME = '{0} - {1} {2} Deals Subsidy Adjusted Statement'; //MN-11102021-US-0010374

    

    // private static String PLV_1ST_STATEM_APPROVAL = 'In 1st Payout Approval';
    // private static String PLV_FINAL_STATEM_APPROVAL = 'In 2nd Payout Approval';

    private static String VF_DS_PAGE = 'DD_DealStatementSpreadsheet';

    // private static Integer CHUNK_SIZE_LIMIT = 25;
    private static final String FIRST_APPROVED_STATUS = '1st Payout Approved';
    private static final String FINAL_APPROVED_STATUS = '2nd Payout Approved';
    private static final String DISPUTE_APPROVED_STATUS = 'Dispute Payout Approved';
    private static final String IN_FIRST_APPROVED_STATUS = 'In 1st Payout Approval';
    private static final String IN_FINAL_APPROVED_STATUS = 'In 2nd Payout Approval';
    private static final String IN_DISPUTE_APPROVED_STATUS = 'In Dispute Payout Approval';

    /*****************************************************************************************************************************
    @ Method:       detectStatusChangedAndGenerateXsl
    @ Author:       Sophal Noch (sophal.noch@gaea-sys.com)
    @ Purpose:      US-000942  - NA Deal Statements - Process fixes and updates
    @               Change Deal Statement Status and Generate Attachment
    @ Event:		before update.
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history:  05.05.2021 / Sophal Noch / US-000942 Created the method.
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history:  11.10.2021 / Mony Nou / US-0010374 - [NA Deal Statement] Adjusted Statement Generation
    @*****************************************************************************************************************************/
    public static void detectStatusChangedAndGenerateXsl(List<Deal_Statement__c> listDs, Map<Id,Deal_Statement__c> mapOldDs){

            List<Deal_Statement__c> list1stDs = new List<Deal_Statement__c>();
            List<Deal_Statement__c> listfinalDs = new List<Deal_Statement__c>();
            List<Deal_Statement__c> listadjusDs = new List<Deal_Statement__c>(); //MN-11102021-US-0010374

            Map<Id,Attachment> mapDsIdToAtt = new Map<Id,Attachment>();

            

            for(Deal_Statement__c ds : listDs){

                if(ds.Subsidy_Final_Calculation__c != mapOldDs.get(ds.Id).Subsidy_Final_Calculation__c){
                    ds.Second_Payout__c = (ds.Subsidy_Final_Calculation__c != null ? ds.Subsidy_Final_Calculation__c : 0) - (ds.Initial_Payout__c != null ? ds.Initial_Payout__c : 0);  // 26.05.2021 / Sophal Noch / US-0009562
                }

                String fileName = '.xls';
                if(ds.Status__c == PLV_1ST_STATEM && ds.Status__c != mapOldDs.get(ds.Id).Status__c){
                    list1stDs.add(ds);
                    fileName = String.format(FIRST_STATEM_FILENAME, getFieldMatches(ds)) + fileName; // 11.06.2021 / Sophal Noch / US-0009686 change the name of first statement excel
                    mapDsIdToAtt.put( ds.Id, createXslFile(ds.Id,fileName) );

                }else if(ds.Status__c == PLV_FINAL_STATEM && ds.Status__c != mapOldDs.get(ds.Id).Status__c){
                    listfinalDs.add(ds);
                    fileName = String.format(FINAL_STATEM_FILENAME, getFieldMatches(ds)) + fileName; // 11.06.2021 / Sophal Noch / US-0009686 change the name of final statement excel
                    mapDsIdToAtt.put( ds.Id, createXslFile(ds.Id,fileName) );
                }
                //MN-11102021-US-0010374
                else if(ds.Status__c == PLV_ADJUS_STATEM && ds.Status__c != mapOldDs.get(ds.Id).Status__c){ 
                    listadjusDs.add(ds);
                    fileName = String.format(ADJUS_STATEM_FILENAME, getFieldMatches(ds)) + fileName; 
                    mapDsIdToAtt.put( ds.Id, createXslFile(ds.Id,fileName) );
                }



            }

            if(!mapDsIdToAtt.isEmpty()){
                // 05.05.2021 / Sophal Noch / US-0009424 insert Attachment but the content is empty here.
                insert mapDsIdToAtt.values();


                if(!list1stDs.isEmpty()){
                    for(Deal_Statement__c ds : list1stDs){
                        ds.MostRecentFirstStatement__c = mapDsIdToAtt.get(ds.Id).Id; // 05.05.2021 / Sophal Noch / US-0009424 update attachment for first statement
                    }
                }
    
                if(!listfinalDs.isEmpty()){
                    for(Deal_Statement__c ds : listfinalDs){
                        ds.MostRecentFinalStatement__c = mapDsIdToAtt.get(ds.Id).Id; // 05.05.2021 / Sophal Noch / US-0009424 update content version for final statement
                    }
                }

                //MN-11102021-US-0010374
                if(!listadjusDs.isEmpty()){ 
                    for(Deal_Statement__c ds : listadjusDs){
                        ds.MostRecentAdjustStatement__c = mapDsIdToAtt.get(ds.Id).Id; 
                    }
                }

            }

    }

    /*****************************************************************************************************************************
    @ Method:       updateXslFromVF
    @ Author:       Sophal Noch (sophal.noch@gaea-sys.com)
    @ Purpose:      US-000942  - NA Deal Statements - Process fixes and updates
    @               Change Deal Statement Status and Generate Attachment
    @ Event:		after update.
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history:  06.05.2021 / Sophal Noch / US-000942 Created the method.
    ----------------------------------------------------------------------------------------------------------------------------------
    @ Change history:  11.10.2021 / Mony Nou / US-0010374 - [NA Deal Statement] Adjusted Statement Generation
    @*****************************************************************************************************************************/
    public static void updateXslFromVF(List<Deal_Statement__c> listDs, Map<Id,Deal_Statement__c> mapOldDs){
        
        Map<Id,Id> mapDsIdToAttId = new Map<Id,Id>();

        // Set<String> criteriaStatus = new Set<String>{PLV_1ST_STATEM,PLV_FINAL_STATEM,PLV_1ST_STATEM_APPROVAL,PLV_FINAL_STATEM_APPROVAL};
        Set<String> criteriaStatus = new Set<String>{PLV_1ST_STATEM,PLV_FINAL_STATEM,PLV_ADJUS_STATEM} ; //MN-11102021-US-0010374 - Added status "Adjust Statement"

        
        for(Deal_Statement__c ds : listDs){

            if( criteriaStatus.contains(ds.Status__c)){

                if(ds.MostRecentFirstStatement__c != null && ds.MostRecentFirstStatement__c != mapOldDs.get(ds.Id).MostRecentFirstStatement__c){
                    mapDsIdToAttId.put(ds.Id,ds.MostRecentFirstStatement__c);
                }else if(ds.MostRecentFinalStatement__c != null && ds.MostRecentFinalStatement__c != mapOldDs.get(ds.Id).MostRecentFinalStatement__c){
                    mapDsIdToAttId.put(ds.Id,ds.MostRecentFinalStatement__c);
                }else if(ds.MostRecentAdjustStatement__c != null && ds.MostRecentAdjustStatement__c != mapOldDs.get(ds.Id).MostRecentAdjustStatement__c){ //MN-11102021-US-0010374 
                    mapDsIdToAttId.put(ds.Id,ds.MostRecentAdjustStatement__c);
                }
            }   

        }

        if(!mapDsIdToAttId.isEmpty()){
            // 05.05.2021 / Sophal Noch / US-0009424 update attachment content

            setupCache(mapDsIdToAttId.keySet());

            updateAttContent(mapDsIdToAttId.values(), mapDsIdToAttId.keySet());

            // (not used for now) split to chunck records to avoid memory limit error when generating xsl file on future method
            // Integer index = 0;
            // Map<Integer,Map<Id,Id>> mapIndexToDsMap = new  Map<Integer,Map<Id,Id>>();
            
            // for(Id dsId : mapDsIdToAttId.keySet()){

            //     if(!mapIndexToDsMap.containsKey(index)){
            //         mapIndexToDsMap.put(index, new Map<Id,Id>() );
            //     }

            //    if(mapIndexToDsMap.get(index).size() < CHUNK_SIZE_LIMIT){
            //         mapIndexToDsMap.get(index).put(dsId, mapDsIdToAttId.get(dsId));
            //    }
            //    if(mapIndexToDsMap.get(index).size() >= CHUNK_SIZE_LIMIT){
            //      index++;
            //    }
                
            // }

            // System.debug('nsp: index === '+index);
            // System.debug('nsp: mapDsIdToAttId === '+mapIndexToDsMap.size());

            // for(Integer chunkIndex : mapIndexToDsMap.keySet()){
            //     Map<Id,Id> mapIdToId = mapIndexToDsMap.get(chunkIndex);
            //     updateAttContent(mapIdToId.values(), mapIdToId.keySet());
            // }   


            
        }

    }

    private static void setupCache(Set<Id> setDsId){
        // these cache will be used in vf page.


        // 20.05.2021 / Sophal Noch / US-0009544 store cache by deal statement id
        for(Deal_Statement__c ds : DD_DealStatementSpreadsheetController.queryDealStatement(setDsId).values()){
            Cache.Org.put(DD_DealStatementSpreadsheetController.DS_CACHE_KEY + ds.Id, ds,300);
        }
        // 20.05.2021 / Sophal Noch / US-0009544 store deal list cache by deal statement id
        Map<Id,List<EBH_Deal__c>> mapCacheDsToListDeal = DD_DealStatementSpreadsheetController.queryDealByDsId(setDsId);
        for(Id dsId : mapCacheDsToListDeal.keySet()){
            Cache.Org.put(DD_DealStatementSpreadsheetController.DEALS_CACHE_KEY + dsId, mapCacheDsToListDeal.get(dsId),300);
        }

    }




    private static Attachment createXslFile(Id dsId,String fileName){
        // 05.05.2021 / Sophal Noch / US-0009424 generate default attachment.

        Blob xlsContent = !Test.isRunningTest() ? Blob.valueOf('') : Blob.valueOf('test');
        Attachment attachment = new Attachment();
        attachment.Body = xlsContent;
        attachment.Name = fileName;
        attachment.ParentId = dsId; 
        return attachment;

    }

    
   @Future(callout=true)
   private static void updateAttContent(List<Id> setAttId, Set<Id> setDsId){
        
        // 05.05.2021 / Sophal Noch / US-0009424 content is from vf page
        List<Attachment> listAtt = [Select Id, Name, ParentId From Attachment Where Id IN: setAttId And ParentId In : setDsId];
       
        if(!listAtt.isEmpty())
        {

            datetime currenttime  = System.now();
            List<Deal_Statement__c> listDsToUpdate = new List<Deal_Statement__c>();

            
            for(Attachment att : listAtt){

                // System.debug('nsp: att.ParentId == '+att.ParentId);

                PageReference xlsGenerater = new PageReference('/apex/'+VF_DS_PAGE);

                xlsGenerater.getParameters().put('Id', att.ParentId);
                xlsGenerater.getParameters().put(DD_DealStatementSpreadsheetController.CACHE_PARAM, 'true'); // will use cache instead of dml in vf page
                
                Blob xlsContent = !Test.isRunningTest() ? xlsGenerater.getContent() : Blob.valueOf('test');

                att.Body = xlsContent;

                

                listDsToUpdate.add(new Deal_Statement__c(Id=att.ParentId,MostRecentFirstStatementDate__c = currenttime, MostRecentFinalStatementDate__c = currenttime, MostRecentAdjustStatementDate__c = currenttime)); //MN-11102021-US-0010374 - Added MostRecentAdjustStatementDate__c
                
            }
            // System.debug('nsp: listDsToUpdate = '+listDsToUpdate);
            if(!listDsToUpdate.isEmpty()){
                update listAtt;
                listAtt.clear(); // to reduce memory consumption after xsl files are updated.

                update listDsToUpdate; // to trigger processs builder to submit for approval

                for(Id dsId: setDsId){
                    Cache.Org.remove(DD_DealStatementSpreadsheetController.DS_CACHE_KEY + dsId);
                    Cache.Org.remove(DD_DealStatementSpreadsheetController.DEALS_CACHE_KEY + dsId);
                }

            }

            
           
        }

   }

   private static String[] getFieldMatches(Deal_Statement__c ds){
    // 11.06.2021 / Sophal Noch / US-0009686 get field values to match excel filename format

    String month = String.isBlank(ds.Month__c) ? '0' : ds.Month__c;
    month = Decimal.valueOf(month) > 9 ? ds.Month__c : '0'+month;

    String year = ds.Year__c == null ? '0000': (''+Integer.valueOf(ds.Year__c));

    return new String[]{ds.eBaySeller_Name__c,month, year};
   }
   
   /*****************************************************************************************************************************
    @ Method:       updateDealStatementApprovalCheckbox
    @ Author:       sovantheany dim (sovantheany.dim@gaea-sys.com)
    @ Purpose:      US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval
    @               AC2) Update Deal Statement Approval process to execute field update to new fields in AC1 based on if 1st, Final or Adjusted Statements are Approved.
    @ Event:		before update.
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history:  19.10.2021 / Sophal Noch / US-0010376 Created the method.
    @*****************************************************************************************************************************/
    public static void updateDealStatementApprovalCheckbox(List<Deal_Statement__c> listDs, Map<Id,Deal_Statement__c> mapOldDs){
    	for(Deal_Statement__c ds : listDs){
    		Deal_Statement__c old_ds = mapOldDs.get(ds.id);
			if(old_ds.Status__c == IN_FIRST_APPROVED_STATUS && ds.Status__c == FIRST_APPROVED_STATUS){
				ds.X1st_Statement_Approved__c = true;
			}else if(old_ds.Status__c == IN_FINAL_APPROVED_STATUS && ds.Status__c == FINAL_APPROVED_STATUS){
				ds.Final_Statement_Approved__c = true;
			}else if(old_ds.Status__c == IN_DISPUTE_APPROVED_STATUS && ds.Status__c == DISPUTE_APPROVED_STATUS){
				ds.Adjustment_Approved__c = true;
			}
    	}
    }
   
   
}