unpackaged/main/default/objects/Deal_Statement__c/Deal_Statement__c.object-meta.xml
<CustomObject>
    <description>US-0008846 - [NA] Migrate JOIN NA Deals Trigger and related Classes to Hive</description>
    <label>Deal Statement</label>
    <nameField>
        <label>Deal Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deal_Statement__c/fields/Adjustment_Approved__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010376: Set to TRUE if Adjusted Statement is fully Approved</description>
    <label>Adjustment Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Amount_Held_Back__c.field-meta.xml
<CustomField>
    <fullName>Amount_Held_Back__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Subsidy Amount Held Back (40%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Disputes_Payout__c.field-meta.xml
<CustomField>
    <fullName>Disputes_Payout__c</fullName>
    <description>US-0008846 - [NA] Migrate JOIN NA Deals Trigger and related Classes to Hive
US-0010372</description>
    <label>Adjusted Payout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/eBay_Seller__c.field-meta.xml
<CustomField>
    <fullName>eBay_Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>eBay Seller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>EBH_Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal Statements</relationshipLabel>
    <relationshipName>Deal_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Final_Statement_Approved__c.field-meta.xml
<CustomField>
    <fullName>Final_Statement_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010376:Set to TRUE if Final Statement is fully Approved</description>
    <label>Final Statement Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Initial_Payout__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payout__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Initial Payout (60%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Second_Payout__c.field-meta.xml
<CustomField>
    <fullName>Second_Payout__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Subsidy Final Payout</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation
US-0010371</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>1st Statement</fullName>
            </value>
            <value>
                <fullName>In 1st Payout Approval</fullName>
            </value>
            <value>
                <fullName>1st Payout Approved</fullName>
            </value>
            <value>
                <fullName>1st Statement Sent out</fullName>
            </value>
            <value>
                <fullName>1st Statement Paid</fullName>
            </value>
            <value>
                <fullName>2nd Statement</fullName>
                <label>Final Statement</label>
            </value>
            <value>
                <fullName>In 2nd Payout Approval</fullName>
                <label>In Final Payout Approval</label>
            </value>
            <value>
                <fullName>2nd Payout Approved</fullName>
                <label>Final Payout Approved</label>
            </value>
            <value>
                <fullName>2nd Statement Sent out</fullName>
                <label>Final Statement Sent out</label>
            </value>
            <value>
                <fullName>2nd Statement Paid</fullName>
                <label>Final Statement Paid</label>
            </value>
            <value>
                <fullName>In Dispute</fullName>
                <label>Adjusted Statement</label>
            </value>
            <value>
                <fullName>In Dispute Payout Approval</fullName>
                <label>In Adjusted Statement Approval</label>
            </value>
            <value>
                <fullName>Dispute Payout Approved</fullName>
                <label>Adjusted Statement Approved</label>
            </value>
            <value>
                <fullName>Dispute Statement Sent Out</fullName>
                <label>Adjusted Statement Sent Out</label>
            </value>
            <value>
                <fullName>Dispute Statement Paid</fullName>
                <label>Adjusted Statement Paid</label>
            </value>
            <value>
                <fullName>Payout Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Subsidy_30_Day_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_30_Day_Calculation__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Subsidy 30 Day Calculation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Subsidy_Final_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Final_Calculation__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <label>Subsidy Final (60-Day) Calculation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Total_Paid_Out__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Out__c</fullName>
    <description>US-0008778 - [NA] Monthly Deal Statement Creation</description>
    <formula>Initial_Payout__c +  Second_Payout__c +  Disputes_Payout__c +  Further_Dispute_Payout__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Paid Out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/X1st_Statement_Approved__c.field-meta.xml
<CustomField>
    <fullName>X1st_Statement_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>US-0010376: Set to TRUE if 1st Statement is fully Approved</description>
    <label>1st Statement Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>US-0009544 - [NA] Changes for NA Deal Statement emails to Seller</description>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement_Summary__c/Deal_Statement_Summary__c.object-meta.xml
<CustomObject>
    <description>US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval</description>
    <label>Deal Statement Summary</label>
    <nameField>
        <displayFormat>DSS-{00000}</displayFormat>
        <label>Deal Statement Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Statement Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deal_Statement_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval</description>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement_Summary__c/fields/Statement_Type__c.field-meta.xml
<CustomField>
    <fullName>Statement_Type__c</fullName>
    <description>US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval</description>
    <label>Statement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Statement</fullName>
            </value>
            <value>
                <fullName>Final Statement</fullName>
            </value>
            <value>
                <fullName>Adjusted Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deal_Statement_Summary__c/fields/Summary_Name__c.field-meta.xml
<CustomField>
    <fullName>Summary_Name__c</fullName>
    <description>US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval</description>
    <formula>TEXT(Month__c)+&#39;-&#39;+TEXT(Year__c)+&#39;-&#39;+TEXT(Statement_Type__c)</formula>
    <label>Summary Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deal_Statement_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval</description>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DealStatementGeneratorController.cls
/*********************************************************************************************************************************
@ Class:          DealStatementGeneratorController
@ Version:        1.0
@ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
@ Purpose:        US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 14.10.2021 / Sovantheany Dim / Created the class.                
*********************************************************************************************************************************/
public with sharing class DealStatementGeneratorController {
    private final static String SOQL_DEALSTATEMENT = 'select id[PLACEHOLDER] from Deal_Statement__c';
    private final static String SOQL_DEALSTATEMENTSUMMARY = 'select Summary_Name__c, Month__c, Year__c, Statement_Type__c, id from Deal_Statement_Summary__c';
    private static Map<String,String> mapField_Type = new Map<String,String>{
        '1st Statement'=>'X1st_Statement_Approved__c',
        'Final Statement'=>'Final_Statement_Approved__c',
        'Adjusted Statement'=>'Adjustment_Approved__c'
    };
    private static set<String> sFields = new set<String>{'eBay_Seller__r.Name','Month__c','Year__c','Initial_Payout__c','Total_Paid_Out__c','Subsidy_30_Day_Calculation__c','Amount_Held_Back__c','Subsidy_Final_Calculation__c','Second_Payout__c','Disputes_Payout__c'};
    private static Map<String,String[]> mapHeaderCol = new Map<String,String[]>
    {
    	'US'=>new String[]{'\uFEFFeBay Seller:Business Name','Month','Year','Initial Payout (60%)','Total Paid Out','Subsidy 30 Day Calculation','Subsidy Amount Held Back (40%)','Subsidy Final (60-Day) Calculation','Subsidy Final Payout','Adjusted Payout'}
    };
    /*****************************************************************************************************************************
	@ Method:   generateToExcel
	@ Version:  1.0
	@ Author:   Sovantheany Dim (sovantheany.dim@gaea-sys.com)
	@ Purpose:  US-0010376 - [NA Deal Statement] Monthly Statement Summary and Approval
	@			Summary Excel will use Month, Year and Statement Type to select Deal Statements to be selected for the file. Only Deal Statements which match Month, Year and the fields in AC1 matching the Statement Type will be included. If AC1 field is FALSE, then that Statement is excluded.
	@			AC5) If no matching Deal Statements for the criteria is found. System will give error message: 'No Deal Statements found for this Summary'
	@			AC5) If Excel file is successfully generated. Deal Statement Summary 'Status' field will be updated to 'Ready for Approval' and Excel file is attached to the Deal Statement Summary record.
	------------------------------------------------------------------------------------------------------------------------------
	@ Change history: 14.10.2021/ Sovantheany Dim / Created the  Method.
	*****************************************************************************************************************************/
    @AuraEnabled
    public static Map<String, Object> generateToExcel(String parentId) {
        Map<String, Object> mResult = new Map<String, Object>();
        List<Attachment> lstAttach = new List<Attachment>();
        String key = 'US';
        String[] listHeader = mapHeaderCol.containsKey(key)?mapHeaderCol.get(key):null;
        List<List<String>> listRows = new List<List<String>>{listHeader};
        try{
            //get deal statement summary
            String month = '';
            String year = '';
            String where_Type = '';
            String dssName = '';
            for(Deal_Statement_Summary__c dss : Database.query(SOQL_DEALSTATEMENTSUMMARY+' where id =: parentId')){
                month = dss.Month__c;
                year = dss.Year__c;
                if(!String.isEmpty(dss.Statement_Type__c) && mapField_Type.containsKey(dss.Statement_Type__c)) where_Type += ' AND '+mapField_Type.get(dss.Statement_Type__c)+' = true';
            	dssName = dss.Summary_Name__c;
            }
            //convert Year from string to integer
            Integer year_int = Integer.valueOf(year);
            String fields = ','+String.join(new List<String>(sFields),',');
            String soql_dealstatement2 = SOQL_DEALSTATEMENT.replace('[PLACEHOLDER]', fields).replace('Month__c','toLabel(Month__c)');
            boolean hasDealStement = false;
            //get Deal Statement
            for(Deal_Statement__c ds : Database.query(soql_dealstatement2+' where Month__c =: month AND Year__c =: year_int'+where_Type)){
            	hasDealStement = true;
                List<String> listCells = new List<String>();
                for(String f : sFields){
                    listCells.add(getFieldValue(f,ds,'UK'));
                }
                listRows.add(listCells);
            }
            if(hasDealStement){
                //update Deal Statement Summary 'Status' to 'Ready for Approval'
                Deal_Statement_Summary__c dssReadyForApproval = new Deal_Statement_Summary__c(id=parentId ,Status__c = 'Ready for Approval');
              	update dssReadyForApproval;
                //generate to excel file
                List<ExcelGenerator.xSheet> listSheets = new List<ExcelGenerator.xSheet>();
                ExcelGenerator.xSheet sheetSTP = new ExcelGenerator.xSheet('Sheet1',listRows);
                listSheets.add(sheetSTP);
                ExcelGenerator generator = new ExcelGenerator(userinfo.getname(),listSheets);
                generator.generateWorkBook();
                String xml = generator.getWorkbookXML();
                String fileName = dssName+'.xls';
                //attached Excel file  to the Deal Statement Summary record
                Attachment attach = createAttachment(Blob.valueOf(xml), filename,'application/vnd.ms-excel', parentId);
                lstAttach.add(attach);
                insert lstAttach;
                mResult.put('isSuccess', true);
                mResult.put('msg', System.label.successAddFile_msg);  
            }else{
               	mResult.put('isSuccess', false);
           		mResult.put('msg', System.label.failAddFile_msg); 
            }
        }catch (Exception ex) { mResult.put('isSuccess', false);mResult.put('msg', ex.getMessage());}
        return mResult;
    }
    
    private static Attachment createAttachment(Blob body, String fileName,String contentType, Id parentId) {
        Attachment att = new Attachment();
        att.Body = body;
        att.Name = fileName;
        att.IsPrivate = false;
        att.ContentType = contentType; 
        att.ParentId = parentId;
        return att;
    }
    private static Map<String,Schema.DisplayType> mapFieldType = new Map<String,Schema.DisplayType>
    {
    	'Deal_Statement__c:Initial_Payout__c' => Schema.DisplayType.Double,
    	'Deal_Statement__c:Total_Paid_Out__c' => Schema.DisplayType.Double,
    	'Deal_Statement__c:Subsidy_30_Day_Calculation__c' => Schema.DisplayType.Double,
    	'Deal_Statement__c:Amount_Held_Back__c' => Schema.DisplayType.Double,
    	'Deal_Statement__c:Subsidy_Final_Calculation__c'=> Schema.DisplayType.Double,
    	'Deal_Statement__c:Second_Payout__c' => Schema.DisplayType.Double,
        'Deal_Statement__c:Disputes_Payout__c' => Schema.DisplayType.Double
    };
    private static String getFieldValue(String fieldName,Sobject sobj,String revRoll)
    {
    	//System.debug('>>>fieldName: '+fieldName);
    	Object val = ApexUtil.getValue(fieldName,sobj);
    	if(val==null)
    	{
    		return '';
        }else{
            if(!mapFieldType.containsKey(sobj.getSObjectType()+':'+fieldName)){
            	return val+''; 
        	}
            Schema.DisplayType fType =  mapFieldType.get(sobj.getSObjectType()+':'+fieldName);
            if(Schema.DisplayType.Percent ==fType)
            {
                //return val +' %';
                return ApexUtil.formatNumber((Decimal)val,2,revRoll)+' %';
            }else if(Schema.DisplayType.Date ==  fType)
            {
                return ((Date)val).format();
            }else if(Schema.DisplayType.DateTime == fType)
            {
                return ((DateTime)val).format();
            }else if(Schema.DisplayType.Currency == fType|| Schema.DisplayType.Integer == fType  || Schema.DisplayType.Double == fType ||  Schema.DisplayType.Long == fType)
            {
                return ApexUtil.formatNumber((Decimal)val,2,revRoll);
            }
        }
    	return val+''; 
    } 
}