unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>EPH-7262 Adjustment to Coupon Object</description>
    <inlineHelpText>Defines the coupon contract type &amp; language - All sellers in that coupon will receive the same template.</inlineHelpText>
    <label>Contract Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <defaultValue>IF( $RecordType.DeveloperName  = &#39;Pop_Coupon&#39;,  DATEVALUE(&quot;2099-1-1&quot;) , null)</defaultValue>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <inlineHelpText>Unique Code that will be used by the buyer to redeem the coupon</inlineHelpText>
    <label>Coupon Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon__c/fields/Days_since_coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Days_since_coupon_End_Date__c</fullName>
    <description>EPH-7162 Object: Coupon__c - Create two record types</description>
    <formula>IF(
  (today()- Coupon_End_Date__c) &lt; 0, NULL,
   today()- Coupon_End_Date__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Coupon End Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contra_LC__c.field-meta.xml
<CustomField>
    <fullName>Contra_LC__c</fullName>
    <description>[#EPH-7796] New finacial fields for Coupon Seller &amp; Coupon Co-Invest Record record</description>
    <inlineHelpText>Coupon Contra in Local Currency</inlineHelpText>
    <label>Contra LC (Payout)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Contract_Language__c.field-meta.xml
<CustomField>
    <fullName>Contract_Language__c</fullName>
    <description>US-0018725 	Coupon Seller - Add condition to workflow for stage T4Statement and T40 Statement</description>
    <formula>TEXT(Coupon__r.Contract_Language__c)</formula>
    <label>Contract Language</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Cost_Share_Seller_LC__c.field-meta.xml
<CustomField>
    <fullName>Cost_Share_Seller_LC__c</fullName>
    <description>US-0018835 Correct Invoice fields on Coupon Seller</description>
    <label>Cost Share Seller (LC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_End_Date__c</formula>
    <label>Coupon End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_ID__c</formula>
    <inlineHelpText>This is the uniqueCouponcode</inlineHelpText>
    <label>Coupon Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Start_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>Coupon__r.Coupon_Start_Date__c</formula>
    <label>Coupon Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Date_34_days_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_34_days_Sent__c</fullName>
    <description>EPH-7565 Coupon - Manhattan Invoice Statment send to coupon seller</description>
    <label>Date 34 days Sent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Date_4days_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_4days_Sent__c</fullName>
    <description>EPH-7565 Coupon - Manhattan Invoice Statment send to coupon seller</description>
    <label>Date 4days Sent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/days_since_coupon_End_Date__c.field-meta.xml
<CustomField>
    <fullName>days_since_coupon_End_Date__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <formula>IF(
  (today()- Coupon_End_Date__c) &lt; 0, NULL,
   today()- Coupon_End_Date__c
)</formula>
    <label>Days Since Coupon End Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/EBH_CouponSellerOwner__c.field-meta.xml
<CustomField>
    <fullName>EBH_CouponSellerOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>(EPH-7591) Add new field Owner to Coupon Seller Object and Coupon Co-Invest Object</description>
    <label>Coupon Seller Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Email_Adress__c.field-meta.xml
<CustomField>
    <fullName>Email_Adress__c</fullName>
    <description>EPH-7157 Object: Coupon Seller</description>
    <inlineHelpText>Email Adress provided by seller</inlineHelpText>
    <label>Email Adress</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/fields/GMV_LC__c.field-meta.xml
<CustomField>
    <fullName>GMV_LC__c</fullName>
    <description>[#EPH-7796] New finacial fields for Coupon Seller &amp; Coupon Co-Invest Record record</description>
    <inlineHelpText>Coupon GMV in Local Currency</inlineHelpText>
    <label>GMV LC (Payout)</label>
    <precision>17</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/BatchSendCouponSellerInvoiceStatement.cls
/*********************************************************************************************************************************
@ Class:          BatchSendCouponSellerInvoiceStatement
@ Version:        1.0
@ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
@ Purpose:        Batch class to send email template to coupon seller
                  EPH-7565 Coupon - Manhattan Invoice Statment send to coupon seller
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 31.07.2019 / Sovantheany Dim (sovantheany.dim@gaea-sys.com) / Created the class.
*********************************************************************************************************************************/

global with sharing class BatchSendCouponSellerInvoiceStatement implements Database.Batchable<SObject>, Schedulable{
    String soql = '';
    
    /*****************************************************************************************************************************
    @ Method:         start
    @ Version:        1.0
    @ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
    @ Purpose:        QueryLocator start method
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 31.07.2019 / Sovantheany Dim (sovantheany.dim@gaea-sys.com) / Created the method.
    ****************************************************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(soql);
    }
    
    /*****************************************************************************************************************************
    @ Method:         execute
    @ Version:        1.0
    @ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
    @ Purpose:        QueryLocator execute method
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 31.07.2019 / Sovantheany Dim (sovantheany.dim@gaea-sys.com) / Created the method.
    *****************************************************************************************************************************/
    global void execute(Database.BatchableContext pBc, List<SObject> scope){
    	/*set<String> emailTemplateName = new set<String>{EBH_ConstantsUtility.DE_INVOICE_4Days_EMAIL_TEMPLATED_NAME,EBH_ConstantsUtility.DE_INVOICE_34Days_EMAIL_TEMPLATED_NAME};
    	String whereCl = ' Where DeveloperName IN: emailTemplateName'; 
    	Map<String,EmailTemplate> mapEmpt = new Map<String,EmailTemplate>();
    	for(EmailTemplate empt : Database.query(EBH_ConstantsUtility.SOQLEMAIL_TEMPLATES + whereCl)){
    		mapEmpt.put(empt.DeveloperName, empt);
    	}
    	List<Messaging.SingleEmailMessage> listEmail = new List<Messaging.SingleEmailMessage>();
    	List<Coupon_Seller__c> lstcouponSeller = new List<Coupon_Seller__c>();
        for(Coupon_Seller__c couponSeller : (List<Coupon_Seller__c>) scope){
        	if(couponSeller.Coupon__r.Contract_Language__c == 'DE'){
	        	if(couponSeller.days_since_coupon_End_Date__c == 4 && mapEmpt.containsKey(EBH_ConstantsUtility.DE_INVOICE_4Days_EMAIL_TEMPLATED_NAME)){
	        		couponSeller.Date_4days_Sent__c = System.now();
	        		lstcouponSeller.add(couponSeller);
	        		
        			EmailTemplate empt = mapEmpt.get(EBH_ConstantsUtility.DE_INVOICE_4Days_EMAIL_TEMPLATED_NAME);
        			Messaging.SingleEmailMessage mail = setSingleEmailMessage(empt, couponSeller);
        			listEmail.add(mail);
	        	}else if(couponSeller.days_since_coupon_End_Date__c == 34 && mapEmpt.containsKey(EBH_ConstantsUtility.DE_INVOICE_34Days_EMAIL_TEMPLATED_NAME)){
	        		couponSeller.Date_34_days_Sent__c = System.now();
	        		lstcouponSeller.add(couponSeller);
	        		
        			EmailTemplate empt = mapEmpt.get(EBH_ConstantsUtility.DE_INVOICE_34Days_EMAIL_TEMPLATED_NAME);
        			Messaging.SingleEmailMessage mail = setSingleEmailMessage(empt, couponSeller);
        			listEmail.add(mail);
	        	}
        	}
        }
       if(!lstcouponSeller.isEmpty()) update lstcouponSeller;
       if(!listEmail.isEmpty() && !Test.isRunningTest()) Messaging.sendEmail(listEmail);*/
    }
    
    /*private static Messaging.SingleEmailMessage setSingleEmailMessage(EmailTemplate empt, Coupon_Seller__c couponSeller){
    	String subject = mergSubject(empt.Subject,couponSeller);
    	String htmlBody = mergeEmailTemplateBody(empt.HtmlValue,couponSeller);
    	
    	Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    	mail.setToAddresses(new String[]{getObjectValue(couponSeller.Email_Adress__c)});
    	mail.setSenderDisplayName('Hive Support');
    	mail.setCcAddresses(new String[]{getObjectValue(couponSeller.EBH_CouponSellerOwner__r.Email)});
    	mail.setSubject(subject);
    	mail.setBccSender(false);
    	mail.setUseSignature(false);
    	mail.setHtmlBody(htmlBody);
    	return mail;
    }
    
    private static String getObjectValue(Object obj){
        if(obj==null)return '';
        return obj + '';
    }
    
    private static String mergSubject(String s, Coupon_Seller__c c)
    {
    	return s==null?'':s.replace('{!Coupon_Seller__c.Coupon_ID__c}',getObjectValue(c.Coupon_ID__c))
    			.replace('{!Coupon_Seller__c.Coupon_Start_Date__c}',(c.Coupon_Start_Date__c == null ? '':c.Coupon_Start_Date__c.format()))
    			.replace('{!Coupon_Seller__c.Coupon_End_Date__c}',(c.Coupon_End_Date__c == null ? '':c.Coupon_End_Date__c.format()));
    		
    }
    
    private static String mergeEmailTemplateBody(String s, Coupon_Seller__c c)
 	{
 		return s==null?'':s
 		.replace('{!Coupon_Seller__c.Coupon_ID__c}',getObjectValue(c.Coupon_ID__c))
 		.replace('{!Coupon_Seller__c.Coupon_Start_Date__c}',(c.Coupon_Start_Date__c == null ? '':c.Coupon_Start_Date__c.format()))
 		.replace('{!Coupon_Seller__c.Coupon_End_Date__c}',(c.Coupon_End_Date__c == null ? '':c.Coupon_End_Date__c.format()))
 		.replace('{!Coupon_Seller__c.GMV_LC__c}',getObjectValue(c.GMV_LC__c))
 		.replace('{!Coupon_Seller__c.Contra_LC__c}',getObjectValue(c.Contra_LC__c)) 
 		.replace('{!Coupon_Seller__c.Cost_Share_Seller_LC__c}',getObjectValue(c.Cost_Share_Seller_LC__c));
 	}*/
 	
    /*****************************************************************************************************************************
    @ Method:         finish
    @ Version:        1.0
    @ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
    @ Purpose:        QueryLocator finish method, it calls the insert batch
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 31.07.2019 / Sovantheany Dim (sovantheany.dim@gaea-sys.com) / Created the method.
    *****************************************************************************************************************************/ 
    global void finish(Database.BatchableContext pBc){
        
    }
    
    /*****************************************************************************************************************************
    @ Method:         execute
    @ Version:        1.0
    @ Author:         Sovantheany Dim (sovantheany.dim@gaea-sys.com)
    @ Purpose:        Allow this batch to be schedulable
    ------------------------------------------------------------------------------------------------------------------------------
    @ Change history: 31.07.2019 / Sovantheany Dim (sovantheany.dim@gaea-sys.com) / Created the method.
    *****************************************************************************************************************************/ 
     global void execute(SchedulableContext sc) { 
        BatchSendCouponSellerInvoiceStatement b = new BatchSendCouponSellerInvoiceStatement();
        Database.executeBatch(b);
    }
}