unpackaged/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon__c/recordTypes/Category_Based.recordType-meta.xml
<RecordType>
    <fullName>Category_Based</fullName>
    <active>true</active>
    <label>Seller / Category Based</label>
</RecordType>

unpackaged/main/default/objects/Coupon__c/recordTypes/Item_Based.recordType-meta.xml
<RecordType>
    <fullName>Item_Based</fullName>
    <active>true</active>
    <label>Item Based</label>
</RecordType>

unpackaged/main/default/objects/Coupon__c/recordTypes/Pop_Coupon.recordType-meta.xml
<RecordType>
    <fullName>Pop_Coupon</fullName>
    <active>true</active>
    <label>Pop Coupon</label>
</RecordType>

unpackaged/main/default/objects/Coupon_Seller__c/Coupon_Seller__c.object-meta.xml
<CustomObject>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon (Seller)</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coupon (Seller)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Coupon_Seller__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[EPH-6086] have coupon details in Hive</description>
    <label>Coupon</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <errorMessage>if coupon is POP, then coupon seller must be pop</errorMessage>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <filterItems>
            <field>Coupon__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Pop Coupon Seller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Coupon Sellers</relationshipLabel>
    <relationshipName>Coupon_Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Coupon_Seller__c/recordTypes/Manhattan_Coupon.recordType-meta.xml
<RecordType>
    <fullName>Manhattan_Coupon</fullName>
    <active>true</active>
    <label>Manhattan Coupon</label>
</RecordType>

unpackaged/main/default/objects/Coupon_Seller__c/recordTypes/Pop_Coupon.recordType-meta.xml
<RecordType>
    <fullName>Pop_Coupon</fullName>
    <active>true</active>
    <label>Pop Coupon Seller</label>
</RecordType>

unpackaged/main/default/classes/CouponSellerRedirector.cls
/*********************************************************************************************************************************
@ Class:          CouponSellerRedirector
@ Version:        1.0
@ Author:         LoumAng SENG (loumang.seng@gaea-sys.com)
@ Purpose:        US-0007360 - wrong coupon seller record when click on NEW
----------------------------------------------------------------------------------------------------------------------------------
@ Change history: 02.04.2020 / LoumAng SENG / Created the class.
				  
*********************************************************************************************************************************/
public class CouponSellerRedirector {
    private static Map<String, String> mCouponSeller_Coupon = new Map<String, String>{
        'Coupon__c' => 'Id'
   	};
    private static Map<String, String> mRT_Coupon_CouponSeller = new Map<String, String>{
        'Item_Based' => 'Manhattan_Coupon',
        'Category_Based' => 'Manhattan_Coupon',
        'Pop_Coupon' => 'Pop_Coupon'
    };
        
    @AuraEnabled
    public static Map<String, Object> doGetCoupon(String recordId) {
        Map<String, Object> mResult = new Map<String, Object>();

        try{
            String queryStr = 'SELECT RecordType.DeveloperName,'+ String.join((Iterable<String>)mCouponSeller_Coupon.values(), ',') +' FROM Coupon__c WHERE Id =: recordId';
            Coupon__c oCoupon = Database.query(queryStr);
            Map<String, Object> mField = new Map<String, Object>();
            for(String cSellerField : mCouponSeller_Coupon.keySet()){
                Object val = oCoupon.get(mCouponSeller_Coupon.get(cSellerField));
                if(val == null) continue;
                mField.put(cSellerField, val);
            }
            // Set default couponSeller recordtype by coupon
            String cSellerRT = mRT_Coupon_CouponSeller.get(''+oCoupon.getSObject('RecordType').get('DeveloperName'));
            mResult.put('recordTypeId', ApexUtil.getRecordTypeByName('Coupon_Seller__c', cSellerRT).Id);
            mResult.put('params', mField);

            mResult.put('isSuccess', true);
        } catch (Exception ex) {
            mResult.put('isSuccess', false);
            mResult.put('msg', ex.getMessage());
        }

        return mResult;
    }
        

}