unpackaged/main/default/objects/Final_Value_Fee_FVF__c/Final_Value_Fee_FVF__c.object-meta.xml
<CustomObject>
    <description>EPH-7355 New object: Final Value Fee (FVF). Record Type - Seller Level</description>
    <label>Final Value Fee (FVF)</label>
    <nameField>
        <displayFormat>FVF-{000000}</displayFormat>
        <label>Final Value Fee ID (External ID)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Value Fee (FVF)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Final_Value_Fee_FVF__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <description>[#EPH-7104] New Permission Set_ Final Value Fee Approval</description>
    <label>Approved Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Final_Value_Fee_FVF__c/fields/Final_Value_Fee_Stage__c.field-meta.xml
<CustomField>
    <fullName>Final_Value_Fee_Stage__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <description>EPH-7355 New object: Final Value Fee (FVF). Record Type - Seller Level</description>
    <label>Final Value Fee Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent_to_eBay_Approval</fullName>
                <label>Sent to eBay Approver</label>
            </value>
            <value>
                <fullName>eBay Approved</fullName>
            </value>
            <value>
                <fullName>Contract Sent</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Contract Declined</fullName>
            </value>
            <value>
                <fullName>Running Contract</fullName>
            </value>
            <value>
                <fullName>Executed Contract</fullName>
            </value>
            <value>
                <fullName>Statement Sent to Seller</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Sent</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Running Campaign</fullName>
            </value>
            <value>
                <fullName>Executed Campaigns</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Final_Value_Fee_FVF__c/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <description>[#EPH-7104] New Permission Set_ Final Value Fee Approval</description>
    <label>Rejected Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/ApproveRejectControllerTest.cls
@isTest
private  class ApproveRejectControllerTest {

    static testMethod void testApproveReject(){
        Final_Value_Fee_FVF__c fvf1 = new Final_Value_Fee_FVF__c(Final_Value_Fee_Stage__c=EBH_ConstantsUtility.FVF_STAGE_EBAY_SENT_TO_APPROVE);
        Final_Value_Fee_FVF__c fvf2 = new Final_Value_Fee_FVF__c(Final_Value_Fee_Stage__c=EBH_ConstantsUtility.FVF_STAGE_EBAY_SENT_TO_APPROVE);
        Final_Value_Fee_FVF__c fvf3 = new Final_Value_Fee_FVF__c(Final_Value_Fee_Stage__c='Draft');
        insert new Final_Value_Fee_FVF__c[]{fvf1,fvf2,fvf3};


        Test.startTest();
            ApproveRejectController.apexInit(fvf1.Id);
            ApproveRejectController.apexDoApprove(fvf1.Id+'', 'comments1');
            ApproveRejectController.apexDoReject(fvf2.Id+'', 'comments2');
            ApproveRejectController.apexDoReject(fvf3.Id+'', 'comments3');

            Final_Value_Fee_FVF__c f1 = [Select Id,Approved_Date__c,Rejected_Date__c From Final_Value_Fee_FVF__c where Id=:fvf1.Id];
            Final_Value_Fee_FVF__c f2 = [Select Id,Approved_Date__c,Rejected_Date__c From Final_Value_Fee_FVF__c where Id=:fvf2.Id];

            System.assert(f1.Approved_Date__c<>null, 'approved date populated');
            System.assert(f2.Rejected_Date__c<>null, 'rejected date populated');
        Test.stopTest();
        
    } 
}